### ISSUE TITLE
[Task]: Revamp of Datasource creation flow Logic 

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#10546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Improve the code readability
- [ ] Improve the performance of the code
- [ ] Remove the hard coded logic

**Comment by parth-appsmith** [comment]
@AmanAgarwal041 can you provide more information about what design improvements are we looking for in this task?

**Comment by rohan-arthur** [comment]
discussion here: https://www.notion.so/appsmith/Datasource-Aggregation-Flow-9d08062455e74d5fbfb7229a8b743971

**Comment by rohan-arthur** [comment]
@AmanAgarwal041 maybe you need to revisit this and see what's remaining?

**Comment by sribalajig** [comment]
@rohan-arthur @AmanAgarwal041 Can you folks please write a description of this feature request from the end user perspective?
