### ISSUE TITLE
[Task]: Template filters

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#10744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Template filters UI
- [x] Integrate with api 
- [x] Filter the template list
