### ISSUE TITLE
[Feature]-[9884]:Disable JS button if the field is not empty or if the default text is modified

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#10833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Disable JS button in property pane controls if the field is not empty or if the default text has changed.
Also, add a popup on the disabled JS button to indicate why it is disabled.

### Why should this be worked on?

The JS toggle interaction is extremely destructive. The JS binding is getting cleared if press the JS mode toggle button. Please see attached screen recording:

https://user-images.githubusercontent.com/10436935/152168497-22754eaf-c1ab-43e1-a010-602b4ca7fc93.mov

See the Slack discussions [here](https://theappsmith.slack.com/archives/C025SE88KNE/p1643799250836589)

**Comment by aswathkk** [comment]
### Tasks

The following tasks needs to be completed to close this issue

- [ ] Add a static method `canDisplayValueInUI(config, value)` to all the property controls
- [ ] We make sure that the PropertyControlFactory has a static map of this using PropertyControlRegistry process
- [ ] PropertyControl component uses to enable or disable JS toggle
- [ ] ActionSelector control, cannot be switched back, if the value has changed in JS mode.

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 2471 |
| Effort (months)  | 0.5 |

Adding the effort for this as 2 person-weeks for now. Feel free to correct me here.
