### ISSUE TITLE
[Task]: Update Typescript to 4.2.4

### ISSUE THREAD

**Issue by yaldram** [appsmithorg/appsmith#11091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Upgrade Typescript
- [ ] Fix type errors
- [ ] Add instability logging to identify data integrity issues

**Comment by riodeuno** [comment]
Detailed fix and alternative for #4382 

Closing #4382 in favour of this.
