### ISSUE TITLE
[Task] Deprecate redundant select component packages

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#11211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Identify which one of the select packages to keep - rc-select, react-select, @blueprintjs/select.
- [ ] Remove the packages except the one which we decided to keep
- [ ] Create components in the Appsmith Design System, if they're not already present, which we will use to replace the components which were dependent on the removed libraries.
- [ ] Identify all effected parts of the application, communicate these with the QA team
- [ ] Test all effected scenarios (cypress tests preferred)
- [ ] Design audit for regression in UI of the select components.
