### ISSUE TITLE
[Epic]: Optimise the first load till the skeleton loaders

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#11524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] #11537
- [x] #11539
- [x] #11553
- [ ] #11538
- [x] #11468

**Comment by Nikhil-Nandagopal** [comment]
@SatishGandham i'm converting this to an issue and moving all the subtasks to #10473

**Comment by somangshu** [comment]
@Nikhil-Nandagopal apologies, I reverted you changes, I need this for better tracking

**Comment by somangshu** [comment]
## Actionable:
- [ ] @arunvjn is working on clean URLs this week
    - [ ] Once 👆 is complete he will pick up #11553 in the current sprint
    - [ ] @nayan-rafiq can contribute to #11539 since that change in on the backend, We will need to find bandwidth for this.
- [ ] @arunvjn will update #11538 as clean URL will bring form calls to parallel which gives us a few seconds improvement 🎉 
- [ ] @ashit-rath will need to confirm that multi-select is the actual cause of delay of modal opening up in #11901. He will also benchmark what is the most time consuming aspect. The results will be detailed in the issue. Since we are working on the theming and JSON form release as well, we might be seeing delays on this.
- [ ] @prsidhu to get #11468 to the done state and get in merged in the next release.
- [ ] @somangshu @Rishabh-Rathod to work on the performance infra app and issue in the suite

cc @mohanarpit @SatishGandham

**Comment by somangshu** [comment]
## Actionable:
- [ ] #11539 was moved to review but there are too many test cases failing here. @arunvjn Will work on resolving them. Review is also pending here. Post this will continue working on #11553 
- [ ] #11901 was profiled by @ashit-rath @SatishGandham, It was found that the table widget is re-rendering and hence causing delay. We need to profile individual widget to check the above condition
    - [ ] Select widget has performance issues - re-renderers a lot. This was also observed in RC-Select. @prsidhu will be creating an actionable out of this and resolve it further. 
- [ ] While working on Clean URLs @arunvjn was able to parallel-ize the form calls > #11538 
    - [ ]  @ayushpahwa will further looking into this
        - [ ] we need to delay the form calls
        - [ ] Make it non blocking 
        - [ ] since they are static, it makes sense to cache them
- [ ] #11468 is completed and tested, is waiting for getting merged, @prsidhu will take the action once the freeze is lifted

### Other items
- [ ] #11760 related to performance Infrastructure  will be resolved by @Rishabh-Rathod in the current sprint.

**Comment by somangshu** [comment]
## Actionable 

- [ ] With #11539, @arunvjn have resolved all the failing cypress tests, We will be closing this soon. We have seen a 300ms improvement with this change. 🎉 
- [ ] #11553 need profiling, @arunvjn will set the benchmarks here. Currently there are many cypress tests failing here, That will be taken care of in the current sprint, We will target closing this. Based on the last profile by @SatishGandham we will see another 300ms improvement here. 
- [ ] `New Scope` @Rishabh-Rathod is picking up #12584
- [ ] No Progress was made on #11538 @ayushpahwa 


### other items
- [ ] #11760 is being handled by @SatishGandham, We will close this in the current sprint. 
    - [ ] One suggestion made here was to use `buildjet` for the machines where the tests are running.
- [ ] We will be creating the issue for the first page load optimisation phase 2 @SatishGandham
- [ ] All pending issues in the performance board under the new / icebox pipeline will be filtered for cleanup and identifying if there any any low hanging fruits we can get to first @somangshu

**Comment by SatishGandham** [comment]
## Actionable 

- [x] With #11539, @arunvjn have resolved all the failing cypress tests, We will be closing this soon. We have seen a 300ms improvement with this change. 🎉 
- [ ] #11553 need profiling, @arunvjn will set the benchmarks here. Currently there are many cypress tests failing here, That will be taken care of in the current sprint, We will target closing this. Based on the last profile by @SatishGandham we will see another 300ms improvement here. 
- [ ] No Progress was made on #11538 @ayushpahwa 
- [ ] @ashit-rath contributing more on #3369, will start focusing on #11901 in the current week.
- [ ] Improve the select widget performance by multiple unnencessary API calls it makes when server side filtering is enabled. Also enable debounce on the filter.
- [ ] Explore different strategies to optimize the widgets.

### other items
- [ ] `New Scope` @Rishabh-Rathod is picking up #12584 
- [ ] `New Scope` @Rishabh-Rathod is picking up #12582 
- [x] #11760 is being handled by @SatishGandham, We will close this in the current sprint. 
    - [x] One suggestion made here was to use `buildjet` for the machines where the tests are running.
- [ ] All pending issues in the performance board under the new / icebox pipeline will be filtered for cleanup and identifying if there any any low hanging fruits we can get to first @somangshu

**Comment by somangshu** [comment]
## Actionable:
- #11538 is pending, @ayushpahwa will push this into review this week
- We removed #11540 from the epic, this is not related to all the user. Will be dealt with separately
- We removed #11901, Not directly related to the EPIC, this will be taken up once @ashit-rath is free from Theming & JSON form maintenance
