### ISSUE TITLE
[Task]: fix git-import audit issues

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#11545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Change color for the sub line to the headline.
- [x] Move "Where would you like to import your application from?" 8px from the icon.
- [x] Change the DB name. DB name on top and avenue at the bottom.

### Others
- [x] Low - Add Icons: taken care by #11546 

### Not working on:
- Icons scale to 24px with 32px circle #11550 
  - **Cannot do this as this requires changes in all places, has to be separate from git feature**

These issues on top of #10950

**Comment by IAmAnubhavSaini** [comment]
94ee724fba fix: do not use older modal
9126748f42 fix: use git import feature flag
b3d5185e2e fix: add a gap and update color
