### ISSUE TITLE
[Task]: Update icons to 24x24 from 16x16

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#11550]
## Description

Icons in a lot of places are 16x16, as per discussions with @Debsourabh on design, we have to move to 24x24 icon with 32x32 bounding box.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] List all icons with 16x16 size
- [ ] List all icons that are needed to be moved to 24x24
- [ ] Update SVG icon sizes to 24x24
- [ ] Keep icon in round container.
- [ ] Container size should be 32x32.

**Comment by IAmAnubhavSaini** [comment]
This will be taken up by design system update.
