### ISSUE TITLE
[Task] Polishing templates epic for phase 1. 

### ISSUE THREAD

**Issue by hiteshjoshi** [appsmithorg/appsmith#11634]
Deploy preview: https://appsmith-79edqojiy-get-appsmith.vercel.app/

- [x] Update template and application import fork icons
- [x] Change the fork app modal to a similar design as the fork templates modal.
- [x] The cards on the first row should be of the same height(the height of the bigger one)
- [x] The tags in the smaller cards should be of 14px instead of 12px and for subtext it should be 13px instead of 12px
- [x] The image section height in the larger cards should be fixed regardless of the image height.
- [x] The padding between back button and title is reduced to 12px
- [x] The font-size of subtext in all the sections is reduced to 16px ( Function , Industry, Datasources )
- [x] "Showing all 5 templates" font size altered to 20px 
- [x] Show filters which have templates associated with it.
- [x] Show filter count alongside each category
