### ISSUE TITLE
[Task]: discard-changes audit issues

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#11709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Turn tertiary button to secondary button, "discard changes"
- [x] On clicking "discard changes" make it say "are you sure?" in place
- [x] Use learn more instead of YES in notification banner
- [x] Get documentation pointed by LEARN MORE -> in notification banner
- [x] Use same progress bar as commit&push uses
- [x] Store state in browser for successfulDiscard and when the application loads, show a toast.
- [ ] Handle failure cases.

**Comment by hiteshjoshi** [comment]
- [ ] Handle failure cases needs brainstorming
