### ISSUE TITLE
[Task]: rest of the git sync polishing tasks

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#11750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Figure out scenarios in which error message come up, and 
- [ ] (try to) remove two error messages on git merge tab
- [x] Update design of disconnection, move error down below, remove breadcrumbs etc 
- [x] Improve repo disconnection messaging ( this has been deprioritised )
- [x] Error toast when remote branches are clicked ( will be resolved via #11757 )
- [x] Hover state for modal elements
- [x] Error should point towards field that needs fixing. ( this requires a design change to form elements overall )
- [ ] Add git error in a notification banner on connection tab

Refer:

Two error messages on git merge
![Two error messages on git merge](https://user-images.githubusercontent.com/217911/156349385-d71dcc89-8201-4472-b401-da9dcbded24f.jpeg)

Improve repo disconnection messaging
![](https://user-images.githubusercontent.com/217911/156343052-49ece49e-39ba-43ac-9c70-7a7133e3295d.png)
The following has been deprioritised because it is hard for user to find it
![](https://user-images.githubusercontent.com/217911/156347581-5cbc6304-260d-4bbc-92ba-a2632af9b5fd.jpeg)

Error toast when remote branches are clicked
![](https://user-images.githubusercontent.com/217911/156343155-5c454ab9-1541-4bad-b24e-54cc5d22a898.png)

Errors should point towards field that can be fixed to correct
(This will be taken up in a separate effort to bring form errors closer to form field.)
![](https://user-images.githubusercontent.com/217911/156347177-63298998-f087-4a0d-aee9-bd04165d272c.jpeg)

These tasks are taken from #11558

**Comment by vuiets** [comment]
De-prioritising
* Change in disconnect flow (We can pick this up as a part of Git Sync enhancements later on)

@Debsourabh to look at
* Hover state for modal
* Error should point towards field that needs fixing
* Improve repo disconnection messaging

@IAmAnubhavSaini to give error scenarios for Git Merge flows.

**Comment by IAmAnubhavSaini** [comment]
Updated Repo limit reached

![Screenshot 2022-03-11 at 12 07 51 AM](https://user-images.githubusercontent.com/1573771/157732504-deaa79d0-b6c3-40f6-8149-a260723f6df7.png)

Disconnect modal
![Screenshot 2022-03-10 at 11 28 56 PM](https://user-images.githubusercontent.com/1573771/157738662-a624fd91-eed3-4d6f-bf76-6b95c99bfa83.png)
![Screenshot 2022-03-10 at 11 28 46 PM](https://user-images.githubusercontent.com/1573771/157738668-6ed67369-2343-450c-b5ac-fe02d936f052.png)
