### ISSUE TITLE
[Bug]: Number of confirmation modals varies with the type of code JS objects is running and API

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Number of confirmation modals are not consistent for JS functions and API queries. 

`Api1.run()` called from `JSObject1.myFun1` is different than when running JSObject on page load without the API call.

Also, related issue is #11763 , observe the confirmation modals opens once for JS even though all are set to have seperate confirmation modals. But when JS object is calling an API that is not set to run on page load - then the JS function has a seperate modal for user confirmation.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/d73ad7d12b01480faafe53022d6df5c1-00001.gif)](https://www.loom.com/share/d73ad7d12b01480faafe53022d6df5c1)

### Steps To Reproduce

Repro from issue #11763 

### Version

Cloud

## Test Plan
- [ ] [[Test Cases]: verify the sequence of JS object execution on page load](https://github.com/appsmithorg/TestSmith/issues/1909)
- [ ] [[Test Case]: verify the sequence of confirmation model of JS object on page load](https://github.com/appsmithorg/TestSmith/issues/1910)
- [ ] [[Test Case]: verify the sequence of API calls on page load](https://github.com/appsmithorg/TestSmith/issues/1911)
- [ ] [[Test Case]: verify the sequence of confirmation model of API calls on page load](https://github.com/appsmithorg/TestSmith/issues/1912)

**Comment by Irongade** [comment]
This issue has been resolved.

**Comment by ramsaptami** [comment]
Each function/query call has a seperate modal that appears hence closing this issue
