### ISSUE TITLE
[Task]: Welcome tour updates and bugs

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#11893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Invert the positions of the CTA's in the intro modal for new users
- [x] Remove step 1 where the user has to update the query as there is a drop off in analytics compared to other steps. Instead we prefill the query as required.
- [x] Show the response tab in the query pane always. Currently it is shown once the query run is successfull.
- [x] Fix the position of the indicator in the explorer in step 2 while indicating to click on CustomersTable widget.
