### ISSUE TITLE
[Task]: Add new test cases for changes applied using Admin settings page

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#12064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Jest tests for new fields added
- [ ] Cypress tests for scenarios not yet added on Admin settings page
- [ ] Cypress tests for Admin settings integration with Login/Signup screen

**Comment by ankitakinger** [comment]
The remaining sub-tasks will be done in #12453
