### ISSUE TITLE
[Task]: Templates UI tweaks

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#12270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Remove usecases and function from filters for now
- [x] UI changes
- [x] Apply OR logic to filters previously it was OR.
- [x] Expand all filters for now.
- [x] Go back should work like browser back button

figma: https://www.figma.com/file/NV3FgZqqe88mU4Tozmwhmd/Templates-Phase-1-Designs-Handoff?node-id=2%3A1

_No response_
