### ISSUE TITLE
[Task]: Add cypress tests for Admin settings page

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#12453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Cypress tests for scenarios not yet added on Admin settings page
- [ ] Cypress tests for Admin settings integration with Login/Signup screen
