### ISSUE TITLE
[Task]:  RCA for #12318, #12520

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#12486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Submit an RCA for #12318 
- [x] Do an RCA for #12520

**Comment by Rishabh-Rathod** [comment]
link to RCA for https://github.com/appsmithorg/appsmith/issues/12318#issuecomment-1100655898
