### ISSUE TITLE
Task: Update property pane configuration dynamically 

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#12491]
For the dynamic height feature, widgets will have to register using widget configs to subscribe.
How will this work?
`hasDynamicHeight` property will be set to `true` for the widgets which would change height based on content. 
This will be set in `widgets/<WidgetFolder>/index.ts`

The `WidgetFactory` will add two properties to this widget's property pane configuration during the `registerBuilder` phase.

**Subtasks.**
- [ ] Table Widget 
- [ ] Text Widget 
- [ ] Container Widget 
- [ ] Modal 
- [ ] Tabs 
- [ ] List Widget 
- [ ] Form Widget 
- [ ] CheckboxGroup Widget 
- [ ] RadioGroup Widget 
- [ ] switch and switch group 
- [ ] Input Widget 
- [ ] Input Currency Widget 
- [ ] Input Phone Widget 
- [ ] Select widget 
- [ ] Multi-select widget 
- [ ] Tree select 
- [ ] Tree multiselect 
- [ ] Datepicker 
- [ ] JSON form widget
