### ISSUE TITLE
[Task]: Calculate possible performance improvement 

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#12593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] onPageLoad calls on server
- [ ] save dependencyMap on server
- [ ] createFirstTree cached for view mode on server

**Comment by SatishGandham** [comment]
@Rishabh-Rathod, Isn't improvement by moving createFirstTree to backend obvious? We save whatever time we spend in creating first tree.

**Comment by Rishabh-Rathod** [comment]
@SatishGandham As we discussed in the meeting, this is a high-effort task moving evaluation logic to the backend to be able to createFirstTree, and with numbers of how much time will it save, helps us prioritize it.
