### ISSUE TITLE
[Task]: User groups listing screen

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#13009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Listing all user groups UI
- [x] Search functionality
- [x] Delete user group
- [ ] Unit tests
