### ISSUE TITLE
[Task]: Single permission group screen

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#13012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Creation of hierarchical and lateral graph
- [x] Library functions for edit permission group
- [x] Parsing and displaying data for each tab
- [ ] Edit name of the permission group
- [ ] Search functionality

**Comment by albinAppsmith** [comment]
Closing this since all the sub tasks are created as separate tasks and assigned to RBAC EPIC
