### ISSUE TITLE
[Task]: Cypress tests for RBAC

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#13015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [X] Test infra
- [x] API integration

**Comment by hiteshjoshi** [comment]
Update : Test plan in review.

**Comment by RakshaKShetty** [comment]
CRUD operations
- [ ] https://github.com/appsmithorg/TestSmith/issues/1712
- [ ] https://github.com/appsmithorg/TestSmith/issues/1713
- [ ] https://github.com/appsmithorg/TestSmith/issues/1714
- [ ] https://github.com/appsmithorg/TestSmith/issues/1715
- [ ] https://github.com/appsmithorg/TestSmith/issues/1716
Multiple permissions
- [ ] https://github.com/appsmithorg/TestSmith/issues/1718
- [ ] https://github.com/appsmithorg/TestSmith/issues/1725
- [ ] https://github.com/appsmithorg/TestSmith/issues/1781
- [ ] https://github.com/appsmithorg/TestSmith/issues/1904
- [ ] https://github.com/appsmithorg/TestSmith/issues/1903

Invite Modal
- [ ] https://github.com/appsmithorg/TestSmith/issues/1720

**Comment by ankitakinger** [comment]
Pending tests:
- [ ] invite users via groups - Ankita
- [ ] invite modal on home page - Ankita
- [ ] audit logs negative scenario - Ankita
- [ ] Execute access spec create: execute, execute - binding, execute - page load, execute - popup if run query or not -> select yes, query timeout - Ankita
- [ ] delete permission: app level -> create new app to check this functionality as that same app is being used in next test -> create permission file - Parthvi
- [ ] after method issues - Parthvi
- [ ] Associate role tests - Parthvi
- [ ] edit permission page level -> add new assertions for widgets and queries - Sangeeth
- [ ] tests for omnibar - Sangeeth
- [ ] test for screenshot - Sangeeth
- [ ] all other negative scenarios
- [ ] Multiple permission tests -> think of scenarios
- [ ] EditGroups - for user is still left to do
- [ ] app/client/cypress/integration/Smoke_TestSuite_Fat/EnterpriseTests/RBAC/RBACUITests/Roles_spec.js
- [ ] Delete user from group

**Comment by ankitakinger** [comment]
All sub-tasks under this issue are complete. Closing this.
