### ISSUE TITLE
[Task]: Single User Group Page

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#13010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Edit user group name
- [x] Search functionality
- [x] Invite user to the user group flow
- [x] UI for existing users listing
- [x] Delete user from the user group
- [x] Permission group listing
- [x] Addition/Deletion of permission groups (assuming it’s a multi select dropdown)
- [x] Unit tests
