### ISSUE TITLE
[Task]: Permission groups listing screen

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#13011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Search functionality
- [x] Listing of existing permission groups
- [x] Delete permission group
- [x] Copy/Clone a permission group
- [x] Unit tests
