### ISSUE TITLE
[Task]: Analytics for SSO configuration

### ISSUE THREAD

**Issue by vuiets** [appsmithorg/appsmith#13071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

For the time being, these BE events should help support our community
- [ ] When a person configures an authentication mode (what's required here is the type of authentication mode that is configured)
- [ ] When a person removes an authentication mode

**Comment by vuiets** [comment]
From FE, for the Configuration funnel
* 'Enable' click on the authentication mode (along with the information on which authentication mode)
* 'Save and Restart' authentication mode configuration page

This is till we add validations and, if at all, autosave for OIDC/SAML configuration fields.

**Comment by trishaanand** [comment]
The ticket got closed for the frontend analytics changes getting merged in. Opening it back up for backend changes.

**Comment by vishnu-gp** [comment]
@vuiets BE Analytics events are now sent for all authentication methods on adding and removal.

**Comment by RakshaKShetty** [comment]
Not able to find back end events so reopening the issue

**Comment by vuiets** [comment]
@hiteshjoshi keeping this open, contrary to what we discussed on the planning call. This task was mainly for the BE events and there are some challenges to it. @vishnu-gp could share the challenge, there was a discussion on Slack about this.

**Comment by vishnu-gp** [comment]
Here's the Slack thread

https://theappsmith.slack.com/archives/C02K2MZERSL/p1655292473840249
