### ISSUE TITLE
[Bug]: [UI] Changes in the UI of entity explorer (needs design)

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#13108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] The currently selected page could be highlighted better
- [ ] Hover state and selected state for query/api/widget is the same

**Comment by arunvjn** [comment]
@aakashDesign Could please provide the necessary design changes required to fix this ?

**Comment by aakashDesign** [comment]
@arunvjn This issue needs to be picked by the design systems team. I've discussed this with @kocharrahul7 and have added it to our design planning board.
CC @vinay-appsmith

**Comment by rohitagarwal88** [comment]
Closing coz this is fixed in https://github.com/appsmithorg/appsmith/pull/22030
