### ISSUE TITLE
[Bug]: [UI] Entity Explorer mismatch between the design system and Production

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#13107]
### SubTasks

- [x]  Design mismatch with search vs. other inputs (https://www.notion.so/appsmith/Design-mismatch-with-search-vs-other-inputs-7f312a9d932f44699113ca02b8d191ae)
- [x]  Hover state on ‘Show all datasources’ is different from other items on the explorer. (https://www.notion.so/appsmith/Hover-state-on-Show-all-datasources-is-different-from-other-items-on-the-explorer-a6662d72145542679e202fd6593b12a6)
- [ ] #24262
- [x] Spacing issues in the entity explorer (https://www.notion.so/appsmith/Spacing-issues-in-Entity-Explorer-88248ee2318b4802bda8e4ff7677848f)

**Comment by hiteshjoshi** [comment]
@rohitagarwal88 are these accounted for? Or if they are already completed or being track somewhere else can we close this?

**Comment by rohitagarwal88** [comment]
@hiteshjoshi : I am creating a new board for the issues having a label **Design system**. We will track all issues there. Any issues that should be part of the new board just add the **Design system** label.

**Comment by rohitagarwal88** [comment]
created a separate issue for which is not fixed  https://github.com/appsmithorg/appsmith/issues/24262
closing this issues
