### ISSUE TITLE
[Task]: [UI] Changes in the UI of Page properties (needs design)

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#13109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Page Properties - The home icon is green. Inconsistent from explorer. (https://www.notion.so/appsmith/Page-Properties-The-home-icon-is-green-Inconsistent-from-explorer-6fe4d8a407fd4ddeab24749f9c0fc018)
- [ ] Hover states for Icons on the right (Settings, duplicate, etc) are missing. (https://www.notion.so/appsmith/Hover-states-for-Icons-on-the-right-Settings-duplicate-etc-are-missing-c6468f3c558847cb8ef7d2412d3fc377)

**Comment by arunvjn** [comment]
@aakashDesign Could please provide the necessary design changes required to fix this ?

**Comment by arunvjn** [comment]
Moving this back to product backlog till the designs are ready.
