### ISSUE TITLE
[Task]: [UI] Home page mismatch between the design system and Production

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#13110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Homepage - Cards in the organisation are not aligned with the Org. title (https://www.notion.so/appsmith/Homepage-Cards-in-the-organisation-are-not-aligned-with-the-Org-title-99aeaef4c3244ef0be5f29bd847cffed)
- [ ] Font size and font weight mismatch in the homepage sidebar (https://www.notion.so/appsmith/Font-size-and-font-weight-mismatch-in-the-homepage-sidebar-9784d786b61b46889783bac3f1edd635)
- [ ] Side nav - scrollbar is different
- [ ] The new organisation CTA is at wrong position in the prod.
- [ ] Font weights and sizes are different in the app card.
- [ ] Edit and Launch buttons position is different when compared to DS and the Prod.

**Comment by RoopKrrish9696** [comment]
**Here are the design system links for the above subtasks:**

cc @akash-codemonk @kocharrahul7 @vinay-appsmith 

1. Home page explorer - https://www.figma.com/file/i80YbQLLs5mXthjIHclPpX/Appsmith-Design-System?node-id=4998%3A24581

2. Home page cards - https://www.figma.com/file/i80YbQLLs5mXthjIHclPpX/Appsmith-Design-System?node-id=4546%3A52654

**Comment by rohitagarwal88** [comment]
Fixed in ADS 2.0
