### ISSUE TITLE
Add functionality contributors in Admin Page

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#13163]
Add the contributors email to give them access for a particular plugin in Admin Page, based on the existing functionality in the Integration Manager.

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/12972337-c415-404e-8865-67a36308a414)

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/2f4bfebf-6973-455d-a45e-9edb82cc13fe)

**Comment by felixsuarez0727** [comment]
Functionality contributors is added in Admin page, contributors can be added or deleted. It is located in the `feature/add-contributors-tap` branch.

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/d69e4030-37fa-435a-82f9-8b542fbccc42)

**Comment by yatinappsmith** [comment]
Need toi and access to this app before we can verify

**Comment by felixsuarez0727** [comment]
Functionality “Contributor” is added in Main branch, contributors can be added or deleted.

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/38d3789c-fbf6-4832-8343-f33d3a3e41f0)

**Note:** Ready for QA

**Comment by yatinappsmith** [comment]
- [ ] [[Test case][Saas Manager] Add invalid emails to contributor ](https://github.com/appsmithorg/TestSmith/issues/1924)
- [ ] [[Test case][Saas Manager] Delete contributor ](https://github.com/appsmithorg/TestSmith/issues/1923)
- [ ] [[Test case][Saas Manager] Add New contributor ](https://github.com/appsmithorg/TestSmith/issues/1922)

**Comment by yatinappsmith** [comment]
Bugs reported https://github.com/appsmithorg/appsmith/issues/14884
https://github.com/appsmithorg/appsmith/issues/14883

**Comment by felixsuarez0727** [comment]
Fixed bugs on issues  https://github.com/appsmithorg/appsmith/issues/14884  and https://github.com/appsmithorg/appsmith/issues/14883.

Added function to validate emails and close modal

![imagen.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/4a301375-57b9-4b90-be8b-b1de96db9c9e)
