### ISSUE TITLE
[Task]: Add in the following backend analytics events

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#13342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Number of Queries on publish app
- [ ] Page count doesn't seem to be working
