### ISSUE TITLE
[Task]: Use design system based colour names

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#13510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Please do not add randomly named colours in app/client/src/constants/Colors.tsx

The first line in the file is:
```
// Color Names generated from http://chir.ag/projects/name-that-color 
```

Do not generate colour names from the link above!

Please take a look at design system -> colour for naming. If a colour is needed and is not in the DS, then ask designers to put it there.

Examples of correct naming, as per DS:
```
  //  Following Design System colours
  GREY_1: "#FAFAFA",
  GREY_2: "#F0F0F0",
  GREY_3: "#EBEBEB",
  GREY_4: "#E8E8E8",
  GREY_5: "#E0DEDE",
  GREY_6: "#A9A7A7",
  GREY_7: "#858282",
  GREY_8: "#716E6E",
  GREY_9: "#4B4848",
  GREY_10: "#090707",
  GREY_11: "#9F9F9F",
  GREY_200: "#E7E7E7",
  GREY_800: "#393939",
```

Examples of incorrect naming:

```
SCORPION: "#575757",
COD_GRAY: "#191919",
MINE_SHAFT_2: "#333333",
```

---

## Tasks

- [ ] Remove the comment in the first line
- [ ] Add all of the design system colours
- [ ] Move whole application from old names to newer, design system based colour names

**Comment by rohitagarwal88** [comment]
Fixed in ADS 2.0
