### ISSUE TITLE
[Feature] Twilio 1.2 API Saas Integration

### ISSUE THREAD

**Issue by felixsuarez0727** [appsmithorg/appsmith#13756]
### Description: 

Provider of cloud communications platform as a service.

------------------------
### Documentation:

https://www.twilio.com/docs

------------------------
### TO-DO

------------------------
### API Actions Progress
| Action                             | EngSpec Doc | SaaS Manager App | SaaS App Run | Test App Run | QA  |
| ---                                | ---         | ---              | ---          | ---          | --- |
| Create Message | Yes | Yes  | Yes | Yes | No  |             
| Schedule Message | Yes | Yes  | Yes | Yes | No  |                  
| Fetch Message  | Yes | Yes  | Yes | Yes  | No  |         
| List Message | Yes | Yes  | Yes | Yes  | No  |      
| Update Message | Yes | Yes  | Yes | Yes  | No  |     
| Delete Message  | Yes | Yes  | Yes | Yes | No  |          
 
------------------------
### Notes 
This is a Twilio integration test, to do all new changes 

### Twilio Integration Observations

|Question/Observation | Related Issue | Resolved |
| ---                                | ---         | ---              |
|  Instead of Username / Password, can we have account SID and auth token in the datasource screen?                                  |   #13758                     |    Yes           |
|The Twilio icon is blurry, we need a proper sharp icon   | #13696   |  Yes  |
| We should have a default for fields like pageSize  |  #13759  | Yes  |
|Can we add tooltips / subtexts like we do for UQI in the query screen?   | #13760  | **Yes** |
| The account SID should always be the first field. It's in different positions depending on the command. Same with the message sid or service sid  |  #13507  |  Yes  |
|To and From are required fields but they don't have a * next to their names | Not applicable, see[ documentation notion](https://www.notion.so/appsmith/To-and-From-are-required-fields-but-they-don-t-have-a-next-to-their-names-124f2432520b4ebfaeb3d5f0c9e5d3ff) | Yes  |
|The order of commands should be Create Message, Schedule Message, List Messages, Fetch Message, Delete Message, Update Message.  | #13537  | Yes |
|For scheduling a message, schedule type doesn't seem configurable so does it need a user input? It can just be hardcoded to fixed right? | #13762 | Yes |
|For the send At field, we should mention the date format in the tooltip / subtext. Placeholder is not enough especially when you're typing | #13506 | Yes|
|For update message, status is an enum field. This can be a dropdown instead of an input right? | #13733 | Yes|
| When creating a twilio datasource, I first see the dropdown to select the authentication type. This contains only one value, “Basic Auth” - so why even show this field? | #12565 | **No** |
| When creating a twilio datasource, I see the fields “username” and “password”, in which I need to enter the twilio “Account SID” and “Auth Token”. why not change the labels of these datasource fields?| #13758 | Yes |
|When creating a query, why do I need to provide the “Twilio Account SID” when I have already specified it in the datasource? |  #14035 | **No**|

**Comment by prapullac** [comment]
Please find the test cases [here ](https://docs.google.com/spreadsheets/d/1RSpbsLiYBDIxtajo1MJW528Np8gMt2UcZ_1zRbcsO6Q/edit#gid=1971687157)

**Comment by felixsuarez0727** [comment]
| Test Case                                                                                                                | Issue                                                         | Status      |
| ---                                                                                                                      | ---                                                           | ---         |
| Entity Explorer: Test cases with respect to action that can be done on Entity explorer                                   | [#1869](https://github.com/appsmithorg/TestSmith/issues/1869) | Pending     |
| Query Pane: Test ideas for Query Pane                                                                                    | [#1868](https://github.com/appsmithorg/TestSmith/issues/1868) | Pending     |
| Active Datasource: Tests on active datasource behaviour                                                                  | [#1867](https://github.com/appsmithorg/TestSmith/issues/1867) | Pending     |
| Connections: Establish connection with Twilio                                                                            | [#1866](https://github.com/appsmithorg/TestSmith/issues/1866) | In Progress |
| Query Pane: Ensure user is able to save the queries                                                                      | [#299](https://github.com/appsmithorg/TestSmith/issues/299)   | Pending     |
| Query Pane: Ensure user is able to add special characters into the name from Pane                                        | [#298](https://github.com/appsmithorg/TestSmith/issues/298)   | Pending     |
| Query Pane: Ensure user is able to add longer name                                                                       | [#297](https://github.com/appsmithorg/TestSmith/issues/297)   | Pending     |
| Query Pane: Ensure user is able change name from the pane                                                                | [#296](https://github.com/appsmithorg/TestSmith/issues/296)   | Pending     |
| Query Pane: Ensure use method from the drop down                                                                         | [#295](https://github.com/appsmithorg/TestSmith/issues/295)   | Pending     |
| Query Pane: Ensure Long body form is added                                                                               | [#294](https://github.com/appsmithorg/TestSmith/issues/294)   | Pending     |
| Query Pane: Ensure the user is displayed appropriate error messages on wrong field data                                  | [#293](https://github.com/appsmithorg/TestSmith/issues/293)   | Pending     |
| Query Pane: Ensure mandatory Field are added                                                                             | [#292](https://github.com/appsmithorg/TestSmith/issues/292)   | Pending     |
| Active Datasource: Ensure if a Query is inactive datasource must be deleted                                              | [#291](https://github.com/appsmithorg/TestSmith/issues/291)   | Pending     |
| Active Datasource: Clicking on Delete from Action icon the action must verify if Query is assocuated with the Datasource | [#290](https://github.com/appsmithorg/TestSmith/issues/290)   | Pending     |
| Connections: Ensure clicking on the back button user should be navigated to active Datasources page                      | [#289](https://github.com/appsmithorg/TestSmith/issues/289)   | Pending     |
| Connections: Ensure on delete if the DS is associated with a query the DS must show an error and unable to delete        | [#288](https://github.com/appsmithorg/TestSmith/issues/288)   | Pending     |
| Connections: Ensure clicking on Delete the DS gets deleted                                                               | [#287](https://github.com/appsmithorg/TestSmith/issues/287)   | Pending     |
| Connections: Ensure user is disaplyed with Auth type and user is able to select Basic Auth                               | [#286](https://github.com/appsmithorg/TestSmith/issues/286)   | Pending     |

**Comment by felixsuarez0727** [comment]
Since there's no method to install individual Integrations to local instances of Appsmith for testing, Nidhi suggested copying the integration config from Prod to Release and enable Twilio on Release. 

To do this, a page was created on the SaaS App to copy the integration's config from Prod to Release. This page will have to meet the following criteria:

- [x] Have dropdown with ONLY 3 collections: plugin, actionTemplate, datasourceTemplate.
- [x] Confirmation is required to run any query that will write to Cloud Services.
- [ ] That this page is not visible by default to the end users of the App, only to admins.

We asked Nidhi to review the queries before running any of them. After having using this, Twilio can be tested on release using Cypress.

Will post an update once this is done

**Comment by felixsuarez0727** [comment]
The feature to import integrations from Prod to Release will be tracked on #15079


Automated testing progress will be tracked on #15134
