### ISSUE TITLE
[Task]: Single User Edit Page

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#13834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] UI for user groups & user information
- [x] Remove user group for a user
- [x] Delete user
- [x] Unit tests
