### ISSUE TITLE
[Task]: Optimise allKeys generation and revisit getAllPaths logic

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#13982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

1. Currently we generate allKeys in `updateDependencyMap`. This is an expensive logic and we could avoid this by tracking differences and adding/removing paths from allKeys accordingly. 
    - [ ] Make sure to run `getAllPaths` only in `createDependencyMap` 

2. Current `getAllPaths` generate paths to 

    `dataFields`, `logBlackList`, `bindingPaths`, `triggerPaths`, `reactivePaths`, `validationPaths`, `dynamicBindingPathList`, `parentId`, `propertyOverrideDependency`, `overridingPropertyPaths`, `privateWidgets`, `ENTITY_TYPE`
    
    these are all internal properties and may not be needed in `allKeys` when generating in `dependencyMap`.
    - [ ] verify if we really need this path. 
    - [ ] If not needed change the logic to selectively add paths that are required.
    

Example of `allKeys`data for application with 5 widgets and 1 Api.

```
 Text1: true,
      'Text1.logBlackList': true,
      'Text1.logBlackList.value': true,
      'Text1.widgetId': true,
      'Text1.widgetName': true,
      'Text1.bottomRow': true,
      'Text1.isLoading': true,
      'Text1.leftColumn': true,
      'Text1.parentColumnSpace': true,
      'Text1.parentRowSpace': true,
      'Text1.renderMode': true,
      'Text1.rightColumn': true,
      'Text1.topRow': true,
      'Text1.type': true,
      'Text1.parentId': true,
      'Text1.version': true,
      'Text1.bindingPaths': true,
      'Text1.reactivePaths': true,
      'Text1.reactivePaths.value': true,
      'Text1.triggerPaths': true,
      'Text1.validationPaths': true,
      'Text1.ENTITY_TYPE': true,
      'Text1.propertyOverrideDependency': true,
      'Text1.overridingPropertyPaths': true,
      'Text1.privateWidgets': true,
      'Text1.text': true,
      'Text1.value': true,
      'Text1.defaultProps': true,
      'Text1.defaultMetaProps': true,
      'Text1.dynamicBindingPathList': true,
      'Text1.dynamicBindingPathList[0]': true,
      'Text1.dynamicBindingPathList[0].key': true,
      'Text1.meta': true,
      Text2: true,
      'Text2.logBlackList': true,
      'Text2.logBlackList.value': true,
      'Text2.widgetId': true,
      'Text2.widgetName': true,
      'Text2.bottomRow': true,
      'Text2.isLoading': true,
      'Text2.leftColumn': true,
      'Text2.parentColumnSpace': true,
      'Text2.parentRowSpace': true,
      'Text2.renderMode': true,
      'Text2.rightColumn': true,
      'Text2.topRow': true,
      'Text2.type': true,
      'Text2.parentId': true,
      'Text2.version': true,
      'Text2.bindingPaths': true,
      'Text2.reactivePaths': true,
      'Text2.reactivePaths.value': true,
      'Text2.reactivePaths.text': true,
      'Text2.triggerPaths': true,
      'Text2.validationPaths': true,
      'Text2.ENTITY_TYPE': true,
      'Text2.propertyOverrideDependency': true,
      'Text2.overridingPropertyPaths': true,
      'Text2.privateWidgets': true,
      'Text2.text': true,
      'Text2.dynamicBindingPathList': true,
      'Text2.dynamicBindingPathList[0]': true,
      'Text2.dynamicBindingPathList[0].key': true,
      'Text2.dynamicBindingPathList[1]': true,
      'Text2.dynamicBindingPathList[1].key': true,
      'Text2.value': true,
      'Text2.defaultProps': true,
      'Text2.defaultMetaProps': true,
      'Text2.meta': true,
      Text3: true,
      'Text3.logBlackList': true,
      'Text3.logBlackList.value': true,
      'Text3.widgetId': true,
      'Text3.widgetName': true,
      'Text3.bottomRow': true,
      'Text3.isLoading': true,
      'Text3.leftColumn': true,
      'Text3.parentColumnSpace': true,
      'Text3.parentRowSpace': true,
      'Text3.renderMode': true,
      'Text3.rightColumn': true,
      'Text3.topRow': true,
      'Text3.type': true,
      'Text3.parentId': true,
      'Text3.version': true,
      'Text3.bindingPaths': true,
      'Text3.reactivePaths': true,
      'Text3.reactivePaths.value': true,
      'Text3.reactivePaths.text': true,
      'Text3.triggerPaths': true,
      'Text3.validationPaths': true,
      'Text3.ENTITY_TYPE': true,
      'Text3.propertyOverrideDependency': true,
      'Text3.overridingPropertyPaths': true,
      'Text3.privateWidgets': true,
      'Text3.text': true,
      'Text3.dynamicBindingPathList': true,
      'Text3.dynamicBindingPathList[0]': true,
      'Text3.dynamicBindingPathList[0].key': true,
      'Text3.dynamicBindingPathList[1]': true,
      'Text3.dynamicBindingPathList[1].key': true,
      'Text3.value': true,
      'Text3.defaultProps': true,
      'Text3.defaultMetaProps': true,
      'Text3.meta': true,
      Dropdown1: true,
      'Dropdown1.logBlackList': true,
      'Dropdown1.logBlackList.selectedOptionLabel': true,
      'Dropdown1.logBlackList.selectedOptionValue': true,
      'Dropdown1.logBlackList.isValid': true,
      'Dropdown1.widgetId': true,
      'Dropdown1.widgetName': true,
      'Dropdown1.bottomRow': true,
      'Dropdown1.isLoading': true,
      'Dropdown1.leftColumn': true,
      'Dropdown1.parentColumnSpace': true,
      'Dropdown1.parentRowSpace': true,
      'Dropdown1.renderMode': true,
      'Dropdown1.rightColumn': true,
      'Dropdown1.topRow': true,
      'Dropdown1.type': true,
      'Dropdown1.parentId': true,
      'Dropdown1.version': true,
      'Dropdown1.bindingPaths': true,
      'Dropdown1.reactivePaths': true,
      'Dropdown1.reactivePaths.selectedOptionLabel': true,
      'Dropdown1.reactivePaths.selectedOptionValue': true,
      'Dropdown1.reactivePaths.isValid': true,
      'Dropdown1.reactivePaths.selectedOption': true,
      'Dropdown1.reactivePaths.filterText': true,
      'Dropdown1.reactivePaths.defaultOptionValue': true,
      'Dropdown1.reactivePaths.': true,
      'Dropdown1.reactivePaths.meta.selectedOption': true,
      'Dropdown1.reactivePaths.meta.filterText': true,
      'Dropdown1.triggerPaths': true,
      'Dropdown1.validationPaths': true,
      'Dropdown1.ENTITY_TYPE': true,
      'Dropdown1.propertyOverrideDependency': true,
      'Dropdown1.propertyOverrideDependency.selectedOption': true,
      'Dropdown1.propertyOverrideDependency.selectedOption.DEFAULT': true,
      'Dropdown1.propertyOverrideDependency.selectedOption.META': true,
      'Dropdown1.propertyOverrideDependency.filterText': true,
      'Dropdown1.propertyOverrideDependency.filterText.DEFAULT': true,
      'Dropdown1.propertyOverrideDependency.filterText.META': true,
      'Dropdown1.overridingPropertyPaths': true,
      'Dropdown1.overridingPropertyPaths.defaultOptionValue': true,
      'Dropdown1.overridingPropertyPaths.defaultOptionValue[0]': true,
      'Dropdown1.overridingPropertyPaths.defaultOptionValue[1]': true,
      'Dropdown1.overridingPropertyPaths.meta.selectedOption': true,
      'Dropdown1.overridingPropertyPaths.meta.selectedOption[0]': true,
      'Dropdown1.overridingPropertyPaths.': true,
      'Dropdown1.overridingPropertyPaths.[0]': true,
      'Dropdown1.overridingPropertyPaths.meta.filterText': true,
      'Dropdown1.overridingPropertyPaths.meta.filterText[0]': true,
      'Dropdown1.privateWidgets': true,
      'Dropdown1.options': true,
      'Dropdown1.options[0]': true,
      'Dropdown1.options[0].label': true,
      'Dropdown1.options[0].value': true,
      'Dropdown1.options[1]': true,
      'Dropdown1.options[1].label': true,
      'Dropdown1.options[1].value': true,
      'Dropdown1.defaultOptionValue': true,
      'Dropdown1.': true,
      'Dropdown1.selectedOptionLabel': true,
      'Dropdown1.selectedOptionValue': true,
      'Dropdown1.isValid': true,
      'Dropdown1.defaultProps': true,
      'Dropdown1.defaultProps.selectedOption': true,
      'Dropdown1.defaultProps.filterText': true,
      'Dropdown1.defaultMetaProps': true,
      'Dropdown1.defaultMetaProps[0]': true,
      'Dropdown1.defaultMetaProps[1]': true,
      'Dropdown1.dynamicBindingPathList': true,
      'Dropdown1.dynamicBindingPathList[0]': true,
      'Dropdown1.dynamicBindingPathList[0].key': true,
      'Dropdown1.dynamicBindingPathList[1]': true,
      'Dropdown1.dynamicBindingPathList[1].key': true,
      'Dropdown1.dynamicBindingPathList[2]': true,
      'Dropdown1.dynamicBindingPathList[2].key': true,
      'Dropdown1.meta': true,
      'Dropdown1.meta.selectedOption': true,
      'Dropdown1.meta.filterText': true,
      Table1: true,
      'Table1.logBlackList': true,
      'Table1.logBlackList.selectedRow': true,
      'Table1.logBlackList.selectedRows': true,
      'Table1.widgetId': true,
      'Table1.widgetName': true,
      'Table1.bottomRow': true,
      'Table1.isLoading': true,
      'Table1.leftColumn': true,
      'Table1.parentColumnSpace': true,
      'Table1.parentRowSpace': true,
      'Table1.renderMode': true,
      'Table1.rightColumn': true,
      'Table1.topRow': true,
      'Table1.type': true,
      'Table1.parentId': true,
      'Table1.version': true,
      'Table1.bindingPaths': true,
      'Table1.reactivePaths': true,
      'Table1.reactivePaths.selectedRow': true,
      'Table1.reactivePaths.selectedRows': true,
      'Table1.reactivePaths.defaultSearchText': true,
      'Table1.reactivePaths.defaultSelectedRow': true,
      'Table1.reactivePaths.tableData': true,
      'Table1.triggerPaths': true,
      'Table1.validationPaths': true,
      'Table1.ENTITY_TYPE': true,
      'Table1.propertyOverrideDependency': true,
      'Table1.propertyOverrideDependency.searchText': true,
      'Table1.propertyOverrideDependency.searchText.DEFAULT': true,
      'Table1.propertyOverrideDependency.searchText.META': true,
      'Table1.propertyOverrideDependency.selectedRowIndex': true,
      'Table1.propertyOverrideDependency.selectedRowIndex.DEFAULT': true,
      'Table1.propertyOverrideDependency.selectedRowIndex.META': true,
      'Table1.propertyOverrideDependency.selectedRowIndices': true,
      'Table1.propertyOverrideDependency.selectedRowIndices.DEFAULT': true,
      'Table1.propertyOverrideDependency.selectedRowIndices.META': true,
      'Table1.overridingPropertyPaths': true,
      'Table1.overridingPropertyPaths.defaultSearchText': true,
      'Table1.overridingPropertyPaths.defaultSearchText[0]': true,
      'Table1.overridingPropertyPaths.defaultSelectedRow': true,
      'Table1.overridingPropertyPaths.defaultSelectedRow[0]': true,
      'Table1.overridingPropertyPaths.defaultSelectedRow[1]': true,
      'Table1.privateWidgets': true,
      'Table1.tableData': true,
      'Table1.dynamicBindingPathList': true,
      'Table1.dynamicBindingPathList[0]': true,
      'Table1.dynamicBindingPathList[0].key': true,
      'Table1.dynamicBindingPathList[1]': true,
      'Table1.dynamicBindingPathList[1].key': true,
      'Table1.dynamicBindingPathList[2]': true,
      'Table1.dynamicBindingPathList[2].key': true,
      'Table1.defaultSearchText': true,
      'Table1.defaultSelectedRow': true,
      'Table1.selectedRow': true,
      'Table1.selectedRow.test': true,
      'Table1.selectedRow.raw': true,
      'Table1.selectedRows': true,
      'Table1.defaultProps': true,
      'Table1.defaultProps.searchText': true,
      'Table1.defaultProps.selectedRowIndex': true,
      'Table1.defaultProps.selectedRowIndices': true,
      'Table1.defaultMetaProps': true,
      'Table1.defaultMetaProps[0]': true,
      'Table1.defaultMetaProps[1]': true,
      'Table1.defaultMetaProps[2]': true,
      'Table1.meta': true,
      'Table1.selectedRowIndex': true,
      Text4: true,
      'Text4.logBlackList': true,
      'Text4.logBlackList.value': true,
      'Text4.widgetId': true,
      'Text4.widgetName': true,
      'Text4.bottomRow': true,
      'Text4.isLoading': true,
      'Text4.leftColumn': true,
      'Text4.parentColumnSpace': true,
      'Text4.parentRowSpace': true,
      'Text4.renderMode': true,
      'Text4.rightColumn': true,
      'Text4.topRow': true,
      'Text4.type': true,
      'Text4.parentId': true,
      'Text4.version': true,
      'Text4.bindingPaths': true,
      'Text4.reactivePaths': true,
      'Text4.reactivePaths.text': true,
      'Text4.reactivePaths.value': true,
      'Text4.triggerPaths': true,
      'Text4.validationPaths': true,
      'Text4.validationPaths.text': true,
      'Text4.validationPaths.text.type': true,
      'Text4.ENTITY_TYPE': true,
      'Text4.propertyOverrideDependency': true,
      'Text4.overridingPropertyPaths': true,
      'Text4.privateWidgets': true,
      'Text4.text': true,
      'Text4.dynamicBindingPathList': true,
      'Text4.dynamicBindingPathList[0]': true,
      'Text4.dynamicBindingPathList[0].key': true,
      'Text4.dynamicBindingPathList[1]': true,
      'Text4.dynamicBindingPathList[1].key': true,
      'Text4.value': true,
      'Text4.defaultProps': true,
      'Text4.defaultMetaProps': true,
      'Text4.meta': true,
      Api1: true,
      'Api1.clear': true,
      'Api1.logBlackList': true,
      'Api1.actionId': true,
      'Api1.name': true,
      'Api1.datasourceUrl': true,
      'Api1.config': true,
      'Api1.config.timeoutInMillisecond': true,
      'Api1.dynamicBindingPathList': true,
      'Api1.isLoading': true,
      'Api1.pluginType': true,
      'Api1.run': true,
      'Api1.data': true,
      'Api1.data[0]': true,
      'Api1.data[0].test': true,
      'Api1.data[1]': true,
      'Api1.data[1].test': true,
      'Api1.responseMeta': true,
      'Api1.responseMeta.isExecutionSuccess': true,
      'Api1.ENTITY_TYPE': true,
      'Api1.bindingPaths': true,
      'Api1.reactivePaths': true,
      'Api1.reactivePaths.isLoading': true,
      'Api1.reactivePaths.data': true,
      'Api1.dependencyMap': true
    }
```
