### ISSUE TITLE
[Type]-[260]:Sunset 'Realtime Commenting' as a feature

### ISSUE THREAD

**Issue by vuiets** [appsmithorg/appsmith#14173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

We aren't going to continue supporting and building on top of commenting as a collaboration feature. We're sunsetting it since it hasn't added enough value to the community.

### SubTasks
- [ ] Add deprecation to each release note henceforth.
- [ ] Add deprecation notice for all users on the comment icon.
- [ ] Add deprecation notice for all users on the notification icon.
- [ ] Add deprecation notice on the comment notification email.
- [ ] Remove feature in 2 weeks. (from the first notification)

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 65 |
| Effort (months)  | 0.5 |

**Comment by kocharrahul7** [comment]
### SubTasks
- [ ] Create a feature flag which will only allow users who are already using commenting to keep using it
- [ ] move APIs calling the commenting features behind the Feature Flag
- [ ] hiding buttons to show and hide comments/enter commenting mode behind the feature flag
- [ ] moving the Hotkeys behind the feature flag (if this is an issue, we can move to disable the hotkeys)


This will allow us to address the current users, while preventing new users from accessing comments.


Points to address:
- [ ] How to move old users off comments as well
