### ISSUE TITLE
[Epic] Canvas Undo/Redo Phase I

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1426]
# Objective
Provide a feature to undo / redo (U/R) actions in the editor (on the canvas) with up to 200 updates.
In the process of building fast, many unforced errors occur which need to be undone. Enabling faster iteration leads to more usage and a better building experience

## Related issues
- [ ] #3917
- [x] #3916
- [x] #3649
- [x] #3918
- [x] #3919
- [x] #3915 
- [x] #5058
- [x] #5059
- [ ] #5060

# Success Metrics
List of all metrics you are tracking and the desired goal.
| Goal  | Metric |
| ------------- | ------------- |
| Encourage the use of undo/redo  | Number of times that people used undo or redo  |
| Let developers to explore and be creative  | Number of people that have used undo or redo more than 20 times at once |

# Assumptions
List any assumptions that you have about your users, technical constraints, or business goals (e.g., Most users will access this feature from tablet).

- Developers want to have undo and redo for the property pane as well

# Requirements
| Requirement   | User Story | Importance | Notes |
| ------------- | ------------- | ------------- | ------------- |
| Undo/Redo for the components  | As a User, I want to be able to U/R the actions that I make on the canvas  | High  |  For dropping a widget, pasting something, removing a widget (cutting as well), changing size etc. |
| U/R in small steps in the property pane | As a user I want to be able to undo what I did in property pane and not lose all my work even after I close the property pane | High  |   |
| Onboarding for the feature | As an existing user that has already tried all the shortcuts for U/R I need to be informed about this new feature  | High  |   |
| Maximum of 200 updates | As a user I want to be able to work care-free when it comes to undo/redo of my work  | High  |   |
| Undo and redo action in a menu behind the logo in the navigation bar | As a user I want to be able to find these actions in the app and not have to search how to do it online  | Medium  |   |
| Version History (Non-linear undo) | As a user I want to skip to a previous version from version history  | Medium  |   |

# Out of Scope
List the things that are out of cope or might be revisited after the first release.
- Undo/redo for anything that is not on the canvas
- Undo/redo across page transitions. As pages can be edited outside of context in a different session, moving from on page to another will not maintain undo/redo context.

# Developer Handoff Document in Figma
Link to the developer Handoff Document: 
https://www.figma.com/file/SHl5JRGZ7AtuwIiiZtCe5U/Undo-Redo-Feature-Handoff-Mon-7-Jun-2021?node-id=0%3A1

# Questions
| Question  | Answer | Date Answered |
| ------------- | ------------- | ------------- |
| Do we enable the users to undo changes in the property pane with tiny steps?  | Yes (Slack discussion https://theappsmith.slack.com/archives/C01J5915Z89/p1622640625119600)  | June 2nd 2021  |

**Comment by riodeuno** [comment]
Undo Redo Product Note:

Scope Phase I:
- [ ] Undo - Redo implementation works in the context of the DSL, which is the Canvas.

Scenarios:
- [ ] Undo and Redo will technically walk through DSL updates. So if anything in the DSL updates, it can be undone and redone.
- [ ] Undo drop widget should remove widget
- [ ] Undo after widget property change should undo the property change
- [ ] User updates a widget property, user closes the property pane - undo here undos the property change
- [ ] Undo works for a minimum of 10 dsl updates.
- [ ] Undo after copy and paste, undos the paste
- [ ] Undo after cut undos the cut
- [ ] Undo after paste undos the paste

Tasks:
- [ ] Platform change to include the DSL in a data structure which allows for tracking and merging changes
- [ ] Undo and Redo operation functions - implementation
- [ ] Implement and test undo redo - as there can be collateral widget property update operations. These are not always atomic.
      We track undo and redo based on actual dsl update actions. Needs triaging
- [ ] Undo redo buttons UI - Needs design.
- [ ] Unit tests for undo redo methods
- [ ] Cypress test for all scenarios above.

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno will it work for 
- Size / position changes
- Meta property updates

**Comment by riodeuno** [comment]
@Nikhil-Nandagopal According to the plans of phase I, this will work for size and position changes, however, it will not effect meta properties. 
We can look into meta properties in the second phase of the project. 
Undo and redo already works for meta properties in Input widget, Rich Text Editor widget, however, it does not for table widget.

**Comment by riodeuno** [comment]
Design overview: https://miro.com/app/board/o9J_l3YFsis=/
