### ISSUE TITLE
[Task]: Template page selection

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#14449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] UI
- [x] Page names for single page templates are not showing up (backend)
- [x] Page id's are required to show the same in the iframe. (backend)
- [x] Select pages to fork and preview them
