### ISSUE TITLE
[Task]-[7142.85]: Use AST parsing of JS function to determine isFunctionAsync

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#14618]
### Issues this task aim to resolve
- https://github.com/appsmithorg/appsmith/issues/14229
- https://github.com/appsmithorg/appsmith/issues/13888
- https://github.com/appsmithorg/appsmith/issues/11589
- https://github.com/appsmithorg/appsmith/issues/12639

### Problems with current approach

when we try to parse JS function which has
1. a conditional code ( myFunc2 ) or 
2. a code with data which is yet not defined while parsing then ( myFun1 )
for those case we failed to determine if the function as actually sync or async.

| Datatree | code |
|---|---|
| ![SCR-20220616-t7u](https://user-images.githubusercontent.com/23132741/174239472-60a36f55-45cd-49ee-8bde-542f5bdd2165.png) | ![SCR-20220616-t87](https://user-images.githubusercontent.com/23132741/174239493-7e51c8c7-49ef-4ac2-8714-2a863c2f364f.png) |

### Solutions

we could parse JS function code via AST and then determine if any `async` action is used in the JS code or not and accordingly decide isFunctionAsync
we could do it in 2 steps
1. ~initial complete JS function code parsing.~ 
2. ~diff code parsing. ( to avoid parsing complete function again when it is edited ) [ just if we feel 1st is slow alone ]~

As we are already parsing JSObject, we could just use parsed JSObject node and determine `isFunctionAsync`

_In future we could let backend do this if this becomes heavy for frontend._

### SubTasks
- [x] Build POC to determine isFunctionAsync using AST Node ( WIP [fix/isAsync-AST](https://github.com/appsmithorg/appsmith/tree/fix/isAsync-AST) )
If POC looks great
- [ ] Complete the implementation and warning for async action assignment to variable
- [ ] Make sure all previous test passes and add more cases if needed

**Comment by Rishabh-Rathod** [comment]
Closing this as parsing changes implemented by Apeksha complete above tasks.

**Comment by Rishabh-Rathod** [comment]
> Closing this as parsing changes implemented by Apeksha complete above tasks.

Parsing changes doesn't add AST for `isFunctionAsync` hence opening this issue again.

**Comment by Rishabh-Rathod** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1250 |
| Effort (months)  | 0.45 |

**Comment by Rishabh-Rathod** [comment]
Moved this to product backlog as issues it resolve are already in product backlog.

**Comment by Rishabh-Rathod** [comment]
We won't be going ahead with AST parsing to solve the tagged issues.  

Internal discussions to understand better https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1666356500517309?thread_ts=1666252020.048049&cid=C02K0SZQ7V3
