### ISSUE TITLE
[Task]: Remove `__evaluation__.evaluatedValues` from dataTree reducing the size of it

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#14710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

We maintain the evaluatedValues of each entity inside dataTree object at propertyPaths and also inside `__evaluation__.evaluatedValues`.

This values are duplicate and after each evaluation when we run 

`diff(oldDataTree,dataTree)` this adds 50% more effort because of duplicate diffs.

- [ ] We make sure to remove usage of `__evaluation__.evaluatedValues` from JSONForm
- [ ] Remove the `__evaluation__.evaluatedValues`
- [ ] measure the performance improvement

Internal discussion on this - https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1655741672536679
