### ISSUE TITLE
[Epic]: Table updates (2.1) : Inline editing validations, switch, select & checkbox column types

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#15473]
### Objective

Updates to newly added Table widget (v2)
- [x] Inline editing validations - https://github.com/appsmithorg/appsmith/issues/13670
- [x] Switch column type- https://github.com/appsmithorg/appsmith/issues/6770
- [ ] Select column type & - https://github.com/appsmithorg/appsmith/issues/6766
- [x] Checkbox column type - https://github.com/appsmithorg/appsmith/issues/7338

### Success Metrics

| Metric         |
| -------------- |
| Customer satisfaction score increases  |
| Decrease churn rate down to 30%        |

### Prioritised User Stories

| User Story    |
| ------------- |
| As a user, I should be able to control the values that can be updated in table cells  |
| As a user, I should to be able to use switch, select & checkbox column types in table  |

### Developer Handoff Document in Figma

https://www.figma.com/file/aJ2Hwz9gH5AK6zaRYtZV8a/Table-widget-update

### RACI matrix

| ------------- | ------------- |
| Responsible   |  @sbalaji1192 @keyurparalkar  |
| Accountable   |    @sbalaji1192 @dilippitchika  |
| Consulted     | @riodeuno  |
| Informed      |    @ashit-rath   |
