### ISSUE TITLE
Widget Grouping

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1568]

**Comment by Debsourabh** [comment]
Description
Appsmith developers often need to perform actions that apply to multiple widgets and not just one widget.

Examples of activities:

1. Delete multiple widgets
2. Copy/Paste multiple widgets
3. ~~Resize multiple widgets~~
4. ~~Move widgets~~
5. Convert grouped widgets selected through a polygon into a container
6. Make the Multiple Selection Property Pane floating. Update the new position when they haven't clicked on a new widget. 
7. Remove Widget Information, Add Align to Container and Group, Make the buttons more clickable.

## Sub Tasks

- [ ] Widgets selection can be toggled (both select and unselect) with `meta + left mouse click`
- [ ]  Widget can be selected by click + drag of the mouse from an empty space in the canvas to create a rectangular area, which will select any widget whose edge falls in the area
- [ ]  Widget groups can be unselected using the `Esc` key
- [ ]  Widget groups on select will have a context menu for actions and `cancel` for unselecting widget group
- [ ]  Widget groups can be copied from context menu and `meta + c`
- [ ]  Widget groups can be cut from context menu and `meta + x`
- [ ]  Widget groups can be deleted from context menu and `del`
- [ ]  Widget groups can also be selected from the entity explorer using the `meta + left mouse click` method mentioned above.
- [ ]  Widget a continuous list of sibling widgets can be selected by selecting one widget and `shift + left mouse click` on another widget sibling. All widgets between the two selected widgets will be selected. Please note this only works for siblings only, not for children, not for parent, etc. (Entity Explorer)
- [ ]  Clicking on `del` when a widget is selected in the entity explorer and no other input fields are focused, will delete the widget
- [ ]  `meta + a` will select all widgets. Other UX in this scenario will be similar to any other widget group
- [ ]  Modals can only be selected from the entity explorer as it exists outside the canvas
- [ ]  Widget groups can be cut and pasted into a new container, with each widget shown vertically one after the other in the newly created container. This newly created container will be created at the end of the canvas, as is the case with cut paste of widgets. (This will change in the future) This feature will only work from the context menu of the widget group, and will not have a shortcut for the time being.

# Subtask V2

1. Let the user change widgets settings from the multiple widget selection pane. They can selected multiple widgets and change their individual property from the same property pane.
2. Align Feature after they make it a container.

**Comment by Debsourabh** [comment]
Final Designs for the above mentioned scope

[https://www.figma.com/file/okCgRwbn6qazHVLmh7MGnU/?node-id=131%3A0](url)

**Comment by intelliot** [comment]
Why is "Move widgets" crossed out? That is what I would like to do: select multiple widgets and move them together.

**Comment by hetunandu** [comment]
I think move widgets should be possible as well. @riodeuno @Debsourabh are there any plans to support this?

**Comment by Nikhil-Nandagopal** [comment]
@intelliot thanks for pointing this out. @riodeuno can you shed some light here? Moving multiple widgets seems like a core requirement of this feature.

**Comment by riodeuno** [comment]
@Nikhil-Nandagopal @intelliot The move widgets feature is crossed out, not because we're not going to implement this feature, but only because we decided to not ship this feature in the first phase of the widget grouping project. 

There are some considerations when it comes to moving widgets. 

Today, Appsmith doesn't support overlapping widgets. Let's say the app developer selects a couple of widgets within a busy page with a lot of widgets (these selected widgets can be any two widgets), when moving these two widgets, the likely hood of the moving widgets "colliding" with other widgets is high, resulting in them not being able to place the widgets. The developers would most likely have to drag the selected widgets all the way down to the bottom of the canvas to be able to place them. This did not seem like a good DX. 

We will need to experiment with approaches on solving this DX issue.

Do you agree/disagree that this is an actual DX issue? Thoughts on how we can deal with this scenario?

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno agreed it's a DX issue but we should solve it because it's a core reason to use this feature. Even if it collides and that's annoying, it still very useful in many other cases where you just want to move items around. 
So If reflowing UI on collision is not handled in V1, I guess that's ok but simply group moving & informing that there's a collision should be supported

**Comment by riodeuno** [comment]
@Nikhil-Nandagopal Agreed. In any case, we'll be releasing this feature in useful parts and will include the drag/drop in this feature.

**Comment by areyabhishek** [comment]
@marks0351 can we close this issue?

**Comment by marks0351** [comment]
we have one last feature to make it to release. #5016
will close this after that.
