### ISSUE TITLE
[Task]: Lazy rendering of widgets

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#15763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

We have users with very long apps, we can improve first load for them if we render the widgets below the fold lazily.

In the widget verify if the widget is in the view port or not and then render the component or render a light weight loader.

A lot of cypress tests are going to fail, probably a command to scroll through the page, will help solve it.

**Comment by somangshu** [comment]
@rohitagarwal88 @riodeuno this still feels like an important optimization that could help apps with a lot of widgets. Would it be possible for you guys to do a short POC here to quantify it. If not, what can a probable timeline look like?

**Comment by riodeuno** [comment]
@somangshu Rendering too many DOM nodes can cause the UI thread to lag. Before we get into the timelines, we must discuss the potential approaches to this solution.  Here is my suggestion:

#### Suggested approach
- [ ] Render all widgets as a single div or box of the appropriate size at the appropriate positions.
- [ ] Use [InteractionObserver API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) to see if the widget is in view
- [ ] If the widget is in view, follow through with the normal render we have in our application.
- [ ] Cypress tests use selectors. This means, that we have to first scroll to a widget -- (as we will have the top level selector for a widget, if not automatically, we can spoof it) -- this will render the widgets properly, making the selectors accessible in the DOM. The selectors in cypress should work fine subsequently.
