### ISSUE TITLE
[Task]: Add missing data for Audit Log Events on EE

### ISSUE THREAD

**Issue by vishnu-gp** [appsmithorg/appsmith#15935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Add Application Info
- [x] Add Workspace Info
- [x] Clean AuditLogService
- [x]  Instance setting events
- [x]  Appsmith version
- [x]  Check Query execution, login, logout, sign up
- [x]  Public Apps activities are missed while logging due to permission Issue
