### ISSUE TITLE
[Task]: Updates to Template Page in Platform (Move 'Fork this template' button, add query param to open forking modal)

### ISSUE THREAD

**Issue by GreenFlux** [appsmithorg/appsmith#15946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

In the Templates tab of the platform, update the individual template page at:
https://app.appsmith.com/templates/APP_ID

- [ ] Move the **Fork this template** button above the iframe so it is visible without having to scroll down. The template title and forking button should both be in the same div, similar to the [website](https://www.appsmith.com/template/discord-bot-for-github-updates)
- [x] Add query parameter that opens the forking modal i.e. `?modal=true` or similar. Adding this to url should trigger the forking modal to open on page load. This will be used when directing a user from the website to the platform.
