### ISSUE TITLE
[Task]: Replace DeepDiff with MicroDiff for faster diffing 

### ISSUE THREAD

**Issue by rishabhrathod01** [appsmithorg/appsmith#15953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### Benchmarks
According to the [benchmarks](https://github.com/AsyncBanana/microdiff#benchmarks) mentioned it claims to be 200% faster then deep-diff for large objects.

```
Benchmarks: Small object
deep-diff: 17929ns - 409% slower
deep-object-diff: 10763ns - 206% slower
jsdiff: 79700ns - 2164% slower
microdiff: 3520ns - Fastest

Benchmarks: Large Object
deep-diff: 272887ns - 259% slower
deep-object-diff: 160019ns - 111% slower
jsdiff: 1688294ns - 2123% slower
microdiff: 75934ns - Fastest
```

### SubTasks
- [ ] POC to test microDiff for different object diff cases with different dataTypes
- [ ] Write test similar to klona for `microDiff` to verify it works for all our cases
- [ ] Replace it with deep-diff
- [ ] Handle all the evaluation code accordingly ( dependencyMap code might get impacted by this )

**Comment by bharath31** [comment]
@satbir121 should we pick this up given the bold benchmark claims?
