### ISSUE TITLE
[Task]: Add beta tag for GraphQL datasource

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#16469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Append beta tag for GraphQL datasource at : 

- [ ] add datasource pane on the 2 GraphQL options
- [ ] GraphQL datasource in the entity explorer
- [ ] GraphQL queries in the entity explorer

**Comment by sumitsum** [comment]
Closing since we have decided not to go with it.
