### ISSUE TITLE
[Task]: Fix reported issues and align with feedback

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#16523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Feedback and issues on 2022.09.02

- [x] Padding is off in the input field once you select an item
    This is not fixable as of today. The component is from design-system.
- [x] There’s a hover state for the date field but not for the other multi-select.
    This is not fixable, component from design-system.
- [x] See “user logged_out” for anonymousUser.
     Backend will handle this.
- [x] Please remove the _ in “logged_in” and “logged_out”. It seems inconsistent with the rest of the descriptions.
    This will be taken care by https://github.com/appsmithorg/appsmith/issues/16557
- [x] Logged_in & logged_out events don’t have an icon
    Icons are in the state of flux. 
- [x] The search icon above the JSON body should not be clickable. I kept clicking on it thinking I’ll filter by the resource ID. 30 secs later, I realised that I have to click on the actual value.
- [x] Logged_in & Logged_out events aren’t populating the id in the JSON search.
- [x] Is the JSON data fields supposed to be collapsible? Currently it’s completely expanded.
- [x] The id fields in the JSON are all truncated. Is it possible for us to increase the max length of each field before we truncate? Ideally, I should be able to copy the ID directly from the JSON.
- [x] The “Clear All” button seems to be buggy. It was taking me to the previous search results.
- [x] There is no hover or feedback on the Refresh button click. I don’t know if the button is clicked or not.
- [x] Documentation button next to refresh does not redirect to a page.
    It will work when we have documentation OR We will remove the documentation link. And with that the more menu too.

Refer: https://github.com/appsmithorg/appsmith/issues/15373

**Comment by IAmAnubhavSaini** [comment]
All of these are done.
