### ISSUE TITLE
[Task]: Action items as per weekly call on audit logs | FE

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#16562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Use tertiary button for refresh
- [ ] Decrease dropdown popup width to match dropdown trigger
- [ ] Subtle end of logs (Need design input)
- [ ] Handle search collapse in dropdown filter for non matching strings
- [ ] "Select x" placeholder

Refer, for FE tracker: https://github.com/appsmithorg/appsmith/issues/15373
