### ISSUE TITLE
[Task]: Use mockStore instead of reduxStore for component testing

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#16636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Problem 
Recently we noticed ColorPickerComponentV2's test to take more than 50s in CI. The core issue was using the redux store instead of the mock store for this test. 

## Solution 
After using mockStore we saw a 50% decrease in the time taken for such tests to complete.
 
> Read Aswath's comment on metrics after using mock store
https://github.com/appsmithorg/appsmith/pull/16596#issuecomment-1239729563

We still have other tests where we use the redux store yet.

## SubTasks
Use mockStore instead of the redux store for 
- [ ] CodeEditor.test.tsx
- [ ] EvaluatedValuePopup.test.tsx
- [ ] CodeEditor/index.test.tsx
- [ ] CanvasSelectionArena.test.tsx
- [ ] MainContainer.test.tsx
- [ ] MainContainerLayoutControl.test.tsx
- [ ] PropertyPaneTitle.test.tsx
- [ ] EntityExplorer.test.tsx
- [ ] GlobalHotKeys.test.tsx
- [ ] DataSourceCard.test.tsx
- [ ] ActionForm.test.js
- [ ] slug.test.tsx
- [ ] ContainerWidget/widget/index.test.tsx
- [ ] DividerWidget/widget/index.test.tsx
- [ ] DropdownWidget/widget/index.test.tsx
- [ ] InputWidget/widget/index.test.tsx
