### ISSUE TITLE
[Task]: Maintain Context and Focus Phase 2

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#16684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Entity Explorer: 
- [x] #17348
- [x] [Entity explorer should stay as you left it when you left the page (collapse levels)](https://github.com/appsmithorg/appsmith/issues/17975)
- [x] [Widget/explorer tab](https://github.com/appsmithorg/appsmith/issues/17975)
- [x] [Width - Should be the same across all pages of an app](https://github.com/appsmithorg/appsmith/issues/17975)
- [x] #15158

## [Canvas / Widgets](https://github.com/appsmithorg/appsmith/issues/17975):
- [x] Complex widgets, multi tier property panes
- [ ] Tabs
- [x] Property Pane width

## APIs:
- [x] #17435
- [x] #17436

## Queries: 
- [ ] ~Right side panel tabs~ No tabs on right unlike api pane

## Datasources
- [ ] ~#17437~
- [x] #17439
- [x] #17438

**Comment by akash-codemonk** [comment]
Query right pane cannot be opened or closed by the user. It opens or closes when there is a response. 
JS Editor has no right pane. Ruling out these two.

**Comment by hetunandu** [comment]
@akash-codemonk We need to maintain the selected tabs on the right side panes.

**Comment by Richarex** [comment]
- [ ] Switching between pages when the user interacts with multi tier property panes is throwing **"Something went wrong"** error. Please refer the attached video: https://jiju8jbmwa.vmaker.com/record/kyYLSSANlPw2VGpV

- [ ] Cursor position is blinking at the starting point when the user switches between **CONTENT** & **STYLE**. Cursor position completely fails to maintain it's previous position when switching between pages. Please refer the attached video:- https://jiju8jbmwa.vmaker.com/record/hwL9U2FJnsoeIeyS

**Comment by rahulramesha** [comment]
@Richarex I have addressed the above mentioned issues, please continue testing the PR.

**Comment by Richarex** [comment]
- [X] Switching between pages when the user interacts with multi tier property panes is throwing "Something went wrong" error. This is fixed, verified it on the DP url.
- [X] Cursor position is blinking at the starting point when the user switches between CONTENT & STYLE. Cursor position completely fails to maintain it's previous position when switching between pages. This issue is fixed verified it on DP.
