### ISSUE TITLE
[Task]: Sliders Bug Master list

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#16760]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Checked bugs are fixed

PR - https://github.com/appsmithorg/appsmith/pull/15712
Notion - https://www.notion.so/appsmith/Slider-Widgets-c8e9fcce6cdf4bcb98923669139b7087

- [x] https://github.com/appsmithorg/appsmith/issues/16759
Fixed in DP - https://appsmith-6u1ow7o9w-get-appsmith.vercel.app/user/login
- [x] https://github.com/appsmithorg/appsmith/issues/16763
Fixed in DP - https://appsmith-ekxlo8e85-get-appsmith.vercel.app/
- [ ] https://github.com/appsmithorg/appsmith/issues/16784
- [x] https://github.com/appsmithorg/appsmith/issues/16789
Fixed in DP - https://appsmith-mir6adygk-get-appsmith.vercel.app/
- [ ] https://github.com/appsmithorg/appsmith/issues/16800
- [ ] https://github.com/appsmithorg/appsmith/issues/16838
- [x] https://github.com/appsmithorg/appsmith/issues/16839
Fixed in DP - https://appsmith-mdcnym5k8-get-appsmith.vercel.app/
- [x] https://github.com/appsmithorg/appsmith/issues/16841

Enhancement suggestions - open for discussion

- [ ] https://github.com/appsmithorg/appsmith/issues/16833
- [ ] https://github.com/appsmithorg/appsmith/issues/16834
- [ ] https://github.com/appsmithorg/appsmith/issues/16835
- [ ] https://github.com/appsmithorg/appsmith/issues/16840

**Comment by yaldram** [comment]
@Sripriya93 for issues - #16784 , #16800 we have an open issue on the fe-coders pod here - #15303
