### ISSUE TITLE
[Task]: Pending Data points from BE 

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#16766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Use app mode for actions and pages
- [x] Destination workspace for forking and cloning
- [x] Visibility of the Application(private/public)
