### ISSUE TITLE
[Task]: Restructuring groupButtons property value 

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#16822]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Internal discussion - https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1663054058685329?thread_ts=1662990518.868189&cid=C02K0SZQ7V3

Use-case for binding in groupButtons
`{{ButtonGroupWidget.groupButtons.groupButton1.isVisible}}`

- [ ] Restructure groupButtons data to not have hash keys
- [ ] new custom button label shouldn’t ideally be named Group Button 1 as property name groupButton1 is already taken
- [ ] Enable autocomplete for `groupButtons`

**Comment by ame-appsmith** [comment]
[Another user](https://app.frontapp.com/open/cnv_18chu9u4?key=wUbF4F2yg51AaDmv-UzA4x1EdJWFFdoM) reported this issue.
