### ISSUE TITLE
[Feature]: Granular Git assets

### ISSUE THREAD

**Issue by jonnysamps** [appsmithorg/appsmith#17033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Today if we have more than one collaborator on a page, merging is an absolute nightmare.  All of the widget config for a page is represented in one single giant JSON blob in `canvas.json` this makes it very hard to make isolated changes.

I'd propose breaking down the git representation into smaller JSON files that are aggregated by the running app.

### Why should this be worked on?

This is almost a non-started for us. If we can only have a single dev working on a page at a time that really restrains how we can scale the use of appsmith in our org. I personally had to spend ~1 hour merging configuration yesterday and because I'm not super familiar with the format, I lost several pieces of functionality from my branch.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_68d70)

Tasks - 
- [x] #21165
- [x] #22800
- [x] #22801
- [x] #22802
- [x] #22803
- [ ] #22804
- [x] https://github.com/appsmithorg/appsmith/issues/23251
- [x] #20853 Handle the file changes in the git status API
- [x] #23763

**Comment by Nikhil-Nandagopal** [comment]
Hi @jonnysamps , this is an interesting use case. We generally see collaborators working across different pages instead of on a single page. I'd love to learn more about how you'll are using Appsmith internally. If you'd be interested in a chat, you can block some time on my calendar below.
https://calendly.com/appsmith-nikhil/30min?back=1&month=2022-09

**Comment by jonnysamps** [comment]
Hi @Nikhil-Nandagopal I scheduled some time today. Looking forward to it.

**Comment by Nikhil-Nandagopal** [comment]
@hiteshjoshi @vuiets this was an interesting call. We realized that real-time collaboration was not useful here because they want to maintain their developer workflow across branches. We also figured that the real problem was with the canvas json which could get quite large and nested. Normalizing the JSON was one solution we thought could help resolve merge conflicts faster and avoid them altogether. Also maintaining the order of the keys would help reduce the number of conflicts.

**Comment by chriscervantes** [comment]
Hi @jonnysamps, I hope we can break down the object changes. Meaning, if you change a single JS object, you will be able to show the object name and give an overview on what was change? currently, It is hard to really see the changes especially if you forgot to commit your changes. You will lost track of it.

**Comment by AnaghHegde** [comment]
Feedback - https://www.notion.so/appsmith/Make-it-easier-to-resolve-the-merge-conflicts-Queries-8d05d66abf0b42049180df2b01afcfdd
