### ISSUE TITLE
[Task]: Add performance test for complex application

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#17037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Current performance tests are run on applications with few entities and worker time is not measured. To understand the degradation in performance for evaluation we will need to create test applications with more entities.

- [ ] Add metrics for worker time ( createFirstTree, updateDataTree )
- [ ] Add tests with more number of entities

Ideal complex application
- 4 Tabs each having table widget data loading from JSObject variable.
- 5 Modal with each having 5-6 widgets or Form

In total around 100 entities that bound together.

**Comment by somangshu** [comment]
@Rishabh-Rathod can you talk about why this should be prioritized?

**Comment by Rishabh-Rathod** [comment]
@somangshu As we track the performance of evaluation in a different way now, the above task is not required.
