### ISSUE TITLE
[Task]: Follow up on PR comments

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#17116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] use `find` instead of `filter` in that saga function
- [ ] move AuditLogs specific strings to EE
