### ISSUE TITLE
[Task]: POC for Draw to add widget on Canvas

### ISSUE THREAD

**Issue by rahulramesha** [appsmithorg/appsmith#17226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Select widget from explorer to enter drawing mode.
- [x] Draw on Main canvas to add widget.
- [x] In the widget drawer, we need to update the text to drag a widget or click to draw.
- [x] Exit Drawing Mode after widget is drawn or when the user hits the `esc` key.
- [x] Show the widget grid borders.
- [x] Disable Widget Dragging when we are in Drawing Mode.
- [x] Identify the canvas Id being drawn to enable drawing on other canvas type widgets.
- [ ] The crosshair changes to a hand when over an existing widget in draw-mode. This can get confusing so the experience here needs some thought.
- [ ] Make sure Drawing sticks to the grid instead of in between the grids.
- [ ] Handle collisions, ( either by stop drawing or by reflowing other widgets ).
- [ ] Discoverability for the feature (Designs) @momcilo-appsmith
