### ISSUE TITLE
[Task] Installation Wizard

### ISSUE THREAD

**Issue by arunvjn** [appsmithorg/appsmith#17309]
### Subtasks
- [x] Trigger the installation wizard from the entity explorer.
- [x] Input box to paste library URL and search libraries.
- [x] Indicate progress for the installation
- [x] Unit test cases
