### ISSUE TITLE
[Task]: Migration of current datasources to support environments

### ISSUE THREAD

**Issue by sondermanish** [appsmithorg/appsmith#17576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks
- [x] Fetch envVars (environment Variables) tagged in the dynamic binding pathlist
- [x] Retrieve values of the envVars
- [ ] Evaluate datasource configuration with the values

How should we handle scenarios with errors in finding the environment variables?

**Comment by sondermanish** [comment]
Migration along with RBAC changes are in Code Review

**Comment by sondermanish** [comment]
Coupled with test datasource PR, expected to go in after datasource context PR.
