### ISSUE TITLE
[Task]: Add two environments Production & staging for workspaces 

### ISSUE THREAD

**Issue by sondermanish** [appsmithorg/appsmith#17578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [X] create environments for existing workspaces
- [X] hook functionality for automated creation of environments for new workspaces

**Comment by sondermanish** [comment]
Handled with with Issue 17571 with PR https://github.com/appsmithorg/appsmith-ee/pull/1027
