### ISSUE TITLE
[Task]: Use the new link component in the user auth flow

### ISSUE THREAD

**Issue by tanvibhakta** [appsmithorg/appsmith#17739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Design a link component 
- [x] create the link component in the design system 
- [x] use that link component in the ~4 places we are directly styling `a` tags in the user auth flow.
