### ISSUE TITLE
[Task]: Instrumentation for action execution errors and resolution

### ISSUE THREAD

**Issue by sribalajig** [appsmithorg/appsmith#17748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

When there is an action execution error, I want to know the following:
- [x] How many users clicked on the debug link on the toast message
- [x] How many users looked at the error in the logs
- [x] How many users resolved the error
- [x] How many users did not resolve the error
- [x] How many apps have at least one query in an error state

**Comment by ChandanBalajiBP** [comment]
@sribalajig Have a few doubts and need clarification from your side
1. How many users clicked on the debug link on the toast message - 
I am not able to find any suitable toast message where debug link is provided, can you please share some examples?
2. How many users looked at the error in the logs -
This event should be captured when the user clicks on the error tab or should we also check whether he has scrolled through all issues? As of now implemented the error tab click, but have logic ready for the scroll also.
3. How many users resolved the error - 
There is an event (DEBUGGER_RESOLVED_ERROR_MESSAGE / DEBUGGER_RESOLVED_ERROR) already present. We can also use (DEBUGGER_NEW_ERROR_MESSAGE / DEBUGGER_NEW_ERROR) if we want to track the error message created. I think these are the same ones you're currently using.
4. How many users did not resolve the error - 
Can you explain more on this point? Not able to think of any logic for this.
5. How many apps have at least one query in an error state-
Should these analytics be logged every time the application is launched or refreshed?

**Comment by ChandanBalajiBP** [comment]
OPEN_DEBUGGER is an event which is logged on the opening error log in the widget editor pane/API pane/JS Editor/Query Pane. It was missing in a few places, have updated them. This is the same event for the first point(Debug button in toast) also.

**Comment by ayushpahwa** [comment]
@ChandanBalajiBP @sribalajig Can you share the answers to the questions you have raised above? Asking for PR review. Thanks!

**Comment by ChandanBalajiBP** [comment]
The following are the answers to the above questions.

1. `OPEN_DEBUGGER` was the event which is already present in prod.
2. `OPEN_DEBUGGER` is the relevant event that was missing in a few events and has been added in the PR.
3. `DEBUGGER_RESOLVED_ERROR_MESSAGE / DEBUGGER_RESOLVED_ERROR` these events will suffice for this use case as we cannot keep track of the particular error is resolved.
4. This is can be achieved in the mix panel.
5. `DEBUGGER_NEW_ERROR` event is used for this analytics.
cc:@ayushpahwa
