### ISSUE TITLE
[Task]: Add Auto Height related actions to editor and viewer contexts

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#17959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Add action to update a widgets' height to editor context
- [ ] Add action to update a widgets' height to viewer context
- [ ] Add action to trigger a check for container auto height to editor context
- [ ] Add action to trigger a check for container auto height to viewer context
