### ISSUE TITLE
[Task]: Split WidgetFeatures into different files

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#17965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Create a WidgetFeatures folder
- [ ] Split the contents of the WidgetFeatures.ts file, such that there is a clean separation between different components of a widget feature.
