### ISSUE TITLE
[Task]: Auto-height widget utils

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#17963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Add helper functions to get the widget's max auto height in rows
- [ ] Add helper functions to get widget's min auto height in rows
- [ ] Add helper to check if widget has auto height enabled
- [ ] Add helper to check if widget has auto height enabled with limits
