### ISSUE TITLE
[Task]: Auto height - computation functions

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#17961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Function to generate auto height layout tree from occupied spaces.
- [ ] Function to generate reflowed positions of boxes based on height delta
