### ISSUE TITLE
[Task]: Create platform structure for adding widget features

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#17976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Widgets can be enhanced by the platform using simple configs. To achieve this, widgets need to enhance the following
- [ ] Property pane configuration
- [ ] Default properties

The following are the subtasks to enable this
- [ ] Create a Widget features registry
- [ ] Enhance property pane configurations based on feature registry and widget feature configs
- [ ] Enhance default properties for widgets based on feature registry and widget feature configs.

To validate this change we'll be using the auto height feature
- [ ] Add auto height to widget features registry
- [ ] Add auto height default properties to widget features map
- [ ] Add auto height property pane enhancements to widget features map
- [ ] Add widget helper utilities for auto height

**Comment by riodeuno** [comment]
Closing this as implemented.
