### ISSUE TITLE
[Task] Auto - Height enhancements for BaseWidget

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#17993]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The BaseWidget should do the following:
- [ ] Enable calls to update auto height of widget
- [ ] Check if this update should be applied
- [ ] Add the auto height overlay in edit mode
- [ ] Wrap widgets in auto height container
