### ISSUE TITLE
[Bug]: RBAC Issues

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#18030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**FRONTEND ISSUES**
- [x] [[Bug]: The hover state looks broken in the firefox browser](https://github.com/appsmithorg/appsmith/issues/18038)
- [ ] unable to check the data in the Groups & roles tab until we refresh the page each time 
- [ ] Low Priority | On visiting roles, all the checkboxes checked should be expanded

**BACKEND ISSUES**
- [x] The user icons not displayed in the workspace level where we show the user icon who are the users that are part of workspace -->This is intended  we will not show the user icon 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/199200189-42644a4c-deab-4a9c-9831-3563d204360c.png">

- [x] When there are 4 pages in a app and in that if one page doesn't have edit permission then deploy doesn't work ->this is expected as per the discussion https://www.loom.com/share/791306fbb3b54a5d813dd233be835c1d

- [X] Even when we have create app access not able to create new apps 
https://40edv1d3xs.vmaker.com/record/9qJSTG4zheGPiA6n

- [x] In the user's tab The User email is displayed in the Roles column
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/199201290-241e78e4-bf4e-4a56-9e37-435bde37dfe3.png">

- [x] [Trim should be done in Datasource & queries page when pages doesn’t have the queries associated with the pages](https://github.com/appsmithorg/appsmith/issues/18312)
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/199201616-795b72ea-9d3e-4ea9-9f53-75c481751c6e.png">

- [x] #18763
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/199203493-a5211314-1592-43d3-91ba-412afd410fb8.png">

- [X] Unable to create a data source. We see Resource Not Found error when we are trying to create a datasource
https://40edv1d3xs.vmaker.com/record/6olr7K7k3r870N2O

- [X]  Can't Create a new Queries from data source
https://40edv1d3xs.vmaker.com/record/rKqKFM42thHuwhCN

- [X] [When user check edit access from workspace level the view access is checked from application level instead of workspace level](https://github.com/appsmithorg/appsmith/issues/18232)
https://40edv1d3xs.vmaker.com/record/ra1IqvIVdQrPkxja

- [x] [[Task - EE]: delete workspace role doesn't work](https://github.com/appsmithorg/appsmith/issues/18216)
https://40edv1d3xs.vmaker.com/record/grqukEEce76a5Cyv

- [x] [[Task - EE]: Even when user doesn't have the edit access the user can edit the data sources and even having the delete access we can not delete the datasource](https://github.com/appsmithorg/appsmith/issues/18237)
https://40edv1d3xs.vmaker.com/record/K8vLq4P1jLzEzlaA

- [x] The role of a user is hidden is the members page login as test4@appsmith.com now invite test6@appsmith.com as a appviewer and assign the role as edit workspace to test user6, Now user can navigate to members tab here the Admin user role is hidden as in screenshot 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/199220064-b1dbd75b-5e67-4d88-aaf6-cfc219903aeb.png">

- [x] Able to give Export permissions for Workspace and Apps, even if no View permissions are selected. Ideally, without View permissions selected, Export permissions should be disabled

- [ ] Recently added groups/roles should be shown at the top in Groups/Roles page.

- [x] The Widgets will be in infinite loading state when page has only view access

- [x] when we try to add a deleted user (deleted from the ACL user listing screen) to a workspace via invite modal on the homepage, we get duplicate key error.
<img width="603" alt="image" src="https://user-images.githubusercontent.com/45958978/199225114-0fd4292c-f1aa-4c31-8feb-3c54ff6227f8.png">

- [x] #18425

- [x] Deploy the app come back to edit mode try to add a widget the No access error is displayed https://www.loom.com/share/b6be1cc5e738448b90f20daf29bd347d

- [x] On clicking create new option from omnibar for user with edit only role, it shows No results found Join our Discord Server for more help

- [x] #18391
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/45958978/199225506-0f736733-f1bf-4c8c-a4de-e85d068e9966.png">

### Steps To Reproduce

1. Login to the instance
2. do the changes in the roles
3. assign it to user 
4. login as a assigned user
5. check the functinality works 

### Version

http://65.0.99.89/settings/roles

**Comment by ankitakinger** [comment]
Re-opening for remaining sub-tasks.

**Comment by berzerkeer** [comment]
Can we create this as a separate issue 
Deploy the app come back to edit mode try to add a widget the No access error is displayed https://www.loom.com/share/b6be1cc5e738448b90f20daf29bd347d

@RakshaKShetty

**Comment by RakshaKShetty** [comment]
adding the separate issue for pending bugs, so closing this issue
