### ISSUE TITLE
[Task]: Update secondary and tertiary states of button 

### ISSUE THREAD

**Issue by tanvibhakta** [appsmithorg/appsmith#18052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

We currently have three states of button:
https://design-system.appsmith.com/?path=/story/design-system-button--primary
https://design-system.appsmith.com/?path=/story/design-system-button--secondary
https://design-system.appsmith.com/?path=/story/design-system-button--tertiary

We use our current secondary design in very few places. 

We want to upgrade our current tertiary design to secondary and we will be introducing a new design for the tertiary button.

This will involve 
- [x] renaming the existing design system components 
- [x] changing the usages of tertiary in core to secondary 
- [ ]  making a list of pages that use secondary button and take a call on what to do with them 
- [ ] ~~carrying out the same exercise in ee~~ There are no usages in EE
- [x] implementing the new tertiary design 
- [ ] ~keeping the two branches in sync and merging successfully.~

**Comment by vasanth-appsmith** [comment]
@tanvibhakta Here is the updated design for this. [Figma](https://www.figma.com/file/4aZWeRRAyIBX660EbIQhXn/DS-Upgrade-Exploration?node-id=1300%3A51079)

**Comment by bhuvanaindukuri** [comment]
@tanvibhakta - Are these changes applicable for a specific theme or the requirement is to update the default theme itself?

**Comment by tanvibhakta** [comment]
hey @bhuvanaindukuri, the changes are applicable for the default components as present in the [design-system](https://github.com/appsmithorg/design-system) repository. Since this is something that requires coordination across multiple repositories, I will be picking this up. Let me know if there's something else you'd like to pick up?
