### ISSUE TITLE
[Epic]: Evaluation performance optimization

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#18060]
### Objective

We are seeing that evaluations is a bottleneck to performance. 
This is specially evident in Complex apps with large data tree.
Our goal is to bring down this time it takes to evaluate the data tree on the first page load under 500ms

### Success Metrics

| Metric         |
| -------------- |
| Evaluations should complete in 500ms or less  |
| User dont feel the lag in their apps loading        |

### Prioritised User Stories

User Story prioritised
- [x] https://github.com/appsmithorg/appsmith/issues/16259 
- [x] https://github.com/appsmithorg/appsmith/issues/11351
- [x] https://github.com/appsmithorg/appsmith/issues/18291
- [x] https://github.com/appsmithorg/appsmith/pull/18433

Needs info:
- [ ] https://github.com/appsmithorg/appsmith/issues/18019
- [ ] https://github.com/appsmithorg/appsmith/issues/18020

Other related issues:
- [x] https://github.com/appsmithorg/appsmith/issues/14760

### Planning Doc
https://www.notion.so/appsmith/Eval-Perf-Optimization-Project-5ce0dc17ab1b4d1eb98033b93389e7d7

### RACI matrix

| | |
| ------------- | ------------- |
| Responsible   |     @rimildeyjsr @Rishabh-Rathod @ohansFavour @SatishGandham  |
| Accountable   |       @satbir121          |
| Consulted     | @mohanarpit, @SatishGandham,  @arunvjn  |
| Informed      |        @somangshu       |

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5wsb0)
