### ISSUE TITLE
[Task]: Codemirror v6 migration POC

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#18249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Potential features to be enabled
- Multiplexing mode to allow SQL + JS autocomplete

### SubTasks
- [ ] Migration docs to follow - [https://codemirror.net/docs/migration/](https://codemirror.net/docs/migration/)
- [ ] Make autocomplete work using Tern or LSP (  https://github.com/furqansoftware/codemirror-languageserver )
    - [ ] Javascript
    - [ ] SQL
    - [ ] Postgres
    - [ ] mongoDB
- [ ] Make linting work using JSHint or eslint
- [ ] Make multiplexing of code work.

### Potential issues to be fixed
- https://github.com/appsmithorg/appsmith/issues/13983 
- https://github.com/appsmithorg/appsmith/issues/6923
- https://github.com/appsmithorg/appsmith/issues/7113

### Autocomplete needs to support languages
- javascript
- SQL, Postgres
- MongoDB
- multiple language support for autocomplete, and linting. 

#### Replacement for tern server
- custom APIs support and custom rules for sorting

**Comment by satbir121** [comment]
POC
- [ ] Check compatibility and performance with other language servers. Check compatibility with Tern Server.
- [ ] Check v6 vs v5 performance.
- [ ] Better support for SQL with Multiplexing.
- [ ] Any bugs that can be fixed just by the upgrade
