### ISSUE TITLE
[Task]: cmd+click analytics events

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#18299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] trigger an event when a user uses cmd+click
- [x] trigger an event when a user clicks on an action on the Entity explorer. (this will be used to figure out how users are navigating)
- [x] If not existing, trigger an event from the omnibar as well, for when a user navigates to an action
