### ISSUE TITLE
[Task]: NPM Dependabot Alerts

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#18490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] **Prototype pollution in webpack loader-utils**
<img width="643" alt="Screenshot 2022-11-28 at 12 00 49 PM" src="https://user-images.githubusercontent.com/890915/204209087-c6325280-8c62-4a20-b057-b1be1b9b635f.png">

- [ ] **Prototype pollution in webpack loader-utils**

 <img width="1273" alt="Screenshot 2022-11-28 at 12 00 15 PM" src="https://user-images.githubusercontent.com/890915/204209026-e361fb31-ae10-453a-b2de-b52b8d691e03.png">

- [ ] **Insufficient validation when decoding a Socket.IO packet** 

 <img width="1273" alt="Screenshot 2022-11-28 at 12 00 15 PM" src="https://user-images.githubusercontent.com/890915/204209558-d8993a4a-83f3-495d-bd84-bc95ace78ecf.png">

- [ ]   **loader-utils is vulnerable to Regular Expression Denial of Service (ReDoS) via url variable**

<img width="1280" alt="Screenshot 2022-11-28 at 12 06 54 PM" src="https://user-images.githubusercontent.com/890915/204209982-ae771c0a-21d9-4cba-96e0-fb233210d539.png">

- [ ] **loader-utils is vulnerable to Regular Expression Denial of Service (ReDoS)**

<img width="1278" alt="Screenshot 2022-11-28 at 12 12 27 PM" src="https://user-images.githubusercontent.com/890915/204210921-0a2fdf7b-bca6-40ef-951d-85ceefb7fcb7.png">

- [ ] **loader-utils is vulnerable to Regular Expression Denial of Service (ReDoS) via url variable**
<img width="641" alt="Screenshot 2022-11-28 at 12 13 37 PM" src="https://user-images.githubusercontent.com/890915/204211125-a80cdb4e-c72f-4334-8600-2dc4b68b4c6b.png">

- [ ] **loader-utils is vulnerable to Regular Expression Denial of Service (ReDoS)**

<img width="641" alt="Screenshot 2022-11-28 at 12 14 22 PM" src="https://user-images.githubusercontent.com/890915/204211227-cf303738-019f-4175-8830-909f16f183c0.png">

- [ ] **loader-utils is vulnerable to Regular Expression Denial of Service (ReDoS) via url variable**

<img width="1277" alt="Screenshot 2022-11-28 at 12 15 30 PM" src="https://user-images.githubusercontent.com/890915/204211408-7c03341b-193d-4b78-9a10-b239d3647481.png">

- [ ] **loader-utils is vulnerable to Regular Expression Denial of Service (ReDoS)** 

<img width="1280" alt="Screenshot 2022-11-28 at 12 16 50 PM" src="https://user-images.githubusercontent.com/890915/204211626-151dbacd-2afe-49e8-af01-090b08aa2f0c.png">

- [ ] **minimatch ReDoS vulnerability**
<img width="1279" alt="Screenshot 2022-11-28 at 12 17 56 PM" src="https://user-images.githubusercontent.com/890915/204211854-e35c888c-d746-46bb-9299-a3c5a1b54401.png">
