### ISSUE TITLE
[Task] maps widget tasks

### ISSUE THREAD

**Issue by ofpiyush** [appsmithorg/appsmith#1861]
While debugging maps infinite loading issue #1833, we found that the library is no longer maintained
https://github.com/tomchentw/react-google-maps/issues/1038

## SubTasks
- [ ] ~Find a stable alternative.~
- [ ] Decide how to deal with widget interaction vs underlying map interaction.
- [x] Ask about the create marker flow and fix/implement that.
- [x] Switch over to functional component design.
- [x] use `useScript` for loading the map.

**Comment by ofpiyush** [comment]
We've decided not to replace the npm package for now.

We'll come back to this before upgrading to react 17.

I'll open another broader issue to discuss canvas vs widget interaction.
