### ISSUE TITLE
[Task]: Check the behaviour of appsmith on ecs-fargate

### ISSUE THREAD

**Issue by pratapaprasanna** [appsmithorg/appsmith#18803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks
- [X] We can launch appsmith on fargate but once there is a restart things will break.**`Done`**
- [x] Check how we can launch ecs-fargate container with efs backend `**In Progress**`

_No response_

**Comment by pratapaprasanna** [comment]
It works

**Comment by pratapaprasanna** [comment]
https://www.notion.so/Using-EFS-on-ECS-fargate-1c8f5a6bb56641a4a38035360c260c3e how to access ecs on efs
