### ISSUE TITLE
[Bug]: Segment adding to the script time

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#18829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Segment is sending lot of tracking events, and adding 5-20% to the scripting time.
Review how we are using it and what we are tracking and remove unnecessary events.

Slack thread: https://theappsmith.slack.com/archives/C024GUDM0LT/p1670261140997809

### Steps To Reproduce

Record a performance profile, and in the call tree search for track and see how long it takes.

### Version

Both

**Comment by somangshu** [comment]
@hetunandu pointed out 
| It is easy to figure this out. On mix panel, you can find the top events fired, find them on our codebase and then comment them out.

### To-do
- [ ] Find all the top events running on segment. @kocharrahul7 can you help us here?
- [ ] Identify the events that are not required
- [ ] Comment out those events on check the performance improvements
    - [ ] Report back the numbers
    - [ ] Final cleanup and Ship

**Comment by kocharrahul7** [comment]
https://mixpanel.com/project/2032485/view/178891/app/dashboards#id=1658069&edited-bookmark=QvmPBjv1dAVr

**Comment by Rhitottam** [comment]
@somangshu , @SatishGandham  Can check the following readings after checking the performance while running the following actions in the Performance Infra Dashboard in local environment
`Action: Reload Release Master Comparison Page of Performance Infra Dashboard and wait for the table data to load completely..
        This action involves loading a table containg data retrieved from two mysql apis
Reading 1: 
  Total Scripting Time: 3510
  Track Scripting Time: 40.9
  Percentage: 1.1%
Reading 2:
  Total Scripting Time: 3729
  Track Scripting Time: 30.4
  Percentage: 0.8% 
After Disabled Logging of events - BINDING_SUCCESS, DEBUGGER_NEW_ERROR, DEBUGGER_NEW_ERROR_MESSAGE
Reading 1:
  Total Scripting Time: 3499
  Track Scripting Time: 20.2
  Percentage: 0.8%
Reading 2:
  Total Scripting Time: 3530
  Track Scripting Time: 26.2
  Percentage: 0.7%

Action: Navaigate to PR Details page of Performance Infra Dashboard and wait for the table data to load completely.
        This action involves loading a table containg data from multiple apis and loading a chart displaying metrics data for multiple PRs
Reading 1: 
  Total Scripting Time: 7879
  Track Scripting Time: 178.8
  Percentage: 2.2%
Reading 2:
  Total Scripting Time: 8059
  Track Scripting Time: 170.8
  Percentage: 2.1%
After Disabled Logging of events - BINDING_SUCCESS, DEBUGGER_NEW_ERROR, DEBUGGER_NEW_ERROR_MESSAGE
Reading 1:
  Total Scripting Time: 7186
  Track Scripting Time: 30.2
  Percentage: 0.4%
Reading 2:
  Total Scripting Time: 7752
  Track Scripting Time: 34.8
  Percentage: 0.4%`

**Comment by somangshu** [comment]
Actionable @Rhitottam 
- [ ] Can we remove the given events `BINDING_SUCCESS`
    - We should also think about how these events can still exist, because analytics might need it.  
- [ ] Find if this is the right optimization

**Comment by Rhitottam** [comment]
We will be using [https://github.com/BuilderIO/partytown](url) for running segment analytics tracking in a web worker. This is done so that in future if more events are being tracked, they won't block the main thread. Ideally there should be a performance improvement without removing any events we were tracking before.
For browsers where service worker is disabled segment will run on the main thread. So there won't be any performance improvement for such cases.
