### ISSUE TITLE
[Task]: Context switching minor UX issues

### ISSUE THREAD

**Issue by rahulramesha** [appsmithorg/appsmith#18827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Widget entity on widget selection does not expand
- [ ] Property pane panel jitters when panel is directly open on selecting a widget.
- [ ] URL does not retain Params while restoring previous url on page change
