### ISSUE TITLE
[Task]: Remove Auto Height from List widget's Children

### ISSUE THREAD

**Issue by rahulramesha** [appsmithorg/appsmith#18825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Remove Auto height Property Control from List widget's Children
- [ ] Change Auto Height to Fixed when moving widget to List Widget
- [ ] Migrate existing list widget's Children to have Fixed Height
