### ISSUE TITLE
[Task]: Merge switch and toggle components

### ISSUE THREAD

**Issue by tanvibhakta** [appsmithorg/appsmith#18822]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

To do this, we have decided to use the toggle component everywhere the switch component is being used. 

- [ ] Refactor in core repository 
- [ ] Refactor in ee
- [ ] Remove Switch in ds
- [ ] Make Toggle use black

**Comment by tanvibhakta** [comment]
Hey @vasanth-appsmith, 

[This](
https://design-system-git-chore-replace-switch-with-toggle-get-appsmith.vercel.app/?path=/story/design-system-toggle--toggle) is the version of Toggle that is the result of merging the [existing Switch]( https://design-system.appsmith.com/?path=/story/design-system-switch--switch ) and the [existing Toggle.](https://design-system.appsmith.com/?path=/story/design-system-toggle--toggle).

Can you please sign off on it?

**Comment by rohitagarwal88** [comment]
Closing coz this is fixed in https://github.com/appsmithorg/appsmith/pull/22030
