### ISSUE TITLE
[Task]: Rename Dialog to Modal 

### ISSUE THREAD

**Issue by tanvibhakta** [appsmithorg/appsmith#18854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Rename Dialog to Modal in the design-system 
- [ ] Refactor usages of Dialog in the main repo 
- [ ] Refactor usages of Dialog in ee
