### ISSUE TITLE
[Task]: Upgrade Spring Boot to 2.7

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#18992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Make sure encryption is still compatible
- [x] Introduce schema version for future migrations of this nature
