### ISSUE TITLE
[Task]: Upgrade to Spring Boot 3

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#18993]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Upgrade to Spring Boot 3
- [x] Upgrade to JDK 17
- [ ] Upgrade Mongock libs
- [x] Upgrade vulnerable deps
- [x] Remove incompatible encryption migration
