### ISSUE TITLE
[Task]: Update UI based on Design QA

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#19040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Edit description role edit box
- [x] Distance between the edit icon and the text should be same for title and desc
- [x] Update text-box placeholder on invite modal
- [x] Heading users instead of user on users page
- [x] Remove padding on left panel (0 0 0 16px)
- [x] Update text-box placeholder on members page invite modal
- [x] Members page - centre align role column
- [x] Role edit page - no results found text on search
