### ISSUE TITLE
[Task]: Fix failing tests due to #19052

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [appsmithorg/appsmith#19060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] fix failing tests
- [x] fix numbering, the next option should be 2
