### ISSUE TITLE
[Task]: Find and rename some components in the ads 

### ISSUE THREAD

**Issue by tanvibhakta** [appsmithorg/appsmith#19234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] ButtonTab to ButtonGroup
- [ ] DialogComponent to Modal 
- [ ] MenuDivider to Divider 
- [ ] ProgressiveImage to Image 
- [ ] RadioComponent to Radio
- [ ] ScrollIndicator to ScrollBar
- [ ] ShowcaseCarousel to Carousel 

### Stretch goals 

Deprecate 
- [ ] EmojiPicker 
- [ ] EmojiReactions
- [ ] LabelWithTooltip
- [ ] TabItemBackgroundFill

Merge usage 
- [ ] CloseButton into Icon
