### ISSUE TITLE
[Task]: Update Error log interface/structure as per new design

### ISSUE THREAD

**Issue by ChandanBalajiBP** [appsmithorg/appsmith#19232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Update Error log interface/structure as per new design w.r.t

- [ ] Lint errors
- [ ] Parse errors
- [ ] Plugin execution errors
- [ ] Validation error
- [ ] Evaluation error
- [ ] Function execution/JSobject errors
