### ISSUE TITLE
[Task]: Code refactor for dataTree split completion

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#19445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Eval Code refactor ( 4-5 days )
   - separate entity config from dataTree and refactor code everywhere it is used. 
- [ ] Main thread code refactor ( 1-2 days )
   - separate entity config from dataTree when sending to main thread. 
   - Refactor main thread code everywhere it is used.
