### ISSUE TITLE
[Task]:  Moving environment and environment variable class to com.appsmith.external package 

### ISSUE THREAD

**Issue by sondermanish** [appsmithorg/appsmith#19501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] move environment variable class
 - [x] move environment class
 - [x] move environmentDTO class

**Comment by sondermanish** [comment]
Closing the issue as the PR has been merged
