### ISSUE TITLE
[Task]: Multi Pane Layout: Phase 3

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#19544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Artifacts when dragging a widget
- [ ] UI clean up
- [ ] Scaling adds scrollbars
