### ISSUE TITLE
[Task]: Update Evaluation errors to new interface

### ISSUE THREAD

**Issue by ChandanBalajiBP** [appsmithorg/appsmith#19647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Update Evaluation errors to new interface

**Comment by btsgh** [comment]
- [ ] As per the figma, the Validation Error is named as per the property which has the error, and takes the user to the property in the Property Pane, in this case "CustomersTable.TableData"

In the DP, The Validation Error is named as say CategorySlider1.Widget (not sure what is meant by .widget here) and it does not point the user to the property in the property pane.
In this case I expected it to be - CategorySlider1.DefaultValue

![ErrorHandling_Widget_ValidationError1.png](https://images.zenhubusercontent.com/6242f2f59960209e891f50ec/3cb04492-dc49-4a97-856b-a7fb61e8b0ca)

![ErrorHandling_Widget_ValidationError.png](https://images.zenhubusercontent.com/6242f2f59960209e891f50ec/ed799be2-13e0-4476-9a72-75e8256cf658)

- [ ] Next to the error type, there is a little icon to indicate the widget. Hovering over it causes the mouse pointer to change to a clickable hand, but clicking on it does nothing. Only when I click on the name of the widget, user is taken to the widget where the error is occurring

- [ ] In case of a MultiTreeSelect Widget, The type error text is going beyond the view port of the error section.
![ErrorHandling_Widget_TypeErrorMultiSelect.png](https://images.zenhubusercontent.com/6242f2f59960209e891f50ec/5ecd2d17-70e9-4edb-b308-1e99f57e5620)
