### ISSUE TITLE
[Feature]: redesigning query components to make them responsive

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#19744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We need to update our query pages and components at a design system level to ensure they work on smaller layouts. Some components do not scale with size at all, while others scale in ways making them unreadable on smaller screens. We would need to update these components to follow better responsive rules. The details about these responsive rules will follow on this issue

### Why should this be worked on?

Currently, our query pages are not responsive. If you resize the window, it doesn't always make sense. Since we are heading towards a split pane layout, we would need these pages to work with narrower panes/windows.

### Subtasks
Update the following Input types to follow the responsive rules mentioned

Input Name | Min width | max width | dependant on
-- | -- | -- | --
INPUT_TEXT | 380px | Current width (seems to be 520 px) | Parent object, should start resizing when the edge of the pane approaches the right-hand side of the pane
QUERY_DYNAMIC_TEXT | 380px | 872px | Parent object should start resizing when the edge of the pane approaches the right-hand side of the pane
NUMBER_INPUT | 380px | Current width (seems to be 520 px) | Parent object, should start resizing when the edge of the pane approaches the right-hand side of the pane
UQI Components | | |[See here](https://zpl.io/RMjYwZE) 

Aditional fields to follow

### Design link
https://zpl.io/RMjYwZE

**Comment by Richarex** [comment]
- [ ] **EVALUATED VALUE** dialog is overlapping on the query setting text input page. Please refer to the attached SS:- ![image.png](https://images.zenhubusercontent.com/62badfdc6f3cdb34fefec47e/80ec45e0-531c-4f53-822f-709d1922753e)
- [ ] Edit icon button is overlapping with the 3dots on the query text input page. Please refer to the attached SS:- ![image.png](https://images.zenhubusercontent.com/62badfdc6f3cdb34fefec47e/15145fdc-5d42-4b16-8dc1-4437e51ba9ee)

**Comment by akash-codemonk** [comment]
## Subtasks

Components which need to be updated

- [ ] Responsive INPUT_TEXT, QUERY_DYNAMIC_TEXT controls
- [ ] Responsive ENTITY_SELECTOR
- [ ] Responsive WHERE_CLAUSE_CONTROL
- [ ] Responsive SORT_CONTROL
- [ ] Responsive PAGINATION_CONTROL

**Comment by akash-codemonk** [comment]
> * [ ]  **EVALUATED VALUE** dialog is overlapping on the query setting text input page. Please refer to the attached SS:- !
> * [ ]  Edit icon button is overlapping with the 3dots on the query text input page. Please refer to the attached SS:- !
> * [ ]  API editor page at the bottom all the headers are overlapping with each other. SS:- ![image.png]

Out of scope of this issue but will be addressed separately.  @Richarex

**Comment by ramsaptami** [comment]
tracking issues mentioned above in #21208 as part of multipane changes
cc: @Richarex
