### ISSUE TITLE
[EPIC]-[650]:Enable embedding of Appsmith apps

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#1979]
## Summary

Appsmith apps can be embedded in other apps. We need to make it easy for developers to find a way to embed Appsmith

Tasks:
- [ ] Make it easy for developers to find a way to embed - Enable an embedding modal/popup which will allow users to access the embedding code block
- [ ] Make it easy for a developer to preview different embed sizes
- [x] Add a watermark linking to Appsmith landing page - needs more info
- [ ] Allow the user to configure settings within the modal - Making the header visible/invisible, setting the dimensions, on and making page names visible/invisible
- [x] #15538
- [x] send messages to the parent iFrame ([Being tackled here](https://github.com/appsmithorg/appsmith/issues/7241))

**Comment by dilippitchika** [comment]
Link to a good UI shared by Dancia - https://theappsmith.slack.com/archives/CNQ9Q91C0/p1645686047713229

![image](https://user-images.githubusercontent.com/19730984/155475559-cb6e2156-c891-4508-854b-539d8ccbf790.png)

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 5000 |
| Effort (months)  | 2 |

**Comment by manikumarnune123** [comment]
I have a idea as shown in the figure.

![image](https://user-images.githubusercontent.com/65438060/172117227-6c9e94aa-e251-4f55-b1ea-a7861b099eb9.png)

**Comment by kocharrahul7** [comment]
Job stories:

When I _build an appsmith app_, I want it to  _embed the app on another platform_ , so I can  _add new functionality to existing tools_ 

When  I _embed an appsmith app_, I want to  _easily configure the properties for embedding_ , so I can  _know all options available to me, and set it up as I please_  

When  _I embed an appsmith app_, I want it to  _have a visual interface to configure the embedded app_, so I can  _do it without having to rely on documentation or outside resources_ 

When  _I embed an app_, I want it to  _communicate with the platform it is embedded in_ , so I can   _leverage existing workflows/functionality of other tools, and enhance them using appsmith_

**Comment by RoopKrrish9696** [comment]
*Here are the first solution explorations around in-app embed settings* : cc @kocharrahul7 @ginilpg @eco-monk 

https://www.figma.com/file/NTbOAyb1Popy6bgiwjOuBy/Enable-embedding-of-Appsmith-apps?node-id=7413%3A33489

Loom - https://www.loom.com/share/378a5ea848ad4bf6ba2a68f0f06bcf0f
