### ISSUE TITLE
[Task]: Responsive Style for Select widgets

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#19819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Select widget
- [ ] Multi Select widget
- [ ] Tree Select widget
- [ ] Multi Tree Select widget
