### ISSUE TITLE
[Task]: Responsive Style for Input widgets

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#19816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Input widget
- [ ] Phone Input widget
- [ ] Currency Input widget
