### ISSUE TITLE
[Task]: Track UI issues on the action selector design PR#19689

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#20016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] #21131
![image](https://user-images.githubusercontent.com/92293815/219320433-2913a4a3-058a-40b4-9dcf-e40ea2df9656.png)

- [x] Displaying actions twice on callbacks feels redundant and confusing. The exact same information is displayed twice and in similar styling and behaviour
https://www.loom.com/share/08800770d60f4aa8b61a129b133b64c5
![image](https://user-images.githubusercontent.com/79509062/214578896-c2e80be9-8c2d-4f96-adaa-95148af64b27.png)

- [x] #21111
![image](https://user-images.githubusercontent.com/79509062/214243189-0c3cc15c-3c2e-422c-8a5f-140e5341a4ee.png)

- [x] Pop up overlapping
![image](https://user-images.githubusercontent.com/92293815/214248664-320cdb71-94c6-426d-aaa0-72b6bfac16b0.png)

- [x] ```Configure onClick``` popup still remains when below steps are performed.
 * Select an action > Execute a query > New query 
 * Select an action > Run an API > New API
 * Select an action > Now click on  Omnibar
![image](https://user-images.githubusercontent.com/92293815/214262250-d75b0165-5d6e-490e-a161-aed716777dcc.png)
![image](https://user-images.githubusercontent.com/92293815/214250448-21c640d2-6d86-4ff1-a30c-132c9d4b18b8.png)

- [x] Search text still persists in ```Configure onClick``` pop up. Refer [video](https://loom.com/share/87f121fb7d5b47d0b84627fef501b2d4)
![image](https://user-images.githubusercontent.com/92293815/214252711-73e215c6-bedc-44f4-853a-7da95b72dfee.png)

- [x] The cursor highlight is present on the last selected action in the pop up. Refer [video](https://loom.com/share/136f7ce3d19b4e0896dffc00e4d1a760)

- [ ] #21112

- [x]  Every time I am trying to add store value data with {{Text.text}}, pop up is removed

Select store value> Add key = abab >> Value = {{text}}>> verify that the pop up is gone
https://user-images.githubusercontent.com/80756091/214266981-5d1d9239-d7ec-474d-9c08-21bed6c65e2e.mov

- [x] For trigger fields _Download_, _Reset widget_ & _Get geolocation_ empty quotes and braces are present 
![image](https://user-images.githubusercontent.com/92293815/214263965-b8889e2a-9661-4b22-afb4-6b173d388862.png)

- [x] Overlapping pop ups for more than one trigger field. And not able to select the earlier one's without deleting. Refer [video](https://loom.com/share/10105e78f8c940a2bd43883f7d4d4039)
![image](https://user-images.githubusercontent.com/92293815/214267601-b84a117f-e553-47ce-91e1-c2177dc85c13.png)

- [ ] #21233
![image](https://user-images.githubusercontent.com/92293815/214275395-77341458-f548-4a1e-b85e-96697ddf98c1.png)

- [x] Placement of elements are too close
![image](https://user-images.githubusercontent.com/79509062/214311088-d4066218-8608-45e5-9967-d75a4ba4795c.png)

- [x] Width of dropdown should be the same as the options field (present on navigateTo dropdown and widget selection for resetWidget, openModal, closeModal)
![image](https://user-images.githubusercontent.com/79509062/214315740-245ef923-8bb8-4948-abc1-afe191a602da.png)

- [x] Dropdown box spills outside of the pop-up container box
![image](https://user-images.githubusercontent.com/79509062/214316291-f7299447-1cee-45b6-a2a9-936a710db226.png)

- [x] Slash command icon is not centered
![image](https://user-images.githubusercontent.com/79509062/214323312-37599b79-ce99-4ae9-94bd-4808e538eeaa.png)

- [x] On adding a new action when an action selector pop-up is already open, then pop-up does not close or switch focus to the newly added action block
![image](https://user-images.githubusercontent.com/79509062/214324113-7fead94d-9d5d-4961-bc64-6c6eac6d5c59.png)

- [x] Selecting an API query from the new option, run an API shows up as "Execute a JS function"
![image](https://user-images.githubusercontent.com/79509062/214325223-6fb766a6-c862-4c5b-bf60-4f1bbd138905.png)
![image](https://user-images.githubusercontent.com/79509062/214325082-a0d7b75e-6710-4367-b3ab-a2ac1a4d6957.png)

- [x] Clicking on JS function turns the text white
![image](https://user-images.githubusercontent.com/79509062/214325750-8ab8e592-41cd-4ccc-a9d5-753d5386720e.png)

- [x] Sub-text is not displayed for closeModal, clearInterval
![image](https://user-images.githubusercontent.com/79509062/214326471-d0fc4f00-3307-4353-ae79-e497db346bb1.png)
![image](https://user-images.githubusercontent.com/79509062/214326635-6eda2238-1fbd-4cb0-95cd-713398720c4d.png)

- [x] There are 2 dots appearing under download action that looks incorrect
![image](https://user-images.githubusercontent.com/79509062/214327060-cf09d6a2-7500-4ee0-906d-87efc8ba8d26.png)

- [x] PostMessage does not have an icon and no sub-text appears for this function
![image](https://user-images.githubusercontent.com/79509062/214327778-cbd1d954-0d1c-4605-b700-552cf5b5abea.png)

- [x] On first selecting an option from dropdown and revisiting the dropdown, we notice none of the options are highlighted. On changing the action and revisiting, we see the previous action highlighted
https://www.loom.com/share/87900e51773b474ba47b64553c7e3f49

- [x] need a better hover state
https://www.loom.com/share/e46195a33846421ab30b6b449413186a

- [x] Uneven font styles and font sizes
![image](https://user-images.githubusercontent.com/92293815/214482915-aafef741-4a1b-404a-b5c3-1a70566c3513.png)

- [x] Long file name in download trigger field causes UI overflow and center aligned (also with navigateTo)
![image](https://user-images.githubusercontent.com/92293815/214511116-588a309c-1472-4275-873b-9663d027365e.png)
![image](https://user-images.githubusercontent.com/92293815/214506368-05313f7b-ed7e-4913-82c1-f317c54d1c7d.png)
![image](https://user-images.githubusercontent.com/79509062/214514023-3c7cec61-410f-4eec-a890-17eaf7358dbc.png)

- [x] Using 'New binding' option from slash command dropdown causes autocomplete to show up on the entity explorer (Timestamp at 15s)
https://www.loom.com/share/c11ff9d8bf25422db994c5e29700a9e1

- [x] Opening up action selector when field is at the bottom of the property pane causes the bottom bar (with git and debugger icons) to expand as seen in the screenshot
https://loom.com/share/b63efa3b8dcc4136af89cb15e53bc0b1
![image](https://user-images.githubusercontent.com/79509062/214514396-4a604c8e-e816-4a0a-89a9-9cb2bc8cc63f.png)

- [x] Need to double click on add button on existing widgets that have an action configured already
https://www.loom.com/share/39fb30df8446449ca284fbb6535257a5

- [x] The size of `+` icon for the onClick action field appears bigger & bolder than the rest of the icons seen on property pane and entity explorer
![image](https://user-images.githubusercontent.com/92293815/214526675-9336736f-f616-4e61-b01a-cb19d7151a9d.png)

- [x] After 5 actions, the pop-up starts showing a non-allowed icon on hover but user can continue to click to add functions. This restriction also does not extend to the plus icon
https://www.loom.com/share/06ca53f17d064b95838d09dd13a9eb4e

- [x] The delete icon is darker than rest of the other icons
![image](https://user-images.githubusercontent.com/92293815/214526319-cdc88d47-7c35-44fc-a214-e49e6a1f97a2.png)

- [x] No tooltip seen for _Callbacks_, _On success_, _On failure_
![image](https://user-images.githubusercontent.com/92293815/214537010-c7188b7d-425b-43f8-a78f-6ba1b2befd72.png)

- [x] When the `+` icon is clicked and Action tab gets added, it last action tab doesn't get focused. 
https://loom.com/share/bf2f6466a49d4c7db289e75820869c9c

- [x] The first action field pop still remains even when a new second action is added. Does not close automatically.
https://loom.com/share/cc1b78903ae0492ba2b3e338ca49f444

- [ ] #21127
![image](https://user-images.githubusercontent.com/79509062/214555346-b4c6f1ca-99c2-48a9-b964-bb4d9021f091.png)
![image](https://user-images.githubusercontent.com/79509062/214555391-236150c2-7a73-47e9-a74d-be0e83098f02.png)

- [x] Too many borders when Callback functions are added
![image](https://user-images.githubusercontent.com/92293815/214567350-ebc83e9e-c4d0-4200-aea5-e02fc858683b.png)

- [x] _On success_ & _On failure_ hover can be better. Does not match with the rest of the fields in the property pane
![image](https://user-images.githubusercontent.com/92293815/214567836-3c23b981-4515-4ec5-825d-97a2e21be0c5.png)

- [x] #21440
https://loom.com/share/2b741c45188e47b5a3d432b6c0705c79

- [x] Box shifts while accommodating border making it feel jittery
https://www.loom.com/share/dfebb806a7e54b2d9a67b2090730f3dd

- [x] pop-up for success and failure blocks opens up next to the parent function instead of next to where the action configuration is happening
![image](https://user-images.githubusercontent.com/79509062/214576463-c7f914fc-1c69-4eef-b8a2-9e3b3899fa08.png)

- [x] Not able to search widgets when Configure onclick pop is open.
https://loom.com/share/88167a3111d4479f86e068d86512e64d

- [x] When a field is selected the border highlight appears DARK grey
![image](https://user-images.githubusercontent.com/92293815/214582664-0a5dc8fc-e417-431c-bafb-1685cac7f1f5.png)

- [x] When more than 10 on success actions are added the pop up appears on the debugger
![image](https://user-images.githubusercontent.com/92293815/214585649-d483e4fe-7135-4e3f-9604-601a25e1d85c.png)

**Comment by shwetha-ramesh** [comment]
- [ ] Pop up overlapping
![image](https://user-images.githubusercontent.com/92293815/214248664-320cdb71-94c6-426d-aaa0-72b6bfac16b0.png)

**Comment by AnandiKulkarni** [comment]
- [ ] Every time I am trying to add store value data with {{Text.text}}, pop up is removed
Select store value> Add key = abab >> Value = {{text}}>> verify that the pop up is gone
https://user-images.githubusercontent.com/80756091/214266981-5d1d9239-d7ec-474d-9c08-21bed6c65e2e.mov

**Comment by shwetha-ramesh** [comment]
All the above raised UI issues are verified, issues that are still pending are created as a separate new issue. Closing this ticket.
cc: @ramsaptami
