### ISSUE TITLE
[Task]: Track functional issues for action selector redesign PR#19689

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#20015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] `+` is active on JS mode of a trigger field and clicking on it causes a `{{undefined;}}` to appear on the field
       Clicking on it each time adds a semicolon to the mustache brackets like `{{undefined;;}}`
![image](https://user-images.githubusercontent.com/79509062/214251230-576b80c7-f07e-4919-81ae-6f5edc034c7f.png)

- [x] From the above mentioned issue when an action is deleted from UI empty mustache brackets are seen. Refer [video](https://loom.com/share/f5bc52536ee34b7cb7081218bd677990)

- [ ] Data does not download for button widget. [Video](https://loom.com/share/6e4d7e0008b74f3680b543459c02b95f)

- [x] #20847
https://www.loom.com/share/0fd48561872e4763bde15230c4bccf16

- [x] Call back does not show up for Geolocation function
![image](https://user-images.githubusercontent.com/79509062/214327457-9a51d183-e078-430f-9a26-cdc954e7b880.png)

- [x] There's no callback function on the following code and UI still shows as above
![image](https://user-images.githubusercontent.com/79509062/214523607-fdddcbd5-3922-425f-b3f8-ef13c66bb7e8.png)

- [ ]  Below functions are not translating properly on Non JS mode -
 `{{function(){Api1.run().then(showAlert('hi'))}()}}  {{(()=>{Api1.run().then(showAlert('hi'))})();}} `

- [x] Add give Action : Api1.Run> On Success> Query1.Run OnFailure> Query2.Run : Observe that Query2 is added for the failure of the Query1 as well, Please check below screenshot
<img width="579" alt="image" src="https://user-images.githubusercontent.com/80756091/214532217-000c719b-ccb5-46b6-9fd3-2de54a80a1d0.png">

- [x] Add new action >> keep the action selected as no action and trigger the field, It gives error 
https://user-images.githubusercontent.com/80756091/214557507-44fc5c42-35dd-4c0a-a954-bdefd1de2271.mov

- [ ] On a page with no queries/API/objects, selecting to add a new entity as suggested does not default to the newly created entity as it does while adding a new modal widget (video attached to the next point)

- [ ] #21133
https://www.loom.com/share/7e4a7f767c7f4f079db0357ca19e5faf

- [x] Treeselect widget drop down forces closes when trigger field is added.
https://loom.com/share/0a8bb721afdc44379672f9942f6ff994
 
- [x] #21132
https://www.loom.com/share/1d78ef34af3a46658268a15769a319da

- [x] Undoing a change on the action selector, only undoes on the pop-up and not the property pane (refer to the end of the video above)

- [x] #21135
https://www.loom.com/share/fe6edd34b1794fdcb4ea1aeffe481af0

- [x] Add action api call for button >> delete it >> click on button >> error is displayed, After deleting the action {{}} is left
https://drive.google.com/file/d/15mmfqchteYAqpAZb2WlWfoAEVHkI8Y4L/view?usp=share_link

- [x] #21136
```
{{(()=>{
	Api1.run((s)=>{
		Api2.run((s)=>{showAlert('success')}).catch((s)=>{console.log('failed')})
	}).catch((s)=>{console.log('failed API1')})
})()}}
```
https://drive.google.com/file/d/15mmfqchteYAqpAZb2WlWfoAEVHkI8Y4L/view?usp=share_link

**Comment by shwetha-ramesh** [comment]
All issues have been verified.
