### ISSUE TITLE
[Task]: handle hover interaction in code editor

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#20022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Deal with underlining the whole chain of object accessor. (e.g. Api1.data -> when hovering on data) -> take later when we increase scope
- [x] Render a blank react component on hover
- [x] Render with 200ms delay
- [x] Don't stop hover when hovering over blank react component
- [x] Hide evaluate value pop-up on hover (Property pane, Api, Query panes)

**Comment by eco-monk** [comment]
Looking for workarounds. Since codemirror doesn't support hover event natively.
Did a POC last week (around 2 - 3 days).
https://theappsmith.slack.com/archives/C02JT9CSE6L/p1674130598706449

Had technical discussions around this, need to work on those.
