### ISSUE TITLE
[Task]: Issues in JSObject Mutation POC

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#20308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks
```[tasklist] 
# Issues to Resolve
- [ ] #20309
- [x] #20310
- [ ] #20311
- [ ] https://github.com/appsmithorg/appsmith/issues/20582
- [x] Get target object from proxy.
```

- [ ] #19913
- [ ] Explore how we could avoid diffing by understanding the core working of immer or mutative.

**Comment by Rishabh-Rathod** [comment]
The issues mentioned above are resolved. Unit test is tracked separately.
