### ISSUE TITLE
[EPIC] User access management through SCIM

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#20404]
When a team manager in a large company wants to manage users’ access on Appsmith, they would like to automatically create, update and delete Appsmith accounts based on the company’s IdP so that they can easily manage access without duplication in efforts or manual errors.

[Product Note](https://www.notion.so/appsmith/User-Lifecycle-Management-previously-IdP-Group-Sync-e1f718e2e34341919d006f20d8cb5deb)
[Project Page](https://www.notion.so/appsmith/SCIM-542e38db627442d0b10a334b885c0002)
```[tasklist]
### Design Tasks
- [ ] Problem Exploration & Research - June 14th
- [ ] Solution Exploration - June 15th
- [ ] Solution refinement - June 16th
- [ ] Design handoff - June 16th
```

**Comment by UMinky** [comment]
When will work be done on this feature? 
We are happy to make ourselves available as beta testers.

Our requirement for SCIM:
- SCIM / AD(Azure) can create and remove users.
- SCIM will submit all roles and/or groups (multi-roles) assigned to the user in AD to AppSmith. These roles and/or groups will be assigned to the user in AppSmith by SCIM. Creation and filling of roles can be done in AppSmith.
- Login by password must still be possible for certain (admin) users. Otherwise administration without AD-connect (network failure...) is not possible.
- Ideally, when users are created by SCIM, an invitation and/or notification email is sent. As well as when the role or group assignment in AD differs from AppSmith and is adjusted by SCIM in AppSmith.

**Comment by trishaanand** [comment]
SCIM has been successfully released to customers. Closing the tracking epic ticket now.
