### ISSUE TITLE
[Epic]:  ADS new component development

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#20457]
```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith/issues/19317
- [ ] https://github.com/appsmithorg/appsmith/issues/19318
- [ ] https://github.com/appsmithorg/appsmith/issues/19319
- [ ] https://github.com/appsmithorg/appsmith/issues/19320
- [ ] https://github.com/appsmithorg/appsmith/issues/19321
- [ ] https://github.com/appsmithorg/appsmith/issues/19322
- [ ] https://github.com/appsmithorg/appsmith/issues/19323
- [ ] https://github.com/appsmithorg/appsmith/issues/19324
- [ ] https://github.com/appsmithorg/appsmith/issues/19325
- [ ] https://github.com/appsmithorg/appsmith/issues/19326
- [ ] https://github.com/appsmithorg/appsmith/issues/19327
- [ ] https://github.com/appsmithorg/appsmith/issues/19328
- [ ] https://github.com/appsmithorg/appsmith/issues/19329
- [ ] https://github.com/appsmithorg/appsmith/issues/19330
- [ ] https://github.com/appsmithorg/appsmith/issues/19331
- [ ] https://github.com/appsmithorg/appsmith/issues/19332
- [ ] https://github.com/appsmithorg/appsmith/issues/19333
- [ ] https://github.com/appsmithorg/appsmith/issues/19334
- [ ] https://github.com/appsmithorg/appsmith/issues/19335
- [ ] https://github.com/appsmithorg/appsmith/issues/19336
- [ ] https://github.com/appsmithorg/appsmith/issues/19337
- [ ] https://github.com/appsmithorg/appsmith/issues/19338
- [ ] https://github.com/appsmithorg/appsmith/issues/19339
- [ ] https://github.com/appsmithorg/appsmith/issues/19340
- [ ] https://github.com/appsmithorg/appsmith/issues/19341
- [ ] https://github.com/appsmithorg/appsmith/issues/19342
- [ ] https://github.com/appsmithorg/appsmith/issues/19343
- [ ] https://github.com/appsmithorg/appsmith/issues/19344
- [ ] https://github.com/appsmithorg/appsmith/issues/19345
- [ ] https://github.com/appsmithorg/appsmith/issues/19357
- [ ] https://github.com/appsmithorg/appsmith/issues/19568
- [ ] https://github.com/appsmithorg/appsmith/issues/19568
- [ ] https://github.com/appsmithorg/appsmith/issues/19537
```
