### ISSUE TITLE
[Epic]: Component deduplication & grayscale in appsmith

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#20460]
```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith/issues/19383
- [ ] https://github.com/appsmithorg/appsmith/issues/19384
- [ ] https://github.com/appsmithorg/appsmith/issues/19385
- [ ] https://github.com/appsmithorg/appsmith/issues/19386
- [ ] https://github.com/appsmithorg/appsmith/issues/19387
- [ ] https://github.com/appsmithorg/appsmith/issues/19388
- [ ] https://github.com/appsmithorg/appsmith/issues/19389
- [ ] https://github.com/appsmithorg/appsmith/issues/19390
- [ ] https://github.com/appsmithorg/appsmith/issues/19391
- [ ] https://github.com/appsmithorg/appsmith/issues/19392
- [ ] https://github.com/appsmithorg/appsmith/issues/19393
- [ ] https://github.com/appsmithorg/appsmith/issues/19394
- [ ] https://github.com/appsmithorg/appsmith/issues/19395
- [ ] https://github.com/appsmithorg/appsmith/issues/19396
- [ ] https://github.com/appsmithorg/appsmith/issues/19397
- [ ] https://github.com/appsmithorg/appsmith/issues/19398
- [ ] https://github.com/appsmithorg/appsmith/issues/19399
- [ ] https://github.com/appsmithorg/appsmith/issues/19400
- [ ] https://github.com/appsmithorg/appsmith/issues/19401
- [ ] https://github.com/appsmithorg/appsmith/issues/19402
- [ ] https://github.com/appsmithorg/appsmith/issues/19403
- [ ] https://github.com/appsmithorg/appsmith/issues/19404
- [ ] https://github.com/appsmithorg/appsmith/issues/19405
- [ ] https://github.com/appsmithorg/appsmith/issues/19406
- [ ] https://github.com/appsmithorg/appsmith/issues/19407
- [ ] https://github.com/appsmithorg/appsmith/issues/19408
- [ ] https://github.com/appsmithorg/appsmith/issues/19409
```
