### ISSUE TITLE
[Bug]: Action selector redesign -(Round 2)

### ISSUE THREAD

**Issue by AnandiKulkarni** [appsmithorg/appsmith#20666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] #20732
https://www.loom.com/share/824ea55d037c4c189caf6b4a8f26eda4

- [ ] #20741
https://loom.com/share/3d57d37a14db462aae4c2e79696e09a9

- [x] #20783
![image](https://user-images.githubusercontent.com/92293815/219367780-b197b664-8454-4004-97aa-900c1c376fb2.png)

- [x] #20734
https://loom.com/share/9b3c6cafcd0143ed811694dc88fd2b0b

- [x] When `+` icon is clicked the pop up opens up with the drop down list. `Select an action` state is missing. Expected: When `+` is clicked `Select an action` must appear and on click on down chevron the drop down list must appear. Also the drop down must appear below and not above
![image](https://user-images.githubusercontent.com/92293815/219334503-714ac798-0fb5-4153-97b8-e6480aee3721.png)

- [x] #20730
![image](https://user-images.githubusercontent.com/92293815/219301828-30a870b6-b7d2-4e24-8e99-90bad7da2e6a.png)

- [x] #20731
![image](https://user-images.githubusercontent.com/92293815/219319636-b586d8c8-f36a-47ad-9853-e8ae72c70511.png)

- [x] #20735
https://drive.google.com/file/d/1j15mQPvFMoPcW0vrFp3QICHR75BsWf_m/view?usp=share_link
{{Api2.run(() => {
showAlert("success", 'success');
storeValue("aba", "as");
}, () => {
showAlert("Failed", '');
}, {});}}

`{{Api1.run(()=>{showAlert("pass")},()=>{showAlert("fail")});Api2.run(()=>showAlert("pass2"),()=>{showAlert("failed2")})}}`

- [x] #20736
https://drive.google.com/file/d/1GTcZ7BJkBhPCvTZY_l1ZRvz4zWqVvf35/view?usp=share_link

- [x] #20737
{{JSobject1.myFun2();setinterval(
showAlert("test");
}, 5000, '');}} this works on release could you please check why it is not working in DP
myFun2: async () => {
showAlert("success")}

- [x] #20738
https://drive.google.com/file/d/11RVV43Pm9gLL7P0jA5WdOZ3DCNKCXREW/view?usp=share_link

- [x] #20739
https://drive.google.com/file/d/1kdzjQICDE2tRFSC_KfPLlJaiba1j7kYN/view?usp=share_link

- [x] #20740
https://drive.google.com/file/d/1j15mQPvFMoPcW0vrFp3QICHR75BsWf_m/view?usp=share_link

- [x] #20767
![image](https://user-images.githubusercontent.com/92293815/219639783-6c607921-121a-4f9b-9fee-726fb7465d70.png)

- [ ] #20768

- [x] #20784
- [x] #20785
<img width="581" alt="image" src="https://user-images.githubusercontent.com/80756091/220072400-d1b7c464-9434-41ff-a3d8-2bf14ebfe0b7.png">

- [x] #20792
https://drive.google.com/file/d/1Hm8YkzXSP07FB3VF-XSIfwm2x4xvYNHo/view?usp=share_link

- [x] #20809
https://drive.google.com/file/d/1vl1iwovRT40725fNu3Bbh7zT8-XWc2rg/view?usp=share_link

- [x] #20811
https://drive.google.com/file/d/1wJZUUaHB4ApK02ZTYSiy3shfFV-W3246/view?usp=share_link

- [x] #21068
https://www.loom.com/share/59c0745f968a46b98f3caa16f305bcf0

- [x] #21069
 https://loom.com/share/c277d352307e4bb8a7c5dc354ab2ed8d

**Comment by AnandiKulkarni** [comment]
- [ ] Call back for error is not working, please refer attached 
https://drive.google.com/file/d/1RaB3rXN_ZlYlY6RcoDCyjOW8ydFs9uiZ/view?usp=share_link
{{Api2.run(() => {
  showAlert("success", 'success');
  storeValue("aba", "as");
}, () => {
  showAlert("Failed", '');
}, {});}}

**Comment by AnandiKulkarni** [comment]
- [ ] Add three action and delete first one, second one disappeared, On toggle from JS to Non JS it comes back
https://drive.google.com/file/d/1GTcZ7BJkBhPCvTZY_l1ZRvz4zWqVvf35/view?usp=share_link

**Comment by AnandiKulkarni** [comment]
- [ ] Appsmith Standup app breaks in JS and non JS mode
https://drive.google.com/file/d/11RVV43Pm9gLL7P0jA5WdOZ3DCNKCXREW/view?usp=share_link

**Comment by AnandiKulkarni** [comment]
every issue mentioned has separate issue in github, clossing this
