### ISSUE TITLE
[Task]: Oracle Plugin: misc tasks

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#20796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Fix semicolon issue
- [x] Remove server timezone option
- [x] Check and fix the usage of result object type.
- [x] Check and fix the handling of result max size
- [x] Check and fix conn pool config. 
- [x] Check and fix DS test conn leak if any. 
- [x] Check function `toOraclePrimitiveTypeName`
- [x] Check if read only works
- [x] Check usage with native JSON type
- [x] Check usage with stored procedures
- [x] Fix plugin name
- [x] Fix plugin icon
- [x] Change `database name` field to `service name`

**Comment by sumitsum** [comment]
Details added to [this Notion doc](https://www.notion.so/appsmith/Oracle-Integration-JSON-DataType-and-stored-procedure-445bd94c436e49fc89c5b315e60015bb).
