### ISSUE TITLE
[Epic]: Backend Load Testing

### ISSUE THREAD

**Issue by Rhitottam** [appsmithorg/appsmith#20839]
### Research
This phase involves the following steps:

- [x] Get a comprehensive list of API’s to test. This list should mostly include all the the APIs that are frequently used.
- [x] Identify the tools to be used for load testing
- [x] Understand the login flow of Appsmith and create a way to make authenticated requests iteratively without needing login again. 
- [x] Add scripts to seed data into a fresh instance, use this to load test create requests. This data will be divided into different parts with increasing volume so as to be able do load testing with different sizes of load.

### Benchmark against recommended server configuration [t3.medium]
- [x] What is typical database size
- [x] Get common use case scenarios from cloud instance. 
   - Example, How many times a dashboard is viewed vs editor vs view mode.
   - How many execute calls on a page.
- [x] Identify commonly used data source
- [x] Create a scenario with the above information, and load test. We should aim for under 300ms response time for all our internal API's.

### Integrate with CI
- [ ] Find common scenarios that would cover broad areas.
- [ ] Identify metrics that can be measured in a short time [under 10min] with proper thresholds.
- [ ] POC For how to provision an AWS instance from CI and do the following
   - Copy server build to AWS and set it up.
   - Load the previously data defined in scenario.
   - Save the results to a central DB, or log to a text file.
   - Terminate the resources used
We will start with static thresholds and explore the possibility of making them dynamic like we have for UI Perf infra.

### Load, Stress and Spike testing cloud
- [ ] Analyze traffic patterns from analytics, determine the peak load and test for it.
- [ ] Create a replica of production, or should we extrapolate?

### As a tool for developers
- [ ] Utility functions for login, shared cookies etc.
- [ ] Command to provision runner, appserver, and run the specified tests.

### Optimize the runner
We don't need this immediately.

### Success Metrics

| Metric         |
| -------------- |
| Determine the performance of commonly use backend apis under high load  |
| Find performance regression with backend apis  |

### RACI matrix

|  Role | People  | 
| ------------- | ------------- | 
| Responsible   |    @Rhitottam @SatishGandham       |
| Accountable   |      @SatishGandham         |
| Consulted     | @mohanarpit @trishaanand   |
| Informed      |    @somangshu            |

**Comment by Rhitottam** [comment]
Ref: https://github.com/appsmithorg/appsmith/issues/20856
