### ISSUE TITLE
[Task FE - App Share]: Members page UI

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#21016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Support CE flow
- [x] Support BE flow
- [x] Add assign custom role in Members dropdown as well
- [x] Update search bar placeholder to "Search Users" for CE and "Search Users or Groups" for BE
- [x] Members page title hover state tooltip remove for shorter names
