### ISSUE TITLE
[Task FE - App Share]: Add app level menu option for Manage users

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#21018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Add app-level menu option for Manage users
- [ ] Filter members list in invite modal based on user email id being typed (QQ: what to do in case there are multiple users being added in input box?) -> Kept on hold, to be looked at later
