### ISSUE TITLE
[Task]: side nav POC

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#21064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Click action to open entity explorer to the side
- [x] Remove hover logic for entity explorer
- [x] Split Entity explorer, datasources and libraries
- [x] Move Settings pane CTA
- [x] Add documentation CTA (dummy)
