### ISSUE TITLE
[Task]: Issues related to redesigning of query components to make them responsive

### ISSUE THREAD

**Issue by Richarex** [appsmithorg/appsmith#21208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] EVALUATED VALUE dialog is overlapping on the query setting text input page. Please refer to the attached SS:- 
![image](https://user-images.githubusercontent.com/93259714/223319691-e2f3d665-44fd-44be-8c88-a4afb6bcb330.png)
- [ ] Edit icon button is overlapping with the 3dots on the query text input page. Please refer to the attached SS:- 
![image](https://user-images.githubusercontent.com/93259714/223319844-e28960a1-b74d-44a2-8435-6a172fc470d3.png)
- [ ] API editor page at the bottom all the headers are overlapping with each other. SS:- 
![image](https://user-images.githubusercontent.com/93259714/223320030-2f3da223-8980-4171-84d5-df7d994d4a5c.png)

 **Note:**
Creating this ticket to just keep the track of the issues which are to be fixed later on as part of multipane changes.

**Comment by rohan-arthur** [comment]
won't fix - project cancelled
