### ISSUE TITLE
[Task]: Port linting related data processing that happens inside evaluation worker to linting worker

### ISSUE THREAD

**Issue by arunvjn** [appsmithorg/appsmith#22146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### Description
_Following logic needs to be ported to linting worker_
<details>
<summary>TriggerFieldDependencyMap computation.</summary>

`TriggerFieldDependencyMap` is a map that tracks the usage of different functions used in a trigger field, eg. onClick, onRowSelected etc.
</details>
 <details> 
<summary>asyncJsFunctionInDataFields computation.</summary>

`asyncJsFunctionInDataFields` is the map that tracks the usage of asynchronous JS functions inside data fields.
</details>

#### Tasks
- [ ] [Introduce an extensible, unit tested relationship graph entity](https://github.com/appsmithorg/appsmith/issues/23446).
- [ ] [Use this new entity to port the linting related logic.](https://github.com/appsmithorg/appsmith/issues/23447)
- [ ] [Separate tight coupling between evalTree and lintTree logic.](https://github.com/appsmithorg/appsmith/issues/23448)
