### ISSUE TITLE
[EPIC]: Optimise onload API calls

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#22310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] #22453
- [x] #22454
- [x] #23075
- [x] #24618
- [x] #24671
- [x] #23512
- [ ] #23513

![Screenshot 2023-04-05 at 11 04 17 PM](https://user-images.githubusercontent.com/66776129/231360903-4c7238d1-bee8-4188-aa19-1d5e7311d73d.png)

Pages API is called to fetch application id, which is used in subsequent calls.
This was the behaviour before clean urls as well. (We just combined two API's - fetch application and page list)

Proposed solution: used pageId in subsequent calls instead of appid
(So the pages API can be called in parallel)
- [x] check where application id and data is used elsewhere in the code.
And ensure those are not affected. (both edit and view mode)
- [x] check where else these API's with applicationId are used and account for that.
  - [x] forkTemplateToApplicationSaga, addApiToPageSaga
- [x] come up with a list of API's where these changes are required.

**Comment by eco-monk** [comment]
API's list:

Viewer:
- v1/actions/view?applicationId={id}
- v1/collections/actions/view?applicationId={id}
- v1/themes/applications/${applicationId}/current?mode=${mode}
- v1/themes/applications/${applicationId}

Editor:
- v1/actions?applicationId={id}
- v1/collections/actions?applicationId={id}
- same 2 theme API's

**Comment by eco-monk** [comment]
- [ ] applicationVersion is used to create url redirect instance 
- [ ] applicationId and applicationVersion used in sentry logs
- [ ] loadGit relies on applicationData
- [ ] loadAppEntities relies on applicationData/query param to send git details to API

**Comment by eco-monk** [comment]
Things established in the discussion
- Most of the delay in pages API is network delay, so there’s not much to improve there.
- Changing APIs to use pageId instead of applicationId or workspaceId will not be a complex task.
- Complexity lies in dealing with dependencies in client side. So we can expect to spend time there.

**Comment by eco-monk** [comment]
AppInit logic needs to be moved from the `AppViewer/index.ts` to loader and somewhere outside.
So the API calls happens before the chunk gets loaded.

P.S. Same for editor

https://theappsmith.slack.com/archives/C024GUDM0LT/p1683549364382939?thread_ts=1680717649.920199&cid=C024GUDM0LT
