### ISSUE TITLE
[Task]: handle login failures properly on cypress

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#22537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description

cy command : `LoginFromAPI`

- Login assertion is a success even though the API returns an error.
https://www.loom.com/share/086ef8c743ab460194b785a4d22e87cf
- We manually navigate to `/applications` everywhere this command is used. Use automatic redirection from API instead.

## Steps to reproduce

- add invalid user credentials to cypress.env.json
- Run any test
- Notice login assertion being a success and then user getting logged out (due to 401)
![image](https://user-images.githubusercontent.com/66776129/232952530-14098b46-3cf2-45df-9592-3833d279ae8b.png)

## To-do:
- [ ] check for test failures in CE & EE
- [ ] check for merge conflicts in EE (index.js)

**Comment by eco-monk** [comment]
Reopening this, since PR #22524 only exposes the actual login error.
Which we can then use to debug the issue.

**Comment by eco-monk** [comment]
Sorry wrong issue.
