### ISSUE TITLE
[Task]: CDN setup for our appsmith cloud!

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#22987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Scope:
Only static files.

Expected Improvement: 300-600ms improvement on first load.

Steps:
- [x] #23339
- [x] #23369
- [x] Identify a CDN, self hosted, third party, AWS [@sharat87]
- [ ] ~~Research: Is it possible to setup re-write rules on CDN?~~ No longer required, refer 23638 below
- [x] #23638
- [x] #23639
- [x] #23640
- [ ] #23875

At this time we are not considering offering this to self hosted instances, but we will in future.
