### ISSUE TITLE
[Task]: Stop building slim images

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#23481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

The slim images (`appsmith-server`, `appsmith-editor` and `appsmith-rts`) have been deprecated in `v1.9.10`. This task is to now stop building them altogather.

What does this involve?

- [ ] Remove building these images from CI.
- [ ] Remove the `Dockerfile`s.
- [ ] Update any contributor guidelines documentation that talks about these images, to start suggesting solutions involving the single container.
- [ ] ~Remove/update any `docker-compose.yml` files in the repo that are using these images.~
- [ ] Change the counter widget on our README to get stats for the `appsmith-ce` image.
