### ISSUE TITLE
[Task] : [Auto Layout] Modal Widget and App Navigation Test Cases

### ISSUE THREAD

**Issue by marks0351** [appsmithorg/appsmith#23715]
### App navigation tests
- [ ] Create an application with App navigation header, while in both top and left configuration, verify the canvas does not have extra height or width
- [ ] Create an application in auto layout mode, modify app navigation bar setting on the right side pane, go back to canvas, verify that the app is still in Auto layout mode https://github.com/appsmithorg/appsmith/issues/21962
- [ ]  For an Application with lots of pages with App navigation side bar, switching to a page by a button click should scroll the App navigation bar to scroll to the particular page as well https://github.com/appsmithorg/appsmith/issues/21974
- [ ] For an Application is top nav bar in deploy mode, when a widget at the bottom of the page is directly accessed via url such that it scrolls to the widget, make sure the App header does not get cutoff https://github.com/appsmithorg/appsmith/issues/22095

### Modal widget
- [ ] When modal widget is added in Auto layout, either by dragging n dropping or through modal, add more widgets after that and verify that the modal does not occupy space in main Canvas

**Comment by marks0351** [comment]
Addressed as part of https://github.com/appsmithorg/appsmith/pull/23830
