### ISSUE TITLE
[Task]: Context switching POC

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#23734]
### Zeplin
https://zpl.io/GEBRKgr

### Figma prototype
https://www.figma.com/proto/9X04vnxPKN3VcsxqNxxg4L/IDE?page-id=791%3A132485&type=design&node-id=863-239759&viewport=-731%2C-8159%2C0.87&scaling=contain&starting-point-node-id=863%3A239759&show-proto-sidebar=1

### Notion docs
https://www.notion.so/appsmith/POC-Handoff-Document-6b17e90cf96c40c7a371a50b68ca3c1d

### SubTasks

- [x] [Switcher between canvas and code](https://github.com/appsmithorg/appsmith/issues/23735)
- [x] [Entity explorer selectively show widgets/ queries, js etc](https://github.com/appsmithorg/appsmith/issues/23736)
- [ ] [Align datasources, js to the bottom](https://github.com/appsmithorg/appsmith/issues/23737)
- [x] [Widgets shouldn’t reload on switching back to canvas ](https://github.com/appsmithorg/appsmith/issues/23738)
- [x] [The last entity visited should be shown again.](https://github.com/appsmithorg/appsmith/issues/23748)
