### ISSUE TITLE
[Task]: Remove css transform from modal

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#23823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Problem
CSS transform: translate(x, y) causes text heavy to modal to render blurry text on low-resolution monitor
Refer the [issue](https://www.notion.so/appsmith/Snippets-overlay-renders-blurred-text-0cdc147a619a430cbcfd113879a5f712) & [PR](https://github.com/appsmithorg/appsmith/pull/23820) for the fix.

The PR fixes one instance of text heavy modal, ADS Modal should fix it holistically.
- [ ] Use margin to center the modal
- [ ] Remove` transform: translate` from the modal
