### ISSUE TITLE
[Task]: Improve UI on Admin settings page for better UX

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#23835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Improve UI on Admin settings page for better UX. Also, fix some issues after ADS deduplication:
- [ ] SAML sub text, Github sub text
- [ ] Audit logs scroll - text is overflowing above the sticky table header
- [ ] Update authentication page title
- [ ] Audit logs - if only email present in table row, then make it bold
- [ ] Update success message for adding users to groups
- [ ] User icon should not have tooltip on user edit page
