### ISSUE TITLE
Reusability impact metrics: Events tracking

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#24061]
### What are the problems today
- We have no way of measuring the impact of using modules in their apps.
- Our current model just relies on measuring how many users copy their widgets/js/queries across pages

### How do we plan to solve it?
- We have to measure the real impact of time consumed in copying and making changes in multiple places
- We will need to introduce further analytics events to make this possible
- We will need to store the details of where a query is copied from to make the change

### What are the next steps
- [x] Make the changes needed in queries to provide the details of where the query was copied from - https://github.com/appsmithorg/appsmith/issues/24734
- [ ] Create a hashing algorithm to cache details of query and update the SAVE_API event to start sending the originalQueryId and the hash
- [ ] Create a report which contains the logic on measuring the time it takes to make the same change across multiple apis.

**Comment by somangshu** [comment]
Discussed this problem with @dilippitchika as well. 
The challenge we figured is tracking such complex data might be cumbersome and complicated to implement on mixpanel. 
We also discussed an alternate approach to track this ourself. 

We are debating what is the right way forward. @dilippitchika will come back with an understanding of how possible this is on mixpanel first.
