### ISSUE TITLE
[Task]: The `Open documentation` button in the error messages tab should lead to the docs.appsmith.com

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#24279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Change existing links from the errors tab to this link: https://docs.appsmith.com/help-and-support/troubleshooting-guide 
- [ ] Verify with the TM pod if we need to take this into account for the airgapped project/version
