### ISSUE TITLE
[Feature]: Sunset Documentation in the omnibar

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#24278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Omnibar Documentation: The purpose of this feature was to help users with in-app documentation that they could use to solve their problems. Over time, the maintenance of this feature has been a major challenge and it's led to poor experiences while using the product. In the future, we will simply open our docs in a new tab.

### Why should this be worked on?

Documentation in the omnibar has been an ongoing problem for us. Maintenance, as well as a lack of user response. We find that users are struggling with this, and usually don't find helpful documentation links

### SubTasks

- [ ] [Change existing links from the errors tab to docs.appsmith.com](https://github.com/appsmithorg/appsmith/issues/24279) 
- [ ] Disable the hotkey and the omnibar section for documentation (possibly move behind FF)
- [ ] Remove the documentation in the omnibar altogether
- [ ] Disable the middle layer we currently use to translate info from the docs to the omnibar format

**Comment by kavitasmoolya** [comment]
Verified the fix  https://github.com/appsmithorg/appsmith/pull/25005 on release and it is working as expected 

![image](https://github.com/appsmithorg/appsmith/assets/134914630/cc616602-d0a9-4591-9639-d97e55b83543)
