### ISSUE TITLE
[Feature]: Remove snippets

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#24280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Snippets are turning out to be difficult to maintain, as well as a very low success rate. It was intended to show users example code, however, we have not seen a great response from users. They usually ignore it, and the few who do end up using it rarely find success

### Why should this be worked on?

Snippets: The purpose of this feature was to help users with example code they could use to achieve their bindings. The feature adoption has been around 12% of the overall user base and only about 1.8% of users ever see success with it. Less than 3% of users have ever used it more than 2 times. On top of that, we have never maintained or updated the snippets here so it warrants us killing it.

### SubTasks
- [ ] Take a dump of all existing snippets, Share the snippets with the docs team to see if they find value in adding them to the documentation page
- [ ] Remove all front end access to the snippets (via omnibar, CTAs and hotkeys)
- [ ] Move the feature behind a featureflag
- [ ] Remove it altogether
