### ISSUE TITLE
[SCIM - Task]: Azure, Okta & Ping Identity SCIM experiments

### ISSUE THREAD

**Issue by nsarupr** [appsmithorg/appsmith#24431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

```[tasklist]
### Tasks
- [ ] Azure AD configuration
- [ ] Okta configuration
- [ ] Ping Identity configuration
- [ ] Make documentation for the production level configurations
```
