### ISSUE TITLE
[SCIM - Task](RTS): Handler methods to perform API calls to Appsmith server

### ISSUE THREAD

**Issue by nsarupr** [appsmithorg/appsmith#24450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

[tasklist]
### Tasks
- [x] Get all users
- [x] Get user by ID
- [x] Create user
- [x] Delete user by ID
- [x] Edit user by ID
- [x] Get all groups
- [x] Get group by ID
- [x] Create group
- [x] Delete group by ID
- [x] Edit group by ID
