### ISSUE TITLE
[Feature]: Configuring session requests for users

### ISSUE THREAD

**Issue by narhzih** [appsmithorg/appsmith#24455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

PCI requires that after 15 minutes of "idle" time, they must log back in. So it means that if a user is logged in, if they haven't interacted with the app at all (ie clicked a button, navigated to a page, typed into an input, etc) for 15 minutes, they need to be kicked back to a login screen.

This would need to be at the Instance level.

### Why should this be worked on?

For security purposes.

**Comment by ame-appsmith** [comment]
[A BE user](https://appsmith3239.zendesk.com/agent/tickets/1413) wants to configure the SSO session timeout to 1 or 2 days.

**Comment by ame-appsmith** [comment]
[Another BE user](https://appsmith3239.zendesk.com/agent/tickets/1439) would like to control session management.

**Comment by AnnPei-YTL** [comment]
It would be nice to have this feature. Our system do require short session timeout period

**Comment by infinitetrooper** [comment]
@AnnPei-YTL  - do you use OIDC for auth? If yes, you can do this by setting the Access Token expiry to your liking in the Identity Provider, and not set refresh tokens. We will honor that expiry in Appsmith.

**Comment by AnnPei-YTL** [comment]
@infinitetrooper we're in the mid of setting up OIDC, we will try it out once we done setting up SSO, thanks

**Comment by abhvsn** [comment]
Update: We have started working on this feature and are expecting to rollout by 25th March. 

### Tasks
- [ ] Session timeout implementation at tenant level with code split (Backend)
- [ ] Input to add/update timeout in UI with code split with minute level precision (Frontend)
- [ ] Feature flag integration
- [ ] Cypress testcases
- [ ] Ramps if applicable (@infinitetrooper please comment here)

**Comment by infinitetrooper** [comment]
@abhvsn  - Ramps not necessary.
