### ISSUE TITLE
[Epic]: Category token developement

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#24524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith/issues/24525
- [ ] https://github.com/appsmithorg/appsmith/issues/24526
- [ ] https://github.com/appsmithorg/appsmith/issues/24527
- [ ] https://github.com/appsmithorg/appsmith/issues/24528
- [ ] https://github.com/appsmithorg/appsmith/issues/24529
- [ ] https://github.com/appsmithorg/appsmith/issues/24530
- [ ] https://github.com/appsmithorg/appsmith/issues/24531
- [ ] https://github.com/appsmithorg/appsmith/issues/24532
- [ ] https://github.com/appsmithorg/appsmith/issues/24533
- [ ] https://github.com/appsmithorg/appsmith/issues/24534
- [ ] https://github.com/appsmithorg/appsmith/issues/24535
- [ ] https://github.com/appsmithorg/appsmith/issues/24536
- [ ] https://github.com/appsmithorg/appsmith/issues/24537
- [ ] https://github.com/appsmithorg/appsmith/issues/24538
- [ ] https://github.com/appsmithorg/appsmith/issues/24539
- [ ] https://github.com/appsmithorg/appsmith/issues/24540
- [ ] https://github.com/appsmithorg/appsmith/issues/24541
- [ ] https://github.com/appsmithorg/appsmith/issues/24542
- [ ] https://github.com/appsmithorg/appsmith/issues/24543
- [ ] https://github.com/appsmithorg/appsmith/issues/24544
- [ ] https://github.com/appsmithorg/appsmith/issues/24545
- [ ] https://github.com/appsmithorg/appsmith/issues/24546
- [ ] https://github.com/appsmithorg/appsmith/issues/24547
- [ ] https://github.com/appsmithorg/appsmith/issues/24548
- [ ] https://github.com/appsmithorg/appsmith/issues/24549
- [ ] https://github.com/appsmithorg/appsmith/issues/24550
- [ ] https://github.com/appsmithorg/appsmith/issues/24551
- [ ] https://github.com/appsmithorg/appsmith/issues/24552
- [ ] https://github.com/appsmithorg/appsmith/issues/24553
- [ ] https://github.com/appsmithorg/appsmith/issues/24554
```
