### ISSUE TITLE
[Task]: Sanitise warning thrown by ADS components

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#24557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Sanitise warning thrown by Link component
- [ ] Sanitise warning thrown by Select component 
- [ ] Sanitise warning thrown by Menu component
