### ISSUE TITLE
[Epic]: Component Documentation for engineer & designers

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#24595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith/issues/24686
- [ ] [Task]: Create color palette
```
