### ISSUE TITLE
[Task]: one click binding feedbacks

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#24605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Order of queries - show select queries on top and order by last executed query
- [x] Converting from JS to dropdown should be possible for the following cases
   - [x] {{Query.data}}
- [x] Improve query names to be generated using the data table or collection we use
- [x] undefined table data value should show an error on the property pane
- [x] Download option should be disabled when table is generated using one click binding
- [x] Remove the insert binding option from the dropdown
