### ISSUE TITLE
[Task]: Import app having module definition and reference present in app json

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#24638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks
- [ ] Import from file
- [ ] Import from Git

_No response_

**Comment by subrata71** [comment]
Since the import flow greatly depends on the exported file structure this is also blocked due to [this](https://github.com/appsmithorg/appsmith/issues/24637#issuecomment-1624908594).

**Comment by subrata71** [comment]
### Outcome

As discussed with @nayan-rafiq , we cannot block the application import because the required packages are missing. In the case of Git import, the underlying file structure is already changed as soon as you pull the changes from the remote. Reverting the changes in the file system is not suggested by Git Pod as it is a complex process and can lead to unexpected behaviour. 

So, here's the decision
We won't revert the changes made in the import flow due to missing packages or modules, rather the import will finish leaving the application having some dead references to the modules and packages. 

cc: @dilippitchika @infinitetrooper 


### [High level Import flow](https://miro.com/app/board/uXjVPniSQ7U=/?moveToWidget=3458764560276253594&cot=14)
