### ISSUE TITLE
[Task]: PoC on module action entering into action execution flow

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#24645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Figma**

- [Create reusable query from scratch](https://www.figma.com/file/Z0QsSdGOydURn6WIMQ3rHM/Solution-Design?type=design&node-id=670-72379&t=6fpnw9vwheFjgypG-0)
- [Create a reusable query from an existing query](https://www.figma.com/file/Z0QsSdGOydURn6WIMQ3rHM/Solution-Design?type=design&node-id=676-84540&t=6fpnw9vwheFjgypG-0)
- [Mockups per user story](https://www.figma.com/file/Z0QsSdGOydURn6WIMQ3rHM/Solution-Design?type=design&node-id=479-63758&t=6fpnw9vwheFjgypG-0)

**Loom Videos**
- [Create a reusable query from scratch](https://www.loom.com/share/86c4d4c8079a48419d8907905ca6c1d2?sid=f3124e76-b70b-4413-b5d2-4bd7de6cd627)
- [Create a reusable query from existing one ](https://www.loom.com/share/aa5fcc6d1bd74ffcba7a5fab431619d3?sid=db1ac3f7-be36-4b3d-a757-9a5528dd4e8f)

Result of PoC
https://www.notion.so/appsmith/POC-Module-action-entering-into-the-action-execution-flow-e62815024e6e4ac6b94e2122efda0789
```[tasklist]
### Tasks
- [x] Run the required PoC and test it for a few plugins
- [x] Document everything related to the PoC
- [x] Discuss within the team and demonstrate the PoC result
- [ ] Get it reviewed by Nidhi
```

**Comment by subrata71** [comment]
## Purpose 💡


<aside>
The purpose of this PoC is to verify whether module action can fit well with the action execution flow without having the associated `pageId` , `applicationId` and without being self-sufficient, unlike regular action.

</aside>

Note: An action e.g. query, API enters into the action execution flow when the user clicks on the run button explicitly or the action is triggered through some other ways e.g. button click, onPageLoad.

## Assumptions and Considerations

Unlike regular action (Query, API, and JS function) the module action doesn’t have any `pageId` and `applicationId`. Instead, it will have the respective `moduleId`. Module action is not self-sufficient because some settings e.g. `timeout`, `executeOnLoad`, `confirmBeforeExecute` are not part of the module action. These settings are part of the module instance. 

What’s an instance? Module consumer needs to instantiate a module before using it. Through instantiation, the module consumer creates an instance of the module and the above settings become part of that very module instance as the module consumer can change these settings according to his/her preference. 

Module instance belongs to a page and a page belongs to an application. Module instance talks to the original action and provides the above three settings at the time of execution.

![Modules_ Schema Design - Schema Design_ MVP_ Query Module_ Iteration 2_ Latest.jpg](https://images.zenhubusercontent.com/6285d4bd3bfe8b03b07c8593/8615058b-8949-41e0-8db9-d79393e84ed4)

https://miro.com/app/board/uXjVMCer_qA=/?moveToWidget=3458764556504997793&cot=14

## Expected Outcome

At the end of this PoC, we will be able to tell whether the module action without being self-sufficient can fit well with the action execution flow or not. 

If it doesn’t fit then we will be able to tell what kind of transformer we need to implement in order to make it compatible with the action execution flow.

### Approaches investigated

- ~~Tried to create module action using the existing implementation of creating a new action by bypassing certain validations but couldn’t make it work as this flow has a lot of dependency on `pageId` and `applicationId` -~~ **FAILED**
- Implemented a new API endpoint which creates a module action without any associated `pageId` and `applicationId`. Through this new endpoint we created a document in newAction without having any associated pageId and applicationId.

## Results

The result is quite satisfactory. In the entire action execution flow there’s no dependency either on `pageId` or `applicationId`. The only information we need to plug into the module action from the module instance is the `timeout` setting. Other than this setting the module action is able to fit well with the action execution flow.

Tested for the following plugins

| Plugin | Remarks |
| --- | --- |
| PostgreSQL | Works |
| MySQL | Works |
| MongoDB | Works |
| REST API | Works |
| GoogleSheets | Works |
| S3 | TBD |

We also need to make necessary changes in the `/execute` API to help server identify the right instantiated module instance. We need to send the `moduleInstanceId` along with the `actionId`. 

```json
{
  "actionId": "648c0b7493c9d5248531b4ea",
  "viewMode": false,
  "paramProperties": {},
  "analyticsProperties": {
    "isUserInitiated": true
  }
}
```

```json
{
  "actionId": "648c0b7493c9d5248531b4ea",
  "moduleInstanceId": "XYZ",
  "viewMode": false,
  "paramProperties": {},
  "analyticsProperties": {
    "isUserInitiated": true
  }
}
```

[Read it on Notion](https://www.notion.so/appsmith/POC-Module-action-entering-into-the-action-execution-flow-e62815024e6e4ac6b94e2122efda0789)
