### ISSUE TITLE
[Task]: Design module schema

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#24659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Figma**

- [Create reusable query from scratch](https://www.figma.com/file/Z0QsSdGOydURn6WIMQ3rHM/Solution-Design?type=design&node-id=670-72379&t=6fpnw9vwheFjgypG-0)
- [Create a reusable query from an existing query](https://www.figma.com/file/Z0QsSdGOydURn6WIMQ3rHM/Solution-Design?type=design&node-id=676-84540&t=6fpnw9vwheFjgypG-0)
- [Mockups per user story](https://www.figma.com/file/Z0QsSdGOydURn6WIMQ3rHM/Solution-Design?type=design&node-id=479-63758&t=6fpnw9vwheFjgypG-0)

**Loom Videos**
- [Create a reusable query from scratch](https://www.loom.com/share/86c4d4c8079a48419d8907905ca6c1d2?sid=f3124e76-b70b-4413-b5d2-4bd7de6cd627)
- [Create a reusable query from existing one ](https://www.loom.com/share/aa5fcc6d1bd74ffcba7a5fab431619d3?sid=db1ac3f7-be36-4b3d-a757-9a5528dd4e8f)

## [View on Miro Board](https://miro.com/app/board/uXjVMCer_qA=/?moveToWidget=3458764556504997793&cot=14)

A package can have one or many modules. The package has similarities to the application.

A module can be of type UI, JS, and Query. For MVP we will only be implementing the Query module.

A query module contains exactly one reusable query.

### Nomenclature

1. **Package Creator -** An Appsmith developer who creates and shares a package; creates/updates a module within the package.
2. **Package Consumer -** An Appsmith developer who consumes a shared package.
3. ********************Package -******************** Collection of modules.
4. **Package Metadata -** (version, description). 
5. **Module -** A module is an entity that is created by the *******************************Package Creator*******************************.
6. ******************************Module Entities -****************************** An entity that is part of a module (Query / JSObject / Widgets / Module Instance).
    1. **Module Private Entity -** An entity that can be interacted within the module only.
    2. **Module Public Entity -** An entity that can be interacted within the module and also is exposed outside of a module but through the interface of a ***Module Instance**.*
7. ************************Module Properties -************************ 
    1. ************************Module Input -************************ Inputs that can be defined by the ******************************Package Creator********************.*
    2. **Module Input Metadata -** These are the properties that define an input. E.g. *********************************controlType, validation, label, etc.*********************************
    3. **Module Metadata -** These are the properties that can describe a module. E.g *description, documentation URL, icon, display name etc.*
8. **Module Config -**
    1. ********Whitelisted Public Entity Config -********
9. **************************************Installed Package -************************************** A package which is added to an application and the modules of the package are ready for instantiation within a page.
10. **Module Instance -** An entity which acts as an interface between the page entities and the module. The module instance holds the state for ******************************************************Module Properties.******************************************************
11. **Module Instance Properties -**
    1. **Module Instance Input -** 
    2. ********************************************Module Instance Config******************************************** -

```[tasklist]
### Tasks
- [x] Write documentation and draw on Miro for everyone's understanding
- [x] Discuss within the team
- [ ] Get it reviewed by Nidhi
```

**Comment by nidhi-nair** [comment]
LGTM

**Comment by subrata71** [comment]
### Outcome

We found that the current schema design for the query module is extensible to the JS module although it's not comprehensive but we agreed that it's open for extension. 

[Schema for Query module](https://miro.com/app/board/uXjVMCer_qA=/?moveToWidget=3458764557923252245&cot=14)

[Schema for JS module](https://miro.com/app/board/uXjVMCer_qA=/?moveToWidget=3458764557894525682&cot=14)


Based on this feedback I am closing this issue.
