### ISSUE TITLE
[Task]: Send `originalActionId` parameters to the create Action API

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#24734]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### SubTasks

To measure the impact of query modules in Appsmith. We need to track the amount of time a user takes to edit a copied query. Today, we do not have a mechanism to understand if a query in question is a copied query. To fix this, the data model of the Query action needs to change to include the `originalQueryId` if a query is, in fact, a copied query. 

- [ ] When a query is first copied, there will be no `originalQueryId` in the action object. In this scenario the client will populate the `originalQueryId` field and call the POST API to create the copied query. 

- [ ] If the query is already a copied query, the client will duplicate the value of the `originalQueryId` when calling the POST API to create the copied query.

### [Related discussion on Notion](https://www.notion.so/appsmith/Backend-dependency-for-modules-instrumentation-889462d461844745be0a2599c8555ca5)

**Comment by subrata71** [comment]
@riodeuno 
The current payload for creating a new action for the PostgreSQL plugin is as follows

```
{
  "actionConfiguration": {
    "pluginSpecifiedTemplates": [
      {
        "value": true
      }
    ]
  },
  "name": "Query3",
  "pageId": "64959533c9ec61457bf6be1d",
  "pluginId": "64297e482273a30d71cf669b",
  "datasource": {
    "id": "6492df2c9e16d365ffd0d30c"
  },
  "eventData": {
    "actionType": "Query",
    "from": "SUBMENU",
    "dataSource": "Users",
    "datasourceId": "6492df2c9e16d365ffd0d30c",
    "pluginName": "PostgreSQL",
    "isMock": true
  }
}
```

Although the client side sends some data in the `eventData` attribute, the server doesn't capture this data.

Do you think the server should capture the entire `eventData` attribute and the new parameter in question `originalQueryId`should also be part of it?

**Comment by subrata71** [comment]
|Case|Creating a query from scratch|
|---|----|
### Request Payload (New)
```
{
    "actionConfiguration": {
        "pluginSpecifiedTemplates": [
            {
                "value": true
            }
        ]
    },
    "name": "Query5",
    "pageId": "64959454c9ec61457bf6be1a",
    "pluginId": "64297e482273a30d71cf669b",
    "datasource": {
        "id": "6492df2c9e16d365ffd0d30c"
    },
    "eventData": {
        "analyticsData": {
            "originalActionId": null,
            "actionType": "Query",
            "from": "SUBMENU",
            "dataSource": "Users",
            "datasourceId": "6492df2c9e16d365ffd0d30c",
            "pluginName": "PostgreSQL",
            "isMock": true
        }
    }
}
```

### Response
```
{
    "actionConfiguration": {
        "pluginSpecifiedTemplates": [
            {
                "value": true
            }
        ]
    },
    "name": "Query5",
    "pageId": "64959454c9ec61457bf6be1a",
    "pluginId": "64297e482273a30d71cf669b",
    "datasource": {
        "id": "6492df2c9e16d365ffd0d30c"
    },
    "eventData": {
        "analyticsData": {
            "actionType": "Query",
            "from": "SUBMENU",
            "dataSource": "Users",
            "datasourceId": "6492df2c9e16d365ffd0d30c",
            "pluginName": "PostgreSQL",
            "isMock": true
        }
    }
}
```


|Case|Create a copy of an existing query through Copy CTA|
|---|----|

### Request Payload (New)
```
{
    "actionConfiguration": {
        "pluginSpecifiedTemplates": [
            {
                "value": true
            }
        ]
    },
    "name": "CopyOfQuery5",
    "pageId": "64959454c9ec61457bf6be1a",
    "pluginId": "64297e482273a30d71cf669b",
    "datasource": {
        "id": "6492df2c9e16d365ffd0d30c"
    },
    "eventData": {
        "analyticsData": {
            "originalActionId": "64991ac8350bc33377739442",
            "actionType": "Query",
            "from": "SUBMENU",
            "dataSource": "Users",
            "datasourceId": "6492df2c9e16d365ffd0d30c",
            "pluginName": "PostgreSQL",
            "isMock": true
        }
    }
}
```

### Response (New)
```
{
    "actionConfiguration": {
        "pluginSpecifiedTemplates": [
            {
                "value": true
            }
        ]
    },
    "name": "CopyOfQuery5",
    "pageId": "64959454c9ec61457bf6be1a",
    "pluginId": "64297e482273a30d71cf669b",
    "datasource": {
        "id": "6492df2c9e16d365ffd0d30c"
    },
    "eventData": {
        "analyticsData": {
            "originalActionId": "xyz",
            "actionType": "Query",
            "from": "SUBMENU",
            "dataSource": "Users",
            "datasourceId": "6492df2c9e16d365ffd0d30c",
            "pluginName": "PostgreSQL",
            "isMock": true
        }
    }
}
```

**Comment by tkAppsmith** [comment]
A lot of fields are missing between the current response data. Such as 
```
"errorReports": [],
"executeOnLoad": false,
"dynamicBindingPathList": [],
"isValid": true,
"invalids": [],
``` 

And also from the nested field "eventData", "analyticData" filed is added but other fields removed. Is there a plan to deprecate these fields or is it just to keep the response and request concise for documentation?

**Comment by subrata71** [comment]
@tkAppsmith 
> A lot of fields are missing between the current response data.

Apologies for missing out on those fields. All the fields in the current response data will continue to appear in the new response as well. In addition, some analytics-related data will also appear under a new attribute e.g. `eventData`. The response that I shared above is not the final one but it's good enough to explain what type of changes we are going to implement.


> And also from the nested field "eventData", "analyticData" filed is added but other fields removed. Is there a plan to deprecate these fields or is it just to keep the response and request concise for documentation?

Can you please elaborate?

**Comment by tkAppsmith** [comment]
> Can you please elaborate?

It is the same comment but for the "eventData" field of the response. I think your last comment resolves this as well. Thanks.

**Comment by subrata71** [comment]
@tkAppsmith Can we finalize the request payload and response? Do you see any problem with the proposal above?

**Comment by tkAppsmith** [comment]
I think the above proposal is fine. One last query I had is that the current request also has eventData field of which following fields are part of. 
```
"eventData": {
    "actionType": "Query",
    "from": "SUBMENU",
    "dataSource": "users",
    "datasourceId": "6492c32222f37825415f1283",
    "pluginName": "PostgreSQL",
    "isMock": false
  }
``` 
Now we are nesting those fields in analyticsData under eventData field. Since this is not yet captured by server then it shall be fine but any other place can you think of where this change might break stuff?
```
"eventData": {
        "analyticsData": {
            "originalActionId": "xyz",
            "actionType": "Query",
            "from": "SUBMENU",
            "dataSource": "Users",
            "datasourceId": "6492df2c9e16d365ffd0d30c",
            "pluginName": "PostgreSQL",
            "isMock": true
        }
    }
```

**Comment by subrata71** [comment]
Although the client side sends this `eventData` as part of the request payload the server doesn't capture this till now. I don't think the change mentioned above will break any stuff. @tkAppsmith

**Comment by subrata71** [comment]
### Decision
So, we are going to introduce a new attribute in the request payload to send all the data related to analytics. Let's call this new attribute `eventData`. And inside `eventData` there's another attribute named `analyticsData`. Inside `analyticsData` attribute you can send whatever you want and those attributes will be reflected in the GET action API.

### Scope of change
- API 
- Query

### Out of scope
- JS Object
Note: If JS object requires similar analytics then we need to implement this in JS object in the same way as JS object has its own endpoint of creating/copying a JS object.

### How to identify whether a query is a copy?
If the `eventData->analyticsData->originalActionId` exists in the GET action response, then it means it's a copied query and the `id` of the original query is `XYZ`. 

```
"eventData": {
        "analyticsData": {
            "originalActionId": "XYZ"
         }
}
```
### How to identify whether a query is a copy?
If the attribute itself doesn't exist or it exists but contains a null value then it denotes that it's not a copied query.

@tkAppsmith Please let me know if the suggested change looks good to you. Based on your confirmation we will start implementing this.

cc: @riodeuno

**Comment by tkAppsmith** [comment]
@subrata71 Hey. I have gone through the final decision. The design and the changes to request and response seems good for the use case. I have completed the review from my end. I dont have any more comments. Thanks.

**Comment by subrata71** [comment]
@riodeuno Based on Tushar's confirmation given [above](https://github.com/appsmithorg/appsmith/issues/24734#issuecomment-1611257598), can we start implementing this? 
Please let me know if the above proposal works for you.

**Comment by riodeuno** [comment]
Just to clarify, the response object for an action will contain the `originalQueryId` in the `eventData`, in case this is a copied action in the first place. 
Please confirm.

**Comment by subrata71** [comment]
Changed the estimate from 1 to 1.5 as the same issue is being used to track both the frontend and backend changes.
