### ISSUE TITLE
[Task]: Remove duplicate frontend events for testing datasource

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#24971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Events to remove:
- [ ] TEST_DATASOURCE_CLICK
- [ ] TEST_DATASOURCE_FAILED
- [ ] TEST_DATASOURCE_SUCCESS
