### ISSUE TITLE
[Task]: Upgrade to storybook 7 

### ISSUE THREAD

**Issue by tanvibhakta** [appsmithorg/appsmith#25000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] upgrade the project to using yarn as well (via zero installs)
- [x] first need to move webpack4 to webpack5
- [x] then need to replace `@storybook/addon-postcss` with `@storybook/addon-styling`  
- [x] rerun the migrator
