### ISSUE TITLE
[Epic] JSON Form: Generate forms from JSON Object/Queries/APIs

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2504]
## Objective

As a user, I should be able to generate a form with input fields by using fields of a DB table schema that automatically generates the queries, bindings and child widgets. As a user, I should be able to configure changes/validations easily here.

## Features

- [ ] It should automatically identify the datatypes and associated widgets for the form
- [ ] It should be able to add basic validations that can be enhanced by the user
- [ ] It should be able to automatically connect the submit buttons to the relevant queries (PUT/POST/CREATE/UPDATE).

## Success Metrics

| Goal  | Metric |
| ------------- | ------------- |
| Simplify user experience  | One-click to generate a form from a single DB schema and be able to map it to a PUT/POST request which updates/saves data |
| Decrease the time needed to build a form  | Time that user spends creating a form |

## Assumptions

- Forms are the core building block of a web application
- It is currently difficult/time-taking to set up a working form comprising of multiple child widgets and bind them all the data query and finally be able to add them to a post request
- One of the most common operations in any DB is the insert/add/create entry operation. It would go a long way to save the user time by generating the scaffolding, if not the complete widget for users

## Requirements

| Requirement   | User Story | Importance | Notes |
| ------------- | ------------- | ------------- | ------------- |
| Connecting to Query/API  | As a user, I should be provided with all the option to connect to different queries and APIs. Furthermore, I should be able to select the fields I need inside the form and I should be able to change the datatype to others from what was automatically connected | High  | If this is not going to be based on the response object and depend on the DB schema, this will be removed from the scope |
| Create a form from a JSON object  | As a user, I should be provided with all the option to create a form from a JSON object apart from the Queries/APIs. All the other functionalities mentioned above will be extended here as well | High  | - |
| Identify datatypes and associated widgets  | As a user, after connecting a DB query to the form, the platform needs to identify the widget types based on the data types. For ex: `Array` maps to `Select` widget. All the widgets need to remain configurable | High  | related to the first requirement |
| Basic input validation  | As a user, I should be able to see basic input validations for the form I have created from an internal DB query and also be able to modify any of these easily | High  | related to the first requirement |
| Connect submit action to queries that update related DB schema | As a user, I should be able to easily configure the submit request which finally updates or saves my data. I should be shown all fields preloaded in my query and appropriate bindings against them  | High  | This might not be involved in this scope |
| Auto naming with schema / object keys | All fields & label in the form should be named based on the schema key they are mapped to | High | - |
| Reopen form config | Once import all fields from an object/datasource I should be able to reopen the config page view to alter any initial configurations. This will reset and changes made to the form elements individually. | High | The default connect data will be used for this, another CTA might be required to update the form data through the same workflow |

### Discussion 21-Sept-2021
- We will get rid of the modal which shows up in when setting up the form fields, Instead we show the fields under the field configuration directly
- Fields on the form will be deep linked to the property pane field configuration, i.e. the respective property pane field setting should open when the field on the form is clicked
- The form fields / view will reflect changes as the form data is updates
- We need to keep in mind a future scope while developing the feature. Nesting of form fields / handling nested form data objects `needs design` `**_pending_**`

### Discussion 27-Sept-2021

We decided that the following will be the type of widget taking into consideration, Additionally the component used in this widget will have there own set of properties (like the table widget) which should be covered by automated tests to avoid any regressions in the future. We also discussed the form properties which will need design review 

Types of fields:
- Text
- Number
- Phone
- Email
- Switch (boolean)
- Checkbox (boolean)
- RadioGroup (exclusive or)
- Select (one out of many)
- Multi-Select (many out of many)
- Files
- Date
- Time
​
Complex fields:
- Grouped fields
​
Additional (optional) fields:
- Rate (Range)
- Map (search)
- JSON object
- Audio

---------------- 

We figured Properties of fields:

Common:
- Type
- Default 
- Label
- Disabled
- Required
- Tooltip
- Visible
- helperText
​
Not common:
- Validation Fn
- Error
- Possible values (options)
- Placeholder
- onChange
​
---------------- 

`**_needs design_**`
Main properties of the form for it to work:
Form: data
Form: submit (action)
Form: source data
Form: Edit the field types and properties
​​
Features in the form:
Form -> input type -> possible properties
Form -> has state of the fields
Form -> onSubmit
Form -> onCancel
Form -> can hide cancel button
Form -> can disable submit button
Form -> can reset itself*
Form -> checks for validations -> knows which fields have errors
Form -> tab navigation works
Form -> can scroll to selected fields
Form -> button location (sticky | bottom)
Form -> field styling (borders, colors, label alignment, error colors, helper text, etc)
Form -> spacing between fields
Form -> all fields have full width

---------

Library to consider: react-hook-forms

------------

### Discussion 19-Oct-2021
`Files` component is being considered out of scope right now as the implementation of the widget component is not well constructed to be used in this widget and would need a lot of refactoring.
This can be considered in the next iteration.

## Out of Scope

- Dynamic width / auto layout of form elements
- Alignment templates/Layouts - As a dev, I should be able to choose the layout for aligning my input fields in the form. Templates can be 2 Column, Single column, Label & input side by side. Or, Drag to re-order elements side by side or one below the other

## Developer Handoff Document in Figma
Link: https://www.figma.com/file/pZuLD9mWXtk45TOjAeh32b/Form-Widget-Thu-26-Aug?node-id=2%3A2

## Questions

| Question  | Answer | Date Answered |
| ------------- | ------------- | ------------- |
| How to identify the submit request needs to be Create/Update? |  It will by default be POST the user can change to there choice |   |
| Can we add necessary formatting function ex: JSON.stringify() automatically to remove any invalid api attributes | | |

**Comment by naveennazimudeen** [comment]
It will be great if this can be combined with #2576 to show related information below. Tables have relationship, sometimes expressed in database as foreign keys, sometimes relationship exist but is not defined. For example Invoices have a 1:n relationship with line-items, line-items might have 1:1 relationship to product,

So when defining an invoice page (View Page), it should be possible to see Invoice Line items as table below, where you can possibly filter, search, create (line by line, or go to new page), and edit. The product column can possibly be linked to the product view page. While creating a line-item, it should be possible to "search as you type" for product.

**Comment by somangshu** [comment]
#1724 is a related issue. Can one of them be closed?

**Comment by Nikhil-Nandagopal** [comment]
Why is 
```
The form can be generated from the JSON object
```
out of scope? That should be the core of it since to generate the form from the DB schema, we need a JSON object right?

**Comment by somangshu** [comment]
Just for the purpose of the design phases, You are right though! I will add it to the list of requirements!

**Comment by somangshu** [comment]
Create granular tasks after design is completed.

**Comment by rishabhsaxena** [comment]
Just to pitch in, I was wondering if we have any plans to do wizard forms, basically a form with multiple steps

**Comment by Nikhil-Nandagopal** [comment]
@rishabhsaxena great point. Thought might need to be a separate widget. Could you raise an issue for a wizard?

**Comment by rishabhsaxena** [comment]
@Nikhil-Nandagopal Yeah just created an issue for this https://github.com/appsmithorg/appsmith/issues/6351

**Comment by somangshu** [comment]
After a brief discussion, Here is what we understand:
- Showing all fields as tile inside the property pane (like table widget) can be a viable option, However this is does not let the user see and change all config together and might be tedious to update. 
- Showing all options in the modal can be better but will be an inconsistent experience
- There are two ways to let the user select layout
    - Through a separate widget (column / layout widget)
    - Giving a few custom options while setting up the form (1 column or 2 column)
- Technically we feel that once the fields are organised and finalised we can do the following:
    - Let the user drag and drop anything they'd like without any constrain, but the initial settings are no longer available. In case they wish to start again, there changes are going to be lost
    - The user is not allowed to D&D anything directly and only allow them to do this via config panel (probably have a separate widget in this case)

@momcilo-appsmith @riodeuno please add anything i might be missing here.

cc: @areyabhishek @Nikhil-Nandagopal 

[Reference form builder](https://formio.github.io/aurelia-formio/)

**Comment by tomjose92** [comment]
Hey team, any timeline on this. This would be a great feature to have

**Comment by somangshu** [comment]
@tomjose92 we are in the process are getting designs done for this feature, We will be taking this up for implementation in the month of sept.

**Comment by riodeuno** [comment]
@areyabhishek @Nikhil-Nandagopal The way I see it, there are two different mechanisms to get the _*form widget schema*_

- DB Schema Mechanism
   - Select a table, sheet, etc., from a Datasource - on click mechanism
   - A way for users to select an existing CRUD operation action
   - Allow users to click and auto-generate the missing CRUD operations ( get inputs from the user regarding defaults and required fields)
   - Allow users to select a different schema
   
- JSON Mechanism
   - User selects a JSON from any source like they select data for the Table.
   - No way to automatically connect any CRUD operations, as the source can be anything, including a hard coded JSON object

After the above, the rest are common features.

  - _*Form Widget Schema*_ is generated. This is different from the DB Schema.
  - Allow users to select the input types for the data types in the resulting form widget schema, edit the fields, order the fields, hide the fields, etc.

_*We need to scope this feature based on how the form widget gets the data to generate the form widget schema. *_

I would suggest we go ahead with the JSON mechanism in the first phase and implement the DB schema approach in the second phase. The way users selects a DB schema and CRUD operations needs to be seamless and intuitive, which IMO, needs a little more thought.

cc @somangshu @momcilo-appsmith @ashit-rath

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno all methods are actually the same they all generate the JSON schema. Selecting the table, sheet (from entity explorer) can also just give the json schema which the user then configures. Missing CRUD ops should be out of scope for this. This should focus on building the form faster and more dynamically

**Comment by vnodecg** [comment]
Hey Guys,
I think adding the following features will make the forms.
1. We need ability to validate forms before submit.
  Use case: Say we are submitting user data. We can have validation that `user.username` should be at least 6 characters length.
  
2. We don't have support for nested forms in the design. It'd be good if we can get sets of data. See https://rjsf-team.github.io/react-jsonschema-form/ `Arrays` section for example

@somangshu  @momcilo-appsmith

**Comment by ashit-rath** [comment]
Discussion update:

- All the properties of the fields in the JSON form widget should be the same as the properties of the individual widgets
- Adding a widget or changing the behavior of its property should reflect the same in the field of the JSON form widget.
- Label styling (label color/label text size etc) would be form-level properties rather than field-level.

Architecture approaches -
1. Use the widget's components and store the state of the form internally.
2. Use the widgets directly in the Form and update DSL accordingly.

Current plan of action -
Develop a POC to check the feasibility of approach 1 with all the individual widget's property being present for its corresponding field type in the JSON Form widget.

**Comment by Nikhil-Nandagopal** [comment]
@ashit-rath why is label styling at the form level? Is it for convenience? It should still be at the widget level and maybe at the form level too.

**Comment by ashit-rath** [comment]
@Nikhil-Nandagopal Yeah, it would be quite convenient to have it at the form level, as forms usually have labels with the same styling, and folks can change it in a single go.
Would field-level label styling be relevant?

**Comment by Nikhil-Nandagopal** [comment]
@ashit-rath of course, what if the user wants to change the label color to red when the input is not valid. Use cases are always infinite. The rule of thumb is, If the property exists at the widget level, it should exist at the field level for the form

**Comment by ashit-rath** [comment]
Update - 
We have hashed out details for the component vs widget approach
https://miro.com/app/board/o9J_lldPLLc=/?invite_link_id=152768602582

Possible timeline
Current approach - ~3 weeks of dev time
Widget approach - 7~8 weeks as this will be a complete re-write.

Note: Widget approach - We still have to discuss how the version change of individual widgets would affect the JSONForm widget and how we would incorporate the new versions.

cc: @Nikhil-Nandagopal @somangshu

**Comment by ashit-rath** [comment]
Update -

After some discussion, it's decided to go with the component approach right now.

Reason -
- For the widget approach to work, the platform has to be re-framed at certain parts to make the nested evaluations work; which is a blocker right now.

In the component approach, we would be using the widget's component directly; so any new implementation in the widget component is implemented here as well. To make sure everything is well maintained, strict typings and jest cases would be written to warn of any missing implementation.

For the component approach, the `JSONForm` widget would have its own set of properties for the fields with would mimic the individual widget's properties.

Reason for not directly importing individual widget's properties -
- Standardization of properties across all fields (label/ label styling, positioning of properties).
- If the widget's individual properties are imported directly then the `derivedProperties` would also have to be imported along with it, whose proper execution in the case of the `JSONForm` widget is not supported by the platform right now.

**Comment by ashit-rath** [comment]
Action Items:
- Discuss all the pieces of the widget for designs
- List out the design pieces for review in the next catchup

**Comment by ashit-rath** [comment]
Items for design review - 
- Disabled state of nested form
- Nested form background color (accordion)
- Nested form accordion title
- Icon for the widget

https://www.figma.com/file/pZuLD9mWXtk45TOjAeh32b/Form-Widget-Thu-26-Aug?node-id=0%3A1

**Comment by Nikhil-Nandagopal** [comment]
@lf-floriandin I see 2 issues. 
1. You would like us to support Snowflake for CRUD app generation. This should be possible, I can see there's an issue open for snowflake here #8702
2. You want a data-driven way to select the fields that should be editable.
This will partly be partly possible with this feature. We may decide to let users select the columns that should be editable as well though that becomes cumbersome for a lot of new users. So at the worst, you may need to simply copy / paste a JSON in this widget to configure the fields that are meant to be editable but we will consider letting users select the editable columns as well.

**Comment by ashit-rath** [comment]
Action Items:
- Final design tweaks for the nested form
- De-scope nested form accordion title
- Implement nested fields designs
- Review form-level events (reset/clear)

**Comment by somangshu** [comment]
@ashit-rath @vivekverma2312 is the test plan ready, If not we should get started on that as well

**Comment by Nikhil-Nandagopal** [comment]
@ashit-rath can you please attach the deploy preview to this issue?

**Comment by ashit-rath** [comment]
Deploy preview -> https://appsmith-git-feature-form-builder-widget-get-appsmith.vercel.app/

**Comment by somangshu** [comment]
Action Items:

- Should we have a clear functionality `product feedback` @dilippitchika 
- The Accordion looks like a select, User might feel confused, @vasanth-appsmith will look for the best scenario
- required fields should be visually depicted to the user @vasanth-appsmith 
- Bug fixes related to the input error state.
- Test plan @vivekverma2312

**Comment by ashit-rath** [comment]
Action Items:
- Solve for the best way to sanitize/represent JSON keys that cannot be referenced with a dot (.) notation (eg "first name")

**Comment by dilippitchika** [comment]
For the clear functionality - 
I was finding any existing bugs linked to form widget where users wanted to keep/remove defaults on click of reset. Found one in support of keeping defaults #4230. I believe removing defaults can be asked by devs at somepoint, but let's wait to see any evidence of this ask and then decide if we want it.

**When we decide** to add the functionality, this is what the change may be
1. Reset a **widget** will have another option to set to empty vs default. This can be used by all buttons and not just form buttons.
2. There should be one button element which can be used in a regular case and form case. Today there’s no binding on property pane for form reset button. Even if you turn off reset on success, it still goes ahead and restores defaults after you click. This binding today is implicit i think. We are planning to solve this #3613

**Comment by somangshu** [comment]
@dilippitchika #3613 is about merging form and normal button and have one for them, which can be used in both places, And henceforth reducing the chance of being error prone. 

I still think that reset should go back to the default set, I am also pointing out to the crud page functionality we have, Where reset goes to default, This is very much expected. Even in this case.

**Comment by dilippitchika** [comment]
Second that @somangshu, just pointing out what we may need to do if we end up implementing it someday. Not doing the clear functionality for now.

**Comment by ashit-rath** [comment]
Action Items:
Required field and accordion updated designs @vasanth-appsmith
Sanitize source data keys similar to Table widget V2 @ashit-rath 
Test Plan @vivekverma2312

**Comment by mmkal** [comment]
Has https://react-jsonschema-form.readthedocs.io been considered for this? It would cover the majority of use cases, but I'd imagine would take hours/days to implement rather than weeks/months/years. You just install the library! It might be worth a separate issue because it seems like there's a little more in scope here. Rjsf wouldn't know about database schemas out of the box, of course, but there would still be huge value in it. Coming from retool, we have a subsection of our api which we map with zero effort to useable UI forms for ops people. I'm new to appsmith, but familiar with react and typescript - is there a way we could use custom react components right now? If so we could probably get it working then contribute a PR.

**Comment by somangshu** [comment]
Hey @mmkal thanks a lot for showing interest on this feature. Yes indeed we have considered this package while building our own JSON Editor. Keeping the usefulness of this feature for the community in mind, we felt we needed customised experience, and hence we went about building stuff by ourself, We are near completion for v1 and would love to have your feedback to you, Please checkout [this deploy preview](https://appsmith-p3upizi4d-get-appsmith.vercel.app/) to try out the feature, You can use any dummy credentials to login.

**Comment by Nikhil-Nandagopal** [comment]
@mmkal just to add to what somangshu means, react-jsonschema-form requires our users to learn a whole new schema language which we felt was too cumbersome. With our current implementation, you can just connect any object and the form will automatically render. You can then customise the properties of every field visually without needing to learn a schema

**Comment by somangshu** [comment]
Actionable: 

- Documentation required @dilippitchika @Pranay105 
- Can start review @riodeuno @ashit-rath 
- can start QA @vivekverma2312 @yatinappsmith 
- Some new widgets have gone into release, so need to port them @ashit-rath (#9582)
- test are written and done with
- Some [issues pointed out](https://www.notion.so/appsmith/JSON-Form-editor-0e20b4529d344a7dbcbbe32fea1e0e40) by @dilippitchika needs to be dealt with - @ashit-rath

**Comment by ashit-rath** [comment]
Actionables:
- Performance profiling @ashit-rath 
- QA  @vivekverma2312 
- Porting of Select & multi-select V2 @ashit-rath  @Tooluloope (#10297)
- Code Review @sbalaji1192

**Comment by ashit-rath** [comment]
Performance issue update:
We had a discussion around the performance of the JSON Form widget when a large source data is used. The render time seems to come around 60 secs if we try to have ~150 fields (mix of arrays and objects) and out of ~60sec evaluations are taking around ~50secs; this is only for the first render.

Next steps:
1. Triage the cause of evaluations taking ~50secs for evaluating the schema.
2. We would be having a limit to how many fields the users are allowed to have in a form as having 200+ fields may lead the app to be in an unrecoverable state.

**Comment by ashit-rath** [comment]
Actionables:
1. Setup an app-building exercise using JSON form and collect feedback. @ashit-rath 
2. Add default source data @ashit-rath 
3. Modify the limit message for the Appsmith app viewers @ashit-rath 
4. Discuss ways to cache/retain fields to reduce loss of configuration. @ashit-rath @riodeuno @somangshu 
5. Implement the ongoing defaultValue DX changes for the select and multi-select V2. (https://github.com/appsmithorg/appsmith/issues/11074) @ashit-rath

**Comment by ashit-rath** [comment]
Actionables:
- Discussion to remove __original_index__ from the Table selectedRow property @sbalaji1192 
- Modify the implementation of the fixed footer @ashit-rath 
- Design for the form mode @vasanth-appsmith @dilippitchika 
- Implementation of the form mode @ashit-rath 
- Discuss support for non-ASCII characters @ashit-rath @sbalaji1192 
- Collapse the style sections in property pane @ashit-rath 
- QA to continue testing @vivek
- Think about ways to educate users about arrays and objects @dilippitchika

**Comment by ashit-rath** [comment]
Actionables:
- Implement support for non-ASCII characters @ashit-rath 
- Assess the naming of the property `Accessor` @dilippitchika 
- Documentation efforts @dilippitchika

**Comment by dilippitchika** [comment]
Accessor name change in JSON form

Suggestion to call this an “Alias” as - "a way to refer this field". We are also following the same pattern in the table widget. 

CC - @ashit-rath @somangshu

**Comment by ashit-rath** [comment]
Actionables:
- [ ] Discuss edge cases and new features with QA. @ashit-rath @vivekverma2312 
- [ ] review non-ASCII @sbalaji1192 
- [ ] documentation @dilippitchika 
- [ ] Work on QA feedback @ashit-rath

**Comment by somangshu** [comment]
- [ ] release
    - [ ] Final QA feedback
    - [ ] test non-ASCII support
    - [ ] address any issue from QA feedback
