### ISSUE TITLE
[Task]: POC/solution exploration for debugger navigation

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#25100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Related to https://github.com/appsmithorg/appsmith/issues/16408

Some key problems to figure out
- [x] How do we map a property to it's location on the UI
- [x] How do we perform this navigation?  Will we do a dom navigation or update existing UI states?
- [x] Fallbacks when we cannot navigate
- [x] Do we have the necessary meta in the debugger error to perform the navigation?

**Comment by akash-codemonk** [comment]
- For property pane we have the property pane config that can be used to identify whether a field is inside a tab or collapsible section. We will need to parse the config, to determine the states to set. 
- For api and query pane we could refer to existing logic used for undo redo. https://github.com/appsmithorg/appsmith/blob/release/app/client/src/sagas/ReplaySaga.ts#L382
