### ISSUE TITLE
[Task]: POC - Explore possibilities of accessing window object

### ISSUE THREAD

**Issue by satbir121** [appsmithorg/appsmith#25168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith/issues/25441
- [ ] https://github.com/appsmithorg/appsmith/issues/25616
- [ ] https://github.com/appsmithorg/appsmith/issues/25624
- [ ] https://github.com/appsmithorg/appsmith/issues/25625
```

**Comment by arunvjn** [comment]
We'll be looking at the data from https://github.com/appsmithorg/appsmith/issues/25625 to determine the next steps

**Comment by arunvjn** [comment]
The data for service worker registration can be found here. https://mixpanel.com/project/2032485/view/178891/app/insights/?discover=1#report/42792921

**Comment by arunvjn** [comment]
Conclusion 
- Allow admin to enable/disable access to whitelisted window APIs 
- Since window access relies on service worker, provide an API to the end user which can check if a service worker is active.
