### ISSUE TITLE
[Task]: Update baseUrl in SCIM config under RTS

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#25309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Update baseUrl in SCIM config under RTS
https://github.com/appsmithorg/appsmith-ee/pull/1770#discussion_r1253968038
- [ ] Update error message for create group duplication, if required
https://github.com/appsmithorg/appsmith-ee/pull/1770#discussion_r1259540183

**Comment by ankitakinger** [comment]
Closing this issue as it is not required to be done. RTS always talks to the server on localhost:8080 itself:
https://theappsmith.slack.com/archives/CPG2ZTXEY/p1693387142234459
