### ISSUE TITLE
[Task]: Serve index.html from CDN

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#25424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

In the current CDN setup, we serve only static files (Everything in the static folder of build) via CDN and index.html from app server.
So index.html is not taking advantage of the CDN, serving it from CDN will save us 200-300ms on first load.

Instructions on how to setup are available [here](https://www.notion.so/appsmith/CDN-for-static-resources-01e82d4b2f914f3ba489616a9f3310bd#b4dbcb5aa90b4d6098412226535da055)

- [ ] Setup on release
- [ ] Setup on prod
