### ISSUE TITLE
[Enhancement]: Show autocomplete suggestions without binding syntax - Assistive JS binding

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#25528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When I try to reference an entity like Query1 without the binding syntax `{{ }}`,  I would like autocomplete suggestions to show up so that, I have a higher chance of writing a successful binding 

### Why should this be worked on?

To improve the binding success percentage [more info](https://www.notion.so/appsmith/Binding-discovery-da6748cb85264a5b8e6883b13732064c)
```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith/issues/26682
- [ ] https://github.com/appsmithorg/appsmith/issues/26685
- [ ] https://github.com/appsmithorg/appsmith/issues/26683
```

**Comment by AnandiKulkarni** [comment]
test cases are added https://github.com/appsmithorg/TestSmith/issues/2507
