### ISSUE TITLE
IA Clean up POC - phase1

### ISSUE THREAD

**Issue by ginilpg** [appsmithorg/appsmith#25806]
```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith/issues/26329
- [ ] https://github.com/appsmithorg/appsmith/issues/26330
- [ ] https://github.com/appsmithorg/appsmith/issues/26331
- [ ] https://github.com/appsmithorg/appsmith/issues/26332
- [ ] https://github.com/appsmithorg/appsmith/issues/26333
- [ ] https://github.com/appsmithorg/appsmith/issues/26334
- [ ] https://github.com/appsmithorg/appsmith/issues/26335
- [ ] https://github.com/appsmithorg/appsmith/issues/26336
- [ ] https://github.com/appsmithorg/appsmith/issues/26337
- [ ] https://github.com/appsmithorg/appsmith/issues/26338
- [ ] https://github.com/appsmithorg/appsmith/issues/26339
- [ ] https://github.com/appsmithorg/appsmith/issues/26340
- [ ] https://github.com/appsmithorg/appsmith/issues/26341
- [ ] https://github.com/appsmithorg/appsmith/issues/26900
- [ ] https://github.com/appsmithorg/appsmith/issues/26901
- [ ] https://github.com/appsmithorg/appsmith/issues/26879
- [ ] https://github.com/appsmithorg/appsmith/issues/27067
```
