### ISSUE TITLE
[Task]: Server side changes to remove isAsync field from JS functions

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#25831]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### SubTasks

- [x] Remove isAsync from JS actions
- [x] Stop resetting configuration fields for JS actions on the basis of isAsync
- [x] Treat all functions as async in the on page load calculations. This means that all functions will need to be parsed through for dependencies, and none of them should show up in on page load, unless they have had a `JSObject1.myFunc1.data` kind of usage
