### ISSUE TITLE
[Epic]: Add support for custom environments

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#25879]
### Objective

When the user has more than 2 environments, they want to be able to create custom environments of their own, so that they are not restricted to just the 2 environments that Appsmith provides by default viz. staging and productio

### Success Metrics

| Metric         |
| -------------- |
| % of users who have created a custom environment  |
| % of users who have at least one successful query on a custom environment |

### Prioritised User Stories

| User Story    |
| ------------- |
| As a user, I want to be able to create a custom environment for my workspace  |
| As a user, I want to be able to remove a custom environment on the workspace  |

### Test Plan

https://github.com/appsmithorg/TestSmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Custom+environments%22

### RACI matrix

| Role | People |
| ------------- | ------------- |
| Responsible   | @ayushpahwa |
| Accountable   | @ayushpahwa @tkAppsmith @parth-appsmith |
| Consulted     | @riteshkew @nidhi-nair @sbalaji1192 |
| Informed      |  @riteshkew @nidhi-nair @sbalaji1192  |

```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith-ee/issues/2172
- [ ] https://github.com/appsmithorg/appsmith-ee/issues/2211
- [ ] https://github.com/appsmithorg/appsmith-ee/issues/2212
- [ ] https://github.com/appsmithorg/appsmith-ee/issues/2214
- [ ] Verify multiple env functioning with new custom envs
```
