### ISSUE TITLE
[Bug]: Limit app viewer access to only production by default

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#26028]
### Is there an existing issue for this?

- [x] I have searched the existing issues

```[tasklist]
### Tasks
- [x] Remove staging access for just app viewer from migration that introduces it for default users
- [x] Remove staging access from migration that introduces it for anon and app share users. For app share users, remove it only from viewer roles
- [x] Remove staging access from createWorkspace flow for app viewer role
- [x] Remove staging access from shareApplication flow for app share role (only view)
- [x] Does the above apply the same thing for anon users? Check and fix
- [x] Add migration to remove access from existing roles
- [x] Test migration to remove access
- [x] Test migration for default users
- [x] Test migration for custom roles
- [x] Tests for create workspace
- [x] Tests for share Application
- [x] Tests for invite user
- [x] Tests for anon user
```
### Steps To Reproduce

1. Invite users to app as app viewer, check that they have access to staging
2. Invite users to workspace as app viewer, check that they have access to staging

### Environment

Production

### Version

Cloud

**Comment by nidhi-nair** [comment]
This will slip into next week, needs extensive QA for all combinations of migrations.
