### ISSUE TITLE
[Task]: Create a checklist for contributors

### ISSUE THREAD

**Issue by tanvibhakta** [appsmithorg/appsmith#26108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Create a checklist for contributors creating a new component
- [x] Also create a checklist for contributors changing a component

- [x] Add this checklist to storybook
- [ ] Add this checklist to github PR templates

**Comment by tanvibhakta** [comment]
https://www.notion.so/appsmith/Contribution-Guidelines-034cf70500d243b6b3fc6a182e581ea9?pvs=4

**Comment by albinAppsmith** [comment]
@tanvibhakta the notion you linked don't have the template for github checklist.
