### ISSUE TITLE
[Task]: Gather feedback & component usage for components.

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#26118]
Details related to component are on [notion](https://www.notion.so/appsmith/Component-Analysis-for-development-d7862290548d4bed8ec5913f062d9d45)
```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith/issues/26437
- [ ] https://github.com/appsmithorg/appsmith/issues/26436
- [ ] https://github.com/appsmithorg/appsmith/issues/26435
- [ ] https://github.com/appsmithorg/appsmith/issues/26434
```
