### ISSUE TITLE
[Task]: Create domain objects, models, repositories and service classes

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#26131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

```[tasklist]
### Tasks
- [ ] Create domain, model, repositories and service classes for Package
- [ ] Create domain, model, repositories and service classes for Module
- [ ] Create domain, model, repositories and service classes for ModuleInstance
```
