### ISSUE TITLE
[Task]: Create package API

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#26134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

```[tasklist]
### Tasks
- [x] Implement `createPackage` in CrudPackageService
- [x] Implement create suffixed package for internal retry in case of name conflict
- [x] Add feature flag protection
- [x] Write migration to create unique index in Package collection to achieve uniqueness in package name
- [x] Write unit test
```
