### ISSUE TITLE
[Bug]: Select widget should display label instead of value while editing a table cell

### ISSUE THREAD

**Issue by keyurparalkar** [appsmithorg/appsmith#26188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Whenever a select column type cell is editable and when user actually selects the value from drop down for the cell, then select option's value property is updated in cell's data. It is expected that select option's label property should get updated in cell data.

### Steps To Reproduce

1. Drag and drop a table widget and bind a query to this widget.
2. Change one of it's column to select type and add select options to it.
3. Make this column editable
4. Now try to edit this cell
5. Observe that selecting an option from the select dropdown sets the cell's data to the `value` property of select option instead of `label`

### Environment

Production

### Version

Cloud
```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith/issues/27061
- [ ] https://github.com/appsmithorg/appsmith/issues/27093
```

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3kid3g)

**Comment by dilippitchika** [comment]
1. Whenever a column is set to select, by default we show labels and not values. 
2. For existing tables, since we have created this problem we ensure we don't break their apps. We will give an option called "Display As" as suggested in the original issue and for new select columns, it will be Label and for existing columns, it will be Value.
3. We make it clear that the computed value here refers to the default value/display value. 
4. We make the select widget changes we did for options in the table and json form as well, create a new issue for this.
5. When the user has turned on server side filtering, we will ask the user to provide additional details for labels to be shown for cases where we cannot find them in options.
6. Depending on the "display as" property, we alter the search, sort and filter behavior accordingly.

@keyurparalkar @sbalaji1192

**Comment by keyurparalkar** [comment]
@dilippitchika I have raised a [new feature request](https://github.com/appsmithorg/appsmith/issues/27062) for point 4 mentioned above.

**Comment by somangshu** [comment]
@rishabhrathod01 you think this is realted to #30074

**Comment by MAL0780** [comment]
Please, prioritize.
Wanted to use select in a table visualizing "labels" and using "values".
Thank you!

**Comment by Scrafi4** [comment]
Hi there!
I made a public app with this bug demonstrated in "gender" column. 
https://app.appsmith.com/app/select-in-column-bug/page1-65cee8067b1fda250a586c71?embed=true
If I try to edit a cell and pick a different option, it will display 1 or 2 in the cell, not "female" or "male". 
`[
  {
    "label": "female",
    "value": 1
  },
  {
    "label": "male",
    "value": 2
  }
]`
I'm glad to provide any additional info.
It's very important for my app, so if you could prioritize this, it would great!
Thanks!

**Comment by Scrafi4** [comment]
Hello!

I've created a public app to demonstrate a bug observed in the "gender" column. You can access the app here:
https://app.appsmith.com/app/select-in-column-bug/page1-65cee8067b1fda250a586c71?embed=true

The issue occurs when I attempt to edit a cell within this column and select a different option. Instead of displaying the labels "female" or "male", the cell shows the numerical values 1 or 2, respectively. Here's the data structure I'm using for the dropdown options:

```json
[
  {
    "label": "female",
    "value": 1
  },
  {
    "label": "male",
    "value": 2
  }
]
```
I'm building an app where managers update client cities from a set list. This bug hurts a lot and makes updates with foreign key relations basically impossible.  
![изображение](https://github.com/appsmithorg/appsmith/assets/122440587/2dfd4a29-3a65-438e-8bad-3546ddecb702)
![изображение](https://github.com/appsmithorg/appsmith/assets/122440587/40fbe616-de00-49e9-af21-3c0c39cee58b)

**Comment by AndreeaIAM** [comment]
Please, prioritize.
I have the same problem as [Scrafi4] . 
Thank you!

**Comment by neilhanhan** [comment]
I have the same problem.
Please, prioritize.
Thanks!

**Comment by rlnorthcutt** [comment]
We had another customer hit this today.

**Comment by rlnorthcutt** [comment]
I think we have a duplicate issue here: https://github.com/appsmithorg/appsmith/issues/21993

**Comment by rlnorthcutt** [comment]
For context, see this screen shot. If I want to edit a field with a select, then I see the `value` (an id) as the default, but I _can_ see the `label` when I'm selecting... but then once it is selected, I see the `value` again. This takes a very simple and powerful feature of the table, and makes it unusable.

In theory, I could parse the DB data, swap out the ids for the labels, and then try to swap them back again before saving to the DB... but this is incredibly messy. For now, it is best to use a JSON form for the editing, which severely limits the edit capabilities of the table row.

![image](https://github.com/appsmithorg/appsmith/assets/673633/efd6b5f3-672d-482b-a446-c428fbbc887c)

**Comment by bastien-naturavelo** [comment]
Looking forward for a fix :)

**Comment by magliok-wwt** [comment]
We have hit this same issue.

**Comment by magliok-wwt** [comment]
Is this fixed for anyone else?   I don't see that this is fixed/updated to v1.32 

The table control still initially shows the value from query (the value of the select options in my case), and even after a new selection, the same thing happens and the table goes back to the value.  Label is only ever used/shown once you're editing the value. 

![image](https://github.com/user-attachments/assets/81bb6d19-fea5-4c75-b6b1-4207762f65b3)
