### ISSUE TITLE
[Epic]: Increase Git Automation Coverage

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#26220]
### Objective

To add below tests:

- [ ] Connect an app to git which is not empty and validate error
- [ ] Click remote branch after deleting the branch locally
- [ ] Add template, discard changes, template should be removed
- [ ] Create an app with all datasources, add queries, JSObject, Custom JS lib, all widgets, theme and app settings, import that app and perform git operations
- [ ] Connect 4th repo as a public repo and then make it private and try to commit.

### Success Metrics

| Metric         |
| -------------- |
| Customer satisfaction score increases  |
| Decrease churn rate down to 30%        |

### Prioritised User Stories

| User Story    |
| ------------- |
| e.g. as a user, I want to be able to access the platform via mobile phone  |
| e.g as a user, I want to be able to communicate with the other members on the canvas  |

### RACI matrix

| Role | People |
| ------------- | ------------- |
| Responsible   |               |
| Accountable   |               |
| Consulted     | @Nikhil-Nandagopal, @mohanarpit, @areyabhishek|
| Informed      |               |
