### ISSUE TITLE
[Task]: Splitting fork application to establish a producer-consumer relationship in code structure

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#26273]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### SubTasks

```[tasklist]
### Tasks
- [x] Create RFC for what this structure would look like
- [x] Break down forking requirements
- [ ] Create a mechanism to mandate unit tests
```
