### ISSUE TITLE
[Task]: Allow DP command to build both arm and amd images for airgap

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#26286]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### SubTasks

- [ ] Create each build in a separate tag
- [ ] Create a manifest file pointing to both these tags
- [ ] Use amd build for DP creation
