### ISSUE TITLE
[Feature]:  Ramps for multiple environments

### ISSUE THREAD

**Issue by ayushpahwa** [appsmithorg/appsmith#26441]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Summary

Update the ramps for multiple environments
- Allow ramps visibility in case of view mode (permissions are missing)
- Remove feature flag from CE repo
- Add fallback for EE repo in case of no feature flag visibility

### Why should this be worked on?

For marketing of multiple environments.
```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith/issues/26443
- [ ] https://github.com/appsmithorg/appsmith/issues/26444
- [x] [Task]: conversation with app viewers pod to add new endpoint for view mode permissions
- [ ] https://github.com/appsmithorg/appsmith/issues/26445
```
