### ISSUE TITLE
[Task]: Create list of new permissions for package, module and module instance entities

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#26446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

```[tasklist]
### Tasks
- [x] Create new permissions for Package
- [x] Create new permissions for Module
- [x] Create new permissions for ModuleInstance
```
