### ISSUE TITLE
[Task]: Publish package without auto-update

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#26450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

```[tasklist]
### Tasks
- [ ] Create version number
- [ ] create new package, modules and underlying newAction documents for each published version of the package
- [ ] Remove policies that can mutate the published version of the package, modules
```
