### ISSUE TITLE
[Task]: Base Widget Restructuring to support multiple layout systems

### ISSUE THREAD

**Issue by marks0351** [appsmithorg/appsmith#26563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Create a Basewidget wrapper that supplies Widget Onion as per the layout system.

- [ ] involves extracting widget layers presently in the BaseWidget into HOCs and hooks and make sure layout systems can be scaled.
- [ ] Make sure Modal widget is handled as a overlay widget whose wrappers are supplied by basewidget instead of modal widget implementing its own editing blocks.

### Issues

- [ ] [BaseWidget HOC Implementation](https://github.com/appsmithorg/appsmith/issues/26674)
- [ ] [Code Review](https://github.com/appsmithorg/appsmith/issues/26675)
- [ ] [BaseWidget QA](https://github.com/appsmithorg/appsmith/issues/26676)

Acceptance Critiera:

- Should be more/same performant when comparing with present day metrics.
- Should result in lesser code complexity and cleaner folder structure.
- All tests except for the individul layers functional tests should pass.
- Fixed Layout and Auto Layout current functionality should be intact.
    - Widgets positioning, resizing, selection, deletion, copy paste, Drag and drop should remain the same post changes
    - Canvas resizer(AutoLayout only), preview mode and navigation settings screen functions should also stay intact.
    - Modal Widget functionalities like selection, resizing, should stay intact.

**Comment by marks0351** [comment]
This is done.
