### ISSUE TITLE
[Task]: Restructure Main Canvas Editing Blocks

### ISSUE THREAD

**Issue by rahulramesha** [appsmithorg/appsmith#26571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Create a cleaner definition of Hierarchy for MainCanvas Editing blocks for cleaner code structure and a clearer mental Model.
- [ ] Restructure Main canvas editor components to have streamlined component hierarchy
- [ ] Rename components to names that describe the component the best
- [ ] Separate layout specific components into a different component

Acceptance Criteria:
- Should be more/same performant when comparing with present day metrics.
- Should result in lesser code complexity and clear Mental model
- Fixed Layout and Auto Layout current functionality should be intact.
