### ISSUE TITLE
[EPIC]: CSS based layout

### ISSUE THREAD

**Issue by prsidhu** [appsmithorg/appsmith#26612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Widgets should be responsible for their own sizes.
- Alignment sizes and wrapping behaviour should be implemented via css.
```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith/issues/26609
- [ ] https://github.com/appsmithorg/appsmith/issues/26611
```
