### ISSUE TITLE
[Task]: BaseWidget Restructring QA

### ISSUE THREAD

**Issue by marks0351** [appsmithorg/appsmith#26676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Regression of both editors functionality
- [ ] Browser compatibility checks
- [ ] Bugs fixes
