### ISSUE TITLE
[Task]: Base Widget HOC Implementation

### ISSUE THREAD

**Issue by marks0351** [appsmithorg/appsmith#26674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Remove getPageView and getCanvasView functions in Basewidget and create one function getWidgetView
- [ ] replace getPageView functions in widgets to getWidgetView
- [ ] Remove BaseWidget getWidgetView function
- [ ] Implement HOC to provide wrappers provided by previous getWidgetView function
- [ ] Fix testcases
