### ISSUE TITLE
[Task]: Base Widget Restructuring Review

### ISSUE THREAD

**Issue by marks0351** [appsmithorg/appsmith#26675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Review new Base widget implementation with other impacting teams.
- [ ] Take in any code review comments
