### ISSUE TITLE
[Task]: Set up chromatic workflows

### ISSUE THREAD

**Issue by tanvibhakta** [appsmithorg/appsmith#26702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] They should trigger once on PR creation and after then on every /ok-to-test 
- [ ] The chromatic check should be mandatory to pass a PR if there is a change as caught in the first PR.
