### ISSUE TITLE
[Task]: Set up the a11y add ons for our storybook

### ISSUE THREAD

**Issue by tanvibhakta** [appsmithorg/appsmith#26701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Set up https://storybook.js.org/addons/@storybook/addon-a11y 
- [ ] Based on what the results of the above is, write some jest-axe tests to make those tests blocking if they fail.
