### ISSUE TITLE
[Task] POC - Explore feasibility of JS Objects in Appsmith as ES Modules

### ISSUE THREAD

**Issue by arunvjn** [appsmithorg/appsmith#26814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

```[tasklist]
### Tasks
- [x] ESM installation in evaluation worker
- [x] Calculate internal dependencies between functions exported from the module
- [x] New Linting rules based off ESM
```

**Comment by arunvjn** [comment]
This [PR](https://github.com/appsmithorg/appsmith/pull/26697) and [DP](https://ce-26697.dp.appsmith.com) contains the POC for multiple exports. 
- Installation of ESM like JS was done by creating blob URLs of the JS file, sharing it with the worker and downloading via dynamic import.
  - Removed the AST parsing from the step
- Parallel evalTree requests are blocked by marking the thread as busy during the dynamic imports
- Linting rules to check if the object starts with `export default` has been removed.
- Calculating the internal dependencies can be done by AST parsing the JS file and figuring out the top level variables and checking their presence in the exported functions. Requires AST parsing (This is not covered in the PR).
- On page load calculations are not covered in the DP. We might need to remove JSActions as a concept and store JS file as plain text without any parsing.

<img width="739" alt="Screenshot 2023-08-31 at 09 03 25" src="https://github.com/appsmithorg/appsmith/assets/32433245/5a5be80e-3342-42b8-bd83-448e59ff3f4a">

**Comment by arunvjn** [comment]
Relationship between functions and variables local to a file can be determined by using a library like [es-stats](https://www.jsdelivr.com/package/npm/es-stats). es-stats is a small library written using @babel/parser & @babel/traverse and we can write custom logic on top of it.

**Comment by arunvjn** [comment]
A function in a JS file needs to have a "Trigger Dependency" which dictates the evaluation of the dependent paths ( Eg. setName(name) should re-evaluate fields that depend on getName(), if setName and getName modify the same private variable
