### ISSUE TITLE
[Task]: Code split for GAC for 1-click upgrade/downgrade

### ISSUE THREAD

**Issue by nsarupr** [appsmithorg/appsmith#26861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

Note: Please create the individual issues for below mentioned tasks and refer to [Notion Page](https://www.notion.so/appsmith/1-Click-upgrade-tasks-GAC-047c6b88cbbd4b13a7dce85501439d26) for estimates

```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith/issues/27219
- [ ] https://github.com/appsmithorg/appsmith/issues/27216
- [ ] https://github.com/appsmithorg/appsmith/issues/27220
- [ ] https://github.com/appsmithorg/appsmith/issues/27177
- [ ] https://github.com/appsmithorg/appsmith/issues/27225
- [ ] https://github.com/appsmithorg/appsmith/issues/27227
- [ ] https://github.com/appsmithorg/appsmith/issues/27230
- [ ] https://github.com/appsmithorg/appsmith/issues/27158
- [ ] https://github.com/appsmithorg/appsmith/issues/27165
- [ ] https://github.com/appsmithorg/appsmith/issues/27155
- [ ] https://github.com/appsmithorg/appsmith/issues/27075
- [ ] https://github.com/appsmithorg/appsmith/issues/27150
- [x] SCIM User Group
- [ ] https://github.com/appsmithorg/appsmith/issues/26985
- [ ] https://github.com/appsmithorg/appsmith/issues/27211
```

**Comment by nsarupr** [comment]
Currently assigning 4.25 SP for all the tasks, but we will try to close this before that.

**Comment by dipyamanbiswas07** [comment]
@nsarupr can we close this ticket now?

**Comment by deepikaappsmith** [comment]
The GAC code split is completed and merged. Closing the ticket
