### ISSUE TITLE
[Bug]: To track all the issues found during DP testing of Custom Environments

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#26886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This issue is opened to track all the issues found during DP testing of Custom Environments

```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith/issues/28507
- [ ] https://github.com/appsmithorg/appsmith/issues/28508
- [x] (Couldn't reproduce) https://drive.google.com/file/d/1JRPn05ZNlVdu3lEaJt8NV2qXImiBnvpo/view?usp=drive_link - forking a git connected app fails
- [x] (Expected behaviour since add env is workspace action) https://czqtakk0ok.vmaker.com/record/uh6EX329rV8JaPgn when the user  tried to add environment he is navigated to homepage on back button rather then leading him to Datasource page
- [x] (Couldn't reproduce) https://drive.google.com/drive/u/1/folders/153PULmm0gZKOSScIKyd4CoOShyqIlYIr -Importing an Gsheet app displays an error
- [ ] https://github.com/appsmithorg/appsmith/issues/27317
- [x] (Done) On creating a GSheets DS, in the Edit DS page, the tooltip for Custom environments needs to be modified. Thread here - https://theappsmith.slack.com/archives/C03QHS03RDK/p1693579569455559
- [ ] https://github.com/appsmithorg/appsmith/issues/27212
- [x] (Done) https://drive.google.com/file/d/1HOstaieq_V4lpQtR5095i-GumVDEpYBT/view?usp=drive_link - When we add a new environment and leave the label field blank, and click create, toast messages come up. This is incorrect, the error should come up on the modal itself to not leave the label blank
- [ ] https://github.com/appsmithorg/appsmith/issues/27344
- [ ] https://github.com/appsmithorg/appsmith/issues/27342
```
