### ISSUE TITLE
[Task]: Anvil(CSS Based Auto Layout) Resizing Module

### ISSUE THREAD

**Issue by marks0351** [appsmithorg/appsmith#26929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] create resizing modulec for Anvil engine
- [ ] create generic resizing library that accepts properties to implement Anvil Resizing
- [ ] create Anvil Resizing Wrapper around generic resizer
- [ ] create functions to calculate component dimensions using width, height props.
- [ ] Make sure resizing works for Modal widget, List Widget as expected.
- [ ] Write test cases for Resizing module and Generic Resizer
- [ ] QA Anvil Resizing Module

Dependencies:
- CSS Based Flex Component Module.
- Widget Positions Calculation Module.
