### ISSUE TITLE
[Task]: Extract Generic Resizer for Anvil Engine from existing Resizing Modules.

### ISSUE THREAD

**Issue by marks0351** [appsmithorg/appsmith#26930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] extract generic resizing implementation from present day Resizers of Auto Layout and Fixed and create a generic resizer that works for any generic props.
- [ ] Generic resizer should take in width and height in percentages/pixels and take in a per pixel change value to manipulate dimensions.
- [ ] Functional test the resizer with test cases
- [ ] Check for places for improvement that could aid in performance.
