### ISSUE TITLE
Integrate On demand migration API with Java server

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#26980]
```[tasklist]
### Tasks
- [ ] Integrate RTS API to apply migration
- [ ] Verify the migration with different test cases
- [ ] Add Junit tests for DSL Migration validation on server
- [ ] Update page apis on Java Server to serve latest DSL always
```

**Comment by nayan-rafiq** [comment]
Closing this PR because this branch has been merged to another PR https://github.com/appsmithorg/appsmith/pull/28518
