### ISSUE TITLE
[Task]: Refactor on page load to allow any executable to be considered in calculations

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#27087]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### SubTasks

- [x] Create an interface for `Executable` types
- [x] Switch to using this across all on page load methods
- [x] Pull out action specific DB calls into different methods
- [ ] Switch them out to another service class
