### ISSUE TITLE
[Task]: Subsequent fixes for Anvil Layout System

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#28164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] UX for entity explorer showing layout preset droptarget groupings
- [ ] Revisit `useCanvasActivation`
- [ ] https://github.com/appsmithorg/appsmith/issues/28471
- [ ] https://github.com/appsmithorg/appsmith/pull/28204/files#r1365714083
- [ ] Try to use the resizeobserver singleton instead of a new import from the polyfill 

- [ ] MainContainerResizer can be removed from edit mode and may only exist in preview mode.
Major
- [ ] Spawn only the layout system specific sagas
- [ ] Break `withWidgetProps` to be layout system specific
- [ ] Store positions data relative to the parent Canvas, and use that to only compute for siblings when something changes. 
- [ ] How do we improve the system of observing elements to minimize performance impact

Issues:
- [ ] Drag icon doesn't show
- [ ] Test legacy apps that don't have appPositioningType
- [ ] Shift + select widgets follows the order in the entity explorer, even though we're selecting on the canvas.

## Tracker for bugs
https://www.notion.so/appsmith/b2691356cc03475db5ad79e510b926e5?v=eb44ac11715241258a6c11dec1e61394

**Comment by Sripriya93** [comment]
Observations in [DP](https://ce-28238.dp.appsmith.com/): @riodeuno 
https://www.loom.com/share/383598e0565848749b73e17c3a92e580
1. When we try to add third widget we are not able to see the highlights, existing widget in canvas when we try to drag it we are able to see highlighters on the top and to the left of the widget and if we drop when left highlighter appear we are able to see the widget disappears

**Comment by Sripriya93** [comment]
Observations in [DP](https://ce-28238.dp.appsmith.com/): @riodeuno 
1. https://www.loom.com/share/383598e0565848749b73e17c3a92e580
when we try to add third widget we are not able to see the highlights, existing widget in canvas when we try to drag it we are able to see highlighters on the top and to the left of the widget and if we drop when left highlighter appear we are able to see the widget disappears

2. https://www.loom.com/share/d26a1e5327d4455abf52252308002032
Widgets after scroll in canvas doesnt have the widget name card, able to see a cut on the Button widget in the above loom

3. RTE , List widgets broken
<img width="533" alt="image" src="https://github.com/appsmithorg/appsmith/assets/104895602/ba99fc34-92d8-4ab8-9802-99887f794bf7">

![image (33)](https://github.com/appsmithorg/appsmith/assets/104895602/0122c00e-b7cf-4cb5-9c86-1b4fe062607e)

**Comment by shadabbuchh** [comment]
Initial observations:

1. The placement indicator glitches when DnDing a widget:

https://github.com/appsmithorg/appsmith/assets/39921438/529ff232-d882-4210-9c0f-db56992ec4a4

2. Placement indicators not visible at appropriate positions once we perform undo or remove widgets:

https://github.com/appsmithorg/appsmith/assets/39921438/41284529-5140-4d57-ac1c-7ecc3ccca3d8

3. Placement indicator not prominent when we try to drop a widget below an already placed widget inside a container:

https://github.com/appsmithorg/appsmith/assets/39921438/7593eb70-1da5-417a-9ed5-6132c9568224

4. Not able to place widgets inside a container within a container: (This leads to placement indicators not being clearly visible inside the parent container)

https://github.com/appsmithorg/appsmith/assets/39921438/56e84446-de70-4ce5-a12f-7622fa681a0c

5. Widgets are not vertically aligned:

https://github.com/appsmithorg/appsmith/assets/39921438/5b6a5252-0d67-46cd-b362-74f3867deeea

6. Divider widget not visible in `Vertical` direction:

https://github.com/appsmithorg/appsmith/assets/39921438/af03be81-2e88-470d-8300-8d7b8e1197f3

**Comment by shadabbuchh** [comment]
Issues in Firefox:

1. Not able to relocate widgets using by clicking on their tags:

https://github.com/appsmithorg/appsmith/assets/39921438/88feb33f-8076-43b7-8728-0e8db328d874

2. Not able to select the desired widget & relocate it on the canvas:

https://github.com/appsmithorg/appsmith/assets/39921438/35ab90cf-3fe0-48d9-8dd9-26910b8d72fc

3. Placement indicators appear after we drag the widget very slowly. Takes a lot of patience:

https://github.com/appsmithorg/appsmith/assets/39921438/e13f8e04-5482-44f5-865d-ac6659cf7c19

4. Horizontal scroll:
<img width="1440" alt="Screenshot 2023-10-23 at 12 01 09 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/bb60ab55-f442-4b97-865f-095c289ae270">
