### ISSUE TITLE
[Task]: Minor Code restructure in Anvil

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#28310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Use `LayoutSystemType` or `LayoutSystemFeatures` instead of feature flags in [`app/client/src/pages/Editor/CanvasPropertyPane/index.tsx`](https://github.com/appsmithorg/appsmith/pull/27966/files/e7603fd21350415d384a68039fa1abc4001b7e59#diff-6ffc62fd8fff7633da84c1bbf822394ff49f1d89dc4ad073fff16e2f5e5d41fd)
- [ ] In `WidgetNamesCanvas` use `SetDragginStateFnType` or `SetDraggingStateActionPayload` and remove the other from the codebase.
