### ISSUE TITLE
[Epic] SAML/SSO

### ISSUE THREAD

**Issue by mikefrancis** [appsmithorg/appsmith#2840]
## Summary

Allow users to be provisioned using customer SAML providers via a SSO service.

## Motivation

It's great that AppSmith offers Google OAuth login however if you do not use Google to authenticate with then this adds another layer of user administration which is difficult to keep in sync at enterprise scale; as an IT admin I want to sign-in with services I already use.

It would be great if in AppSmith's configuration you could integrate with custom SAML IDP providers.

Test plan : https://docs.google.com/spreadsheets/d/1kZjf3oZKPP0ILf0c_Rw-5KvPUykCkzExBYSVYNBxZ2g/edit?usp=sharing
Design files : https://www.figma.com/file/68AfRvev6NkcPFFUamsAq3/SSO%2FSAML?node-id=265%3A1791

**Comment by areyabhishek** [comment]
@mikefrancis Thanks for creating this issue. We are planning to introduce integrations with SAML providers. Do you have a preferred provider? 
The popular ones seem to be:
1. Auth0
2. Okta
3. Ping
4. Active Directory(MSFT)
5. Duo security

**Comment by mikefrancis** [comment]
We use a custom provider so the ability to add custom ones via IdP Metadata XML would be great (I imagine this is what is used under-the-hood?).

**Comment by dani** [comment]
OpenID Connect (with a custom provider) would also be great to have. Using Lemonldap::NG so SAML or OIDC would work for me (though OIDC is simpler to setup)

**Comment by DaSchTour** [comment]
> @mikefrancis Thanks for creating this issue. We are planning to introduce integrations with SAML providers. Do you have a preferred provider?
> The popular ones seem to be:
> 
> 1. Auth0
> 2. Okta
> 3. Ping
> 4. Active Directory(MSFT)
> 5. Duo security

@areyabhishek I would suggest Keycloak. As this is also something you could have as own infrastructure like Appsmith.

**Comment by areyabhishek** [comment]
@DaSchTour I'll check out Keycloak. 
About your second comment. Could you describe the experience you'd want? We were discussing a similar feature a few weeks ago and would love to know what exactly you'd like it to be.

Did you mean a business user will need to authenticate before they can run a REST API? Like I hit a button that calls an authenticated API, the button then pops up a modal to authenticate me. I get authenticated for the session and then I can continue to call the API without needing to sign in.

**Comment by DaSchTour** [comment]
@areyabhishek so my idea was that I can use Keycloak to login into the application and the token I get from Keycloak can be used for the Authorization header to call the REST APIs. We would use the Keycloak instance we have for our other applications and our APIs also for appsmith.

The idea to authenticate before runing a REST API also sounds good.

**Comment by codedmind** [comment]
Take a look at univention.com they provide SSO using samba/active directory, they also have and appcenter and would be great see appsmith in there :D

**Comment by kritid11** [comment]
It would be good to have Azure Active directory SSO.

**Comment by Hokwang** [comment]
I am using keycloak and it supports openID and SAML both.
and now, most of tools are supporting OIDC, I think.

**Comment by wlatic** [comment]
It'd be great to have either OpenID or OIDC enabled.

With the app already supporting these functions from Github and Gsuite this may not be too difficult:

```
Define OIDC_PROVIDER "https://<URL>/auth/realms/"
Define OIDC_REALM "<REALM NAME>"
Define OIDC_CRYPT <CRYPTPASS>
Define OIDC_CLIENT <CLIENT NAME>
Define OIDC_SECRET <CLIENT KEY>

<IfModule auth_openidc_module>
    OIDCProviderIssuer ${OIDC_PROVIDER}${OIDC_REALM}
    OIDCProviderAuthorizationEndpoint ${OIDC_PROVIDER}${OIDC_REALM}/protocol/openid-connect/auth
    OIDCProviderJwksUri ${OIDC_PROVIDER}${OIDC_REALM}/protocol/openid-connect/certs
    OIDCProviderTokenEndpoint ${OIDC_PROVIDER}${OIDC_REALM}/protocol/openid-connect/token
    OIDCProviderUserInfoEndpoint ${OIDC_PROVIDER}${OIDC_REALM}/protocol/openid-connect/userinfo
    OIDCSSLValidateServer Off
    OIDCRedirectURI /redirect_uri/
    OIDCCryptoPassphrase ${OIDC_CRYPT}
    OIDCClientID ${OIDC_CLIENT}
    OIDCClientSecret ${OIDC_SECRET}
    OIDCRemoteUserClaim preferred_username
    OIDCInfoHook userinfo
</IfModule>

```

This is an example from Apache, which is much more complicated than nodejs implementation, using OIDC from KeyCloak.

https://github.com/keycloak/keycloak-nodejs-connect

For the moment I've got Apache2 doing auth and going to see if I leave AppSmith URL open and authenticate via the proxy server using different URLS. Not ideal but for now it should work.

**Comment by Hokwang** [comment]
please re-arrange this issue's priority in your roadmap. Q4 is too late, I think.

**Comment by Nikhil-Nandagopal** [comment]
@Hokwang this is now being picked up in Q3. Thank you for contributing to this issue!

**Comment by mingfang** [comment]
Integration with Keycloak(and probably any oauth provider) is already possible using Spring security settings.
I built this example to demonstrate integration with Keycloak using environment variables. 
https://github.com/mingfang/terraform-k8s-modules/blob/master/examples/appsmith/main.tf#L39

**Comment by lf-floriandeutsch** [comment]
> Active Directory(MSFT)

Are you referring to NTLM/Kerberos or ADFS? Many customers are still using a "simple" ActiveDirectory without Federation Services

**Comment by mohanarpit** [comment]
@lf-floriandeutsch At this juncture, we haven't made a decision whether we'll support both AD & ADFS. 

Based on your response, we'll keep in mind that users may be using the "simple" ActiveDirectory without the federation services.

**Comment by mohanarpit** [comment]
- First cut of wireframes from UX flow - @Debsourabh 
- Initiate POC for code splitting on the frontend - @rashmi-rai @rishabhsaxena 

More details can be found at: [https://www.notion.so/appsmith/SSO-835bf30d62974817ac88ef6810ba50f1](https://www.notion.so/appsmith/SSO-835bf30d62974817ac88ef6810ba50f1)

**Comment by trishaanand** [comment]
*Goal* : Planning for the feature to be complete by December 1st

- Code splitting POC
     - Frontend - @rishabhsaxena @rashmi-rai 
     - Backend - @trishaanand @AnaghHegde 
- Test out the complete integration flow with a couple of providers and share a video with the team - @trishaanand

**Comment by trishaanand** [comment]
- Continue with PoC for code splitting. Only backend right now - @trishaanand 
- Finalize wireframes for Authentication. - @Debsourabh 
- Implementation research for SAML/OIDC/LDAP with webflux - @trishaanand

**Comment by Debsourabh** [comment]
WIP SSO/SAML : https://www.figma.com/file/68AfRvev6NkcPFFUamsAq3/?node-id=8%3A69

**Comment by trishaanand** [comment]
- Wireframe to be shared with the team next week - @Debsourabh 
- Publish Test plan for the feature - @RakshaKShetty 
- Publish all the input field requirements for the feature - @trishaanand

**Comment by trishaanand** [comment]
Last week's update : 
- Explore keycloak to be used as a broker - @trishaanand 
- BE Code split - @trishaanand 
- FE Code split strategy development - @pranavkanade 
- Incorporate design review comments - @Debsourabh

**Comment by RakshaKShetty** [comment]
WIP SSO Testplan  : https://docs.google.com/spreadsheets/d/1kZjf3oZKPP0ILf0c_Rw-5KvPUykCkzExBYSVYNBxZ2g/edit#gid=0

**Comment by pranavkanade** [comment]
FE Code splitting guidelines - https://www.notion.so/appsmith/FE-code-splitting-guidelines-V2-7333eaa05e1540b898feb540b5f0f330

**Comment by trishaanand** [comment]
Weekly targets : 
- POC of SSO with keycloak and configuration on appsmith via docker environment - @trishaanand 
- FE code split finalization and POC of code split - @pranavkanade 
- FE task breakdown for SSO - @pranavkanade @ankitakinger 
- RBAC requirements documentation - @vuiets

**Comment by trishaanand** [comment]
Weekly targets :
* Test SSO with common identity providers (Okta, PingId) - @trishaanand 
* Set up demo instance with SSO enabled for testing - @trishaanand 
* Polish UI for configuring SSO - @pranavkanade @ankitakinger 
* Design QA - @Debsourabh 
* Get started with tests - @RakshaKShetty

**Comment by trishaanand** [comment]
Weekly targets : 
- Design QA - @Debsourabh 
- Continue with test cases - @RakshaKShetty 
- Admin APIs for the server for configuration of IdP (Over the next two weeks) - @trishaanand 
- Continue with cypress tests - @pranavkanade  @ankitakinger 
- CE upgrade to paid plan flow to be designed and finalized (Over the next two weeks) - @Debsourabh 
- New designs for login screen containing only Sign in with SSO - @Debsourabh 
- Test SSO with Rippling - @trishaanand @vuiets
- Fat container setup containing keycloak - @trishaanand 
- Explore solutions for licensing the EE image - @trishaanand @mohanarpit

**Comment by pranavkanade** [comment]
**TODO**
1. Get new designs for admin settings page, login page from - @Debsourabh
2. UI changes for admin settings page- @ankitakinger 
3. Go through test plan - team
4. Fat container setup - @trishaanand 
5. Documentation for enterprise

**Deprioritised Items**
1. Admin APIs
2. Upgrade to paid plan

**Comment by hiteshjoshi** [comment]
- New OIDC integration directly with Spring JAVA. - In PR
- Admin APIs to configure OIDC on Appsmith - Not Started
- Expose the JWT tokens as server side replacement - In Progress

**Comment by hiteshjoshi** [comment]
- Merge OICD integration (build on top of Spring )  - In PR @trishaanand 
- Refactoring of JWT tokens to make it production ready. - In progress @trishaanand 
- Admin APIs to configure OIDC on Appsmith ( overflows to next week ) @trishaanand 
- Admin settings page and login page changes to be merged - @pranavkanade 
- Fat container QA - @RakshaKShetty 
- Update test plans and add JWT token scenarios as well.  - @RakshaKShetty 
- Start doing documentation for integrations - @Pranay105 @trishaanand @ankitakinger 
- UI improvements on admin settings page for SSO configuration.  - @Debsourabh

**Comment by trishaanand** [comment]
- Admin settings page changes with new designs - @ankitakinger 
- Fix fat container deployment - @trishaanand 
- Fat container QA - @RakshaKShetty
- Continue adding more JWT token scenarios to the test plan and review - @RakshaKShetty @trishaanand @ankitakinger 
- Start doing documentation for integrations with OIDC - @Pranay105 @trishaanand @ankitakinger @vuiets 
- Documentation for JWT tokens - @vuiets @trishaanand @Pranay105 
- Licensing Flow - @trishaanand

**Comment by trishaanand** [comment]
- Minor changes for OIDC settings page to be true to designs - @ankitakinger 
- Continue adding more JWT token scenarios to the test plan and review - @RakshaKShetty @trishaanand @ankitakinger
- Continue with documentation of integrations with OIDC - @jnikhila @ankitakinger @trishaanand 
- Documentation for JWT tokens - @vuiets @trishaanand @Pranay105
- Licensing Flow - @trishaanand
- Add a client side check for at least one authentication method being available before allowing disconnect - @ankitakinger 
- Refresh token test for OIDC - @trishaanand

**Comment by hiteshjoshi** [comment]
**Notes from Product, UI, QA catchup.**

- [ ] Form login reset button. Needs to be bundled with form login auth type. @ankitakinger 
- [ ] Buggy Server restart ( Fat container issue probably @trishaanand to check @yatinappsmith to provide logs )
- [ ] Improve UX for failed server restart modal. ( Ideas : add docs ) @Debsourabh  ![image](https://user-images.githubusercontent.com/217911/156510086-ecf9aea5-9cdd-4e5a-9dd7-9a0f747e6fb7.jpeg)

**Comment by trishaanand** [comment]
Minor change post design review on OIDC configuration screen - @ankitakinger 
Bug fixes with fat container - @trishaanand 
Bug fix for disconnect of OIDC leading to bad state - @trishaanand 
Get started with SAML admin APIs - @trishaanand 
Update restart banner - @ankitakinger

**Comment by hiteshjoshi** [comment]
User request around JWT tokens. 
“JWT token authentication on AppSmith editor GUI #7353”

**Comment by genfx86** [comment]
hello guys, any expected date for the release of this feature? as it was marked as part of Q4 2021

**Comment by Nikhil-Nandagopal** [comment]
@genfx86 this feature is actually now live and available in our enterprise edition.
If you'd like to upgrade and start using our enterprise edition, you can find some time on our calendar below
https://calendly.com/d/yvb3-dyks/talk-to-appsmith-team?month=2022-02

**Comment by woutr-nl** [comment]
So this feature won't be deployed to the community-edition?

**Comment by Nikhil-Nandagopal** [comment]
@woutr-nl yes it will only be available in the enterprise edition.

**Comment by mikefrancis** [comment]
As the OP, it's a real shame this won't be available in the community edition.

I'm a huge fan of AppSmith and would love to suggest future features, but the profiteering from community ideas makes me feel very uneasy. 

SSO is a basic security requirement, this website explains more and highlight companies that follow a similar within:

https://sso.tax

I'd love to ask you to reconsider, and wish you a good day.

**Comment by Nikhil-Nandagopal** [comment]
@mikefrancis thank you for your contribution. To be honest, we had planned on monetizing SSO as part of our paid edition since the inception of Appsmith. We do agree that it is a very important security requirement and we're working with all our early users on a usage-based pricing model that is fair, scalable and not a tax on organizations that need it. Appsmith has always intended to monetize features that are valuable to organizations that are willing to pay for them while continuing to provide a stellar open-source platform for individual developers and smaller teams to build their internal apps on. We have Google SSO available in the community edition because we saw that smaller teams did tend to need it a lot. Our monetization is with the sole goal of sustaining the development and growth of this project that we love. We hope you can see it from that perspective too.

**Comment by mikefrancis** [comment]
@Nikhil-Nandagopal if you scroll back to the early comments after I created this, it's not clear that this would be enterprise only. A lot of the other commenters provide lots of product insight which you've used to help build your product. For free. 

I understand y'all need to pay the bills and absolutely agree you should monetise this amazing software, but IMO you should make it clear when things are on an enterprise roadmap or that community ideas that are realised *might not* be available in the community edition.

**Comment by wlatic** [comment]
It'd be far better having the easier Gmail, office etc. Connectors in the enterprise and having saml, which requires far more configuration on the user end as part of open source. All saml would need is the end points.

**Comment by dncpax** [comment]
I'm not new to open source projects, having been involved in an os association. To be fair, appsmith did say from early on this was planned as a payed feature. If you search discord I'm sure you'll find this.

We may disagree, we may argue otherwise, we may try to show arguments in favor of including some feature in the self hosted version, but it's for the team to make this project sustainable - which is crucial for all of us users too. It's not written in stone what will be monetized...

In this road to meet both ends, open and sustainable, we've seen many projects sacrifice too much on the open side of things. We hope it does not happen to the projects we invest in as users, especially early on.
But it certainly hasn't happened to appsmith. If anything, I've seen the team revert payed features to free (git-sync limits comes to mind, it was 4 repos, and it's now 4 per org).

Just my 2 cents.

PS - I'm also interested in this feature, and would love it to be included in the self hosted version, but am otherwise hoping for affordable pricing...

**Comment by Nikhil-Nandagopal** [comment]
@mikefrancis that's a really great point! We have been transparent about our plans like we did in [this comment](https://github.com/appsmithorg/appsmith/issues/2840#issuecomment-952693850) but I can see how it got buried under the flurry of information and we should strive to more proactively communicate this instead of having users ask us about our plans. Thank you for the feedback! We're going to work on being more upfront on what features we plan on monetizing.

**Comment by Nikhil-Nandagopal** [comment]
@wlatic our entire belief in appsmith has been that an individual developer or small team should be easily able to build their first application without any barriers and that is why we don't have any integrations that are useful for app building behind a paywall. We believe any developer out there might have a need for a Gmail connector and we should help them with that.

In regards to SAML, while the configuration is higher, we felt that it was not essential to the app-building process or even necessary for most small teams. It generally becomes a necessity once you're convinced that Appsmith can work really well for your use case and now you really need better security for wider adoption. We believe that is something organizations are willing to pay for because our community edition has convinced them that it does exactly what it promises.

**Comment by codedmind** [comment]
I already give my opinion some time ago, i'm with @mikefrancis in this. Since the begin isn't very clear the is will be only on enterprise or not, better, for me at least i only understand that will be a enterprise feature some time after we start talk about SSO.
The issue is from Feb and and the comment is from Oct... for us that are here almost two years the perception is different.

**Comment by Nikhil-Nandagopal** [comment]
@dncpax we already have this feature available and piloting it with users! Please block some time with us to talk about the pricing, we're working on making it super affordable and scalable :)

**Comment by Nikhil-Nandagopal** [comment]
@codedmind thanks for the feedback! We'll work on communicating more about our plans upfront

**Comment by hiteshjoshi** [comment]
Closing this. SAML phase 1 is completed and available for enterprise. Please get in touch if you would like to test it out.

**Comment by thomas10-10** [comment]
For information buildbase sefhosted support sso

**Comment by Nikhil-Nandagopal** [comment]
@thomas10-10 we have custom SSO support in our self hosted business edition and Google SSO support in our self hosted community edition.

**Comment by thomas10-10** [comment]
I specify, custom sso in the free selfhosted community,

**Comment by Nikhil-Nandagopal** [comment]
@thomas10-10 I'm not sure what their thought process is but we've generally seen that smaller teams don't need custom SSO and larger teams are more than happy to pay for this feature. In fact, our pricing is very reasonable for all team sizes so if you're interested in the feature, we'd love to talk to you about it.

**Comment by SamirSaidani** [comment]
> @thomas10-10 we have custom SSO support in our self hosted business edition and Google SSO support in our self hosted community edition.

It would be more consistent to have a community-supported SSO protocol in your self hosted community edition, like LDAP, instead of Google. Usually, opensource-oriented people tend to use opensource-based protocol.

**Comment by thomas10-10** [comment]
It's exactly for this reason that buildbase attracts me more, their selfhosted version is really opensource, you feel more like contributing for this kind of solution.

**Comment by thomas10-10** [comment]
I saw that you refused a merge because it was competing with your paid version
https://github.com/appsmithorg/appsmith/pull/8443
It might be interesting to derive appsmith and merge those pull requests

**Comment by mohanarpit** [comment]
@thomas10-10 @SamirSaidani Thanks for your inputs. I understand your POV. In this case, we need to ensure that the Appsmith project is sustainable. This means we need to charge for certain features. Making open source projects sustainable ensures that we can continue to build an incredible platform for everybody to build apps really quickly. 

@thomas10-10 We believe in doing the right thing at all times. This is why we didn't accept a contributor PR since we wanted to charge for it. We don't believe in charging for any feature that the community contributes towards. 

I hope this makes sense.

**Comment by DaSchTour** [comment]
> @thomas10-10 I'm not sure what their thought process is but we've generally seen that smaller teams don't need custom SSO and larger teams are more than happy to pay for this feature. In fact, our pricing is very reasonable for all team sizes so if you're interested in the feature, we'd love to talk to you about it.

Well. Nice assumption. But in fact after I've seen that we would have to pay for SSO we choose a different solution and now I wouldn't even consider using appsmith anymore. It's a bit sad. I waited for that feature so long.

Maybe I also understand the reason behind using SSO different. But for me that has nothing to do with team size but with infrastructure. We use Keycloak for our application and we have a lot of microservices that use Keycloak OAuth. So I would like to be able to use these APIs with the Token I get from my Keycloak login.

**Comment by pharindoko** [comment]
> @thomas10-10 I'm not sure what their thought process is but we've generally seen that smaller teams don't need custom SSO and larger teams are more than happy to pay for this feature. In fact, our pricing is very reasonable for all team sizes so if you're interested in the feature, we'd love to talk to you about it.

LOL - you never worked in an enterprise I assume ...

@DaSchTour: Which solution have you used instead ?

**Comment by serega404** [comment]
I was looking for a solution for my student creative project. I use Keycloak in order to relieve myself of the responsibility for authorization and spend time implementing more functions of my project. Unfortunately, I had to abandon appsmith, since I can't use keycloak, which most of my api works with.
