### ISSUE TITLE
[Task]: FE changes for Homepage experience - Content side (Applications area) 

### ISSUE THREAD

**Issue by ankitsrivas14** [appsmithorg/appsmith#28787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] 1. Show only apps of the current workspace selected.
- [x] 2. UI changes on the right side - Font and styles 
- [x] 3. Update the empty state on the right side 
- [x] 4. Implement workspace and Application GET APIs - [TBD]
- [ ] 5. ~~Cypress~~ Tracking at https://github.com/appsmithorg/appsmith/issues/28980

<img width="724" alt="image" src="https://github.com/appsmithorg/appsmith/assets/67647761/a229cb9e-f8d1-4add-b5db-1bb1c6b246d3">

**Comment by ankitsrivas14** [comment]
Reduced 0.5sp from this ticket as we are tracking cypress changes in this ticket https://github.com/appsmithorg/appsmith/issues/28980

**Comment by deepikaappsmith** [comment]
fixed and merged in release. Hence closing the ticket
