### ISSUE TITLE
[Task]: FE changes for Homepage experience - Search bar

### ISSUE THREAD

**Issue by ankitsrivas14** [appsmithorg/appsmith#28788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] 1. Search bar UI
- [x] 2. API integration
- [x] 3. Real-time filtering to server side search with debounce
- [ ] 4. ~~Cypress~~ Tracking at https://github.com/appsmithorg/appsmith/issues/28980

<img width="739" alt="image" src="https://github.com/appsmithorg/appsmith/assets/67647761/da9941af-d9b1-4c40-895c-b600b0a5c148">

**Comment by ankitsrivas14** [comment]
Reduced 0.5sp from this ticket as we are tracking cypress changes in this ticket https://github.com/appsmithorg/appsmith/issues/28980

**Comment by deepikaappsmith** [comment]
fixed and merged in release. Hence closing the ticket
