### ISSUE TITLE
[Task]: FE changes for Homepage experience - Header

### ISSUE THREAD

**Issue by ankitsrivas14** [appsmithorg/appsmith#28786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] 1. Search bar in the header 
- [x] 2. Upgrade in header - 
- [x] 3. Admin settings in the header 
- [x] 4. Left side option in the header under a dropdown 
- [x] 5. Rendering condition to not render on settings page 
- [ ] 6. ~~Cypress~~ Tracking at https://github.com/appsmithorg/appsmith/issues/28980

<img width="936" alt="image" src="https://github.com/appsmithorg/appsmith/assets/67647761/383d6f67-a45d-44da-80bd-f1d516ff9f17">

**Comment by deepikaappsmith** [comment]
fixed and merged in release. Hence closing the ticket
