### ISSUE TITLE
[Task]: FE changes for Homepage experience - Minor UI changes

### ISSUE THREAD

**Issue by ankitsrivas14** [appsmithorg/appsmith#28789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] 1. Help section (0.5sp)
- [x] 2. Sidebar (0.25sp)
- [x] 3. Workspace More Dropdown (0.25sp)
- [ ] 4. ~~Cypress coverage for above changes(0.5sp)~~ Tracking at https://github.com/appsmithorg/appsmith/issues/28980

<img width="437" alt="image" src="https://github.com/appsmithorg/appsmith/assets/67647761/29fca827-abee-44e8-8d17-b969e390bc4d">

<img width="315" alt="image" src="https://github.com/appsmithorg/appsmith/assets/67647761/6320ead3-9c34-431b-989d-aed04e3bf570">

<img width="416" alt="image" src="https://github.com/appsmithorg/appsmith/assets/67647761/59d173d5-24ac-47b4-b878-26e048820017">

**Comment by ankitsrivas14** [comment]
Reduced 0.5sp from this ticket as we are tracking cypress changes in this ticket https://github.com/appsmithorg/appsmith/issues/28980

**Comment by deepikaappsmith** [comment]
fixed and merged in release. Hence closing the ticket
