### ISSUE TITLE
[Task]: Introduce `contextId` and `contextType` in executables

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#28797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

```[tasklist]
### Tasks
- [ ] Add contextId and contextType field in ActionCE_DTO
- [ ] Add contextId and contextType field in ActionCollectionCE_DTO
- [ ] Add new methods to fetch by contextId and contextType for each executable
```
