### ISSUE TITLE
[Task]: FE changes for Homepage experience - Create New Application

### ISSUE THREAD

**Issue by ankitsrivas14** [appsmithorg/appsmith#28790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] 1. New App dropdown
- [x] 2. Templates page
- [ ] 3. ~~Cypress~~Tracking at https://github.com/appsmithorg/appsmith/issues/28980

**Comment by ankitsrivas14** [comment]
Reduced 0.5sp from this ticket as we are tracking cypress changes in this ticket https://github.com/appsmithorg/appsmith/issues/28980

**Comment by deepikaappsmith** [comment]
fixed and merged in release. Hence closing the ticket
