### ISSUE TITLE
[Task]: FE changes for Homepage experience - Templates

### ISSUE THREAD

**Issue by ankitsrivas14** [appsmithorg/appsmith#28899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] 1. Remove templates from header.
- [x] 2. Search for the usage of/templates and related routes in the project.
- [x] 3. templates and other associated routes should redirect to 404
- [x] 4. Remove and update jest and cypress test cases for templates.

**Comment by ankitsrivas14** [comment]
Since the new sign-up flow is using the templates page at the `/applications` route. This change was reverted.
Read More:
https://theappsmith.slack.com/archives/C05P3ME9MBR/p1700114194446139
https://theappsmith.slack.com/archives/C05P3ME9MBR/p1700205976233739

**Comment by deepikaappsmith** [comment]
fixed and merged in release. Hence closing the ticket
