### ISSUE TITLE
[Task]: Homepage experience Cypress test coverage

### ISSUE THREAD

**Issue by ankitsrivas14** [appsmithorg/appsmith#28980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

This task is to fix test cases failing because of changes made in the Homepage experience and add more coverage.

- [ ] Cypress for #28786 - 0.5sp
- [ ] Cypress for #28789 - 0.5sp
- [ ] Cypress for #28790 - 0.5sp
- [ ] Cypress for #28788 - 0.5sp
- [ ] Cypress for #28787 - 0.5sp
- [ ] Cypress for #28978 - 0.5sp

**Comment by deepikaappsmith** [comment]
all the cypress issues related to homepage were fixed and merged to release
