### ISSUE TITLE
[Task]: Additional fixes required in project after integrating Workspaces and Applications API - Homepage experience

### ISSUE THREAD

**Issue by ankitsrivas14** [appsmithorg/appsmith#29043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Rename Application
- [x] Update App Icon, App Color
- [x] Fork Application
- [x] Delete Application
- [x] Rename Workspace
- [x] Delete Workspace
- [x] Delete Multiple Applications
- [x] New Button is missing for few cases

**Comment by ankitsrivas14** [comment]
There are other more occurrences for usage of userWorkspaces, its selectors, reducer and Sagas etc. We need to update all the components / area of codes to use latest state of workspace/applications/packages. Need to update the estimations accordingly.

**Comment by deepikaappsmith** [comment]
fixed and merged in release. Hence closing the ticket
