### ISSUE TITLE
[Task]: Mobile UI changes for Homepage

### ISSUE THREAD

**Issue by ankitsrivas14** [appsmithorg/appsmith#29080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Workspace Selector
- [x] Search UI on mobile
- [x] UI fixes on mobile

**Comment by deepikaappsmith** [comment]
fixed and merged in release. Hence closing the ticket
