### ISSUE TITLE
[Task]: Introduce code split for application publish flow

### ISSUE THREAD

**Issue by subrata71** [appsmithorg/appsmith#29183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

Out of scope: Move existing entities to this interface

```[tasklist]
### Tasks
- [x] Add code split to create extension point for module instances
- [x] Create an interface for application publishing service to be implemented by module instances
```
