### ISSUE TITLE
[Task]: Handle query module instance related issues

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#29270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Query module instance of one page is showing in another - reset it on page change
- [x] Tooltip on query module instance name on explorer menu options
- [x] Use default name of module for module instance
