### ISSUE TITLE
[Task]: Handle evaluation issues related to query module instances

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#29271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] FETCH_MODULE_INSTANCE_ENTITIES_SUCCESS -> starts evaluating before reducer is even updated
- [x] Add new redux state for save module instance name success which should be added in evalutionsActionsList after fetch entities is done
- [x] `fetchAllPageEntityCompletion` should have fetching of module instance entities - else its giving error in evaluations
