### ISSUE TITLE
[Task]: Handle module instance editor related issues

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#29272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Refactor of module instance name is not working on module instance editor - https://theappsmith.slack.com/archives/C04GRCN4CS3/p1701437221331239?thread_ts=1701410712.706839&cid=C04GRCN4CS3
- [ ] On page load toggle inside query module instance editor is not turned on even when you directly bind module instance to widgets while it should be auto turned on - using response of updateLayouts API -> actionUpdates
- [ ] UPDATE_MODULE_INTSANCE_ON_PAGE_LOAD_SETTING_ERROR -> isSaving of undefined
