### ISSUE TITLE
[FEATURE]: Improve templates gallery

### ISSUE THREAD

**Issue by jacquesikot** [appsmithorg/appsmith#29456]
**Tasks to be completed**

- [x] Make each template height fixed
- [x] Update "Templates" title copy to "Operations"
- [x] Extend current template card to account for building blocks
- [x] Use grid instead of Masonry to align templates and building blocks
