### ISSUE TITLE
[Task]: Design fixes for pages pane

### ISSUE THREAD

**Issue by albinAppsmith** [appsmithorg/appsmith#29501]
```[tasklist]
### Tasks
- [ ] Empty query state in add new section
- [ ] No queries UI fixes
- [ ] No JS objects fixes
- [ ] Remove collapssible parent from widgets
```
