### ISSUE TITLE
Task: Integrate Appsmith AI datasource with AI Server

### ISSUE THREAD

**Issue by vivonk** [appsmithorg/appsmith#29742]
```[tasklist]
### Tasks
- [ ] Implement text generation use-case
- [ ] Implement text classification use-case
- [ ] Implemented text summarisation use-case
```
