### ISSUE TITLE
[Task]: Refactoring name of private entities

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#29762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Refactor private entity name - requires `layoutId`, `pageId` ——> use new function `refactorActionBasedOnEntityType`
- [ ] Remove menu items condition for page from files context provider and instead have default value and get non-default from props if required
- [ ] Private entities js object name not updating unless clicked ——> fetch entities again after renaming 
- [ ] Show no context menu for JS object private entity (Main file)
- [ ] Remove settings icon from left pane
- [ ] Change enum to const for `CreateNewActionKey` and `ActionContextType`
- [ ] JS object name selection on entity explorer pane -> both private entity (Main) + module should be selected
