### ISSUE TITLE
[Task]: Page Pane Visual Design Rivisions

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#29921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Revert the change for the pane background around segments
- [ ] Make the Add button bigger to match the height of the segments
- [ ] Blank state CTAs to be made secondary
- [ ] Update pane headers to have `spaces-2` padding on the right side
- [ ] Increase gap between list items divided by headers (Queries and Queries Add) to `spaces-4`
- [ ] Remove any gap present between list items
- [ ] Add background to the add state headers under the segments

**Comment by vinay-appsmith** [comment]
One more fix: 
<img width="241" alt="image" src="https://github.com/appsmithorg/appsmith/assets/101088862/0e081878-b4e7-484d-ae47-d22092cde3db">
