### ISSUE TITLE
[Task]: Query / JS Editor Toolbar

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#29957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

A common toolbar for all Edit modes of Query and JS in Split screen and full screen mode.
Currently the new toolbar is under feature flag and can be seen for ide-design login.

Needs to be customisation friendly

<img width="515" alt="Screenshot 2023-10-23 at 5 10 09 PM" src="https://github.com/appsmithorg/appsmith/assets/12022471/961c7612-12af-438d-bf38-b403cd5c8000">

```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith/issues/35529
- [ ] https://github.com/appsmithorg/appsmith/issues/35528
- [ ] https://github.com/appsmithorg/appsmith/issues/35512
- [ ] https://github.com/appsmithorg/appsmith/issues/35533
- [ ] https://github.com/appsmithorg/appsmith/issues/35534
- [ ] https://github.com/appsmithorg/appsmith/issues/35535
- [ ] #34670
- [ ] https://github.com/appsmithorg/appsmith/issues/35532
- [ ] https://github.com/appsmithorg/appsmith/issues/30630
- [ ] https://github.com/appsmithorg/appsmith/issues/30658
- [ ] https://github.com/appsmithorg/appsmith/issues/36927
- [ ] https://github.com/appsmithorg/appsmith/issues/36920
- [ ] https://github.com/appsmithorg/appsmith/issues/36943
- [ ] https://github.com/appsmithorg/appsmith/issues/36973
- [ ] https://github.com/appsmithorg/appsmith/issues/37578
```

**Comment by albinAppsmith** [comment]
Closing this task since most of the task inside this is complete.
