### ISSUE TITLE
[Task]: IDE component

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#29956]
### SubTasks

Create a single entry point IDE component that implements the routing and context retention of IDE. This should work with Module and Workflow editors as well
```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith/issues/30544
- [ ] https://github.com/appsmithorg/appsmith/issues/34438
- [ ] https://github.com/appsmithorg/appsmith/issues/34439
- [ ] https://github.com/appsmithorg/appsmith/issues/34441
- [ ] https://github.com/appsmithorg/appsmith/issues/34537
- [ ] https://github.com/appsmithorg/appsmith/issues/34538
- [ ] https://github.com/appsmithorg/appsmith/issues/34539
- [ ] https://github.com/appsmithorg/appsmith/issues/34541
- [ ] https://github.com/appsmithorg/appsmith/issues/34542
- [ ] https://github.com/appsmithorg/appsmith/issues/34543
- [ ] https://github.com/appsmithorg/appsmith/issues/34544
- [ ] https://github.com/appsmithorg/appsmith/issues/34545
- [ ] https://github.com/appsmithorg/appsmith/issues/34554
```

**Comment by hetunandu** [comment]
All items completed
