### ISSUE TITLE
[Task]: Remove the Guided Tour

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#30082]
### SubTasks

- [ ] Remove the button to start the guided tour
- [ ] Remove any code that takes new users into guided tour
- [ ] Remove Entity Explorer hide and pin logic
- [ ] Remove any guide saga logic for guided tour
- [ ] Remove all component props that are used to render guided tour hints
