### ISSUE TITLE
[Bug]: Listed bugs for modules

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#30158]
### SubTasks

Ref: https://docs.google.com/spreadsheets/d/1zZX8wrnBvfNaQltCMFBq8s0_I3frxti7RKEflMxHrWQ/edit#gid=447050749

- [x] In the DS page, the current selected datasource is not highlighted - (Query Modules - Consumer Side)
- [x] Data not being seen in the Query Pane when executeOnLoad is run for the first time - (Query Modules - Consumer Side)
- [x] Redirection to DS pages from editor is not happening - (JS Modules - Creator Side)
- [x] The boolean state of Run on Page load is not preserved when the state is modified and we switch between pages, 
we need to specifically refresh the page for the correct states to appear - (JS Modules-Consumer side)
- [x] when ConfirmBeforeExecute is turned on, it does not work unless we refresh the page - (JS Modules-Consumer side)
- [x] Data is not getting rendered in the query pane when module is first instantiated and executed - (JS Modules-Consumer side)
- [x] The editor data (e.g function name in the dropdown) is not getting updated during module switch. - (JS Modules-Consumer side)
- [x] [CREATOR] issue 1: unable to get message -> Environment switched to staging/prod successfully . Check migrateDSL - (Muti-environment issues)
- [x] [CREATOR] when env is switched, the data in the right hand side API right pane schema doesnt get updated api/v1/datasources/ this api is not getting called - (Muti-environment issues)
- [x] [CREATOR] the toast message during env switch says all associated pageLoad actions will be loaded automatically but there are no pageLoad actions for package - (Muti-environment issues)
- [x] "For app level share with developer access, 
1. Check the developer app instance.
2. Even though the create module is in disabled state, the action is still clickable
 " - (Create module from existing query)
