### ISSUE TITLE
[Task]: Create and update the new icons for workflows as per the designs

### ISSUE THREAD

**Issue by ayushpahwa** [appsmithorg/appsmith#30174]
### SubTasks

- [ ] Create new icons in design system
- [ ] Create new release for design systems
- [ ] Pull these icons into the code
