### ISSUE TITLE
[Task]: Improve test coverage for git + module instances

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#30215]
### SubTasks

Test for:
- [x] Apps with module instances working in the same branch
- [x] Apps with module instances working in different branches
- [ ] Apps with module instances working across workspaces with package definition present
- [ ] Apps with module instances working across workspaces with package definition absent
- [ ] Apps with module instances working across workspaces with package definition present in a different version
