### ISSUE TITLE
[Bug]: Issues related to Query and JS module instances 

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#30309]
### SubTasks

- [x] When we switch between two Query module instances, the editor doesn't get updated for settings and hence sends the wrong id in the API for updates - (Query Modules-Consumer Side)
- [x] when ConfirmBeforeExecute is turned on, it does not work unless we refresh the page - (JS Modules-Consumer side)
- [x] Unable to change the function from dropdown on the Consumer side - (JS Modules-Consumer side)
