### ISSUE TITLE
[Task]: Handle JS module instance and multi-env related issues

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#30461]
### SubTasks

Ref: https://docs.google.com/spreadsheets/d/1zZX8wrnBvfNaQltCMFBq8s0_I3frxti7RKEflMxHrWQ/edit#gid=447050749

- [x] after you delete a JS module and add any new JS module , execute call is not happening. it starts working on page refresh - (JS Modules-Consumer side)
- [x] After deleting a JS module, If you click on any other JS module, editor doesn't render. It starts working on page refresh. - (JS Modules-Consumer side)
- [x] "[Creator] When environment switches , the debugger state is not refreshed and old errors still popup
Replication steps: 
1. Setup staging with invalid config
2. Switch environment from prod to staging and then back to prod
Notice soft refresh for debugger didn't happen" - (Multi-environment issues)
