### ISSUE TITLE
[Task]: killing delete multiple apps feature

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#30660]
### SubTasks

- [x] Removed front-end code
- [x] Removed backend-end code
- [x] Removed cypress test cases
