### ISSUE TITLE
[Task]: update hotkeys for view and edit mode which are hard to accidentally click

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#30825]
### SubTasks

- [x] Create a hotkey for preview mode (which is not just a single key)
- [ ] Update the hotkey for Edit mode (to something which is not a single key)
- [ ] Update the tooltips for Preview and Edit modes to reflect the new hotkeys
<img width="602" alt="image" src="https://github.com/appsmithorg/appsmith/assets/20532920/cb57117d-2be7-4aec-88c4-b7c3e8cf6986">

**Comment by kocharrahul7** [comment]
This has been done
