### ISSUE TITLE
[Task]: Import package from within the package

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#31528]
### SubTasks

- [ ] New modules UUIDs should get appended to the package with a new UUID
- [ ] Existing modules should get overridden completely if the same UUID is imported
- [ ] Package should retain versioning info from the original package (not the imported one)
