### ISSUE TITLE
[Task]: Change default name for module instances

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#31949]
### SubTasks

- [ ] Change default name for module instances by removing the _ in the naming convention
- [ ] Removing repeated text "Add" which prepends all the options to create new module instances
- [ ] Show beta description for all the options to create new module instances
