### ISSUE TITLE
[Task]: Widget selection in Anvil: Prototype

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#31947]
### SubTasks

This is a prototype implementation task to understand if the hypothesis for the new widget selection mechanism is valid.
If the validity is confirmed, or we agree to bet on it, we will re-implement properly as production code.

Note: The following will be done as cheaply as possible (Cheaper === lower time taken to implement)

- [ ] Create new components for widget name
![Screenshot 2024-03-20 at 1 11 24 PM](https://github.com/appsmithorg/appsmith/assets/103687/8e990c38-4597-44b4-8b19-926b161f20ad)

- [ ] Create constants for new colors to be tokenized later.
- [ ] Customize Widget Development API to accept specific colors for widget borders and widget name component
![Screenshot 2024-03-20 at 1 12 46 PM](https://github.com/appsmithorg/appsmith/assets/103687/78174601-8ae8-4b6a-a6cd-7d806fe970ea)

- [ ] Widget name render
   - Constraint 1: It should be implemented while relying on CSS as much as possible.
   - Constraint 2: It should not introduce any abstraction leaks
   - Constraint 3: No new selectors in the layout rendering flow, if the data isn't already available, we render it from the layer where the data is available.

- [ ] Feature: Click on arrow in widget name component to select parent widget
- [ ] Feature: Click on exclamation icon in widget name component to open debugger (optional)

- [ ] Discuss with the team to understand if the hypothesis' implementation is complete and valid for release on Anvil Instance
- [ ] Breakdown tasks for Anvil instance release.
