### ISSUE TITLE
[Epic] Git Sync & Version Control

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#3199]
## Problem statement
Today we get a lot of requests around migrating applications between instances as well as moving applications across organizations.
There is also a need to have some kind of version control that will make it easy to restore the state of applications.
This should also make it easy for other developers in a team to do code reviews of changes to applications.
Changes to an application by a developer should not overwrite the changes other developers make.

## Related issues

- [x] #488
- [x] #2285
- [x] #3089
- [x] #3190

# Solution
- Make it easy to bring up Appsmith locally
- Make it easy to get access to the application I need to work on
- Make it easy to get my changes reviewed, approved and merged as one process
- Make it easy to develop and test in different environments

# The Story

## Discovery
A developer comes to appsmith and wants to try it out. She runs a docker command and gets it running on her local system #4430. A browser window opens and she is welcomed. She mentions that she is developing locally and the mode of the app changes to offline mode. She goes through our onboarding. She is prompted to connect to her data source. She is able to easily connect to her local API / DB without NGrok. She is in an offline mode and is not able to share/invite users to her application.

- No account creation or need for access
- Direct connection to local datasources
- No organisations

## Sharing
She builds her first application with a lot of excitement and wants to share it so everyone gets access to it. This prompts her to connect a Git Repository and select a directory to commit her app & docker-compose file to. The readme of the repository is also updated with

1. The steps of starting the application locally
2. The documentation links
3. The discord support links
4. The name / image of the app

[https://github.com/Nikhil-Nandagopal/codesandbox](https://github.com/Nikhil-Nandagopal/codesandbox)

After the git repo is connected, the user is asked to connect to deploy a cloud version and is prompted to either select appsmith cloud or their own private cloud. Selecting appsmith cloud will ask the user to create / sign in to an account. Once this is successful, the user has to select an organisation and the app gets created in that org.

If the user select private cloud, they are prompted to deploy appsmith using the steps below
- Docker
- K8s
- Heroku
- AWS

They must then enter the URL of their appsmith login page and follow the steps to login / select the org.
She accesses her appsmith cloud and is prompted to create the datasources that she created locally. She then invites all her users to use the app. She should be able to change the cloud environment she is pointing to.

## Iteration
Her users get invites to the application and begin trying it out. They leave her feedback using the commenting feature which she receives via email. She opens the application on her local and is able to see all the comments. She creates a branch of the application and makes changes to it. She configures new datasources on this branch that point to her staging environment. She is able to make changes to the application on this branch and test them out. She then hits deploy which commits the changes to the new git branch and she is given the link of the branch. She now raises a pull request from this branch to master and pings a colleague to review/test the changes. The colleague goes over the PR, uses a visual diff tool, tests it, and approves it. The PR is merged to master and the new changes of the application are deployed to all users. The actions do not change the datasource they were pointing to on merge.

## Evangelism
As more developers review her PR, they are able to see a link of the cloud instance of the tool in the PR to review & test. They try out the tool and are automatically able to get access to it by authenticating with a common Google domain or setting it up locally.

They begin to learn more about the tool and try to create an app. All the underlying deployment & environment infrastructure is already set up for them. New developers in the team are easily able to check out the app locally and request access to take their changes online.

Every new app developed locally must be committed to a git repo and select an organization in the cloud to be a part of.

## Git Syncing
App branches may go out of sync or have merge conflicts and we should intimate developers of this and allow them to manually update their branches as well as inform them of conflicts and links of where to resolve them.
Users can authentication with a git repo specifying their username/password or their public key.
Users should enter the git path to connect to a repo.
Every commit should autogenerate a message. Users can manually specify a message for certain commits.
(Enhancement) Allow users to authenticate with Github to select their git repo and credentials.

# Summary
1. Developers can easily bring appsmith up locally using a docker-compose file. #4430 
2. There is a version of appsmith in their cloud which business users use.
3. All local instances can switch between online/offline versions. The offline version is limited without auth, users, orgs and contains apps from all the repos that the user has access to.
4. Developers can create a version of an app from anywhere (cloud / local) & commit it to a git branch in the global git repo.
5. The cloud backend is reading/updating each application from a git branch.
6. Comments and feedback can be given on individual versions of the application on the git branch

# CE Constraints
1. Each commit comes with a hash generated by the instance. This hash contains the hash of the version and a secret of the instance to prevent rehydration on any system that is not the instance that created it.  This prompts larger companies that need staging and production on separate sandboxes to pay for us.
2. Environments will not be available and all datasources are tracked against the branch (except secrets)

# Flows
1. Deploying Appsmith Locally #4430 
2. Connect to their local data sources
3. Switch between offline & live modes
4. Deploy their app to a cloud instance
5. Connect their app to a git repo
6. Commit changes
7. Create branches for their apps & Sync apps across branches
8. Deploying changes to branches

## Details
The Git Repository must have a clean human-readable structure.
Pages
-- Page1
-- Widgets
---- Widget1
---- Widget2
---- Widget3
-- Actions
---- Action1
---- Action2
Datasources
-- Datasource1

Each widget / action / data source should have a clean JSON of it's properties
The git repository must have a readme with the information of the application and appsmith.

## Figma
https://www.figma.com/file/TdPXDzYZvb11PYUmVAU4r1/Local-Dev-Flows?node-id=0%3A1&viewport=683%2C-1019%2C0.2663029432296753

https://www.figma.com/file/dHbJ2KNXa9597W6BzsFIuE/Local-Dev-Git-Sync?node-id=1%3A594

## Test env
http://ec2-3-108-64-217.ap-south-1.compute.amazonaws.com

## Docs (wip)
https://docs.google.com/document/d/1765hZEen2sip_LwXF5C9_hfTLE7FZaM9X4zAo_gCHrc/edit?usp=sharing

**Comment by marcius** [comment]
This would be an awesome feature!

**Comment by sharat87** [comment]
Also slightly related: #3424.

**Comment by srijanshetty** [comment]
This would be a great addition!

**Comment by ioloc** [comment]
This is for sure, my most anticipated feature :)

**Comment by ec-raphael** [comment]
This is something we'd _love_ as well. We see AppSmith as a nice companion to tools like [Hasura](https://hasura.io/). Open source, but was a SaaS option for cases where we can't/don't want to deal with hosting. 

The open source bit is important because it lets us run the full suite of tools on a developer machine (as opposed to something like Retool). With Hasura, we love the declarative configuration, which you can export/import, and allows a developer to create a configuration locally and apply it in staging/prod. Environment variables are used for things like api, endpoints, secrets, etc.

The reason this could be so _magical_ with a tool like AppSmith is it would allow a developer who has intimate knowledge of the system they are building to quickly put together admin tools as a part of that system. With platforms like Retool, etc. the admin side feels pretty disconnected from dev. It feels like an "addon" rather than part of a system. 

For us, this is _the_ potential differentiator with platforms like Retool. For now, the differentiator is more control, which is honestly far less appealing. Maybe cost? Depends on the setup.

**Comment by Nikhil-Nandagopal** [comment]
@ec-raphael that's a really neat take on this feature. We'd love to hear more from you on your thoughts about this as a product differentiator. Would you be up for a quick chat? This is my calendly, I'd love for just 30mins of your time to hear your ideas 
https://calendly.com/appsmith-nikhil/appsmith-meeting

**Comment by ericwooley** [comment]
I'm in the same situation as @ec-raphael, currently, we are using Hasura with retool to quickly build out some proof of concepts. 

The only reason we are using retool is that it has better graphql support. I was very tempted to use app smith anyways, because I love the direction, but asking other devs to manually translate grapqhl in regular post requests was too much. Even with that, if there were git versioning, I think we would have gone with app smith.

I even considered using appsmith with a mongo docker instance, that had it's db volume mounted inside our git repo, so we could just commit that, but it seemed a little to janky. I don't want think I want to see what a merge conflict would look like.

While your considering thing, I just wanted to point out that hasura uses yaml, and nx.dev uses json to keep track generated things. Having dealt with merge conflicts in each, yaml is soooooooo much easier to handle conflicts in. Not having all the opening and closing brackets (which don't technically conflict), is really helpful.

If git integration does happen, I would use app smith for sooooo so many projects, that I use CRA, or nextjs with vercel for now. Especially if you can create a vercel like workflow for deployments. 

------

Great project! Keep up the awesome work!

**Comment by ericwooley** [comment]
OH, I got carried away and forgot the original reason I commented.

Since you are using mongo now, it might not be that hard to implement this feature using https://github.com/louischatriot/nedb

**Comment by Nikhil-Nandagopal** [comment]
HI @ericwooley thanks for your input! YAML does seem like a better option for resolving conflicts. We're now releasing a quick import/export feature which you can write a job on top of to commit to git. We'll work on improving this to directly sync to GitHub as well and include YAML instead of JSON as an option.

I'm interested to know what you feel is lacking in our GraphQL Support. Would you be up for a quick chat regarding this?
This is my Calendly https://calendly.com/appsmith-nikhil/appsmith-meeting

**Comment by ereio** [comment]
The lack of version control is a major blocker in my experience for getting teams approval for appsmith or similar. It would make a pivotal difference if appsmith had this ability! :)

**Comment by Nikhil-Nandagopal** [comment]
Hi @ereio 👋 We're picking this up soon! You can expect to see something by end of July :)

**Comment by Rishabh-Rathod** [comment]
Showing Difference for JSON can be something similar to the UI in [DiffyCurl](https://rishabh-rathod.github.io/DiffyCurl/)

**Comment by ereio** [comment]
No rush, just wanted to check in and see where this is in priority. Still hoping to work on the feature soon?

**Comment by Nikhil-Nandagopal** [comment]
@ereio development is already well underway! You can expect an early preview at the end of the month 😁

**Comment by polwayne** [comment]
Any update when this will be released? :-)

**Comment by Nikhil-Nandagopal** [comment]
Hey @polwayne 👋 it's scheduled for release late this month 🙂

**Comment by Nikhil-Nandagopal** [comment]
Hello @roitalpaz 👋 
This has been delayed due to unforeseen technical challenges. We're still hard at work on it and we're optimistic about a beta preview in another 2 weeks :)
You can look at the early release in our test env here
http://ec2-3-108-64-217.ap-south-1.compute.amazonaws.com

**Comment by RakshaKShetty** [comment]
Adding the Testplan Link here for reference https://docs.google.com/spreadsheets/d/1bLZb7lDy8CySKa0oByFUS7ICw3BWfnMKZxqqwr8dxHE/edit#gid=0\

**Comment by rishabhsaxena** [comment]
Pending decisions/inputs needed:
- Design inputs (@Debsourabh)
  - Merge success indication on the merge tab
  - Branch list: segregate branches into local and remote (for both the switch branch dropdown and the destination branch on the merge tab)
  - Communicating the limitations w.r.t. the number of repos in CE
- Product inputs (@Nikhil-Nandagopal )
  - Decide on the limitations w.r.t. the number of repos in CE
  
More details can be found here: https://www.notion.so/appsmith/Gitsync-and-version-control-0c0ef0365495400db85e7e209c3d6c79#a6ee85d90c0740028198696683776a59

**Comment by rishabhsaxena** [comment]
Blockers for going to prod with the beta version:
- Check for count of private repos and UX flow around this
- Disconnect git flow
- Documentation
- Stacks folder prefix
- Essential analytics

**Comment by rishabhsaxena** [comment]
Next set of action items:
- Update generated `README.md` for repos (@vuiets)
- Close import flow designs (@Debsourabh)
- Discuss on migration during import (including DSL and backend migrations) (@abhvsn)
- Update analytics issue to include the disconnect git flow (@rishabhsaxena)

**Comment by rishabhsaxena** [comment]
Posting the updates from the last catchup, for ref:

BE:
- API to generate SSH key without linking to application in DB (This is to avoid stale apps if user don’t follow the complete git-import flow) @Anagh
- API to connect application which will accept json, md, licence files @Anagh
- JSON schema migration @Abhijeet
- Keep local git-repo and DB in sync when the local repo is deleted @Abhijeet
- Clone remote repo
- Check apps in DB which are linked to the repo and pull these branches in local
- Improve TC around merge branch @Abhijeet
- Commit datasource configs except credentials to git @Abhijeet

FE
- Merge cypress TCs
- Import flow

Design
- Design updates to incorporate datasource secrets @Joy

**Comment by rishabhsaxena** [comment]
- Edge cases for import flow:
  - If we have an existing datasource with the same name but a different type that in the repo, the import api should fail
  - Handle app name conflict during import
- Edge cases for git pull involving datasources:
    - A new datasource got pulled: it won't be configured so the associated actions would fail
    - A conflicting datasource got pulled (same name but diff type)
- Allow creating a new datasource only if an existing datasource with the same name doesn’t exist already in the org 

Design changes:
- Test and save button
- Prevent closing the DB configuration modal, ask for confirmation

Action items:
- Import via git UI @rishabhsaxena 
- Update Import APIs: @AnaghHegde 
  - Handle app name conflict during import
  - If we have an existing datasource with the same name but a different type from that in the repo, the import api should fail
- Migrations and import APIs: PRs under review

**Comment by AnaghHegde** [comment]
- Mix panel dashboard set up @vuiets 
- Readme file designs @vuiets 
- Beta flag design for git-sync
- Polished Import flow mid next week:
    - Api to fetch not configured DS @AnaghHegde 
    - Front end flow @rishabhsaxena @haojin111 
- Flow for ssh key management
- Bugs fixes:
    - Auth around google sheets
    - Other issues

**Comment by hiteshjoshi** [comment]
- Mix panel events  @vuiets (P1)
- Readme file designs @vuiets ( P2)
- Beta tag by end of week @Debsourabh (P1)
- Monday release under beta. (P1)
- DP for Import flow -> http://ec2-3-108-64-217.ap-south-1.compute.amazonaws.com/
- UI changes for app import. @Debsourabh @vuiets (P1)
  - Changes to data source sections, remove sections and put a tick for configured and non configured datasources
  - UI to connect data sources to existing data sources.
- {BUG} While existing the same application ( shows uncommitted changes , related to DSL changes) (P1)
- Link to documentation about making sure to allow write access. @Debsourabh  (P2)
- Better error message if SSH auth fail. (P2)
- {BUG} Oauth redirection for import flow. (P1)
- Quick review of docs links. @Debsourabh @vuiets (P2)

**Comment by AnaghHegde** [comment]
- After entering credentials and clicking save next unConfigured datasource should be selected and if none show a toast and redirect
- Design : DB Name should be at top 
- Export, Fork and Delete on branch level
- Pull changes button enabled
- Create branch UX - similar to github

**Comment by AnaghHegde** [comment]
- After entering credentials and clicking save next unConfigured datasource should be selected and if none show a toast and redirect
- Design : DB Name should be at top 
- Export, Fork and Delete on branch level
- Pull changes button enabled
- Create branch UX - similar to github

**Comment by abhvsn** [comment]
Next set of action items:

- [ ] Provide a way to change the default branch to be in sync with remote @AnaghHegde @Debsourabh https://github.com/appsmithorg/appsmith/issues/11223
- [ ] Discard and pull changes and rehydrate the application @abhvsn https://github.com/appsmithorg/appsmith/issues/10863
- [ ] UI for export, clone, fork applications at branch level @haojin111 @Debsourabh https://github.com/appsmithorg/appsmith/issues/11270
- [ ] Pull changes button should be enabled without taking the input from status api @haojin111 
- [ ] Give user context if the changes are because of the migration or the user has manually updated the application @abhvsn @IAmAnubhavSaini @Debsourabh https://github.com/appsmithorg/appsmith/issues/10644
- [ ] **Fix uncommitted changes that show up without user modifying the application and even without the migration change @AnaghHegde https://github.com/appsmithorg/appsmith/issues/11266** 
- [ ] Improve directory structure to store the application in git to reflect the way we represent in Appsmith UI @abhvsn https://github.com/appsmithorg/appsmith/issues/11267
- [ ] Git import bugfixes and polishing @AnaghHegde @RakshaKShetty @haojin111 https://github.com/appsmithorg/appsmith/issues/10950
- [ ] Provide an option to delete branch @AnaghHegde https://github.com/appsmithorg/appsmith/issues/11272

**Comment by abhvsn** [comment]
Blockers for the public announcement of Git Sync:

- [ ] Discard changes for git @IAmAnubhavSaini Discard and pull changes and rehydrate the application @abhvsn https://github.com/appsmithorg/appsmith/issues/10863 
- [ ] Stray changes popping up on changing branch or opening app after a while @AnaghHegde https://github.com/appsmithorg/appsmith/issues/11266
- [ ] Give user context if the changes are because of the migration or the user has manually updated the application  @IAmAnubhavSaini @Debsourabh https://github.com/appsmithorg/appsmith/issues/10644
- [ ] Mimic the directory structure on the app @abhvsn https://github.com/appsmithorg/appsmith/issues/11267


Good to have 

- Git import bugfixes and polishing @AnaghHegde @RakshaKShetty @haojin111 https://github.com/appsmithorg/appsmith/issues/10950
- Pull changes button should be enabled without taking the input from status api @haojin111

Requires discussion:
- Automated commit and push after migration when there are no uncommitted changes from the user, think through with multiple instance scenario

**Comment by abhvsn** [comment]
### Next set of action
- Create a test plan after the app is connected to git, including the git-import scenarios @Parthvi12 @RakshaKShetty 
- Documentation for git directory update @abhvsn @Pranay105 
- Update the mixpanel dashboard @vuiets 
- Remove feature-flag for git-import https://github.com/appsmithorg/appsmith/pull/12909 @AnaghHegde 
- Introduce discard changes feature https://github.com/appsmithorg/appsmith/pull/11835 @IAmAnubhavSaini  
- Merge PRs 
  - https://github.com/appsmithorg/appsmith/pull/11705
  - https://github.com/appsmithorg/appsmith/pull/12288
  - https://github.com/appsmithorg/appsmith/pull/11549

**Comment by abhvsn** [comment]
### Next set of action
- Create a flowchart for commit-pull-push flow https://github.com/appsmithorg/appsmith/issues/13256
- Optimize import application flow https://github.com/appsmithorg/appsmith/issues/13398
- Add a field in the analytics event for system-generated events
- Improve error logging in mixpanel for missing event 
- Add client-side analytics events

**Comment by abhvsn** [comment]
### Next set of action items:
- Merge discard and pull PR @IAmAnubhavSaini https://github.com/appsmithorg/appsmith/pull/11835
- Add cypress testcases for discard changes @Parthvi12 @IAmAnubhavSaini https://github.com/appsmithorg/appsmith/issues/13615
- Add cypress testcase for delete branch @IAmAnubhavSaini https://github.com/appsmithorg/appsmith/issues/13616
- Updates on deploy modal to convey migration changes @Debsourabh @IAmAnubhavSaini 
- Bring SSH key ellipsis to the front to have a visual feedback for regenerate flow @IAmAnubhavSaini @Debsourabh 
- Limit status API calls if user switches between deploy and merge tab @IAmAnubhavSaini 
- Provide options for supported SSH keys within vertical ellipsis in connect modal @AnaghHegde @IAmAnubhavSaini 
- Add missing client-side analytics events @vuiets

**Comment by hiteshjoshi** [comment]
Closing this.
