### ISSUE TITLE
[Bug]: UI issues in the property pane

### ISSUE THREAD

**Issue by sneha122** [appsmithorg/appsmith#32069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Following UI issues have been observed in the property pane during development of https://github.com/appsmithorg/appsmith/issues/30980
![image (6)](https://github.com/appsmithorg/appsmith/assets/30018882/254c9e9a-a669-4e26-849e-b9f52e3b556c)
![image (5)](https://github.com/appsmithorg/appsmith/assets/30018882/3d8f1c97-4ea7-4aed-ab40-b0f47fbbe217)
![image (4)](https://github.com/appsmithorg/appsmith/assets/30018882/14a156b2-9306-4837-847f-5deb3501e661)

### Steps To Reproduce

1. Drag table and json widgets
2. Observe property pane

### Environment

Production

### Severity

Low (Inconsistent UI/UX)

### Version

Cloud/ Self-Hosted - 1.17
```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith/issues/32098
- [ ] https://github.com/appsmithorg/appsmith/issues/32099
- [ ] https://github.com/appsmithorg/appsmith/issues/32100
```
