### ISSUE TITLE
[Task]: Quality changes for building block on canvas

### ISSUE THREAD

**Issue by jacquesikot** [appsmithorg/appsmith#32332]
### SubTasks

- [x] Remove containers from all building blocks, publish and update S3 JSON
- [x] Rename building blocks to look and feel more relevant in the canvas, shorter names, max 2 lines
- [x] Update new explorer building block icons
- [x] Update the content of the sample db to include more meaningful and better looking content
