### ISSUE TITLE
[Task]: Code change fixes for building block on canvas

### ISSUE THREAD

**Issue by jacquesikot** [appsmithorg/appsmith#32331]
### SubTasks

- [x] Update copy in widget explorer from "Widgets" to "UI elements"
- [x] Remove highlighting of newly imported building block widgets on the canvas
- [x] Update copy from "Multi" to "Multiple selected"
