### ISSUE TITLE
Anvil Widget selection - Iteration 2

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#32363]
### SubTasks

Following #31947 

- [ ] Feature: Click on exclamation icon in widget name component to open debugger (optional)

- [ ] Feedback phase: Discuss with the team to understand if the hypothesis' implementation is complete and valid for release on Anvil Instance

- [ ] Prototype Update: Update prototype with missing features/bugs.

- [ ]  Iteration 2 execution: Step 1: Breakdown tasks for Anvil instance release.
