### ISSUE TITLE
[Bug]: Add a Modal.name property to be used in showModal

### ISSUE THREAD

**Issue by rishabhrathod01** [appsmithorg/appsmith#32410]
## Problem statement 

- When user uses `showModal("ModalName")` in code and later change the modalName the code won;t work anymore and they need to manually find the code and change it. 
- This is tedious and bad UX for users 

https://theappsmith.slack.com/archives/CNQ9Q91C0/p1712211027550769?thread_ts=1712161637.270239&cid=CNQ9Q91C0 A user complained about this being bad UX. 

### SubTasks

- [x] Add modal.name property
- [x] Suggest modal.name property in action selector
- [ ] Suggest modal.name property in docs
- [x] Give warning for using string in showModal and suggest to replace with modal.name
