### ISSUE TITLE
[Epic] Linting & Errors

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#3272]
## Product Notes

Improve the existing code errors a developer comes across while developing on Appsmith and introduce code linting support

### Linting
Linting helps in understanding issues with code via static analysis. This is a ubiquitous tool used by developers to understand issues and warnings in their code as they type. 
In Appsmith, a developer would write code in various languages like JS, JSON, SQL (and flavours) and potentially many more in the future.

### JS Errors
When a developer tries to reference or invoke something that does not exist or syntax error, the code cannot be executed and results in an error. 
These errors are now getting shown in the Evaluated Value popup and the Debugger, but the experience needs to be improved where more helpful errors are shown. We should also document these errors and their meaning for users to understand how to resolve them.

### Validation Errors
Each property expects a value of a certain type or a specific structure. These errors generally cause a transformation issue in the code. To help in this, we provide the user with their current evaluated value and the expected type.
In Appsmith, these errors were already present in widgets but were missing for actions. The error messages were also not very helpful as there was a generic validation error and the user had to manually compare evaluated vs expected value to understand what went wrong.

## Tasks
- [ ] Add linter to generate errors
    - [x] #4977 
    - [ ] JSON
    - [ ] SQL
    - [ ] Mongo?
- [ ] Display lint errors
   - [x] #5661 
   - [x] #5662 
- [ ] Improve JS error experience
   - [x] #5819
   - [ ] #5818
- [ ] Improve Validation Error Experience
    - [ ] #2675 
    - [x] #5821
    - [x] #5820

**Comment by Nikhil-Nandagopal** [comment]
@aakashDesign @mohanarpit @hetunandu @ApekshaBhosale 
can we get designs for the experience and link them here?
I think other languages apart from JS should be out of scope till we get JS right, should we focus on this or is it marginal effort to add other languages?

**Comment by mohanarpit** [comment]
The experience of displaying error messages to users and linting is independent of language. 

From an engineering standpoint, we need to be able to multiplex multiple linters into a single CodeMirror field. For a given editor like CodeMirror, the linter libraries are already available. Within Appsmith, we need to be able to:
1. Seed the linter with the required information (schema, variables, etc)
2. Be able to multiplex multiple linters in a single field
3. Be able to display the linting errors in various places (inline, debug console, etc)

**Comment by Nikhil-Nandagopal** [comment]
Yeah that's fine, can we get the design experience for all the cases here. I think this needs to be thought through deeply.
How does it look in the property pane when a user hovers over the lint error? Do we give quick-fix solutions? Can we search the web for their JS error because the debugger searches our docs which is kind of pointless?

**Comment by hetunandu** [comment]
@mohanarpit Most linters out there have some kind of filesystem dependency. While generating lint errors for JS I came across this problem as ESlint does not allow for running on the browser https://github.com/eslint/eslint/issues/8348

So instead I figured we can lint different languages separately and use the lint plugin of Codemirror to just show these errors. This way we do not have to worry about multiplexing for linting. 

@Nikhil-Nandagopal Once we have the base ready for JS linting, adding other languages would marginal but not trivial as each linter library could bring its own challenges
