### ISSUE TITLE
[Epic]: Workflow test coverage

### ISSUE THREAD

**Issue by srix** [appsmithorg/appsmith#32722]
Segments to be covered
- [] History service
- [] Trigger service
- [] Health service
- [] Temporal utils

```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith/issues/33258
- [ ] Trigger service unit tests
- [ ] Health service unit tests
- [ ] Temporal utils unit tests
```
