### ISSUE TITLE
[Epic] Git usability issues - Phase 1

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#32944]
**Design handoff** for the tickets that require design: 
https://zpl.io/Gn74rN3

```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith/issues/33063
- [ ] https://github.com/appsmithorg/appsmith/issues/32976
- [ ] https://github.com/appsmithorg/appsmith/issues/32974
- [ ] https://github.com/appsmithorg/appsmith/issues/32975
- [ ] https://github.com/appsmithorg/appsmith/issues/32973
- [ ] https://github.com/appsmithorg/appsmith/issues/30321
```
