### ISSUE TITLE
[Feature]: Develop Diagnosis script to check possible failures

### ISSUE THREAD

**Issue by pratapaprasanna** [appsmithorg/appsmith#32971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A script which helps in running diagnosis incase of downtimes

### Why should this be worked on?

Helps in pin pointing problems and helps in faster resolution
```[tasklist]
### Tasks
- [ ] Determine data points desired to be captured. These data points include -- but may not be limited to -- component configuration settings, logs and status and relevant system configuration settings, logs and status. Ideally the tooling should be a single script smart enough to be portable across platforms irrespective of deployment methodology.
- [ ] Create tooling to parse gathered data for known mis-configurations, known bugs and common errors, with the ability to rapidly add further tests and analysis and expand the scope of error detection.
```

**Comment by zbuildz** [comment]
this is in progress with pull https://github.com/appsmithorg/appsmith/pull/35640

**Comment by zbuildz** [comment]
this was completed and pull request has been pending so just been awaiting. closing as completed as it is simply awaiting to be merged.

**Comment by zbuildz** [comment]
actually, as this is  an epic and we will undoubtedly be making enhancements, i will leave it open so as to track further work

**Comment by zbuildz** [comment]
pushed to production
