### ISSUE TITLE
[Task]: Enable new widget selection UX for Anvil

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#33130]
### SubTasks

- [ ] Update selection handlers
- [ ] Add widget name component to `AppsmithEditorWrapper`
- [ ] Fix any issues found when integrating the previous changes w.r.t the new widget selection UX.
