### ISSUE TITLE
[Task]: Anvil Widget Selection Issues

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#33138]
### SubTasks

- [ ] Modal border radius goes away in preview mode.
- [ ] Fix issue where we can't click on modal name component when hovering over a widget that is not selected.
- [ ] When a widget is selected and we hover over it, the border thickness reduces.
- [ ] Widget name component takes a few milliseconds to appear in the right position when scrolling.
- [ ] When clicking on the error button, the property control with the error is not focused.
- [ ] When multi-selecting, widget name components overlap (see screenshot)
![Screenshot 2024-05-02 at 5 22 23 PM](https://github.com/appsmithorg/appsmith/assets/103687/2918a016-d102-4391-a785-3e12c2cae42b)

**Comment by ramsaptami** [comment]
@riodeuno the last issue here is _okay experience_ imo, not necessary to solve since it does not hinder interaction
