### ISSUE TITLE
[Task]: Analytics for side by side canvas

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#33159]
### SubTasks

Must haves:
- [ ] Trigger an event whenever a user hovers on the Canvas when in side-by-side mode
- [ ] This event should have a property which mentions if the user navigated or not
- [ ] This event should have a property which mentions if a user hovers on a widget or not
Nice to have:
- [ ] A property which lists the types of widgets the user hovered on.

Examples:
If a user hovers on the canvas, but on no widgets: Event triggers 
Event fired CANVAS_HOVER {
  navigated: false, 
  widgetHover: false,
  widgetTypes: []
}

If a user navigates using cmd+click on a text widget:
Event fired CANVAS_HOVER {
  navigated: true, 
  widgetHover: true,
  widgetTypes: [Text]
}

If a user doesn't navigate but only hovers on 3 widgets: table1, table2, and select1
Event fired CANVAS_HOVER {
navigated: false, 
widgetHover: true,
widgetTypes: [Table, Select]
}
