### ISSUE TITLE
[Task]: Replace `APPSMITH_MONGODB_URI` with more generic `APPSMITH_DB_URL` 

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#33562]
### SubTasks

- [x] Add fallback logic for `APPSMITH_MONGODB_URI` to `APPSMITH_DB_URL`
- [ ] https://github.com/appsmithorg/appsmith-docs/issues/2270
- [x] Start using `APPSMITH_DB_URL` for env manager in the codebase

**Comment by abhvsn** [comment]
Closing this as completed.
