### ISSUE TITLE
[Epic] App theming

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#3369]
## Objective
To enable developers to build beautiful applications on Appsmith

## Solution
We will provide users with 3 out of the box themes that they can use to style their applications. We will improve the set of properties that developers can control for every widget to give them more control over the style of the widget. We will also provide a way to apply common styles across all widgets inside an application. Users updating properties at the widget level will be unlinked from the theme and not updated if the theme property is updated. The icon of the app should show as a favicon in the tab.

## Out of Scope
- Creating widget variants & managing a widget library
- Extending the master theme from inside Appsmith
- Branding
- Revamping widget

## Figma Design
https://www.figma.com/file/l58dRgau7gCASJSJN3OicH/Application-Theming-Thu-19-Aug-2021?node-id=519%3A143413

## Deploy Preview
https://appsmith-git-theming-phase-1-get-appsmith.vercel.app/

## RACI
| | | 
| ------------- | ------------- |
| Responsible   | @sbalaji1192 @jsartisan, @vivekverma2312 |
| Accountable   |  @sbalaji1192   |
| Consulted     | @Nikhil-Nandagopal, @momcilo-appsmith |
| Informed      | @areyabhishek @somangshu  |

**Comment by Schnurres** [comment]
I feel like the possiblity to add theming or add custom colors to reuse within the app would really improve Appsmith and make it more attractive for private and enterprise customers.

**Comment by Nikhil-Nandagopal** [comment]
Next Actions:
- List all style properties for every widget @sbalaji1192 
- Find out if we can redesign the property pane in this phase @jsartisan 
- Publish a stylesheet format @jsartisan @sbalaji1192 
- Engineering Plan @jsartisan @sbalaji1192 
- Dedicated Backend Bandwidth @somangshu 
- Improve Color Picker Control @momcilo-appsmith 
- Test Plan @vivekverma2312

**Comment by sbalaji1192** [comment]
Table of widgets that has theme properties - https://www.notion.so/appsmith/18716ad5c62246319badc60612a87dc2?v=6c50a6a861564127a47df3ac6344dd54

**Comment by sbalaji1192** [comment]
Draft Theme schema - https://jsonformatter.org/809e14#save

**Comment by sbalaji1192** [comment]
Since we had a short week last week, most of the next action items are carrying from previous window.

**Next Actions:**

- Expose missing style properties in property pane of widgets @jsartisan 

- POC to demonstrate the high level architecture of the Theming controls @sbalaji1192 

- Do RnD and publish a stylesheet format  @jsartisan @sbalaji1192

- Engineering Plan - issue breakups @jsartisan @sbalaji1192

- Dedicated Backend Bandwidth @somangshu

- Improve Color Picker Control @momcilo-appsmith

- Test Plan @vivekverma2312

**Comment by momcilo-appsmith** [comment]
Liz is going to update the property panes for the theming project this week and after that, we can review if the color picker still needs to be updated.

**Comment by jsartisan** [comment]
config ( list of possible values for theming )
```
{
    colors: {
      blue: {
        50: "#eff6ff",
        100: "#dbeafe",
        200: "#bfdbfe",
        300: "#93c5fd",
        400: "#60a5fa",
        500: "#3b82f6",
        600: "#2563eb",
        700: "#1d4ed8",
        800: "#1e40af",
        900: "#1e3a8a",
      },
      gray: {
        50: "#fafafa",
        100: "#f4f4f5",
        200: "#e4e4e7",
        300: "#d4d4d8",
        400: "#a1a1aa",
        500: "#71717a",
        600: "#52525b",
        700: "#3f3f46",
        800: "#27272a",
        900: "#18181b",
      },
      green: {
        50: "#f0fdf4",
        100: "#dcfce7",
        200: "#bbf7d0",
        300: "#86efac",
        400: "#4ade80",
        500: "#22c55e",
        600: "#16a34a",
        700: "#15803d",
        800: "#166534",
        900: "#14532d",
      },
      indigo: {
        50: "#eef2ff",
        100: "#e0e7ff",
        200: "#c7d2fe",
        300: "#a5b4fc",
        400: "#818cf8",
        500: "#6366f1",
        600: "#4f46e5",
        700: "#4338ca",
        800: "#3730a3",
        900: "#312e81",
      },
      pink: {
        50: "#fdf2f8",
        100: "#fce7f3",
        200: "#fbcfe8",
        300: "#f9a8d4",
        400: "#f472b6",
        500: "#ec4899",
        600: "#db2777",
        700: "#be185d",
        800: "#9d174d",
        900: "#831843",
      },
      purple: {
        50: "#faf5ff",
        100: "#f3e8ff",
        200: "#e9d5ff",
        300: "#d8b4fe",
        400: "#c084fc",
        500: "#a855f7",
        600: "#9333ea",
        700: "#7e22ce",
        800: "#6b21a8",
        900: "#581c87",
      },
      red: {
        50: "#fef2f2",
        100: "#fee2e2",
        200: "#fecaca",
        300: "#fca5a5",
        400: "#f87171",
        500: "#ef4444",
        600: "#dc2626",
        700: "#b91c1c",
        800: "#991b1b",
        900: "#7f1d1d",
      },
      yellow: {
        50: "#fefce8",
        100: "#fef9c3",
        200: "#fef08a",
        300: "#fde047",
        400: "#facc15",
        500: "#eab308",
        600: "#ca8a04",
        700: "#a16207",
        800: "#854d0e",
        900: "#713f12",
      },
    },
    borderRadius: {
      none: "0",
      xs: "0.125rem",
      md: "0.375rem",
      lg: "0.5rem",
      xl: "0.75rem",
      "2xl": "1rem",
      "3xl": "1.5rem",
      full: "9999px",
    },
    boxShadows: {
      none: "0 0 transparent",
      sm: "0 1px 2px 0 var(--aps-shadow-color)",
      md: "0 4px 6px -1px var(--aps-shadow-color), 0 2px 4px -1px var(--aps-shadow-color)",
      lg: "0 10px 15px -3px var(--aps-shadow-color), 0 4px 6px -2px var(--aps-shadow-color)",
      xl: "0 20px 25px -5px var(--aps-shadow-color), 0 10px 10px -5px var(--aps-shadow-color)",
      "2xl": "0 25px 50px -12px var(--aps-shadow-color)",
    },
  }
  ```
  
  theme value object
  ```
  {
    colors: {
      primaryColor: "<theme value>",
      backgroundColor: "<theme value>",
    },
    borderRadius: "<theme value>",
    boxShadow: "<theme value>",
    boxShadowColor: "<theme value>"
  }```

**Comment by sbalaji1192** [comment]
**Next Actions:**
- Work on the Epic tasks #9146 & #9147 @jsartisan 
- Rework POC to abstract theming from widgets configuration. @sbalaji1192 
- Dedicated Backend Bandwidth @somangshu
- Test Plan @vivekverma2312

**Comment by sbalaji1192** [comment]
=========================================================
    Widget Property Pane     ||     App Theme Pane
=========================================================
widget property -> theme property -> theme property value
=========================================================
padding         ->   medium       ->   5px
font-size.      ->   h1           ->   21px
button color    ->   mainColor    ->   red-50
radius          ->   curved       ->   4px
shadow          ->   small        ->   2px

==========
Theme File
==========
{
  "colors": {
    "color1": "#f3f4f3",
    "color2": "#f3f4f3",
    "color3": "#f3f4f3",
    "color4": "#f3f4f3",
    "color5": "#f3f4f3",
  },
  "borderRadius": {
    "appBorderRadius": "4px"
  },
  "fontSizes": {
    
  },
  "shadow": {
    "appShadow": "3px"
  },
  "shadowColor": {
    "appShadowColor": "#f4f4f4"
  },
  "fontFamily": {
    "appFont": "Arial"
  }
}



{
  "colors": {
    "color1": "#f3f4f3",
    "color2": "#f3f4f3",
    "color3": "#f3f4f3",
    "color4": "#f3f4f3",
    "color5": "#f3f4f3",
  },
  "borderRadius": {
    "buttonRadius": "4px": [0, 5, 10]
    "tableRadius": "2px",
  },
  "fontSizes": {
    
  },
  "shadow": {
    "appShadow": "3px"
  },
  "shadowColor": {
    "appShadowColor": "#f4f4f4"
  },
  "fontFamily": {
    "appFont": "Arial"
  }
}



==================
STYLE SHEET
==================

{
  "BUTTON": {
    color: {{theme.color2}}
    radius: {{theme.appRadius}}
  }
}

Button.color: colors.color2
Button.borderRadius: 

==================
Property Controls
==================


BUTTON1: {
  color: {{theme.color1}} // "#f4f4f4",
  radius: {{theme.appRadius}}
}



## We need to evalaute how hard / easy it is to link a property to a theme value. If this is hard, in V1 we should communicate that changing a property to JS will unlink it from the theme
## Can property pane values be driven by js values?

**Comment by sbalaji1192** [comment]
Next Actions: 

- Expose theme object to evaluations and theme provider implementation @sbalaji1192 @jsartisan 
- Test plan @vivekverma2312

**Comment by sbalaji1192** [comment]
Next Actions:

- Migrations for borderRadius and boxShadow - @jsartisan 
- Intergration with BE API - @jsartisan 
- Rest API to update themes - @nayan-rafiq 
- Test plan - @vivekverma2312 

DP - to be updated

**Comment by sbalaji1192** [comment]
Migrations for borderRadius and boxShadow, Theme bound state for Property controls UI - @jsartisan 
Include theme in the exported application json and CRUD templates - @nayan-rafiq  
Initial testing &  Test plan - @vivekverma2312

**Comment by sbalaji1192** [comment]
**Next actions:**
- Cypress tests and fix QA callouts - @jsartisan 
- Design for reset indicator - @liz
- Initial DP testing - @vivekverma2312

**Comment by sbalaji1192** [comment]
Next actions:
- API integration - @jsartisan @nayan-rafiq 
- Cypress tests for view mode - @jsartisan
- QA testing - @vivekverma2312

**Comment by somangshu** [comment]
@sbalaji1192 any actionable for the design could be recored. @dilippitchika Since you have a note of it, Could you drop it off here

**Comment by dilippitchika** [comment]
Adding the discussed items and questions to discuss next
## Saving and editing themes

1. User starts with default themes we provide, can preview it and apply.
2. Once applied, this theme can be customised by the user and is not linked to the default theme anymore. They can chose to save the theme with a custom name when customising.
    1. Need an option to “save theme as”
3. When they chose to apply a new default theme again from the list of themes, we ask the user if they want to save the current working theme from step 2 if it’s not already saved as a custom theme.
4. To save the current applied theme, they provide a name to theme and save it. 
5. After this we apply the new default theme and make a working copy of it. Similar to step 2 this theme can again be customised and saved as a new theme.
6. Any updates to a custom theme after it’s saved will just update the theme and users will not be allowed to “save as” again. 
    1. Need option to “save” a custom theme

### Questions pending discussion

1. Where will users see all the custom themes?
    1. Suggestion - In the theme list, we need to differentiate default vs custom
2. Do we give option to delete custom themes, if so what will be the behavior?
    1. Suggestion - Provide the users to delete a custom theme, if the theme is already in use deletion may revert to a default appsmith theme.

## Variants

1. Currently variant creation will only be supported for buttons. Needs to be discussed further.
2. We need to show all the variants associated with the widgets in some place, to help users understand what are the default variants for each widget.
3. Users can choose to update variants from this page.
4. In V2, we add the ability to create new variants for all widgets.

### Questions pending discussion

1. Full scope of v1 for variants needs to be finalised asap.
2. How to add new properties at theme level, like new colors etc on top of the existing primary and secondary colors.
    1. Suggestion - Allow users to add new styles in theme properties which can be then used in variants or widgets directly.

**Comment by dilippitchika** [comment]
Other items to discuss with Design team
1. Font previews on the font selection dropdown
2. Theme colors JS editable, bug in the color picker and dark light mode switch

**Comment by dilippitchika** [comment]
Notes - 3 Jan 22

V1 pending
1.  Discuss with Liz about the custom themes display and deletion
2. @jsartisan to fix the color picker bug which prevents users from typing the color.
3. Discuss with Will on the themed navigation and sidenav and importance for V1.

Blockers/Time consumers
1. Since there are backend changes involved in the project and we are working on both backend and frontend simultaneously is not smooth. Needs some inputs from @somangshu on how to manage this better.

**Comment by dilippitchika** [comment]
Items discussed
Saving default themes and creating new themes
- Option 1 : Ask user to save current theme when they try to load/apply a new theme
- Option 2 : Ask user to save when the start to make a change on a default theme
- Option 3 : Autosave as a new theme when change happens, when user tries to load a new theme, this theme persists.
- Option 4 : Autosave a theme, when user tries to apply another theme this theme is persisted instead of default theme. Provide users with a way to revert.
Action : Liz to check and suggest

Border radius full issue in dropdowns
Action : Remove the full radius and only give 3 border radius options by default. Full is unnecessary for us.

Currently the loaded theme shows "Change theme" and "Edit theme" as options and it's confusing as names are similar, also looks like flow has unnecessary extra steps.
Action : Liz to check and suggest

**Comment by keyurparalkar** [comment]
Theming v1 has a migration that migrates: `borderRadius`, `boxShadow`, and `fontSize` properties for all the widgets. It also adds primary color to the following widgets:
```
"DATE_PICKER_WIDGET2",
    "INPUT_WIDGET",
    "INPUT_WIDGET_V2",
    "LIST_WIDGET",
    "MULTI_SELECT_TREE_WIDGET",
    "DROP_DOWN_WIDGET",
    "TABS_WIDGET",
    "SINGLE_SELECT_TREE_WIDGET",
    "TABLE_WIDGET",
    "BUTTON_GROUP_WIDGET",
    "PHONE_INPUT_WIDGET",
    "CURRENCY_INPUT_WIDGET",
    "SELECT_WIDGET",
    "MULTI_SELECT_WIDGET_V2",
```
Also includes specific fixes as follows:
1. For `AUDIO_RECORDER_WIDGET` the borderRadius is set to `9999px` to make it circular.
2. For `FILE_PICKER_WIDGET_V2` the button color is set to green(`#03B365`).
3. For `CHECKBOX_WIDGET`, `CHECKBOX_GROUP_WIDGET`, `SWITCH_WIDGET`, and `SWITCH_GROUP_WIDGET` the background color is set to green(`#03B365`).
4. For `TEXT_WIDGET` we are keeping the JS toggle of the font size property to be enabled for some of these cases. These cases occur when user previously had font size `HEADING1`, `HEADING2`, and `PARAGRAPH2`. This is done because in current theming we don't have options to show these sizes in the font-size drop down. To mitigate this we toggle the JS to showcase these custom sizes so that the user experience is not confusing.

From testing perspective, I have tested the above scenarios for all the widgets. The testing was performed in the following manner:
1. Create a new page on the release app.
2. Drop the widget on to the new page.
3. Open the same app on the local instance (with local BE instance) and check if the migrations are working as expected. In case of theming, we are migrating couple of properties like boxShadow, borderRadius, fontSize etc.
4. Also checked for few widgets if the binding is getting migrated or not.

Below are the slack threads which will give more info in general about testing migrations:
https://theappsmith.slack.com/archives/C02JV8G1MP0/p1646393509037079
https://theappsmith.slack.com/archives/C025SE88KNE/p1646919304066019 

Keep QA in loop so that they are informed about this migrations
CC: @vivekverma2312 @shwetha-ramesh @somangshu @dilippitchika @jsartisan

**Comment by somangshu** [comment]
cc @riodeuno @marks0351 👆

**Comment by somangshu** [comment]
### Actionable  

- [ ] Documentation @dilippitchika 
- [ ] Finish all bugs @jsartisan @keyurparalkar 
- [ ] Test plan for migration on frontend @vivekverma2312 @shwetha-ramesh 
- [ ] merge backend migration to release @nayan-rafiq 
    - [ ] test plan around migration on backend @vivekverma2312 @shwetha-ramesh 
- [ ] Release plan
     - [ ] With above feedback any work on dev @jsartisan @keyurparalkar 
     - [ ] JSON form will need to be adjusted on the theming epic @ashit-rath @jsartisan @keyurparalkar

**Comment by keyurparalkar** [comment]
### Minutes of meeting: app-viewer standup

* As per the discussion in the meeting, JSON form will be going first into the release.
* Properties that are newly introduced into the theming such as boxShadow, borderRadius, fontSize and color etc. should be added in the property pane of the JSON form widget.
* Migrations should be written/required for the JSON form widget from the first level of widget perspective before app theming is released.

### Points discussed from theming-form discussion meeting:

* Currently we have two sets of widgets:
    * Widgets that are independently used such as INPUT_WIDGET, BUTTON_WIDGET etc.
    * Widgets that are combination of other widgets such as TABLE_WIDGET, BUTTON_GROUP_WIDGET etc.
* There should be a way to extend the properties of independent widgets in the dependent/combined widgets in the `system-themes.json` file. For example,
```
"BUTTON_WIDGET": {
        "buttonColor": "{{appsmith.theme.colors.primaryColor}}",
        "borderRadius": "{{appsmith.theme.borderRadius.appBorderRadius}}",
        "fontFamily": "{{appsmith.theme.fontFamily.appFont}}",
        "boxShadow": "none"
      },
      "BUTTON_GROUP_WIDGET": {
        "__extend": buttonWidgetProperties,
        "primaryColor": "{{appsmith.theme.colors.primaryColor}}",
      },
```
* If JSON form widget is released first, then it should consists of placeholder properties for the theming properties before going into the release.

Please feel free add any points if missed from my end.

CC: @dilippitchika @somangshu @riodeuno @ashit-rath @jsartisan

**Comment by keyurparalkar** [comment]
### Minutes of meeting: app-viewer standup

* As per the discussion in the meeting, JSON form will be going first into the release.
* Properties that are newly introduced into the theming such as boxShadow, borderRadius, fontSize and color etc. should be added in the property pane of the JSON form widget.
* Migrations should be written/required for the JSON form widget from the first level of widget perspective before app theming is released.

### Points discussed from theming-form discussion meeting:

* Currently we have two sets of widgets:
    * Widgets that are independently used such as INPUT_WIDGET, BUTTON_WIDGET etc.
    * Widgets that are combination of other widgets such as TABLE_WIDGET, BUTTON_GROUP_WIDGET etc.
* There should be a way to extend the properties of independent widgets in the dependent/combined widgets in the `system-themes.json` file. For example,
```
"BUTTON_WIDGET": {
        "buttonColor": "{{appsmith.theme.colors.primaryColor}}",
        "borderRadius": "{{appsmith.theme.borderRadius.appBorderRadius}}",
        "fontFamily": "{{appsmith.theme.fontFamily.appFont}}",
        "boxShadow": "none"
      },
      "BUTTON_GROUP_WIDGET": {
        "__extend": buttonWidgetProperties,
        "primaryColor": "{{appsmith.theme.colors.primaryColor}}",
      },
```
* If JSON form widget is released first, then it should consists of placeholder properties for the theming properties before going into the release.

Please feel free add any points if missed from my end.

CC: @dilippitchika @somangshu @riodeuno @ashit-rath @jsartisan

**Comment by somangshu** [comment]
### Actionable
- [ ] Migrations changes are not yet tested - is dependent on:
    - [ ] @keyurparalkar will finish working on the pending use cases by Wed EOD
    - [ ] @vivekverma2312 @shwetha-ramesh will get a test plan around testing migrations on older apps
- [ ] JSON form is a dependency on the theming EPIC and needs to be changed accordingly by @ashit-rath - is dependent on:
     - [ ] some changes that need to be made in the theming epic to accommodate composite widget as suggested by @ashit-rath @riodeuno will be worked on by @jsartisan @keyurparalkar 
     - [ ] The changes will need to be tested along with the JSON form widget
- [ ] Issue #11913 is still a release blocker from @appsmithorg/fe-coders-pod, need @ajinkyakulkarni to help

### RACI

| Responsible | Accountable | Consulted | Informed | 
| ---- | ----- | ----- | ----- |
| @keyurparalkar @vivekverma2312 @shwetha-ramesh @jsartisan @ashit-rath | @jsartisan | @ashit-rath @riodeuno | @Nikhil-Nandagopal @dilippitchika @ajinkyakulkarni @mohanarpit @somangshu |

**Comment by keyurparalkar** [comment]
### Catchup on migration changes: 29 March 2022

**Actionable**

@keyurparalkar 

In theming post migration, 
- boxShadow's none option should get selected if no boxShadow is set previously for the widget.
- boxShadow's JS option should be toggled if previously their existed boxShadow for the widget.
- borderRadius's JS option should be toggled if previously their was a boxShadow that is not matching with the current theming borderRadius options. For example, if previous borderRadius = 123px then post migration the JS should be toggled showing 123px.

For all the widgets,
- borderColor should be JS toggled.

@jsartisan 

- Revert icon is changing the position of the properties inside the property pane.

**Comment by somangshu** [comment]
### Release planning

- [ ] 1. Table widget & JSON Form migrations in progress @keyurparalkar - 2 - 31st March
    - [ ] Config change PR to be merged into release @jsartisan > this will be required for testing the migration on button group, table, JSON form - 30th March
        - [ ] `QA` Button group, Table, JSON form migration needs testing - 5th - 6th Apr
- [ ] QA bugs reported by Shwetha @jsartisan - 31st March
- [ ] JSON Form compatible with theming - @ashit-rath - 30th March
- [ ] Table widget compatible with theming -  @jsartisan - 1st Apr
- [ ] PR review - @ashit-rath - 4th Apr
- [ ] @ashit-rath discuss #11913 with Favour and move forward by End of this week
- [ ] `QA` - JSON Form, Table Widget, Button Group, Pending Bugs - 7th - 8th Apr

11th Release we will skip, Address any feedbacks, Merge by **_13th Apr 2022_**

**Comment by jsartisan** [comment]
Plan of action is:
- to finish all QA bugs + Table widget + Button group updates by Wednesday @jsartisan 
- to complete everything around migration and get migration tested from QA. There might be few edge cases around JSON_FORM that can stretch upto thursday/friday @keyurparalkar @shwetha-ramesh . 
- to complete all the updates required on JSON_FORM to make it work with theming - @ashit-rath 
- to start verifying all the pending QA bugs on thursday @shwetha-ramesh 
- to start peer code review on Thursday on the PR @ashit-rath @jsartisan 
- to check cypress test results and close if there is any issue in that on monday/tuesday @keyurparalkar @jsartisan 

The plan is to get theming merged into release by April 13th. Right now, there are no blockers that we know of. Will update the thread if any blocker is encountered.

cc: @somangshu @dilippitchika

**Comment by somangshu** [comment]
Release plan:

Development
- [ ] Fix conflict from input widget changes @jsartisan - 18th Apr
- [ ] Few bugs around table and json form @jsartisan @ashit-rath - 19th Apr
- [ ] Check cypress test @jsartisan, Fix any failing tests - 21th Apr
- [ ] QA Callouts on migration; 90% complete and 10% remaining @keyurparalkar - 20th Apr
- [ ] Any callouts from the current migration testing - JSON form, Table, Button group - @jsartisan @keyurparalkar 26th Apr


QA - 
- [ ] Verify all issue that are done @shwetha-ramesh @jsartisan  - 21st Apr
- [ ] Migration not yet tested on button-group, Table, JSON Form @chandannkumar @shwetha-ramesh @btsgh - 20th Apr
- [ ] QA callouts fixed by Keyur need to be verified (44 reported issues) @shwetha-ramesh @btsgh - 22nd Apr
- [ ] Regression Testing on theming after all issues are verified - 27th Apr

Release date - **28th to 30th Apr**

**Comment by shwetha-ramesh** [comment]
**QA update 21/04**  @somangshu 
Migration on ButtonGroup, Table & JSON form is comepleted. Raised few issues. @chandannkumar @btsgh - Completed on 20 April
As of 21 Apr @btsgh is looking at dp bug verification & @shwetha-ramesh looking at migration bug verification.

**Comment by jsartisan** [comment]
**Dev update 21/04 @somangshu** 

- Fixing every callout being made while QA is doing dp bug verification. 
- Will be checking cypress tests today
- I will be checking callouts made by QA on the migrations side tomorrow.

This time I don't see any blocker. Everything is going as planned.

**Comment by shwetha-ramesh** [comment]
QA update 22/04 @somangshu @btsgh @chandannkumar cc: @vivekverma2312 

* Re-tested all bug fixes  on DP  - left few comments for dev
* Re-tested all migration bug fixes  - left few comments for dev

Pending
* Awaiting bug fixes for Migration issues for  buttongroup, table, Json.
* Awaiting few bug fixes on DP
* Regression after all bug fixes.

**Comment by dilippitchika** [comment]
Had a founders discussion today on the theme flow, here are a list of changes we will be doing. All of these are small changes in the UX we will do

### Editing themes
1. Current theme will be in expanded state by default
2. A user can click on a button on the current theme to start customising the theme rather than having to click back.
3. Back button will still be there because if the user doesn't make any selection on theme they can go back

### Change theme button
1. Change theme will be shown on hovering the card rather than an explicit button

### Font hierarchy in the page 
1. What should be the font size for the "Theme properties" heading vs customisation options

### Font names
1. We will use small, medium and large as the font sizes instead of sm, base and lg
2. Regarding font names for xl, 2xl, 3xl - I will add the new names here

### Text wiget
1. Text widget needs to show the orange dot if it has deviated from the theme

### Color picker
1. If color picked in the color picker is not a valid hex, we default to white but it's not reflected in the color picker's selected color.

**Comment by dilippitchika** [comment]
@jsartisan regarding few items above

Font hierarchy in the page - I don't think we need to solve it, just removing the button is solving it for us 
![Screenshot 2022-04-27 at 4 09 06 PM](https://user-images.githubusercontent.com/19730984/165502387-1fc8b026-5208-47cd-b891-1b2ad3453389.png)

Font names
Here's the suggested font names
![Screenshot 2022-04-27 at 4 17 31 PM](https://user-images.githubusercontent.com/19730984/165502438-a88548ec-987a-4662-a528-288ba454fe41.png)

**Comment by shwetha-ramesh** [comment]
@jsartisan @keyurparalkar @dilippitchika @somangshu After regression bug verification theming looks good. Moving this to DONE.
cc: @btsgh @vivekverma2312

**Comment by jsartisan** [comment]
Closing as it is merged.
