### ISSUE TITLE
DR: Git flow for default resources, end to end.

### ISSUE THREAD

**Issue by sondermanish** [appsmithorg/appsmith#34091]
```[tasklist]
### Tasks
- [x] Commit-artifact
- [x] Checkout branch
- [x] Checkout remote branch
- [x] create branch
- [x] connect to git
- [x] import from git
- [x] discard
- [x] pull
- [x] push
- [x] List and update branches
- [x] Get/Update protected branches
- [x] delete branch
- [x] disconnect git artifact
- [x] fetch remote
- [x] git status
- [ ] autocommit
- [ ] merge
- [ ] merge status
- [ ] Fix test cases
- [x] Git profiles CRUD
- [ ] Set Default branch in EE
```
