### ISSUE TITLE
[Task]: Tag exported partial apps with the layout system type

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#34160]
### SubTasks

- [ ] When importing a partial app into an incompatible layout system, we risk breaking systems. So, if a widget is added to an export, the layout system should also be tagged along with the exported json.
- [ ] When importing a partial app, we need to make sure that the layout systems of the target app is compatible with the one being imported.
- [ ] This check is not necessary if no widgets are being exported.
