### ISSUE TITLE
[Task]: Disable Git for Anvil applications

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#34163]
### SubTasks

- [ ] Git has multiple issues with Anvil apps. For this we need to remove the Git features for Anvil applications.
- [ ] We cannot integrate an Anvil application with Git.
- [ ] We cannot import an Anvil application with Git.
