### ISSUE TITLE
[Task]: Update Query form configs to use the Responsive Zones and Sections

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#34323]
Update the form configs to match the organisation done in the designs here:
https://app.zeplin.io/project/6683c698d2210f2b0697d978/dashboard

## Checklist
- [ ]  Add `SECTION_V2`, `SINGLE_COLUMN_ZONE`, and `DOUBLE_COLUMN_ZONE` as per design.
- [ ]  Check and remove custom styles if it defies new section and zone component styles.
- [ ]  Ensure the identifiers are added for sections and zones as it is important for conditional statements to work.
- [ ]  When removing an old section, ensure that its conditions are accurately transferred and incorporated into the new zones and sections.
- [ ]  All fields/form controls should be inside either a `SINGLE_COLUMN_ZONE` or `DOUBLE_COLUMN_ZONE` .
- [ ]  Verify the integrity of the migration by comparing it with the production before committing the code.

```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith/issues/35509
- [ ] #35494
- [ ] https://github.com/appsmithorg/appsmith/issues/36499
- [ ] #35503
- [ ] https://github.com/appsmithorg/appsmith/issues/35545
- [ ] #35496
- [ ] #35497
- [ ] #35500
- [ ] #35495
- [ ] #35484
- [ ] #35485
- [ ] #35487
- [ ] #35488
- [ ] #35489
- [ ] #35490
- [ ] #35491
- [ ] #35492
- [ ] #35493
- [ ] #35483
- [ ] #35498
- [ ] #35499
- [ ] #35501
- [ ] #35502
- [ ] #35504
- [ ] #35505
- [ ] #35506
- [ ] #35486
- [ ] https://github.com/appsmithorg/appsmith/issues/36326
- [ ] https://github.com/appsmithorg/appsmith/issues/36587
```
