### ISSUE TITLE
[Task]: Git default resources git refactor bugs:

### ISSUE THREAD

**Issue by sondermanish** [appsmithorg/appsmith#34391]
## Description
- Anticipating bugs after the git service refactor for default resource adaptibility

```[tasklist]
### Tasks
- [ ] Git sync Ids are getting overwritten for queries, after a branch checkout
- [ ] Can't connect an application with Private repository in git
- [ ] checkout branch failure file locks
```
