### ISSUE TITLE
[Task]: Separate New and Classic applications in a workspace

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#34576]
### SubTasks

- [ ] If the Anvil toggle is enabled, users should see two sections within the workspace. 
- [ ] The New, Anvil, applications shall be listed first and the Classic Fixed mode applications will be listed second
- [ ] All relevant copies in the empty state or otherwise needs to be updated to properly represent the state of the system.
- [ ] Show Anvil alpha badge on the “New Applications” heading to represent the apps being Anvil applications.
