### ISSUE TITLE
[EPIC]: Actions redesign

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#34663]
### Designs

https://www.figma.com/design/8L9BXMzNTKboGWlHpdXyYP/Appsmith-IDE?node-id=174-9578&t=gd2Tcqe4snbtB0nb-0

https://app.zeplin.io/project/6683c698d2210f2b0697d978/dashboard

[UQI](https://www.notion.so/appsmith/Unified-Query-Interface-UQI-459647c7d3414d899d797f702ebf7054)

```[tasklist]
### UQI Updates
- [ ] #34319
- [ ] https://github.com/appsmithorg/appsmith/issues/35214
- [ ] https://github.com/appsmithorg/appsmith/issues/35544
- [ ] https://github.com/appsmithorg/appsmith/issues/35799
- [ ] #34322
```

```[tasklist]
### UQI config updates
- [ ] #34323
```

```[tasklist]
### Modularisation
- [ ] #34324
- [ ] #34672
- [ ] #36152
- [ ] #36153
- [ ] #36154
- [ ] #36155
- [ ] https://github.com/appsmithorg/appsmith/issues/36345
- [ ] https://github.com/appsmithorg/appsmith/issues/36344
- [ ] https://github.com/appsmithorg/appsmith/issues/36439
- [ ] https://github.com/appsmithorg/appsmith/issues/36438
- [ ] https://github.com/appsmithorg/appsmith/issues/36498
- [ ] https://github.com/appsmithorg/appsmith/issues/36624
- [ ] https://github.com/appsmithorg/appsmith/issues/36644
- [ ] https://github.com/appsmithorg/appsmith/issues/36645
- [ ] https://github.com/appsmithorg/appsmith/pull/36800
- [ ] https://github.com/appsmithorg/appsmith/issues/36802
- [ ] https://github.com/appsmithorg/appsmith/issues/36793
- [ ] https://github.com/appsmithorg/appsmith/issues/36898
- [ ] https://github.com/appsmithorg/appsmith/issues/36964
- [ ] https://github.com/appsmithorg/appsmith/issues/37096
- [ ] https://github.com/appsmithorg/appsmith/issues/37076
- [ ] https://github.com/appsmithorg/appsmith/issues/37701
```

```[tasklist]
### Toolbar Updates
- [ ] #29957
```

```[tasklist]
### Tabs
- [ ] #32440
- [ ] https://github.com/appsmithorg/appsmith/issues/36968
```

```[tasklist]
### Bottom pane
- [ ] https://github.com/appsmithorg/appsmith/issues/35289
- [ ] https://github.com/appsmithorg/appsmith/issues/35290
```

```[tasklist]
### Misc
- [ ] #34321
```

```[tasklist]
### Cleanup
- [ ] https://github.com/appsmithorg/appsmith/issues/38630
```
