### ISSUE TITLE
[Task]: Run same case for N number of times with CI command

### ISSUE THREAD

**Issue by sagar-qa007** [appsmithorg/appsmith#34840]
### SubTasks

- [ ] Research on CI for running test case
- [ ] Research on how to run same command multiple time.
- [ ] Incorporate with repository configuration
- [ ] Test setup on CE repository.
- [ ] Test setup on EE repository.

**Comment by sagar-qa007** [comment]
Shift to PMS
