### ISSUE TITLE
[Task]: Fix and Enable Git for Anvil Apps

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#35101]
### SubTasks

- [ ] Resolve various issues that result in Anvil apps breaking for Git.
- [ ] Resolve connecting Anvil apps to Git
- [ ] Resolve importing Anvil apps from Git
