### ISSUE TITLE
[Task]: Update the event ExecuteAction to include new properties about bindings

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#35291]
### SubTasks

- [ ] Include the `request` parameter for all execute action events (currently it isn't firing for anonymous users)
- [ ] Add a new property which shows all the parameters. This should be an array for instance:  {{Table1.pageSize}}, {{Table1.pageOffset}},{{Select1.selectedOptionValue}}
- [ ] Have a new property which shows the raw query without the substitutions. For instance: `SELECT * FROM TABLE WHERE country =  {{Select1.selectedOptionValue}}`, along with request, which currently returns: `SELECT * FROM TABLE WHERE country = "China"`

### Why?
If we look at the queries users are writing, it can be a great indicator of what progress they are making in their app. For instance, if they are using the pageSize and pageOffset property in a select query, they are doing server side pagination. This will allow us to measure:
(a) How many users are progressing through their app building journey
(b) Are we noticing patterns of what order users are building out this functionality
(c) What stage do users get to before they get stuck, or lost

All these tracking can be added to the same `Execute Action` event already present in the backend.
