### ISSUE TITLE
[Task]: Do not  override types for reducers where it could be self referred l

### ISSUE THREAD

**Issue by rishabhrathod01** [appsmithorg/appsmith#35617]
### SubTasks

- [ ] Enable createReducer and createImmerReducer to support generic types
- [ ] Remove overriding of types in reducers ( 5 per PR )
- [ ] Remove AppState type import from selectors and let the type be self-inferred for store
