### ISSUE TITLE
[Task]: Drag and Drop on large screens

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#35621]
### SubTasks

With the recent new feature where we can set a static widths of the apps in Anvil. Further changes become necessary.
- [ ] Drag and Drop test updates to test on large viewports. This works today because the cypress browser viewport is small enough to prevent any dead space between the left and right panels and the canvas.
- [ ] Snapshot tests for large viewports. This works for the same reasons as above (I assume)
- [ ] Signifier for the drop area. When dragging a new widget in large viewports, there is substantial dead space where no highlights are show. This can be a DX issue and should be handled.
