### ISSUE TITLE
Bug: Document viewer widget unable to load base64 file >2MB

### ISSUE THREAD

**Issue by rahulbarwal** [appsmithorg/appsmith#35917]
The user is not able to display larger files in the Document Viewer widget. Note that the file is < 5 MB and not converted to blob, so we expect it to display.

[Slack Message](https://theappsmith.slack.com/archives/C0341RERY4R/p1724403110243859?thread_ts=1721337572.699409&cid=C0341RERY4R)

Steps:

Add a file picker widget
Add a document viewer & bind the Document link property to Filepickers data.
Try selecting a pdf file >2MB in size.
Actual: Document viewer breaks.
Expected: Document viewer should load the file

[Sample production app](https://app.appsmith.com/app/document-viewer-issue/page1-66cea1289e0a425810b6f319/edit/widgets/laz0no2sna)
```[tasklist]
### Tasks
- [ ] Find out alternatives that don't add too much bundle size.
- [ ] Do a POC and get product and design inputs
- [ ] Ensure enough Unit tests are for the new document viewer.
```

**Comment by rahulbarwal** [comment]
The problem is with [`react-documents` package](https://www.npmjs.com/package/react-documents), which is not being maintained properly, it was last published 2 years ago.

we need to try alternatives to it which will lead to design/product changes and will have an impact on bundle size of our client.

[An example alternative](https://www.npmjs.com/package/@cyntler/react-doc-viewer) which is large in size :(

**Comment by tmerrill-BCOE** [comment]
I am facing this issue. Please don't close it.

**Comment by tmerrill-BCOE** [comment]
I just wanted to see if any progress has been made on this issue. I have entered beta testing on the app I built and I would love for this functionality to work.

**Comment by mike-gigs** [comment]
To add to this since I haven't seen it mentioned, this issue seems to only be present in Chrome. In my testing, files around 1.6mb in size fail in Chrome, the largest file I tested in Firefox was 13.6mb which worked without issue.
