### ISSUE TITLE
[Task]: Create a test setup for prod data

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#36060]
### SubTasks

- [ ] Create a prod DB dump
- [ ] Migrate the data to Postgres RDS instance and make sure to keep the location in Mumbai region (close to VM machine on which Appsmith will be hosted)
- [ ] Start the Appsmith instance that supports Postgres DB and use the DB created in step 2
