### ISSUE TITLE
[Task]: Update xpath locator for the mongodb related spec

### ISSUE THREAD

**Issue by sagar-qa007** [appsmithorg/appsmith#36230]
### SubTasks

- [ ] app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/Mongo_Spec.ts
- [ ] app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/MongoURI_Spec.ts
- [ ] app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/MySQL1_Spec.ts
- [ ] app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/MySQL2_Spec.ts
- [ ] app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/Postgres1_Spec.ts
- [ ] app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/Postgres2_Spec.ts
- [ ] app/client/cypress/e2e/Regression/ServerSide/QueryPane/Mongo1_spec.ts
- [ ] app/client/cypress/e2e/Sanity/Datasources/MsSQL_Basic_Spec.ts
