### ISSUE TITLE
[Task]: GraphQL form render function

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#36624]
### SubTasks

- [x]  Render the common editor form
- [x]  Handle resize of body editors (query variables)
- [x]  Define the Pagination UI Component
