### ISSUE TITLE
[Task]: Handle running the action

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#36644]
### SubTasks

- [ ]  Same in modules
- [ ]  Same in workflows
- [ ]  Log analytics when Run button is clicked
    - [ ]  Changes for modules and workflows here
