### ISSUE TITLE
[Task]: Check if your repository is affected by licence change of TinyMCE 

### ISSUE THREAD

**Issue by like-a-bause** [appsmithorg/appsmith#36859]
### SubTasks

Hey. 
TinyMCE which gets used by RichTextEditor Widget recently changed their licence from MIT to GPL.
See https://github.com/tinymce/tinymce/issues/9453#issuecomment-2327646149 for reference. Since GPL is copyleft this could have implications on your business (I am not a lawyer). I would suggest the following actions:

 - [x] Check if this affects your product, business etc.
 - [x] Check what you can do immediately to mitigate ( e.g. pin the last version that was shipped with MIT )
 - [ ] Add a License scan workflow so something like this doesn't go unnoticed

**Comment by carinanfonseca** [comment]
Thank you so much, @like-a-bause, for bringing this to our attention. We are ensuring that we use a version that is fully compliant with the MIT license. Additionally, we will explore alternative solutions to ensure that Appsmith users can continue to use the RichTextEditor in a secure and up-to-date manner.

**Comment by rahulbarwal** [comment]
Opening this issue to track the last task.

**Comment by like-a-bause** [comment]
Pinging here as well, this happened again: https://github.com/appsmithorg/appsmith/issues/40365
