### ISSUE TITLE
[Task]: Test cases for action selector: removeValue()

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#37159]
### SubTasks

refer [here](https://docs.google.com/spreadsheets/d/1Vq5vRUyAMv2npPv4j41omzZrYcRUb8LEOhNVu_O4OE8/edit?gid=1727375547#gid=1727375547&range=A2:A9) for full test case descriptions

```[tasklist]
- [ ] Test the behavior of removeValue() when attempting to remove a key that does not exist in local storage. The function should not throw any errors, and the local storage remains unchanged.
- [ ] Ensure multiple values can be removed sequentially using removeValue().
- [x] Test if a value removed with removeValue() is no longer accessible from the appsmith.store object.
- [ ] Ensure that calling removeValue() with a non-string key (e.g., number or object) fails.
- [ ] Ensure that calling removeValue() on one key does not affect other stored values.
- [ ] Test if removeValue() correctly removes a value even when it was stored with the persist option set to false. The key should be removed, even though it was not persisted across sessions.
- [ ] Test the function using JS Objects as well as the action selector in property pane
- [ ] Test the functionality in deploy mode

**Comment by sagar-qa007** [comment]
Done from my side
