### ISSUE TITLE
[Task]: Test cases for action selector: showAlert()

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#37155]
### SubTasks

refer [here](https://docs.google.com/spreadsheets/d/1Vq5vRUyAMv2npPv4j41omzZrYcRUb8LEOhNVu_O4OE8/edit?gid=1727375547#gid=1727375547&range=A2:A9) for full test case descriptions

```[tasklist]
- [ ] Trigger the action without editing any field in the action selector dropdown - error should be for missing message and not something arbitrary like unexpected token
- [ ] Select alert type without adding any message and execute trigger - no error should be displayed
- [x] In a JS Object set up the showAlert() function & trigger the same using a button (onClick -> execute JS Object)
- [ ] Check different message types works as expected when selected from the dropdown or added through code
- [x] Display the contents of another widget e.g. Text, Input etc. in the message section by binding those widgets.
- [ ] Test the function using JS Objects as well as the action selector in property pane
- [ ] Test the functionality in deploy mode

**Comment by sagar-qa007** [comment]
Done from my side
