### ISSUE TITLE
[Task]: Test cases for action selector: storeValue()

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#37158]
### SubTasks

refer [here](https://docs.google.com/spreadsheets/d/1Vq5vRUyAMv2npPv4j41omzZrYcRUb8LEOhNVu_O4OE8/edit?gid=1727375547#gid=1727375547&range=A2:A9) for full test case descriptions

```[tasklist]
- [ ] Test if storeValue() can store a boolean value in local storage.
- [ ] Ensure that when the persist parameter is set to false, the value is not saved after refreshing the page.
- [ ] Ensure value stored under a key can be successfully overwritten.
- [ ] Test if multiple values can be stored at once using an object.
- [ ] Ensure that calling storeValue() without a key parameter does not store any value.
- [ ] Ensure that calling storeValue() with a non-string key fails. The value should not be stored, and an error should be thrown due to an invalid key type.
- [x] Test if the value stored using storeValue() can be accessed through appsmith.store
- [ ] Test the function using JS Objects as well as the action selector in property pane
- [ ] Test the functionality in deploy mode
```

**Comment by sagar-qa007** [comment]
Done from my side
