### ISSUE TITLE
[Task]: Test cases for action selector: showModal()

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#37156]
### SubTasks

refer [here](https://docs.google.com/spreadsheets/d/1Vq5vRUyAMv2npPv4j41omzZrYcRUb8LEOhNVu_O4OE8/edit?gid=1727375547#gid=1727375547&range=A2:A9) for full test case descriptions

```[tasklist]
- [ ] Ensure that a modal is displayed automatically when the page loads using a JSObject with "Run on Page Load" enabled.
- [ ] Test the behavior when an invalid modal name is provided to the showModal() function. The modal should not open, and an error should be thrown.
- [x] Test if the showModal() function successfully opens the modal when a valid modal name is provided. The modal should open and come into focus.
- [ ] Ensure that the modal remains in focus after it is opened using the showModal() function preventing interaction with the underlying page.
- [ ] Test the function using JS Objects as well as the action selector in property pane
- [ ] Test the functionality in deploy mode

**Comment by sagar-qa007** [comment]
Done from my side
