### ISSUE TITLE
[Task]: Test cases for action selector: navigateTo()

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#37154]
### SubTasks

refer [here](https://docs.google.com/spreadsheets/d/1Vq5vRUyAMv2npPv4j41omzZrYcRUb8LEOhNVu_O4OE8/edit?gid=1727375547#gid=1727375547&range=A2:A9) for full test case descriptions

```[tasklist]
- [x] 1. Add a widget with a trigger field on canvas,2. Select navigateTo from the action selector dropdown syntax on selection : {{navigateTo('Page2', {}, 'SAME_WINDOW');}}
- [x] Trigger the action without editing any field - error should be for missing navigation path and not something arbitrary like unexpected token
- [ ] Remove placeholder for query params and trigger navigation - navigation should happen without throwing error since default values are now added to the syntax
- [ ] Add a widget navigation using URL containing widgetID
- [ ] Add a navigation using URL containing links to third party websites
- [ ] Validate navigation to a hidden page in same as well a new window
- [ ] Test the function using JS Objects as well as the action selector in property pane
- [ ] Test the functionality in deploy mode

**Comment by sagar-qa007** [comment]
Done from my side
