### ISSUE TITLE
[Task]: Test cases for action selector: closeModal()

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#37157]
### SubTasks

refer [here](https://docs.google.com/spreadsheets/d/1Vq5vRUyAMv2npPv4j41omzZrYcRUb8LEOhNVu_O4OE8/edit?gid=1727375547#gid=1727375547&range=A2:A9) for full test case descriptions

```[tasklist]
- [x] Test if the closeModal() function successfully closes an open modal when a valid modal name is provided.
- [ ] Test the behavior when an invalid modal name is provided to the closeModal() function. The modal should not close, and there should be no action and an error should be thrown
- [ ] Test the function using JS Objects as well as the action selector in property pane
- [ ] Test the functionality in deploy mode

**Comment by sagar-qa007** [comment]
Done from my side
