### ISSUE TITLE
[Task]: Test cases for action selector: clearInterval()

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#37166]
### SubTasks

refer [here](https://docs.google.com/spreadsheets/d/1Vq5vRUyAMv2npPv4j41omzZrYcRUb8LEOhNVu_O4OE8/edit?gid=1727375547#gid=1727375547&range=A2:A9) for full test case descriptions

```[tasklist]
- [ ] Ensure that calling clearInterval() stops the interval from executing further.
- [ ] Verify the behaviour while clearing interval using wrong ID. The interval should not be cleared.
- [ ] Verify behavior when calling clearInterval() with an invalid or non-existent ID. No interval should be cleared, and the system should handle the invalid ID gracefully without errors.
- [ ] Verify that multiple intervals can be cleared simultaneously without any issues.
- [ ] Verify behavior when calling clearInterval() multiple times on the same interval.The interval should be cleared the first time, and no errors should occur upon subsequent calls.
- [ ] Verify behavior when clearInterval() is called without an ID.
- [ ] Test the function using JS Objects as well as the action selector in property pane
- [ ] Test the functionality in deploy mode

**Comment by sagar-qa007** [comment]
Done from my side
