### ISSUE TITLE
[Task]: Test cases for action selector: postWindowMessage()

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#37167]
### SubTasks

refer [here](https://docs.google.com/spreadsheets/d/1Vq5vRUyAMv2npPv4j41omzZrYcRUb8LEOhNVu_O4OE8/edit?gid=1727375547#gid=1727375547&range=A2:A9) for full test case descriptions

```[tasklist]
- [ ] Verify that postWindowMessage() can successfully send a message to the parent application’s window.
- [ ] Verify that postWindowMessage() can successfully send a message to a specified iframe embedded within Appsmith.
- [ ] Verify the behavior of postWindowMessage() when sending an empty message.
- [ ] Verify behavior when an invalid or malformed URL is provided as targetOrigin.
- [ ] Test the function using JS Objects as well as the action selector in property pane
- [ ] Test the functionality in deploy mode

**Comment by sagar-qa007** [comment]
Done from my side.
