### ISSUE TITLE
[Task]: Test cases for action selector: resetWidget()

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#37164]
### SubTasks

refer [here](https://docs.google.com/spreadsheets/d/1Vq5vRUyAMv2npPv4j41omzZrYcRUb8LEOhNVu_O4OE8/edit?gid=1727375547#gid=1727375547&range=A2:A9) for full test case descriptions

```[tasklist]
- [x] Verify that a single widget can be reset to its default state.
- [x] Verify that resetting a container widget also resets all child widgets when resetChildren is set to true.
- [x] Verify that resetting a parent widget does not reset its child widgets when resetChildren is set to false.
- [ ] Verify the behavior when an invalid widget name is provided. The function should not reset any widget, and an appropriate error should be logged.
- [ ] Verify the behavior when attempting to reset a widget that has no child widgets, but resetChildren is set to true.
- [ ] Verify behavior when trying to reset a widget that does not exist on the page. No widget should reset, and an appropriate error or message should be logged.
- [ ] Test the function using JS Objects as well as the action selector in property pane
- [ ] Test the functionality in deploy mode

**Comment by sagar-qa007** [comment]
Done from my side
