### ISSUE TITLE
[Task]: Test cases for action selector: action selector

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#37168]
### SubTasks

refer [here](https://docs.google.com/spreadsheets/d/1Vq5vRUyAMv2npPv4j41omzZrYcRUb8LEOhNVu_O4OE8/edit?gid=1727375547#gid=1727375547&range=A2:A9) for full test case descriptions

```[tasklist]
- [ ] Verify that actions can be configured 
- [ ] Verify that callbacks can be configured with a success event
- [ ] Verify that callbacks can be configured with a failure event
- [ ] Verify that callbacks can be chained
- [ ] Verify that callbacks can be deleted
- [ ] Verify that the Callbacks section reflects the number of active callbacks accurately
- [ ] Verify that configured actions on existing apps are intact
- [ ] Verify that configured actions stay intact on import of an app
- [ ] Verify that configured actions stay intact on partial import of a page
- [ ] Verify that configured actions stay intact on forking an app
- [ ] Verify that configured actions stay intact on navigating between pages

**Comment by sagar-qa007** [comment]
Done from my side
