### ISSUE TITLE
[Task]: Test cases for action selector: clearStore()

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#37160]
### SubTasks

refer [here](https://docs.google.com/spreadsheets/d/1Vq5vRUyAMv2npPv4j41omzZrYcRUb8LEOhNVu_O4OE8/edit?gid=1727375547#gid=1727375547&range=A2:A9) for full test case descriptions

```[tasklist]
- [x] Test if the clearStore() function successfully clears all key-value pairs from local storage.
- [x] Test the behavior of clearStore() when no values are stored in local storage. The function should not throw any errors, and local storage should remain empty.
- [ ] Ensure both persistent and session-specific stored values are cleared when clearStore() is called.
- [ ] Ensure that clearStore() only removes values stored by the application and does not affect other unrelated data in the browser's local storage.
- [ ] Ensure that clearStore() only affects the current tab's storage and does not inadvertently impact session storage across tabs.
- [ ] Test the function using JS Objects as well as the action selector in property pane
- [ ] Test the functionality in deploy mode

**Comment by sagar-qa007** [comment]
Done from my side
