### ISSUE TITLE
[Task]: Test cases for action selector: setInterval()

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#37165]
### SubTasks

refer [here](https://docs.google.com/spreadsheets/d/1Vq5vRUyAMv2npPv4j41omzZrYcRUb8LEOhNVu_O4OE8/edit?gid=1727375547#gid=1727375547&range=A2:A9) for full test case descriptions

```[tasklist]
- [ ] Verify that the callback function is executed at regular intervals specified by the setInterval() function.
- [ ] Verify that multiple setInterval() functions can run at the same time.
- [ ] Verify behavior when an invalid callback function is passed to setInterval(). An error should be thrown, and no interval should be set.
- [ ] Verify behavior when an invalid time interval is provided. An error should be thrown, and no interval should be set.
- [ ] Verify that intervals are cleared after a page refresh.
- [ ] Test the function using JS Objects as well as the action selector in property pane
- [ ] Test the functionality in deploy mode
