### ISSUE TITLE
[Task]: Test cases for action selector: download()

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#37161]
### SubTasks

refer [here](https://docs.google.com/spreadsheets/d/1Vq5vRUyAMv2npPv4j41omzZrYcRUb8LEOhNVu_O4OE8/edit?gid=1727375547#gid=1727375547&range=A2:A9) for full test case descriptions

```[tasklist]
- [ ] Test if the download() function downloads query data as a CSV file.
- [x] Test if the download() function correctly downloads a file from a given URL. 
- [ ] Ensure the file downloads correctly without specifying the fileType, but with a file extension in the filename.
- [ ] Test the behavior of the download() function when no file extension is provided in the fileName. The download should fail, or the file should be unusable due to the lack of an extension.
- [ ] Test the download() function when invalid or null data is passed. The download should fail, or an appropriate error message should be logged.
- [ ] Test how the function behaves when an unsupported or incorrect file type is specified. The file should not download, or it should be unusable due to the incorrect file type.
- [ ] Test the download() function when no file name is provided. The download should fail, or the file should have a default or incorrect name.
- [ ] Ensure if the download() function correctly downloads an image file.
- [ ] Test the behavior when the fileType does not match the file extension in the fileName. The file should download but may be unusable due to the mismatch between file extension and type.
- [ ] Test the function using JS Objects as well as the action selector in property pane
- [ ] Test the functionality in deploy mode

**Comment by sagar-qa007** [comment]
Done from my side
