### ISSUE TITLE
[Task]: Test cases for action selector: watchGelolocation()

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#37169]
### SubTasks

refer [here](https://docs.google.com/spreadsheets/d/1Vq5vRUyAMv2npPv4j41omzZrYcRUb8LEOhNVu_O4OE8/edit?gid=1727375547#gid=1727375547&range=A2:A9) for full test case descriptions

```[tasklist]
- [ ] Verify that getCurrentPosition successfully retrieves the current position and automatically updates appsmith.geolocation.currentPosition.coords
- [ ] Verify that calling getCurrentPosition when a geolocation watch is active throws an error.
- [ ] Verify that the error callback is executed when getCurrentPosition encounters an error (e.g., location services disabled or permission denied).
- [ ] Verify that getCurrentPosition correctly handles the options parameter for maximumAge, timeout, and enableHighAccuracy.
- [x] Test the function using JS Objects as well as the action selector in property pane
- [ ] Test the functionality in deploy mode
```

**Comment by sagar-qa007** [comment]
Done from my side
