### ISSUE TITLE
[Task]: Test cases for action selector: stopWatchingGeolocation()

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#37170]
### SubTasks

refer [here](https://docs.google.com/spreadsheets/d/1Vq5vRUyAMv2npPv4j41omzZrYcRUb8LEOhNVu_O4OE8/edit?gid=1727375547#gid=1727375547&range=A2:A9) for full test case descriptions

```[tasklist]
- [x] Verify that geolocation.clearWatch() successfully clears an active geolocation watch.
- [ ] Verify that calling geolocation.clearWatch() when no geolocation watch is active throws an error.
- [ ] Verify that geolocation.clearWatch() allows clearing the current watch, and a new geolocation watch can be started immediately after.
- [ ] Test the function using JS Objects as well as the action selector in property pane
- [ ] Test the functionality in deploy mode

**Comment by sagar-qa007** [comment]
Done from my side.
