### ISSUE TITLE
[Task]: Update functionality for the Custom widget editor using an AI assistant

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#37250]
### SubTasks

- [x] Create a function which allows the response from our AI chat widget to update the HTML, CSS, and Javascript inputs based on the response from the chat widget
- [x] Remove the split view and remove the tabs at the top
- [x] Add one function to post a message to the iframe with the original contents of the widget whenever the editor mode is opened
- [x] Add one function to list the iframe for messages and update the custom widget editor

Example of the chat widget response we expect:
<img width="1482" alt="image" src="https://github.com/user-attachments/assets/5cea1ce9-5630-4069-aa2b-ccbe792d77d1">

Current custom widget editor:
<img width="1482" alt="image" src="https://github.com/user-attachments/assets/7731107f-787f-4a86-8f93-3461bfa598f7">

Removal of the split view:
<img width="1482" alt="Screenshot 2024-11-06 at 2 56 45 PM" src="https://github.com/user-attachments/assets/b01d5b8f-56ad-4117-9620-6a1e7937039a">
