### ISSUE TITLE
[Epic]: Entity Explorer Modularization

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#37342]
All the components below which will not have any business logic in it anymore, needs to be moved to the ADS package. Each of these components should have a **story** added in the **storybook**. And, the old implementations needs to be **replaced** with these new ADS components, keeping the **test ids** intact. 
Checkpoints for all the below tasks:
- Add a Story in storybook
- Replacing old implementation with the new
- Keeping the test ids intact

 **TBD** 
- [ ] UI segment - navigation for add view

 **Designs:** 
https://www.figma.com/design/sz08OJt2VrEgxQ8eToFIqG/ADS2.0---Components?node-id=4759-9383&p=f&t=nBc8TK48V3EneYmY-0

```[tasklist]
### Explorer
- [ ] #37609
``` 

```[tasklist]
### Editor Segments
- [ ] #37612
- [ ] #37614
- [ ] #37611
```

```[tasklist]
### Search & Add bar
- [ ] https://github.com/appsmithorg/appsmith/issues/37888
- [ ] https://github.com/appsmithorg/appsmith/issues/37769
```

```[tasklist]
### Entity List Item
- [ ] #37620
- [ ] https://github.com/appsmithorg/appsmith/issues/37896
```

```[tasklist]
### List View
- [ ] #37615
- [ ] #37616
- [ ] https://github.com/appsmithorg/appsmith/issues/37770
- [ ] https://github.com/appsmithorg/appsmith/issues/38281
```

```[tasklist]
### Replacing current implementations
- [ ] https://github.com/appsmithorg/appsmith/issues/38286
- [ ] https://github.com/appsmithorg/appsmith/issues/38287
- [ ] https://github.com/appsmithorg/appsmith/issues/38288
- [ ] https://github.com/appsmithorg/appsmith/issues/38289
- [ ] https://github.com/appsmithorg/appsmith/issues/38290
```

```[tasklist]
### Editor Tabs
- [ ] #37688
- [ ] #37689
- [ ] #37690
- [ ] #37692
- [ ] #37651
- [ ] #37775
- [ ] #37647
- [ ] #37649
- [ ] #37648
```

```[tasklist]
### Miscellanous
- [ ] #38292
- [ ] #39067
- [ ] #39673
- [ ] #39919
```

```[tasklist]
### QA issues
- [ ] #39589
- [ ] #39602 
- [ ] #39599 
- [ ] #39598
- [ ] #39641
- [ ] #39665
- [ ] #39707
```

**Comment by farzan190** [comment]
design file wants request access

**Comment by ankitakinger** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IDE-Pod-60507ad1d4b98d00150a2858/issues/appsmithorg/appsmith/37342?planning-poker) with Zenhub @alex-golovanov @hetunandu

**Comment by vivek-appsmith** [comment]
One last bug to be resolved before going to prod. Expecting to be done today.

**Comment by ankitakinger** [comment]
This is now completed.
