### ISSUE TITLE
[Task]: Cleanup IDE module

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#37361]
### SubTasks

- [ ] Move the folder inside /modules
- [ ] Move any IDE components inside IDE module
- [ ] Update folder structure for the IDE modules
- [ ] Fix exports of IDE modules
