### ISSUE TITLE
[Task]: Evaluate the difficulty of creating custom integration on Paragon

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#37558]
### SubTasks

- [x] Create custom integration
- [x] Create workflows on top of it
- [x] Test the custom integration using our POC for paragon code.

**Comment by AmanAgarwal041** [comment]
Tried creating a custom integration with :
- Zendesk:
  - While creating a oauth2 authorization encountered one issue <img width="1418" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHpYQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e84d08ccaac88deb7a49b7493356b7cd53349a82/Screenshot%202024-11-19%20at%202.42.57%20PM.png" alt="Screenshot 2024-11-19 at 2.42.57 PM.png" /> . Wasn't able to fix that, which when it was conveyed to the Paragon's team, it was difficult to verify but they provided with a video with oauth authorization working on different integration

- Trello
  - While creating API key authentication, encountered one issue<img width="1418" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUhYQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--747bfc55f7bda9813fe478a7a78cc63134748935/Screenshot%202024-11-21%20at%202.32.16%20PM.png" alt="Screenshot 2024-11-21 at 2.32.16 PM.png" /> . Waiting from the response from Paragon's team to move forward.

**Comment by AmanAgarwal041** [comment]
The POC is completed using Paragon and Appsmith DP.
The integration is created for OpenAI. Here's the loom video for the same :
https://www.loom.com/share/ea139ea8d8b14f1eb38c679e246ae766?sid=d6a98cfc-9423-4fe4-a698-2827bcfb8af8
