### ISSUE TITLE
[Task]: Debugger Quick Fixes

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#37676]
### SubTasks

```[tasklist]
### Errors Tab
- [x] Rename the "Errors" Tab to "Linter"
- [x] Remove PluginExecutionErrors from "Errors" tab
- [x] Update Debug Trigger button by replacing icon and adding "Debug" button text
- [x] Remove the Inspect Element tab
- [x] Reorg errors: All lint errors will be of the form ▶ [Entity]: [Error] where the entity is clickable and navigates to the entity
- [x] The get appsmith support context menu should pre-fill the error in the intercom chat
```

```[tasklist]
### Logs Tab
- [ ] https://github.com/appsmithorg/appsmith/issues/37682
- [ ] https://github.com/appsmithorg/appsmith/issues/37678
- [ ] https://github.com/appsmithorg/appsmith/issues/37679
- [ ] https://github.com/appsmithorg/appsmith/issues/37680
- [ ] https://github.com/appsmithorg/appsmith/issues/37677
- [ ] https://github.com/appsmithorg/appsmith/issues/37681
- [x] The timestamp for console logs should not be hard coded
- [x] The positions of the clear icon and select filter of the logs will be inverted such that it is [Select Filter] [Search bar] [Clear icon]
```

```[tasklist]
### Action Response Tabs
- [ ] https://github.com/appsmithorg/appsmith/issues/37766
- [ ] https://github.com/appsmithorg/appsmith/issues/37834
- [ ] https://github.com/appsmithorg/appsmith/issues/37835
- [ ] https://github.com/appsmithorg/appsmith/issues/37767
- [ ] https://github.com/appsmithorg/appsmith/issues/37836
```
