### ISSUE TITLE
Appsmith Admin controlled RAG upload configuration

### ISSUE THREAD

**Issue by nsarupr** [appsmithorg/appsmith#37754]
Expose an API from backend which can then be used to configure the RAG Upload configurations.
This will include the following activities:
- [x] Backend exposing an API to return the configuration.
- [x] Frontend removing the hard-coded configuration.
- [x] Frontend to consume the exposed API.
- [x] Expose an API from AI server to return the configurations.
- [x] Store the configuration on Database.
- [ ] Create an appsmith application to control the configuration on database.(Optional)
