### ISSUE TITLE
[Task]: Improve visual hierarchy of the IDE navigational elements

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#37881]
### SubTasks

Designs: https://www.figma.com/design/bZjsnswdcTOGwaOLPg7Zhd/Onboarding-flow?node-id=571-67374&node-type=frame&m=dev

- [ ] Update the Sidebar selected and hover colors to be more subtle
- [ ] Move Datasources to the bottom in the App IDE
- [ ] Show tooltip when hovered over Datasources
- [ ] Add icons on segmented header
- [ ] Selected segment should have bold text
- [x] Add hover state for segmented header
