### ISSUE TITLE
[EPIC] Core platform implementation - phase 1

### ISSUE THREAD

**Issue by NilanshBansal** [appsmithorg/appsmith#37917]
### Objective
Enable Appsmith to turn on any integration on the Paragon dashboard

Below are all the milestones for implementing native SAAS integrations in Appsmith using Paragon.

```[tasklist]
### Core platform implementation
- [x] [Implement authentication mech. with Paragon in CS](https://github.com/appsmithorg/appsmith/milestone/52)
- [x] [Creation of a new maven package for external plugin to enable basic display](https://github.com/appsmithorg/appsmith/milestone/54)
- [x] [Display list of integrations in UI](https://github.com/appsmithorg/appsmith/milestone/55)
- [x] [Logic for all functions in the maven package, datasource creation, API action creation, and CS proxy trigger.](https://github.com/appsmithorg/appsmith/milestone/56)
- [x] [Paragon Proxy API response and error handling in CS.](https://github.com/appsmithorg/appsmith/milestone/61)
- [x] [Resolving Known Issues to enable one integration](https://github.com/appsmithorg/appsmith/milestone/66)
- [x] [Enable Usage of Actions Kit API from Paragon](https://github.com/appsmithorg/appsmith/milestone/68)
- [x] [Enable Second Integration (Salesforce) using Paragon](https://github.com/appsmithorg/appsmith/milestone/70)
- [x] [Test Party Issues for Zendesk Integration](https://github.com/appsmithorg/appsmith/milestone/67)
```
([Reference: Paragon Engineering Implementation doc](https://www.notion.so/appsmith/Paragon-Engineering-Implementation-14bfe271b0e280d2848ff44fee2408e0?pvs=25))

### Success Metrics
The ability to successfully activate an integration on the Paragon dashboard and use it in the Appsmith IDE, with 100% functionality validated for at least four integrations: Salesforce, Zendesk, Slack, and JIRA.

### Prioritised User Stories

| User Story    |
| ------------- |
|  As a user, I want to easily find new integrations, so I can quickly explore and choose the one I need. |
|  As a user, I want to authenticate seamlessly with an integration, so I can securely connect my account. |
| As a user, I want to write queries on the datasource, so I can interact with it consistently, like with other SaaS datasources. |
| As a user, I want integrations to perform reliably and maintain high quality, so I can use them confidently without disruptions. |

### RACI matrix

| Role | People |
| ------------- | ------------- |
| Responsible   |   @NilanshBansal @AmanAgarwal041      |
| Accountable   |    @NilanshBansal @AmanAgarwal041 @carinanfonseca            |
| Consulted     | @nerbos @carinanfonseca @Nikhil-Nandagopal, @mohanarpit|
| Informed      |    @areyabhishek        |

**Comment by NilanshBansal** [comment]
Closing this EPIC as all issues are completed. 
cc: @vivek-appsmith @carinanfonseca @appsmithorg/query-widgets-pod
