### ISSUE TITLE
[Epic] Widget Grouping: Phase - I

### ISSUE THREAD

**Issue by marks0351** [appsmithorg/appsmith#3796]
Ability to select multiple widgets.
- [ ] Command-click, Ctrl-click on multiple widgets to select them.

Functions/Actions to allow selecting multiple widgets.

- [ ] Add actions to select multiple widgets.

Ability to unselect all selected widgets.

- [ ] Click outside of the selected widgets or on one of them to deselect all the selected widgets.

- [ ] Add Escape shortcut key to deselect all widgets.

- [ ] Add Ctrl + A, CMD + A to select all widgets on canvas

**Comment by areyabhishek** [comment]
Added some keyboard shortcuts in the above description. Shift+Click, Ctrl+Click
