### ISSUE TITLE
[Task]: Add calendly link for the schedule a call button in the Premium integration modal

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#38262]
### SubTasks

Earlier related issue : https://github.com/appsmithorg/appsmith/issues/37853
- [ ] Currently only the analytic event is fired, we need to open the calendly link as well to let users directly schedule a call.
- [ ] Move the premium datasources list from most popular to saas integrations section
- [ ] Add Slack and Jira in the premium datasources list
