### ISSUE TITLE
[Task]: Move side by side out of beta

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#38305]
### SubTasks

 - [ ] Remove the beta warning for users the first time they move to side-by-side mode
 - [ ] Add a nudge to all existing users (who have had an active account for more than 1 week) to move over to side-by-side mode. This should only be shown once per user. Even if the user has tried out side-by-side mode, they should be given the nudge
 - [ ] for new users, refer to [this document](https://www.notion.so/appsmith/Trigger-based-contextual-nudges-113fe271b0e28011ad07f17265ab8419?pvs=4#113fe271b0e280f6aa97dc936bfa34e8) to determine the criteria to show the nudge 

(beta warning screenshot)
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/c3f9f636-6e26-49d6-bb7f-eaa5eab87c53" />

(side-by-side nudge)
<img width="1125" alt="image" src="https://github.com/user-attachments/assets/f0deaf6b-858f-4e5d-9f11-2bb6257fa7d7" />
