### ISSUE TITLE
 [Enhancement] Platform change to include the DSL in a data structure which allows for tracking and merging changes

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#3915]
We should be handling the undo-redo states from a separate thread to avoid blocking the UI thread while the undo-able DSL is being updated.

Libraries which can be used:
- [yjs](https://github.com/yjs/yjs)
- (optional) Redux in workers to store the DSL
- (optional) Store state in [indexeddb](https://github.com/yjs/y-indexeddb)

Derisk
====
- [ ] yjs undo manager supports redo
- [ ] Performance of undo redo updates on DSL
- [ ] Performance optimizations by using diffs for DSL updates
- [ ] Setting up yjs-indexeddb for persisting state. This includes cache invalidating from the servers.

Tasks
====
- [ ] Setup yjs data structure on page load
- [ ] Function to convert DSL update paths to yjs data structure updates
- [ ] Function to convert yjs undone changes to DSL update paths
