### ISSUE TITLE
[Epic] Widget grouping Phase - II

### ISSUE THREAD

**Issue by marks0351** [appsmithorg/appsmith#4526]
Drag and draw on canvas to select widget in it
- [ ] Ability to draw on the canvas
- [ ] Widgets that fall in the drawn rectangle should be selected.

Multi-Select from Entity Explorer Tree 
- [ ] Cmd + Click on nodes on Entity Explorer to multi-select widgets 
- [ ] Shift + Click on Nodes to all nodes between the present node and last selected node of the same parent.

**Comment by areyabhishek** [comment]
Will the user be able to move widgets around? Even if that causes collisions, we should let the user move widgets in a group.

**Comment by marks0351** [comment]
I did a POC to check the feasibility of moving widgets in groups. we need one more solution by doing some restructuring of the current ways of how we drag and drop to do multi widget drag. we decided to strike off all the feasible features(with solutions or easy solutions) wrt Widget grouping in the first phases and then take up multi widget drag.

**Comment by areyabhishek** [comment]
Understood. So there'll be a phase 3 for widget grouping then?
