### ISSUE TITLE
[Feature] Input widget 2.0

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#4606]
## Summary
The input widget is one of the commonest widgets in use. We can do a large number of variations. Some small, while others deserving their own separate component.

Input properties:
- Placeholder text - This property will populate the placeholder text and work the same as the text property of a textview
- Default text - This property populates the input text widget with text that can be erased or edited
- Label text- This text appears beside or on the top of the input widget
- Tooltip text- Show an explanation
- Error message - This property displays an error when the specified criteria are not met
- Text Type - This property gives the context to the type of textual data.
    - Address
    - Integer
    - Decimal
    - Text
    - Email
    - Password
    - Currency
    - Search
- AutoComplete data - This property specifies a range of values. The value should be maintainable in a list
- Max Chars - This number specifies the maximum number of characters
- Icon - Choose an icon to show in the input field
- Alignment options for the icon
- Auto Focus - This can be a switch and will determine whether the input text will automatically bring up the keyboard and gain focus on load
- Focus Index - This property determines the order of focus when using the tab key

**Comment by somangshu** [comment]
@momcilo-appsmith @areyabhishek 
Note based on the above:

### Low effort:
- [ ] Tooltip text - Helper for input
- [ ] Label text - This text appears beside or on the top of the input widget
- [ ] Auto Focus - This can be a switch and will determine whether the input text will automatically bring up the keyboard and gain focus on load
- [ ] Icon - Choose an icon to show in the input field
- [ ] Icon alignment - `left` or `right`
- [ ] Max Chars - This number specifies the maximum number of characters

### Should be a separate widget:
- [ ] Autocomplete

### Needs Triaging:
- [ ] Focus Index - This property determines the order of focus when using the tab key

### Needs clarity:
- [ ] Input type `search` - what is the intent here?

### Already available:
- Default text - This property populates the input text widget with text that can be erased or edited
- Error message - This property displays an error when the specified criteria are not met
- Placeholder text- This text is pre-filled in the input field and disappears on focus
- Input type - email, password, text, number (integer & decimal)

We can pick up low effort right away. Let me know what you guys think.

**Comment by momcilo-appsmith** [comment]
@somangshu I agree
