### ISSUE TITLE
Widget Grouping - DND Multiple widgets

### ISSUE THREAD

**Issue by marks0351** [appsmithorg/appsmith#5017]
- [ ] DnD re-architecture - use html canvas as an overlay over the appsmith canvas for dropzones (Needs POC)
     - [ ] Allow any set of widgets to be shown as dragging
     - [ ] Algo: Allow collision detection for multiple rectangles
     - [ ] Out of bounds calculation for multiple rectangles
     - [ ] Size updates when changing parents while dragging for multiple widgets
- [ ] Implement multiple widget drag and drop
- [ ] Drag and scroll the canvas
- [ ] drag and increase container height wrt the last widget(in terms of position) being dragged.
