### ISSUE TITLE
[Performance] Optimise CodeMirror mount time

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#5402]
## Description
Codemirror is used for our code editors all over the app and most of the times we load multiple small editors on a single page. This slows down the loading of the whole pane where there are too many editors already.

### Tasks
- [ ] Improve mount by moving expensive operations to `finishInit` event of Codemirror
- [ ] Improve style loading to avoid browser re-calculating styles repeatedly.
- [ ] Create a Shared Tern Server and divide up defs per entity
