### ISSUE TITLE
Add validations for each form element component

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#5702]

**Comment by rohan-arthur** [comment]
details [here](https://docs.google.com/document/d/1E-3fc3xSk0aQ4r6iOlz9nFtuqUeozsyFuDOaD5dcSDQ/edit#). 

Here are the issues:

- [ ] Extracting requirements from JSON #10230
- [ ] Supply config to validations service #10231
- [ ] Implementing types of validations #10232
- [ ] Show errors #10233
- [ ] DynamicTextControl and DynamicInputTextControl #10234
- [ ] Backend Changes and Migration #10235
