### ISSUE TITLE
[Bug][deploy preview-6264]The Generate page issue for S3 datasource 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6419]
## Description
The Generate page issue for S3 datasource 
[What happened]

- [ ] The bucket list should be displayed with a bucket name which has access #6529
- [x] In the quick wizard page The region dropdown should be displayed so based on the region selected the bucket list should be filtered #6529
- [x] The error is displayed inside the Add file button **pending fix**
- [ ] The select file button is retained with the "1 file selected " text when the user try to select the second file #6492
- [ ] When the Page is autogenerated the error is displayed in the debugger section #6493 
- [ ] When the user search for the file name or a folder name which is not there in the list the error is displayed in the debugger #6494 
- [x] Download the image with the Png extension then open the downloaded image the error is displayed **Tested ok**
- [x] When the user upload a file other than Image and try to download it the Application breaks **Tested ok**
- [x] Deleting table entry does not remove it from the table **Tested ok**
- [x] Include an option to delete individual files during multi-file upload **Cannot be implemented in this release**
- [x] Single file upload failure during multi-file select currently fails the entire upload attempt and provides no option to delete failed files **Cannot be implemented in this release**
- [x] Multi-file upload of pdf/docx is failing (can't be queried or downloaded) but shows a success message when upload button is clicked **Tested ok**
- [x] PDF/Docx files are not uploaded with file extension so any file download is without a file extension **Tested ok**
- [x] When file type is docx or pdf, table entry of object name is null and cannot be queried **Tested ok**
- [x] [Bug] Option to delete failed file upload must be provided for S3 generate page template #6398 **Work around provided. Tested ok**
- [x] Download button's text is not completely visible on lower resolution screen, i.e. text is not displayed properly on the button
- [x] [Bug][Deploy Preview] The update fails in s3 generate page when the user tries to update an image for the file which is of a different file type #6530 **Tested ok**
- [ ] #6771

### Important Details

- Version: [Cloud ]
- OS: [.MacOSX, Win10]
- Browser [ chrome, ]
- Environment [deploy preview]

**Comment by Rishabh-Rathod** [comment]
> 1.  The bucket list should be displayed with a bucket name that has access.

@abhvsn  Is it possible to get details about bucket's permission is accessible?

> 2. In the quick wizard page the region dropdown should be displayed so based on the region selected the bucket list should be filtered.

@RakshaKShetty  AFAIK about the current implementation, the S3 datasource config already has a region field and appsmith doesn't allow multiple region support in a single S3 datasource. Assuming this to be true then, to select other regions user might need to create a separate S3 datasource.

**Comment by Nikhil-Nandagopal** [comment]
@RakshaKShetty 
> * [ ]  The bucket list should be displayed with a bucket name that has access
Which buckets are shown where we don't have access?
> * [ ]  In the quick wizard page The region dropdown should be displayed so based on the region selected the bucket list should be filtered
The datasource has the region already so the buckets only for that region should already be showing
> * [ ]  The select file button is retained with the "1 file selected " text when the user try to select the second file
Not related to this project. This is a general problem with file pickers. Please log it separately
> * [ ]  When the Page is autogenerated the error is displayed in the debugger section
The errors here are related to the list so please log it wrt the list
> * [ ]  When the user search for the file name or a folder name which is not there in the list the error is displayed in the debugger
Same, its related to the list
> * [ ]  Inside the Upload file pop up the added images displayed
Can you explain this?
> * [ ]  Add option to filter bucket on the template
This is not expected. The template is for a single S3 bucket

**Comment by RakshaKShetty** [comment]
@Nikhil-Nandagopal 
Inside the upload file pop up the added images displayed even after successful upload of the file
if You see in the screenshot i had uploaded the file but again when i click on Add file button the image is retained 
![image](https://user-images.githubusercontent.com/45958978/128688933-3fe2de39-9552-44c5-819d-16dc70607180.png)

**Comment by Nikhil-Nandagopal** [comment]
@RakshaKShetty that is because the added file is in the filepicker. It's related to the issue where filepicker does not get reset

**Comment by Rishabh-Rathod** [comment]
> - The error is displayed inside the Add file button
> - The select file button is retained with the "1 file selected " text when the user tries to select the second file

Related to List Widget, can be created as a separate issue for List widget.

**Comment by Rishabh-Rathod** [comment]
@Nikhil-Nandagopal 
Can we disable pdf and Docx files till issues for them aren't resolved?

> - Multi-file upload of pdf/docx is failing (can't be queried or downloaded) but shows a success message when upload button is clicked
> - PDF/Docx files are not uploaded with file extension so any file download is without a file extension
> - When file type is docx or pdf, table entry of object name is null and cannot be queried

**Comment by Rishabh-Rathod** [comment]
All the non-ticked issues are created as separate issues.
