### ISSUE TITLE
[Bug] JS Editor Autocomplete issues

### ISSUE THREAD

**Issue by ApekshaBhosale** [appsmithorg/appsmith#7712]
### Done
- [x] #9692
- [x]  https://github.com/appsmithorg/appsmith/issues/7612
- [x] The JS static values do not show up in the autocomplete for the best match

### Features
- [ ] Autocomplete for JS function arguments #4789
- [ ] Autocomplete for JS function arguments 2 #10578
- [ ] The JS functions do not show up in autocomplete for the best match (to be discussed) Dependant on https://github.com/appsmithorg/appsmith/issues/9480

### Need to Fix
- [ ]  ~Need to be able to access outer objects in the callback of a run function~ (Need to be fixed separately)
- [ ] ~Autocomplete doesn't work inside map functions~ It does work in case array of object which is mapped should have definition. Please correct if any edge case is missed. 
- [ ]  ~Undefined is a function in the autocomplete and add ()~ Checked latest version undefined is correctly shown as undefined
- [ ]  Autocomplete not opening on tab+space sometimes (check commands)

**Comment by Rishabh-Rathod** [comment]
Closing above issue as all unclosed issue are tracked separately.
