### ISSUE TITLE
[Feature] Improve the Guided Tour for new developers

### ISSUE THREAD

**Issue by Debsourabh** [appsmithorg/appsmith#7758]
## Objective
Improve the guided tour for new users

## Problems to solve
1. Improve Discovery of Guided Tour
2. Explain core concepts better

## Solution
The guided tour will take users through the journey of building a customer support dashboard. The tour will focus on 
- Fetching data & binding it to a widget
- Accessing widget properties or states
- Triggering Queries from widgets

## Success
- Developers taking the guided tour should have 2x better retention than those who don't
- Developers should be able to complete the guided tour on their own

## Context
- Painting a story is important. The tour should give people a clear picture of what they are doing
- Positive reinforcement is important. The tour should make people feel like they are achieving something

## Design File
https://www.figma.com/file/iABPoDneYyyKasVz9bRGRx/New-FTU-OB-Experience?node-id=346%3A11220

## Deploy Preview
https://appsmith-jen6z4jzt-get-appsmith.vercel.app/

## RACI
| ------------- | ------------- |
| Responsible   | @akash-codemonk , @RoopKrrish9696  |
| Accountable   | @RoopKrrish9696  |
| Consulted     | @Nikhil-Nandagopal, @areyabhishek, @aakashDesign |
| Informed      | @hiteshjoshi, @sbalaji1192 |

**Comment by Nikhil-Nandagopal** [comment]
Next Actions Items:
- @RoopKrrish9696 to come back with high fidelity designs next week

**Comment by RoopKrrish9696** [comment]
Research regarding FTU OB can be found here https://appsmith.notion.site/First-Time-User-On-Boarding-94f4b32151c74d97a15a04ab86be6045

**Comment by RoopKrrish9696** [comment]
**First draft Figma Links:**

1. Design Link: https://www.figma.com/file/iABPoDneYyyKasVz9bRGRx/New-FTU-OB-Experience?node-id=658%3A29727
2. Prototype Link : https://www.figma.com/proto/iABPoDneYyyKasVz9bRGRx/New-FTU-OB-Experience?page-id=490%3A12080&node-id=658%3A29727&viewport=324%2C48%2C1.02&scaling=min-zoom&starting-point-node-id=658%3A29727

**Next Action Items:**

@RoopKrrish9696 
1. Update the flow on basis of new feedback 
2. Finish the starting and ending of the Welcome Tour - How they will discover welcome tour , What happens once the tour ends?

@akash-codemonk 
1. Figure out how much Backend support is needed
2. Breakdown of tasks and estimates

**Comment by Nikhil-Nandagopal** [comment]
@RoopKrrish9696 also to figure out how we can incorporate autocomplete in the flow

**Comment by RoopKrrish9696** [comment]
**Final Flow & UI Link ( In progress - signing off content & UI )**
https://www.figma.com/file/iABPoDneYyyKasVz9bRGRx/New-FTU-OB-Experience?node-id=1221%3A36301

**Deploy Preview Link from ( Started off with basic flow )**
https://deploy-preview-9125--appsmith-editor-ce.netlify.app/

**Next Action Items:** 

@RoopKrrish9696 @areyabhishek  to finalise content & UI , and share developer handoff

@akash-codemonk to finish off all the steps in the tour for the deploy preview above.

**Comment by RoopKrrish9696** [comment]
**Next Action Items:**

@RoopKrrish9696 to share the developer handoff

@akash-codemonk to polish the deploy preview shared ( https://deploy-preview-9125--appsmith-editor-ce.netlify.app/ )

@ramsaptami to draft a test plan for welcome tour

**Comment by RoopKrrish9696** [comment]
**Developer Handoff Link:**

https://www.figma.com/file/yPl21EAM7iGPVMMe4NGFTS/New--Guided-Tour-Experience?node-id=2%3A1

**Comment by akash-codemonk** [comment]
Additional feedback and bugs

- [ ] Stars in the ratings color to be altered
- [ ] Jetbrains font to be used wherever the "moustache syntax" is written (will be updated on figma as well)
- [ ] Progress bar time should be reduced (will be updated on figma as well)
- [ ] Indicators missing at some places
- [ ] Indicator position to be fixed ( mostly on the right )(will be updated on figma as well)
- [ ] Button text should be "Click to update " by default
- [ ] Analytics for each step and end tour
- [ ] Analytics for rating
- [ ] mark only the id, name, email, country fields as visible in the CustomerTable during onboarding
- [ ] The details container is slightly misaligned with the table, it needs to move a little higher
- [ ] The customer update form text should be of size H2 and other container styles
- [ ] rectangular border indicator should reposition

**Comment by RoopKrrish9696** [comment]
**Next Action Items:**

@akash-codemonk to fix the minor bugs and update the DP

@ramsaptami Testing required from the QA team

**Comment by akash-codemonk** [comment]
Analytics events
 - [ ] WELCOME_TOUR_CLICK(event exists already): When the user clicks on welcome tour
 - [ ] GUIDED_TOUR_REACHED_STEP: When the user reaches a step. For e.g when the user finishes  step 2 and goes to step 3, this event is fired with params 
     ```
     {
          step: 3,
     }
      ```
- [ ] END_GUIDED_TOUR_CLICK: When the user clicks on the end tutorial button.
- [ ] GUIDED_TOUR_RATING: When the user choses a rating. E.g params
   ```
    {
      rating: 5,
    }
   ```
