### ISSUE TITLE
Appsmith Hacktoberfest! Help us fix bugs, improve code, make new features, write examples and many more!

### ISSUE THREAD

**Issue by vihar** [appsmithorg/appsmith#8168]
Hey Contributors 👋🏻 !

We're back again this year for an exciting month-long virtual festival supporting open-source projects. We love it because it's celebratory and community-oriented! 

This issue tracks all the engineering, design, content-related ideas, issues and contribution guidelines to help you get started with Appsmith and Hacktoberfest!

Before contributing to Appsmith, please fill out the form [here](https://app.appsmith.com/applications/6152d7065566f37f8ac7a416/pages/6152d7065566f37f8ac7a418) so that we will make sure that the swag reaches you correctly. We highly recommend you to follow these [guidelines](https://github.com/appsmithorg/appsmith/blob/release/contributions/CodeContributionsGuidelines.md) for code related issues and [these](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md) for content-related issues. 

> Before working on an issue, please discuss it with the maintainer and get it assigned to you 😄 

This can be a great way to get started with Appsmith and contribute to our fantastic open-source project.

Feel free to share more feature requests and content ideas as a comment on this issue.

## Good First Issues / Bug Fixes / Code Improvements 

If you're new to Appsmith and Hacktoberfest, this is the best place to start with; we have a bunch of [good-first-issues](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22hacktoberfest%22+label%3A%22Good+First+Issue%22+) for hacktoberfest that are tagged [frontend](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3AFrontend%2C+hacktoberfest), [bug](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest%2C+bug+), and many more. You can pick from these based on your expertise and can start working on them. If you need help understanding the issue or code-related things, do chat with us on [Discord](https://discord.com/invite/rBTTVJp) channel.

> For content related to contributions please check out our documentation repo [here](https://github.com/appsmithorg/appsmith-docs), and guidelines [here](https://github.com/appsmithorg/appsmith-docs/issues/244). 

## Contribute to Appsmith's Documentation 📃

Check out these issues to contribute to our documentation.

### How-to Guides (Data source reference) 

- [ ] [How to use Redis as a data source on Appsmith](https://github.com/appsmithorg/appsmith-docs/issues/209) 
- [ ] [How to use ArangoDB as a data source on Appsmith](https://github.com/appsmithorg/appsmith-docs/issues/210)
- [ ] [How to use Snowflake as a data source on Appsmith](https://github.com/appsmithorg/appsmith-docs/issues/211)
- [ ] [How to use Redshift as a data source on Appsmith](https://github.com/appsmithorg/appsmith-docs/issues/212)
- [ ] [How to use MsSQL as a data source on Appsmith](https://github.com/appsmithorg/appsmith-docs/issues/213)
- [ ] [How to use ElasticSearch as a data source on Appsmith](https://github.com/appsmithorg/appsmith-docs/issues/214)
- [ ] [How to work with GraphQL on Appsmith](https://github.com/appsmithorg/appsmith-docs/issues/215)
- [ ] [How to use Notion as a Database on Appsmith](https://github.com/appsmithorg/appsmith-docs/issues/216)

### How-to Guides (Appsmith Widget reference) 

- [ ] [How to create Custom Charts on Appsmith](https://github.com/appsmithorg/appsmith-docs/issues/217)
- [ ] [How to use filters on Appsmith Table Widget](https://github.com/appsmithorg/appsmith-docs/issues/218)
- [ ] [How to build auto-generated forms using the list widget](https://github.com/appsmithorg/appsmith-docs/issues/219)
- [ ] [How to group multiple widgets on Appsmith](https://github.com/appsmithorg/appsmith-docs/issues/220)

## Blog and Tutorial Contributions

On Appsmith, you can build internal applications, admin panels, CRUD dashboards, and many more. If you would like to build one and write a blog post or tutorial around it, please share your idea with us, and we will create an issue on this repo. Our editorial team will review it, and you can raise a PR to list it on the documentation. Here are some of the examples of blog posts and tutorials to help you get started.

1. [Building an E-commerce Store using Appsmith and Postgres](https://blog.appsmith.com/building-an-e-commerce-store-using-appsmith-and-postgres)
2. [Building a Shopify Admin Panel: A Step by Step Guide](https://blog.appsmith.com/building-a-shopify-admin-panel-a-step-by-step-guide)

_The blog post can be published either on your blog or can be submitted to the Appsmith blog._

Please comment on what you would like to work on, and we will update this list with your name and assign the issue to you. 

To check out our swag and events, please visit https://hacktoberfest.appsmith.com

Happy Hacking!

**Comment by siddhantdixit** [comment]
Hello, I would like to work on this repo! Can u assign me issues?

**Comment by oliver-pham** [comment]
Hi! I'd like to build a project management app with Appsmith and write a blog post about it. How can I share my idea with your editorial team?

**Comment by somangshu** [comment]
Greetings @siddhantdixit, thanks for showing interest 🎉 , you can look under the `hacktoberfest` label to find more issues to work on, Leave a comment on the issue you like to work on and tag one of us in the team, You will be assigned to it 🙂 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md).

Also, please don't forget to register with [Appsmith's Hacktoberfest Community](https://hacktoberfest.appsmith.com/) in order to be eligible for Appsmith swag.

**Comment by vihar** [comment]
Hey @oliver-pham, a **Project Management App with Appsmith** is super cool. Can you share your idea on our [discord](https://discord.com/invite/rBTTVJp) channel? We have a dedicated `#hactoberfest` channel!
