### ISSUE TITLE
[Task] Appsmith applicaiton Copy

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#8389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Migrate orphaned messages from the code base into `messages.ts`
- [ ] Create static list of messages which can be used by `cypress` and the Appsmith application in isolation.
- [ ] Consider the feasibility of translations using this list of messages and make changes (optional)
- [ ] Utilise the static messages in cypress to achieve one source of messages in the Appsmith codebase

**Comment by rafaeelaudibert** [comment]
Hey, could I work on this for Hacktoberfest?

**Comment by rafaeelaudibert** [comment]
I've actually already opened a PR to fix this in https://github.com/appsmithorg/appsmith/pull/8930
