### ISSUE TITLE
[Task] Move migrations to the backend

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#8889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Migrations of the DSL needs to be performed on the servers before serving the updated DSLs to the client
- [ ] DSL migrations to be removed from the client
- [ ] Facility for incremental migrations, based on the DSL version
- [ ] Migrations of bindings in actions

**Comment by riodeuno** [comment]
A reference to a dependent PR.
https://github.com/appsmithorg/appsmith/pull/7684#discussion_r737265072
