### ISSUE TITLE
[Task] [GitSync] Progress bar and error states on the connection and deploy tabs

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#8956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Show progress bar on clicking connect. Should mock the progress: (@haoin111) https://www.figma.com/file/dHbJ2KNXa9597W6BzsFIuE/Local-Dev-WIP?node-id=3%3A6076
- [x] Show connection error:(@haojin111) https://www.figma.com/file/dHbJ2KNXa9597W6BzsFIuE/Local-Dev-WIP?node-id=3%3A6611
- [x] Show progress bar on during commit and push: (@haojin111)  https://www.figma.com/file/dHbJ2KNXa9597W6BzsFIuE/Local-Dev-WIP?node-id=3%3A7707
- [x] Show errors during commit and push: (@haojin111) https://www.figma.com/file/dHbJ2KNXa9597W6BzsFIuE/Local-Dev-WIP?node-id=206%3A8238, https://www.figma.com/file/dHbJ2KNXa9597W6BzsFIuE/Local-Dev-WIP?node-id=206%3A9285
- [x] Display help message on top along with the doc link on the generate key step: https://www.figma.com/file/dHbJ2KNXa9597W6BzsFIuE/Local-Dev-WIP?node-id=1%3A47586
- [x] Update deploy key section UI: https://www.figma.com/file/dHbJ2KNXa9597W6BzsFIuE/Local-Dev-WIP?node-id=3%3A5544. (  @Rishabh-Rathod  )
- [x] Validate ssh url, should still continue on failing validation since it's difficult to validate all cases, regex:  `/^(ssh|.+@).*/`, i.e. url should either start with `ssh://` or `user@` (  @Rishabh-Rathod  )

Other tasks
- [x] Show Positive reinforcement in deploy preview (  @Rishabh-Rathod  )
- [x] Show Loader for git status  ( @Rishabh-Rathod  )
- [x] Show Loader for merge status  (  @Rishabh-Rathod  )
- [x] Success, and Failure states for merge status ( @Rishabh-Rathod  )
https://www.figma.com/file/dHbJ2KNXa9597W6BzsFIuE/Local-Dev-WIP?node-id=206%3A9837 
- [x] Show changes being pushed ( like n widgets modified, m queries modified )(@haojin111)
https://www.figma.com/file/dHbJ2KNXa9597W6BzsFIuE/Local-Dev-WIP?node-id=206%3A8238
- [x] Show Last Deployed time ( @Rishabh-Rathod  )
<img width="408" alt="Screenshot 2021-11-09 at 3 45 19 PM" src="https://user-images.githubusercontent.com/23132741/140907935-82f25feb-2749-4199-b892-3b9bdc31749c.png">

### Not yet ready
- [ ] Using Default config and application config test ( backend dependency )
