### ISSUE TITLE
[Epic]: Performance Infrastructure

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#8995]
### Objective

Create performance infrastructure that will enable every developer inside appsmith to analyze the performance implications of their pull requests.

### Success Metrics

| Goal          | Metric         |
| ------------- | -------------- |
| Generate a performance  | All PRs generate perf reports  |

### Requirements

App Generator Script: Developers should be able to generate an app to test performance against. The script should generate an app that is heavy on performance 
App Performance Report: We should be able to generate a performance report on an application for a defined set of actions. The performance report should contain the number of renders / component / action, the evaluation time / action, the render time / component / action
Components to profile: Every widget, Entity Explorer, Debugger, Topbar, Property Pane, Code Mirror
Profiling should be run in edit mode

### Out of Scope

- Fixing performance issues
- Automating performance checks

### RACI matrix

| ------------- | ------------- |
| Responsible   |  @SatishGandham   |
| Accountable   | @SatishGandham  |
| Consulted     | @Nikhil-Nandagopal, @mohanarpit|
| Informed      |  @somangshu  |

**Comment by SatishGandham** [comment]
Figure out possible ways to automate performance measurements lile

- Chrome dev tools
- Markers in code

**Generate report**
Generate a report with the captured values and compare it with previous run.
Store the values in a DB to generate historical reports?

**Comment by mohanarpit** [comment]
Metrics to track:
1. Render count grouped by component
2. Scripting time during an interaction
3. Scripting time on page load
4. Long running functions

TODO:
- [ ] Figure out how to record React profile to measure the number of renders
- [ ] If the above doesn't work, evaluate React Profiler API. Risk: It's deprecated and may not be available in React 17.
- [ ] Parse the JSON data being returned by the Chrome profile.

**Comment by mohanarpit** [comment]
TODOs:
- [ ] How to access the downloaded React profile file from headless Chrome browser
- [ ] Test out React profile on headless browser
- [ ] Test out non-headless chrome browser on an EC2 instance
- [ ] Check standard deviation of metrics that are tracked across runs

**Comment by SatishGandham** [comment]
- [ ] Generate an optimised but un-minified build with react dev tools
- [ ] Evaluate libraries to parse performance profile
- [ ] Debounce not triggered in puppeteer

**Comment by SatishGandham** [comment]
- [ ] Test the github workflow and upload the artifact
- [ ] Define actions on the chosen golden app.
- [ ] Need for a normaliser/multiply factor?
- [ ] Debounce not triggered in puppeteer
