### ISSUE TITLE
[Epic]Table widget V2

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#9135]
## Objective

As a user, I should be able to 

- [x] Edit cells of a table

As an Appsmith developer, I should be able to

- [x] Bind a custom column with another custom column
- [x] Modify the keys to access custom column to my liking
- [x] Allow content to wrap in cells of the table
- [x] Add special characters in column headers

## Success Metrics

| Goal  | Metric |
| ------------- | ------------- |
|  The user should be able to edit and save table data quickly and easily |    |
|  There should be no discrepancy between edited column header and displayed column header |  Any character added to a column header should be displayed/rendered as is  |
|  Users should have an option to be able to see all content in a cell without having to hover or interact with the cell  |  Fixes for #5693 and #4328  |
|  Appsmith developers should be able to bind row data using keys of their choice  |  Facility to update the keys which refer to a cell's data #10497  |
|  _*Stretch*_ Appsmith developers can access any column's data to bind in another column, including custom columns |  `currentRow` should have all column data (Fix for #5090) |
| _*Stretch*_ Specified columns should always be visible | Fix for #3265 | 

## Requirements

| Requirement   | User Story | Importance | Notes |
| ------------- | ------------- | ------------- | ------------- |
| | | | |

## Out of Scope
- Infinitely scrolling table
- Table's height increases dynamically based on data

## Questions

| Question  | Answer | Date Answered |
| ------------- | ------------- | ------------- |

## Checklist
- [ ] Appsmith developers can switch on the `isSticky` property in a column - https://github.com/appsmithorg/appsmith/issues/3265
- [x] Appsmith developers can define key names for columns which will be showin the `selectedRow` `triggeredRow`, `currentRow`, `selectedRows`, `finalTableData`
- [x] Appsmith developers can add special characters like emojis and international script
- [ ] Appsmith developers can bind `customColumn1` in `customColumn2` and vice-versa - https://github.com/appsmithorg/appsmith/issues/5090
- [x] Appsmith developers can enable `textWrap` property for columns, which results in content in columns getting wrapped, while it increases the height of the whole row if necessary.
- [x] `textWrap` can be a JS convertible property
- [x] Appsmith developers can enable `isEditable` property for columns
- [x] Appsmith developers can enable `isEditable` property for the whole table.
- [x] The column `isEditable` property overrides the table `isEditable`
- [x] When table's `isEditable` is toggled the `isEditable` for all the columns are reset to the global value automatically
- [x] `isEditable` is not JS convertible
- [x] `onCellEdit` handler is shown when `isEditable` for a column is `true`. - renamed to `onSubmit`
- [x] `onCellEdit` is triggered when a user blurs a editable cell after editing - renamed to `onSubmit`
- [x] `onCellEdit` is not triggered if the user does not change the value in the cell - renamed to `onSubmit`
- [x] Users can double-click on an editable cell to convert it into a input-like editable component
- [x] When done editing any cell, the trigger handlers are triggered on blur/ESC key press
- [x] When using `resetWidget` for the Table, all the edited cells will revert back to the original values.
- [x] `finalTableData` (working property name) can be used to bind with the final filtered/sorted/searched data in the table.
- [ ] `finalTableData` will also show up in the Table property autocomplete.
- [x] `primaryKeyColumn` can be defined by the Appsmith developer on the table, to help deal with indexing and internal react keys.
- [x] `primaryKeyColumn` can be JS covertible
- [ ] Tables must work with 100,000 data entries while including a couple of custom columns and making it editable, and the height of the table is 100 rows tall and 10 columns wide.
- [ ] Table column's evaluated values should only show the current page's values.
- [ ] Download should download all data from the final table data. (filtered/searched/sorted)
- [x] Column keys cannot have a number at the beginning - we are supporting numbers at the beginning.
- [x] Spaces will automatically be trimmed in key names at the ends
- [x] Spaces within the key would be converted to `_` - we are supporting spaces inbetween
- [x] Column headers will be shown as entered
- [x] After editing a cell, the content will be the new edited content until the page is refreshed. 
- [x] The updated values in the cells can be persisted in a datasource or locally using either the `onCellEdit` trigger or creating a new button type column in whose `onClick` we should be able to bind `currentRow.key`, which will now have the new edited value instead of the old original value.
- [x] Cells that have been edited can be identified visually 

Related issues: 
https://github.com/appsmithorg/appsmith/issues/11280

## Figma Design Links:

Handoff file (Cell-level editing only for now): https://www.figma.com/file/JEalu7g3jDLzWWnKsfE6mB/Table-Improvements-2022?node-id=2%3A1

**Comment by sbalaji1192** [comment]
@dilippitchika Currently we have columns types `plain text / Number`. But both are handled the same way. We need to evaluate how these two columns should be processed and rendered.
Excerpt from [slack thread](https://theappsmith.slack.com/archives/CGBPVEJ5C/p1644904831594039?thread_ts=1644903142.733629&cid=CGBPVEJ5C)  :

> Abhinav Jha: Ideal behavior here should be as follows:
>    If the column type is text, make sure the value’s string value is used. Unless it is null/undefined.
>   If the column type is a number, make sure we try to parse the number. If we cannot parse it, we return null/undefined

**Comment by sbalaji1192** [comment]
Action Items:
- [] Implement the cell level saving experience @sbalaji1192 
- [] Discussion about the table level save @momcilo-appsmith @dilippitchika @sbalaji1192 
- [] Designs for property pane changes to toggle column editability at table level- @momcilo-appsmith

**Comment by momcilo-appsmith** [comment]
@sbalaji1192 Here is the handoff for cell-level editing: https://www.figma.com/file/JEalu7g3jDLzWWnKsfE6mB/Table-Improvements-2022?node-id=2%3A1

**Comment by sbalaji1192** [comment]
Actions Items:
- Coupling of column and cell level editing options @sbalaji1192

**Comment by ivishalgandhi** [comment]
Looking for the feature to allow displaying multiple values as pills/labels in a table column. If possible it will help a lot, I have a requirement to address for an app I am developing using appsmith. Thank you.

**Comment by sbalaji1192** [comment]
@vivekverma2312 You can start testing this feature. Please test the following issues as well
#13223
#13325
#9284
#4183
#5693
#11243
#5445
#10497
#11403

**Comment by sbalaji1192** [comment]
Next action Items:

- [ ]  QA to complete with first iteration of testing 27th May - @vivekverma2312 @shadabbuchh 
- [ ] Cypress tests 2 jun- @sbalaji1192 
- [ ] Evaluating the inline editing feedbacks from Joseph 26 May- @dilippitchika
