### ISSUE TITLE
[Feature][Epic] Form Field widget standardisation

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#9136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Acheive predictable grouping and set of properties in all the Form field widgets

- [ ] Input Widget
- [ ] DatePicker Widget
- [ ] Switch Widget
- [ ] FilePicker Widget
- [ ] Select Widget
- [ ] Multi-select Widget
- [ ] Checkbox Widget
- [ ] RadioGroup Widget
- [ ] TreeSelect Widget
- [ ] Multi-TreeSelect Widget
- [ ] Audio Recorder Widget
- [ ] RichTextEditor Widget
- [ ] Rate Widget
- [ ] CheckboxGroup Widget

A few potential issues to note, 
- [ ] Padding is inconsistent between CheckboxGroup and Checkbox Widget
- [ ] Labels are only available in InputWidget, TreeSelect Widget, Multi Tree Select Widget
- [ ] Position of labels are different in InputWidget and (Multi)TreeSelectWidget
- [ ] Inconsistent popovers between Multi and Tree Select Widgets

Common list of properties in a general form field component
- [ ] defaultValue
- [ ] onChange/onValueChange
- [ ] Label
- [ ] onKeyPress
- [ ] isVisible
- [ ] isRequired
- [ ] isDisabled
- [ ] ValidationFn
- [ ] Tooltip (Helper Text)
- [ ] Tooltip (Error)
- [ ] onFocus
- [ ] onBlur
- [ ] Label Styles and or field styles

### Why should this be worked on?

- [ ] It is hard to consistently find properties as they lack predictable grouping
- [ ] Some properties are missing in widgets, which should ideally have them
- [ ] Alignment and such concerns arise if the padding and UI are not consistent

**Comment by somangshu** [comment]
This is mix of changes related to property pane and widget components, We have two projects upcoming which this can be a part of:
- Widgets styling
- Property Pane controls ( UI )

We need to take a call to fix this under one scope
