### ISSUE TITLE
[Task]: Move all widget style properties to Style category on property pane

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#9147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [x] Move all the style-related properties to the Style category on the property pane.
- [x] Remove default values for style properties.
- [x] Standardize style properties of all widgets, ex. Container widget border-radius expects value in pixel, it should be a dropdown with three border-radius options.
- [x] Write DSL migrations for breaking changes.
