### ISSUE TITLE
[Bug]-[6720]:"Navigate to" option on trigger fields has a '#' which implies number and any information added to this placeholder throws an error

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On property pane trigger fields, we have an option to navigate to a different page, but on selecting the option from dropdown, **Page Name or URL** field has a placeholder "#" that implies a number is expected. In addition, using page name or URL along with this placeholder "#" gives an error.

As per Arpit's feedback, # is used for self-reference but this fails too, i.e. leaving the **_#_** in the field throws an error (see second screenshot)

![image](https://user-images.githubusercontent.com/79509062/142168326-c30b43f5-b06a-4cfa-85d9-a75596dfe0f8.png)
![image](https://user-images.githubusercontent.com/79509062/142171552-820612d9-0fd1-4761-a70f-d61f47d3166a.png)

Also provide a list of pages here as a dropdown. More on this [over here](https://theappsmith.slack.com/archives/CGBPVEJ5C/p1637140592455500?thread_ts=1637139698.450800&cid=CGBPVEJ5C)

### Steps To Reproduce

1. Go to property pane of any widget with a trigger field and use the **Navigate to** option from the actions dropdown.
2. Observe the **_#_** present under **Page name or URL** field and the error displayed if this value is retained during execution.

### Environment

Production

### Version

Cloud

## Test Plan
- [ ] [[Test Case]: https://github.com/appsmithorg/TestSmith/issues/2053
- [ ] [[Test Case]: verify the self-referencing functionality with “#” placeholder under Page Name or URL in “Navigate to” option](https://github.com/appsmithorg/TestSmith/issues/1906)
- [ ] [[Test Case]: verify the self-referencing functionality with Page Name or URL along with placeholder “#” in “Navigate to” option](https://github.com/appsmithorg/TestSmith/issues/1907)
- [ ] [[Test Case]: verify that list of available pages appears as dropdown under “Navigate to” Option in trigger field](https://github.com/appsmithorg/TestSmith/issues/1908)

**Comment by rohan-arthur** [comment]
incidence of `#' is not a valid URL`, 6m: 840

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 840 |
| Effort (months)  | <<number>> |
