### ISSUE TITLE
[Task]: Create and import golden app for performance testing

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#9926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Create the golden app
- [ ] Write script to import the golden app
